const COMMON_TASKS=[
  ['karteikarten.html','Karteikarten'],['hoeren.html','Hören'],['bild-wort.html','Bild → Wort'],['wort-bild.html','Wort → Bild'],['artikel.html','Artikel'],['plural.html','Plural'],['memory.html','Memory'],['schreiben.html','Schreiben'],['sprechen.html','Sprechen']
];
const L3_T1_TASKS=[['karteikarten.html','Karteikarten'],['bild-wort.html','Bild → Wort'],['wort-bild.html','Wort → Bild'],['hoeren.html','Hören'],['artikel.html','Artikel'],['plural.html','Plural'],['memory.html','Memory'],['fragen-bilden.html','Fragen bilden'],['ein-eine.html','ein / eine'],['kein-keine.html','kein / keine']];
const L3_T2_TASKS=[['karteikarten.html','Karteikarten'],['bild-wort.html','Bild → Wort'],['wort-bild.html','Wort → Bild'],['hoeren.html','Hören'],['artikel.html','Artikel'],['drag-drop-artikel.html','Artikel zuordnen'],['plural.html','Plural'],['plural-drag-drop.html','Pluralgruppen'],['memory.html','Memory'],['verpackungen.html','Verpackung + Produkt'],['preis-hoeren.html','Preis hören'],['preis-schreiben.html','Preis schreiben'],['preis-sprechen.html','Preis sprechen'],['frage-und-antwort.html','Frage & Antwort']];
const L4_T2_TASKS=[['karteikarten.html','Karteikarten'],['hoeren.html','Hören'],['artikel-klick.html','Artikel klicken'],['artikel.html','Artikel zuordnen'],['plural.html','Plural'],['bild-wort.html','Bild → Wort'],['wort-bild.html','Wort → Bild'],['kategorien.html','Kategorien'],['dialoge.html','Dialoge']];
const STRONG_IRREGULAR_VERBS=new Set(['sein','haben','werden','tun','wissen','kommen','gehen','bringen','denken','gewinnen','springen','verlieren','beißen','gießen','reißen','genießen','singen','schließen','rennen','finden','schneiden','streiten','essen','sprechen','fahren','schlafen','sehen','lesen','rufen','schreien','schieben','ziehen','empfehlen','geben','befehlen','helfen','braten','waschen','nehmen','stehlen','tragen','brechen','laufen','vergessen','messen','fressen','graben','schlagen','sterben','treffen','werfen','fangen','blasen','fallen','saufen','halten','laden','lassen','wachsen','werben','raten','stechen','gefallen']);
function theme(key,title,tasks=COMMON_TASKS,sets=[]){return {key,title,tasks,sets}}
function genericLesson(n,themeCount=4){return {key:`A1-Lektion-${n}`,title:`A1 Lektion ${n}`,themes:Array.from({length:themeCount},(_,i)=>theme(`Thema-${i+1}`,`Thema ${i+1}`,COMMON_TASKS,[]))}}
const RELEASE_CATALOG={modules:[{key:'Fragen A1',title:'Fragen A1'},{key:'Wortschatz',title:'Wortschatz'},{key:'Verben A1',title:'Verben A1'}],lessons:[genericLesson(1),genericLesson(2),{key:'A1-Lektion-3',title:'A1 Lektion 3',themes:[theme('Thema-1','Thema 1 · Lebensmittel & Getränke',L3_T1_TASKS),theme('Thema-2','Thema 2 · Mengen & Verpackungen',L3_T2_TASKS),theme('Thema-3','Thema 3 · Einkaufen',COMMON_TASKS),theme('Thema-4','Thema 4 · Kochen',COMMON_TASKS)]},{key:'A1-Lektion-4',title:'A1 Lektion 4',themes:[theme('Thema-1','Thema 1 · Räume',COMMON_TASKS),theme('Thema-2','Thema 2 · Zimmer & Möbel',L4_T2_TASKS,[{key:'book',aliases:['buch','basis','im-buch'],title:'Wortschatz aus dem Buch'},{key:'extra',aliases:['plus','nicht-aus-dem-buch'],title:'Wortschatz nicht aus dem Buch'}]),theme('Thema-3','Thema 3 · Farben & Adjektive',COMMON_TASKS),theme('Thema-4','Thema 4 · Wohnungsanzeigen',COMMON_TASKS),theme('Thema-5','Thema 5 · Am Telefon',COMMON_TASKS)]},genericLesson(5),genericLesson(6),genericLesson(7),genericLesson(8),genericLesson(9),genericLesson(10),genericLesson(11),genericLesson(12),genericLesson(13),genericLesson(14)]};
const ReleaseDraft={courseName:null,courseCode:null,data:null,clone(x){return JSON.parse(JSON.stringify(x||{}))},open(course){this.courseName=Courses.docId?Courses.docId(course):(course.id||course.name);this.courseCode=Courses.code?Courses.code(course):(course.courseCode||course.id||course.name);this.data=this.clone({enabledModules:course.enabledModules||{},enabledLessons:course.enabledLessons||{},enabledThemes:course.enabledThemes||{},enabledTasks:course.enabledTasks||{},enabledWords:course.enabledWords||{},enabledSets:course.enabledSets||{},releases:course.releases||{}});this.ensureDefaults()},ensureDefaults(){if(!this.data)return;this.data.enabledModules=this.data.enabledModules||{};this.data.enabledLessons=this.data.enabledLessons||{};this.data.enabledThemes=this.data.enabledThemes||{};this.data.enabledTasks=this.data.enabledTasks||{};this.data.enabledWords=this.data.enabledWords||{};this.data.enabledSets=this.data.enabledSets||{};this.data.releases=this.data.releases||{}},set(path,value){this.ensureDefaults();let cur=this.data;for(let i=0;i<path.length-1;i++){cur[path[i]]=cur[path[i]]||{};cur=cur[path[i]]}cur[path[path.length-1]]=value},setMany(paths,value){paths.forEach(p=>this.set(p,value))},get(path,fallback=false){let cur=this.data;for(const p of path){if(!cur||!(p in cur))return fallback;cur=cur[p]}return cur},getAny(paths,fallback=false){for(const p of paths){const v=this.get(p,undefined);if(v!==undefined)return v}return fallback},checkbox(paths){return this.getAny(Array.isArray(paths[0])?paths:[paths],false)?'checked':''},setSet(lessonKey,themeKey,setKey,aliases,value){const keys=[setKey,...(aliases||[])];const paths=[];keys.forEach(k=>{paths.push(['enabledSets',`${lessonKey}/${themeKey}/${k}`],['enabledSets',`wortschatz/${lessonKey}/${themeKey}/${k}`],['enabledSets',`${themeKey}/${k}`],['enabledSets',k])});this.setMany(paths,value);this.set(['releases','wortschatz','lessons',lessonKey,'themes',themeKey,'sets',setKey],value);this.set(['releases','Wortschatz','lessons',lessonKey,'themes',themeKey,'sets',setKey],value)},setTask(lessonKey,themeKey,file,value){this.setMany(taskReleasePaths(lessonKey,themeKey,file),value)},setVerb(verb,value){this.setMany(verbReleasePaths(verb),value)},normalizeBeforeSave(){for(const lesson of RELEASE_CATALOG.lessons){for(const th of lesson.themes){(th.sets||[]).forEach(set=>{const value=this.getAny(setPaths(lesson.key,th.key,set.key,set.aliases),false);this.setSet(lesson.key,th.key,set.key,set.aliases,value)});(th.tasks||[]).forEach(t=>{const value=this.getAny(taskReleasePaths(lesson.key,th.key,t[0]),false);this.setTask(lesson.key,th.key,t[0],value)})}}verbList().forEach(v=>{const value=this.getAny(verbReleasePaths(v),false);this.setVerb(v,value)});return this.data},async save(){if(!this.courseName||!this.data)return alert('Keine Freigabe ausgewählt.');await Courses.update(this.courseName,this.normalizeBeforeSave());alert('Freigabe gespeichert.');TeacherApp.render()}};
function setPaths(lessonKey,themeKey,setKey,aliases=[]){const keys=[setKey,...aliases];const paths=[];keys.forEach(k=>{paths.push(['enabledSets',`${lessonKey}/${themeKey}/${k}`],['enabledSets',`wortschatz/${lessonKey}/${themeKey}/${k}`],['enabledSets',`${themeKey}/${k}`],['enabledSets',k],['releases','wortschatz','lessons',lessonKey,'themes',themeKey,'sets',k],['releases','Wortschatz','lessons',lessonKey,'themes',themeKey,'sets',k])});return paths}
function taskReleasePaths(lessonKey,themeKey,file){return [['enabledTasks',`wortschatz/${lessonKey}/${themeKey}/${file}`],['enabledTasks',`${lessonKey}/${themeKey}/${file}`],['enabledTasks',`${themeKey}/${file}`],['releases','wortschatz','lessons',lessonKey,'themes',themeKey,'tasks',file],['releases','Wortschatz','lessons',lessonKey,'themes',themeKey,'tasks',file]]}
function themeReleasePaths(lessonKey,themeKey){return [['enabledThemes',`${lessonKey}/${themeKey}`],['enabledThemes',`wortschatz/${lessonKey}/${themeKey}`],['releases','wortschatz','lessons',lessonKey,'themes',themeKey,'enabled']]}
function themeSetCommand(lessonKey,themeKey){return `ReleaseDraft.setMany(${JSON.stringify(themeReleasePaths(lessonKey,themeKey))},this.checked)`}
function taskSetCommand(lessonKey,themeKey,file){return `ReleaseDraft.setTask(${JSON.stringify(lessonKey)},${JSON.stringify(themeKey)},${JSON.stringify(file)},this.checked)`}
function verbList(){return (typeof ALL_VERBS!=='undefined'?ALL_VERBS:[]).map(x=>x.v).filter(Boolean)}
function sortedVerbs(list){return [...list].sort((a,b)=>a.localeCompare(b,'de',{sensitivity:'base'}))}
function isStrongIrregularVerb(v){return STRONG_IRREGULAR_VERBS.has(v)}
function verbGroups(){const verbs=sortedVerbs(verbList());return {weak:verbs.filter(v=>!isStrongIrregularVerb(v)),strong:verbs.filter(isStrongIrregularVerb)}}
function verbReleasePaths(verb){return [['enabledWords',verb],['enabledWords',`verben-A1/${verb}`],['enabledWords',`Verben A1/${verb}`],['releases','verben-A1','words',verb],['releases','Verben A1','words',verb]]}
function verbSetCommand(verb){return `ReleaseDraft.setVerb(${JSON.stringify(verb)},this.checked)`}
function releaseCheck(label,paths,onchange){const flat=(Array.isArray(paths[0])?paths:[paths]);const id='rel_'+flat[0].join('_').replace(/[^a-z0-9_]/gi,'_');const change=onchange||`ReleaseDraft.set(${JSON.stringify(flat[0])},this.checked)`;return `<label class="check-row"><input id="${id}" type="checkbox" ${ReleaseDraft.checkbox(flat)} onchange='${change}'><span>${label}</span></label>`}
function renderVerbGroup(title,verbs,note=''){return `<details class="release-sub"><summary>${title} · ${verbs.length}</summary>${note?`<div class="debug-box small">${note}</div>`:''}<div class="release-grid">${verbs.map(v=>releaseCheck(v,verbReleasePaths(v),verbSetCommand(v))).join('')}</div></details>`}
function renderVerbReleaseSection(){const groups=verbGroups();if(!groups.weak.length&&!groups.strong.length)return `<details class="release-section"><summary>Verben A1</summary><div class='empty'>Verbenliste konnte nicht geladen werden.</div></details>`;return `<details class="release-section"><summary>Verben A1 · einzelne Verben freigeben</summary><div class="debug-box small">Alphabetisch sortiert. Häkchen = dieses Verb ist für TN freigeschaltet und kann eingeschätzt/geübt werden.</div>${renderVerbGroup('Schwache / reguläre Verben',groups.weak)}${renderVerbGroup('Starke / irreguläre Verben',groups.strong,'Hier stehen starke Verben und wichtige unregelmäßige Sonderverben wie sein, haben, werden, wissen und tun.')}</details>`}
function renderReleaseEditor(course){ReleaseDraft.open(course);const name=Courses.displayName?Courses.displayName(course):(course.id||course.name||'');let html=`<div class="release-toolbar sticky-release"><h3>Freigabe ${TeacherEnv.safe(name)}</h3><div><button onclick="TeacherApp.render()">Aktualisieren</button><button class="save-btn" onclick="ReleaseDraft.save()">Speichern</button></div></div>`;html+=`<div class="debug-box small">Häkchen setzen und oben speichern. Nicht freigegebene Aufgaben erscheinen bei TN nicht und zählen nicht für die Prüfung. Neue Lektionen nutzen diese Standardstruktur automatisch.</div>`;html+=`<details class="release-section" open><summary>Module</summary>`;for(const m of RELEASE_CATALOG.modules){html+=releaseCheck(m.title,[['enabledModules',m.key],['releases',m.key,'enabled']],`ReleaseDraft.setMany([["enabledModules","${m.key}"],["releases","${m.key}","enabled"]],this.checked)`)}html+=`</details>`;html+=`<details class="release-section" open><summary>Lektionen, Themen und Aufgaben</summary>`;for(const lesson of RELEASE_CATALOG.lessons){html+=`<details class="release-sub"><summary>${lesson.title}</summary>`;html+=releaseCheck(lesson.title,[['enabledLessons',lesson.key],['enabledLessons',`wortschatz/${lesson.key}`],['releases','wortschatz','lessons',lesson.key,'enabled']],`ReleaseDraft.setMany([["enabledLessons","${lesson.key}"],["enabledLessons","wortschatz/${lesson.key}"],["releases","wortschatz","lessons","${lesson.key}","enabled"]],this.checked)`);for(const th of lesson.themes){html+=`<details class="release-sub"><summary>${th.title}</summary>`;html+=releaseCheck(th.title,themeReleasePaths(lesson.key,th.key),themeSetCommand(lesson.key,th.key));if(th.tasks&&th.tasks.length){html+=`<div class="release-subtitle">Aufgaben in diesem Thema</div><div class="release-grid">`;for(const t of th.tasks){html+=releaseCheck(t[1],taskReleasePaths(lesson.key,th.key,t[0]),taskSetCommand(lesson.key,th.key,t[0]))}html+=`</div>`}if(th.sets&&th.sets.length){html+=`<div class="release-subtitle">Wortschatz-Sets</div>`;for(const set of th.sets){html+=releaseCheck(set.title,setPaths(lesson.key,th.key,set.key,set.aliases),`ReleaseDraft.setSet("${lesson.key}","${th.key}","${set.key}",${JSON.stringify(set.aliases||[])},this.checked)`)}}html+=`</details>`}html+=`</details>`}html+=`</details>`;html+=renderVerbReleaseSection();return html}
