import { db, doc, getDoc, setDoc, serverTimestamp, collection, query, where, getDocs, limit } from "./firebase.js";
import { getActiveProfile } from "./auth.js";

const MODULE_KEYS=["fragen","wortschatz","verben","grammatik"];
const RULES={taskPoints(run){run=Number(run)||1;if(run===1)return 5;if(run===2)return 10;if(run===3)return 15;return 1},examMax(run){run=Number(run)||1;if(run===1)return 100;if(run===2)return 200;if(run===3)return 300;return 1},examEarned(run,percent){run=Number(run)||1;percent=clamp(percent);if(run>=4)return percent>=100?1:0;return Math.round(this.examMax(run)*percent/100)}};
const TECH=new Set(["state","progress","stars","activeVerbs","learnedVerbs","known","unknown","unsure","updatedAt","lastActive","lastLogin","lastPage","lastAction","totals","current","profile","metadata"]);
const TOPICS=[
 {key:"SP_L4_T1_V2",module:"wortschatz",moduleTitle:"Wortschatz",level:"A1",lesson:"4",theme:"1",topicId:"wortschatz-a1-lektion-4-thema-1",title:"A1 Lektion 4 · Thema 1",href:"/wortschatz/A1-Lektion-4/Thema-1/",files:["karteikarten.html","hoeren.html","artikel-klick.html","artikel.html","plural.html","bild-wort.html","wort-bild.html","wo-ist.html","ist-hier.html","pruefung.html"]},
 {key:"SP_L4_T2_FINAL_V3",module:"wortschatz",moduleTitle:"Wortschatz",level:"A1",lesson:"4",theme:"2",topicId:"wortschatz-a1-lektion-4-thema-2",title:"A1 Lektion 4 · Thema 2",href:"/wortschatz/A1-Lektion-4/Thema-2/",files:["karteikarten.html","hoeren.html","artikel-klick.html","artikel.html","plural.html","bild-wort.html","wort-bild.html","kategorien.html","dialoge.html","pruefung.html"]},
 {key:"SP_L4_T3_V2",module:"wortschatz",moduleTitle:"Wortschatz",level:"A1",lesson:"4",theme:"3",topicId:"wortschatz-a1-lektion-4-thema-3",title:"A1 Lektion 4 · Thema 3",href:"/wortschatz/A1-Lektion-4/Thema-3/",files:["karteikarten.html","hoeren.html","farben.html","memory.html","gegenteile.html","kein.html","reaktionen.html","gefallen.html","saetze-bauen.html","schreiben.html","pruefung.html"]},
 {key:"SP_L5_T1_V1",module:"wortschatz",moduleTitle:"Wortschatz",level:"A1",lesson:"5",theme:"1",topicId:"wortschatz-a1-lektion-5-thema-1",title:"A1 Lektion 5 · Thema 1",href:"/wortschatz/A1-Lektion-5/Thema-1/",files:["karteikarten.html","bild-wort.html","wort-bild.html","hoeren-schreiben.html","trennbare-verben.html","trennbare-verben-im-satz.html","marias-tag.html","was-machst-du-gern.html","ja-nein-fragen.html","verb-passt.html","pruefung.html"]},
 {key:"SP_L5_T2_V1",module:"wortschatz",moduleTitle:"Wortschatz",level:"A1",lesson:"5",theme:"2",topicId:"wortschatz-a1-lektion-5-thema-2",title:"A1 Lektion 5 · Thema 2",href:"/wortschatz/A1-Lektion-5/Thema-2/",files:["karteikarten.html","artikel.html","plural.html","sehen-schreiben.html","hoeren-schreiben.html","sprechen.html","formell-informell.html","frage-antwort.html","schon-erst.html","pruefung.html"]},
 {key:"SP_L5_T3_V2",module:"wortschatz",moduleTitle:"Wortschatz",level:"A1",lesson:"5",theme:"3",topicId:"wortschatz-a1-lektion-5-thema-3",title:"A1 Lektion 5 · Thema 3",href:"/wortschatz/A1-Lektion-5/Thema-3/",files:["karteikarten.html","sortieren.html","um-am.html","hoeren-waehlen.html","saetze-bauen.html","plan-lesen.html","sprechen.html","dialoge.html","schreiben.html","pruefung.html"]}
];
const TASK_TITLES={"karteikarten.html":"Karteikarten","hoeren.html":"Hören","artikel-klick.html":"Artikel klicken","artikel.html":"Artikel zuordnen","plural.html":"Plural","bild-wort.html":"Bild → Wort","wort-bild.html":"Wort → Bild","kategorien.html":"Kategorien","dialoge.html":"Dialoge","wo-ist.html":"Wo ist?","ist-hier.html":"Ist hier?","farben.html":"Farben","memory.html":"Memory","gegenteile.html":"Gegenteile","kein.html":"nicht / kein","reaktionen.html":"Reaktionen","gefallen.html":"Gefallen","saetze-bauen.html":"Sätze bauen","schreiben.html":"Schreiben","sehen-schreiben.html":"Sehen → Schreiben","hoeren-schreiben.html":"Hören → Schreiben","sprechen.html":"Sprechen","formell-informell.html":"formell ↔ informell","frage-antwort.html":"Frage / Antwort","schon-erst.html":"schon / erst","trennbare-verben.html":"Trennbare Verben","trennbare-verben-im-satz.html":"Sätze bauen","marias-tag.html":"Marias Tag","was-machst-du-gern.html":"Was machst du gern?","ja-nein-fragen.html":"Ja-/Nein-Fragen","verb-passt.html":"Mini-Situationen","sortieren.html":"Gruppen","um-am.html":"Präpositionen","hoeren-waehlen.html":"Hören","plan-lesen.html":"Plan lesen","pruefung.html":"Prüfung"};
function now(){return new Date().toISOString()}
function cleanId(s){return String(s||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"item"}
function clamp(v){return Math.max(0,Math.min(100,Math.round(Number(v)||0)))}
function uniq(a){return [...new Set((a||[]).filter(Boolean).map(String))]}
function read(k){try{return JSON.parse(localStorage.getItem(k)||"null")}catch(e){return null}}
function profile(){try{return getActiveProfile()||read("SP_USER_PROFILE")||read("SP_STUDENT_PROFILE")||{}}catch(e){return {}}}
function course(p=profile()){return p.kurs||p.kursnummer||p.courseCode||p.course||localStorage.getItem("SP_COURSE_CODE")||""}
function email(p=profile()){return String(p.email||"").trim().toLowerCase()}
function fallbackId(p=profile()){return cleanId((p.courseDocId||course(p)||"kurs")+"_"+(email(p)||p.vorname||p.firstName||"student"))}
function idCandidates(p=profile()){return uniq([p.docId,p.studentId,p.userId,p.uid,p.id,localStorage.getItem("SP_STUDENT_ID"),fallbackId(p)])}
function primaryIds(p=profile()){return uniq([p.docId,p.studentId,p.userId,localStorage.getItem("SP_STUDENT_ID"),fallbackId(p)]).slice(0,3)}
function studentId(p=profile()){return idCandidates(p)[0]||fallbackId(p)}
function name(p=profile()){return [p.vorname||p.firstName||p.name,p.nachname||p.lastName].filter(Boolean).join(" ")||p.displayName||p.email||"Schüler/in"}
function isTeacherPreview(){try{if(typeof window.spIsTeacherPreview==="function")return window.spIsTeacherPreview();const role=String(localStorage.getItem("SP_LOGIN_ROLE")||localStorage.getItem("SP_ACTIVE_ROLE")||"").toLowerCase();const prev=read("SP_TEACHER_PREVIEW")||read("teacherPreview");return role==="teacher"||!!(prev&&prev.teacherPreview===true)||sessionStorage.getItem("SP_TEACHER_PREVIEW")==="1"||localStorage.getItem("SP_TEACHER_PREVIEW")==="1"}catch(e){return false}}
function canWrite(){if(isTeacherPreview())return false;if(typeof window.spCanWriteFirebaseProgress==="function")return window.spCanWriteFirebaseProgress();return true}
function isTopicRecord(k,v){return !TECH.has(k)&&!!(v&&typeof v==="object"&&!Array.isArray(v)&&(v.tasks||v.exam||v.current||v.lifetime||v.progressPercent||v.title||v.moduleTitle))}
function verbLen(x){return Array.isArray(x)?x.length:(x&&typeof x==="object"?Object.keys(x).length:0)}
function verbStats(mod={}){const learned=verbLen(mod.learnedVerbs||mod.known||mod.state?.learnedVerbs||mod.state?.known||[]);const active=verbLen(mod.activeVerbs||mod.state?.activeVerbs||mod.state?.active||[]);const known=verbLen(mod.known||mod.state?.known||[]);const unsure=verbLen(mod.unsure||mod.state?.unsure||[]);const unknown=verbLen(mod.unknown||mod.state?.unknown||[]);return{learned,active,known,unsure,unknown,contentsDone:Math.floor(learned/20),currentPackagePercent:Math.min(100,Math.round(((learned%20)||(learned?20:0))/20*100))}}
function topicId(p){return p.topicId||p.themeId||cleanId([p.module||"wortschatz",p.level||"A1","lektion",p.lesson||p.lektion||"","thema",p.theme||p.thema||""].filter(Boolean).join("_"))}
function runKey(scope){return`SP_SCORE_RUN_${scope}`}
function currentRun(scope){return Math.max(1,Math.round(Number(localStorage.getItem(runKey(scope))||1)||1))}
function setRun(scope,run){localStorage.setItem(runKey(scope),String(Math.max(1,Math.round(Number(run)||1))))}
function localPoints(){return Math.max(0,Number(localStorage.getItem("SP_POINTS_TOTAL")||0)||0)}
function point(v){const n=Number(v);return Number.isFinite(n)?n:0}
function strongest(...records){let best=localPoints();records.filter(Boolean).forEach(r=>{best=Math.max(best,point(r.lifetimePoints),point(r.pointsTotal),point(r.punkteGesamt),point(r.totals?.points));MODULE_KEYS.forEach(m=>Object.values(r[m]||{}).forEach(t=>{if(t&&typeof t==="object"&&!Array.isArray(t))best=Math.max(best,point(t.lifetime?.points),point(t.lifetimePoints),point(t.pointsTotal))}))});return best}
function addDelta(progress,delta){delta=Math.max(0,point(delta));if(delta)progress.__pointsDelta=point(progress.__pointsDelta)+delta}
function takeDelta(progress){const d=Math.max(0,point(progress?.__pointsDelta));if(progress&&Object.prototype.hasOwnProperty.call(progress,"__pointsDelta"))delete progress.__pointsDelta;return d}
function betterTask(a={},b={}){return clamp(b.percent)>clamp(a.percent)?b:{...b,...a,percent:Math.max(clamp(a.percent),clamp(b.percent)),completed:!!(a.completed||b.completed),done:Math.max(Number(a.done||0),Number(b.done||0)),total:Math.max(Number(a.total||0),Number(b.total||0)),points:Math.max(Number(a.points||0),Number(b.points||0)),pointsByRun:{...(b.pointsByRun||{}),...(a.pointsByRun||{})}}}
function mergeRuns(a={},b={}){const out={...b,...a};Object.keys(b||{}).forEach(k=>out[k]=Math.max(Number(out[k]||0),Number(b[k]||0)));Object.keys(a||{}).forEach(k=>out[k]=Math.max(Number(out[k]||0),Number(a[k]||0)));return out}
function mergeTopic(a={},b={}){const out={...b,...a};const tasks={...(b.tasks||{})};Object.entries(a.tasks||{}).forEach(([k,v])=>{tasks[k]=betterTask(tasks[k]||{},v)});out.tasks=tasks;const vals=Object.values(tasks);out.completedTasks=vals.filter(t=>t.completed||clamp(t.percent)>=100).length;out.totalTasks=Math.max(Number(a.totalTasks||0),Number(b.totalTasks||0),vals.length);out.progressPercent=vals.length?clamp(vals.reduce((s,t)=>s+clamp(t.percent||0),0)/Math.max(vals.length,out.totalTasks||vals.length)):Math.max(clamp(a.progressPercent||a.current?.percent||0),clamp(b.progressPercent||b.current?.percent||0));out.current={...(b.current||{}),...(a.current||{}),percent:out.progressPercent,completedTasks:out.completedTasks,totalTasks:out.totalTasks,updatedAt:now()};const ae=a.exam||{},be=b.exam||{};out.exam={...be,...ae,bestPercent:Math.max(Number(ae.bestPercent||ae.percent||0),Number(be.bestPercent||be.percent||0)),percent:Math.max(Number(ae.percent||0),Number(be.percent||0)),stars:Math.max(Number(ae.stars||0),Number(be.stars||0)),attempted:!!(ae.attempted||be.attempted),completed:!!(ae.completed||be.completed)};const al=a.lifetime||{},bl=b.lifetime||{};out.lifetime={...bl,...al,points:Math.max(Number(al.points||0),Number(bl.points||0)),taskPointRuns:{...(bl.taskPointRuns||{}),...(al.taskPointRuns||{})},examPointRuns:mergeRuns(al.examPointRuns||{},bl.examPointRuns||{}),resets:Math.max(Number(al.resets||0),Number(bl.resets||0)),finishedRuns:Math.max(Number(al.finishedRuns||0),Number(bl.finishedRuns||0))};return out}
function mergeProgress(a={},b={}){const out={...b,...a};MODULE_KEYS.forEach(m=>{const mod={...(b[m]||{})};Object.entries(a[m]||{}).forEach(([k,t])=>{if(isTopicRecord(k,t))mod[k]=mergeTopic(t,mod[k]||{});else mod[k]=t});out[m]=mod});out.lifetimePoints=Math.max(point(a.lifetimePoints),point(b.lifetimePoints),point(a.totals?.points),point(b.totals?.points));out.pointsTotal=Math.max(point(a.pointsTotal),point(b.pointsTotal),out.lifetimePoints);out.punkteGesamt=Math.max(point(a.punkteGesamt),point(b.punkteGesamt),out.lifetimePoints);return out}
async function readProgress(id=null){const ids=id?[id]:primaryIds();let merged={};for(const one of ids){try{const snap=await getDoc(doc(db,"progress",one));if(snap.exists())merged=mergeProgress(snap.data()||{},merged)}catch(e){}}return merged}
function recalcTotals(progress){let points=0,stars=0,progressSum=0,progressCount=0,completedTasks=0,completedExams=0;MODULE_KEYS.forEach(m=>{const mod=progress[m]||{};Object.entries(mod).forEach(([k,t])=>{if(!isTopicRecord(k,t))return;const lifetime=t.lifetime||{};points+=point(lifetime.points);const pct=clamp(t.progressPercent??t.current?.percent??0);progressSum+=pct;progressCount++;Object.values(t.tasks||{}).forEach(task=>{if(task&&task.completed)completedTasks++});if(t.exam?.attempted){completedExams++;stars+=Number(t.exam.stars||0)}});if(m==="verben"){const vs=verbStats(mod);if(vs.learned||vs.active||vs.known||vs.unsure||vs.unknown){progressSum+=vs.currentPackagePercent;progressCount++;completedTasks+=vs.contentsDone}}});return{points,stars,progressPercent:progressCount?clamp(progressSum/progressCount):0,completedTasks,completedExams,updatedAt:now()}}
async function writeProgress(next){if(!canWrite())return null;const p=profile(),id=studentId(p),kurs=course(p);if(!id)return null;let previous={};try{previous=await readProgress(id)}catch(e){}if(!previous.studentId&&!previous.totals&&!previous.wortschatz&&!previous.verben){try{previous=await readProgress()}catch(e){}}const earned=takeDelta(next);next=mergeProgress(next,previous);next.studentId=id;next.userId=id;next.docId=id;next.kurs=kurs||next.kurs||"";next.kursnummer=kurs||next.kursnummer||"";next.courseCode=kurs||next.courseCode||"";next.studentName=name(p);next.email=p.email||next.email||"";next.muttersprache=p.muttersprache||p.motherLanguage||next.muttersprache||"";next.lastActive=serverTimestamp();next.updatedAt=serverTimestamp();next.lastActiveAt=now();next.lastPage=location.pathname;next.totals=recalcTotals(next);const preserved=Math.max(strongest(previous)+earned,strongest(previous),strongest(next));next.lifetimePoints=preserved;next.pointsTotal=preserved;next.punkteGesamt=preserved;next.totals.points=Math.max(point(next.totals.points),preserved);try{await setDoc(doc(db,"progress",id),{...next,canonicalStudentId:id,aliasIds:idCandidates(p)},{merge:true})}catch(e){console.warn("Progress write failed",id,e)}try{localStorage.setItem("SP_STUDENT_ID",id);localStorage.setItem("SP_POINTS_TOTAL",String(preserved));localStorage.setItem("SP_PROGRESS_LAST_SYNC",now())}catch(e){}return next}
function taskTitle(file){return TASK_TITLES[file]||String(file||"Aufgabe").replace(/\.html$/i,"").replace(/-/g," ")}
async function recordTaskProgress(payload={}){if(!canWrite())return null;try{const moduleKey=payload.module||"wortschatz",id=topicId(payload),run=currentRun(id);const rawKey=payload.file||payload.taskKey||payload.taskTitle||"task";const pointsKey=cleanId(rawKey);const current=await readProgress();const mod={...(current[moduleKey]||{})};const topic={...(mod[id]||{})};const tasks={...(topic.tasks||{})};const old=tasks[rawKey]||tasks[pointsKey]||{};let percent=clamp(payload.percent??payload.progress??0);if(!payload.allowDecrease)percent=Math.max(percent,clamp(old.percent||0));const completed=!!payload.completed||percent>=100;const lifetime={...(topic.lifetime||{})};const taskPointRuns={...(lifetime.taskPointRuns||{})};const thisRuns={...(taskPointRuns[pointsKey]||{})};let delta=0;if(completed&&!thisRuns[String(run)]){delta=RULES.taskPoints(run);thisRuns[String(run)]=delta;taskPointRuns[pointsKey]=thisRuns}const wrong=[...(old.wrongItems||[]),...(payload.wrongItems||[])].slice(-50);tasks[rawKey]={...old,key:rawKey,file:payload.file||old.file||rawKey,title:payload.taskTitle||old.title||taskTitle(payload.file||rawKey),percent,completed,total:Number(payload.total||old.total||0),done:Number(payload.done||old.done||0),attempts:Number(old.attempts||0)+(payload.countAttempt?1:0),tries:Number(payload.tries||old.tries||0),wrongItems:wrong,lastWrongItem:payload.lastWrongItem||old.lastWrongItem||"",lastActiveAt:now(),completedAt:completed?(old.completedAt||now()):(old.completedAt||null),points:Number(old.points||0)+delta,pointsByRun:thisRuns,run};const values=Object.values(tasks);const avg=values.length?clamp(values.reduce((s,t)=>s+Number(t.percent||0),0)/values.length):percent;const done=values.filter(t=>t.completed).length;lifetime.points=Number(lifetime.points||0)+delta;lifetime.taskPointRuns=taskPointRuns;lifetime.completedTasks=Math.max(Number(lifetime.completedTasks||0),done);lifetime.resets=Math.max(Number(lifetime.resets||0),run-1);topic.title=payload.title||topic.title||`A1 Lektion ${payload.lesson||""} · Thema ${payload.theme||""}`;topic.moduleTitle=payload.moduleTitle||topic.moduleTitle||"Wortschatz";topic.level=payload.level||topic.level||"A1";topic.lesson=payload.lesson||topic.lesson||"";topic.theme=payload.theme||topic.theme||"";topic.progressPercent=avg;topic.completedTasks=done;topic.totalTasks=values.length;topic.tasks=tasks;topic.current={percent:avg,completedTasks:done,totalTasks:values.length,updatedAt:now()};topic.lifetime=lifetime;mod[id]=topic;current[moduleKey]=mod;addDelta(current,delta);return await writeProgress(current)}catch(e){console.warn("SPProgress task sync failed",e);return null}}
async function recordExamResult(payload={}){if(!canWrite())return null;try{const moduleKey=payload.module||"wortschatz",id=topicId(payload),run=currentRun(id);const current=await readProgress();const mod={...(current[moduleKey]||{})};const topic={...(mod[id]||{})};const exam={...(topic.exam||{})};const percent=clamp(payload.percent??payload.scorePercent??payload.score??0);const earned=RULES.examEarned(run,percent),maxScore=RULES.examMax(run);const lifetime={...(topic.lifetime||{})};const examRuns={...(lifetime.examPointRuns||{})};const oldBest=Number(examRuns[String(run)]||0);const better=Math.max(oldBest,earned);const delta=Math.max(0,better-oldBest);examRuns[String(run)]=better;const attempts=Number(exam.attempts||0)+1;const stars=Number(payload.stars??(percent>=100?3:percent>=70?2:percent>=50?1:0));topic.exam={attempted:true,unlocked:true,attempts,lastScore:earned,lastPercent:percent,lastStars:stars,lastAttemptAt:now(),bestScore:Math.max(Number(exam.bestScore||0),earned),bestPercent:Math.max(Number(exam.bestPercent||0),percent),stars:Math.max(Number(exam.stars||0),stars),maxScore,completed:percent>=100||exam.completed===true};lifetime.points=Number(lifetime.points||0)+delta;lifetime.examPointRuns=examRuns;lifetime.resets=Math.max(Number(lifetime.resets||0),run-1);lifetime.bestExamPercent=Math.max(Number(lifetime.bestExamPercent||0),percent);lifetime.bestStars=Math.max(Number(lifetime.bestStars||0),stars);lifetime.examAttempts=attempts;topic.lifetime=lifetime;topic.examUnlocked=true;topic.title=payload.title||topic.title||`A1 Lektion ${payload.lesson||""} · Thema ${payload.theme||""}`;topic.moduleTitle=payload.moduleTitle||topic.moduleTitle||"Wortschatz";topic.level=payload.level||topic.level||"A1";topic.lesson=payload.lesson||topic.lesson||"";topic.theme=payload.theme||topic.theme||"";mod[id]=topic;current[moduleKey]=mod;addDelta(current,delta);return await writeProgress(current)}catch(e){console.warn("SPProgress exam sync failed",e);return null}}
async function recordThemeReset(payload={}){if(!canWrite())return null;try{const moduleKey=payload.module||"wortschatz",id=topicId(payload);setRun(id,currentRun(id)+1);const current=await readProgress();const mod={...(current[moduleKey]||{})};const topic={...(mod[id]||{})};const lifetime={...(topic.lifetime||{})};lifetime.resets=Number(lifetime.resets||0)+1;topic.progressPercent=0;topic.completedTasks=0;topic.totalTasks=topic.totalTasks||0;topic.tasks={};topic.current={percent:0,completedTasks:0,totalTasks:topic.totalTasks||0,resetAt:now()};topic.examUnlocked=false;topic.exam={...(topic.exam||{}),unlocked:false};topic.lifetime=lifetime;mod[id]=topic;current[moduleKey]=mod;return await writeProgress(current)}catch(e){console.warn("SPProgress reset sync failed",e);return null}}
async function touch(payload={}){if(!canWrite())return null;try{const current=await readProgress(studentId());current.lastPage=location.pathname;current.lastAction=payload.action||"active";return await writeProgress(current)}catch(e){console.warn("SPProgress touch failed",e);return null}}
async function loadCurrentStudentProgress(){if(isTeacherPreview())return{};return await readProgress()}
async function loadCourseRanking(courseCode=course()){if(isTeacherPreview()||!courseCode)return[];const q=query(collection(db,"progress"),where("kurs","==",courseCode),limit(100));const snap=await getDocs(q);return snap.docs.map(d=>({id:d.id,...d.data()}))}
function topicFromPath(){const p=location.pathname;return TOPICS.find(t=>p.startsWith(t.href))||null}
function topicFromStorageKey(k){return TOPICS.find(t=>String(k||"").startsWith(t.key+"_"))||null}
function fileFromStorageKey(t,k){const f=String(k||"").slice(t.key.length+1);return t.files.includes(f)?f:""}
function statePercent(st){if(!st||typeof st!=="object")return{percent:0,total:0,done:0,started:false};const total=Number(st.total||0)||0;const done=Array.isArray(st.done)?st.done.length:Number(st.done||0)||0;const percent=total?clamp(done/total*100):clamp(st.percent||0);return{percent,total,done,started:percent>0||done>0||st.current!==null&&st.current!==undefined||Number(st.tries||0)>0||st.hadWrong===true}}
function localPayload(t,file,st){const p=statePercent(st);return{module:t.module,moduleTitle:t.moduleTitle,level:t.level,lesson:t.lesson,theme:t.theme,topicId:t.topicId,title:t.title,file,taskKey:file,taskTitle:taskTitle(file),percent:p.percent,completed:p.percent>=100,total:p.total,done:p.done,countAttempt:false}}
async function syncLocalFile(t,file){const st=read(t.key+"_"+file);if(!st)return;const p=statePercent(st);if(!p.started&&p.percent<=0)return;if(file==="pruefung.html")await recordExamResult({...localPayload(t,file,st),scorePercent:p.percent,score:p.percent,stars:p.percent>=100?3:p.percent>=70?2:p.percent>=50?1:0});await recordTaskProgress(localPayload(t,file,st))}
async function syncExistingLocal(){for(const t of TOPICS){for(const file of t.files){try{await syncLocalFile(t,file)}catch(e){}}}}
async function syncCurrentTopicLocal(){const t=topicFromPath();if(!t)return;for(const file of t.files){try{await syncLocalFile(t,file)}catch(e){}}}
function localTaskStateFromRemote(task){const total=Math.max(1,Number(task.total||task.done||100)||100);const done=Math.max(0,Math.min(total,Number(task.done||Math.round(total*clamp(task.percent||0)/100))||0));return{total,done:[...Array(done).keys()],queue:[...Array(total).keys()].filter(i=>i>=done),current:null,tries:Number(task.tries||0)||0,hadWrong:!!task.hadWrong,completed:done>=total}}
async function hydrateCurrentTopic(){const t=topicFromPath();if(!t||!canWrite())return 0;let count=0;try{window.__SP_PROGRESS_HYDRATING=true;const current=await readProgress();const topic=current[t.module]?.[t.topicId]||{};const tasks=topic.tasks||{};for(const file of t.files){const remote=tasks[file]||tasks[cleanId(file)];if(!remote)continue;const remotePct=clamp(remote.percent||0);if(remotePct<=0)continue;const k=t.key+"_"+file;const local=read(k);const localPct=statePercent(local).percent;if(remotePct>localPct){localStorage.setItem(k,JSON.stringify(localTaskStateFromRemote(remote)));count++}}window.__SP_PROGRESS_HYDRATING=false;if(count){window.dispatchEvent(new CustomEvent("SP_TOPIC_PROGRESS_HYDRATED",{detail:{topic:t,count}}));if(/\/Thema-\d+\/?(?:index\.html)?$/i.test(location.pathname)){const flag="SP_TOPIC_HYDRATE_RELOAD_"+t.topicId;if(sessionStorage.getItem(flag)!=="1"){sessionStorage.setItem(flag,"1");setTimeout(()=>location.reload(),150)}}}}catch(e){window.__SP_PROGRESS_HYDRATING=false;console.warn("SPProgress hydrate failed",e)}return count}
function patchStorage(){if(window.__SP_PROGRESS_STORAGE_PATCHED)return;window.__SP_PROGRESS_STORAGE_PATCHED=true;const native=Storage.prototype.setItem;const timers=new Map();Storage.prototype.setItem=function(k,v){const out=native.apply(this,arguments);try{if(window.__SP_PROGRESS_HYDRATING)return out;const t=topicFromStorageKey(k);if(t){const file=fileFromStorageKey(t,k);if(file){clearTimeout(timers.get(k));timers.set(k,setTimeout(()=>syncLocalFile(t,file),1200))}}}catch(e){}return out}}
async function migrateLegacyLocalProgress(){if(!canWrite())return;await syncExistingLocal()}
function boot(){if(location.pathname.startsWith("/student-dashboard/"))return;patchStorage();if(topicFromPath())hydrateCurrentTopic();}
const API={RULES,recordTaskProgress,recordExamResult,recordThemeReset,touch,loadCurrentStudentProgress,loadCourseRanking,migrateLegacyLocalProgress,verbStats,currentRun,taskPointsForRun:RULES.taskPoints,examMaxForRun:RULES.examMax,examEarnedForRun:RULES.examEarned,idCandidates,syncCurrentTopicLocal};
window.SPProgress=API;
const q=window.SP_PROGRESS_QUEUE||[];window.SP_PROGRESS_QUEUE=[];for(const item of q){if(item&&API[item.method])API[item.method](item.payload||{})}
boot();
export{recordTaskProgress,recordExamResult,recordThemeReset,touch,loadCurrentStudentProgress,loadCourseRanking,migrateLegacyLocalProgress,verbStats};