import('/js/topbar-standard.js?v=7').catch(function(){});
(function(){
let remoteData=null;
let refreshDone=false;
let refreshPromise=null;
function safeJson(s,f){try{return JSON.parse(s||'')||f}catch(e){return f}}
function profile(){try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||'null')||JSON.parse(localStorage.getItem('SP_STUDENT_PROFILE')||'null')||{}}catch(e){return {}}}
function courseCode(){const p=profile();return String(p.kurs||p.kursnummer||p.courseCode||localStorage.getItem('SP_COURSE_CODE')||'').trim()}
function cachedData(){const p=profile();return p.assignments||safeJson(localStorage.getItem('SP_COURSE_RELEASES'),{})||{}}
function localData(){return remoteData||cachedData()||{}}
async function readCourseByCode(code){try{const mod=await import('/js/firebase.js?v=6');if(mod.authReady)await mod.authReady;for(const c of [code,code.toUpperCase(),code.toLowerCase()].filter((v,i,a)=>v&&a.indexOf(v)===i)){const snap=await mod.getDoc(mod.doc(mod.db,'courses',String(c)));if(snap.exists())return snap.data()||{}}for(const field of ['courseCode','kurs','kursnummer','name','courseName','code']){try{const q=mod.query(mod.collection(mod.db,'courses'),mod.where(field,'==',String(code)),mod.limit(1));const s=await mod.getDocs(q);if(s&&!s.empty)return s.docs[0].data()||{}}catch(e){}}}catch(e){console.warn('Freigaben konnten nicht aktualisiert werden',e)}return null}
async function refresh(){if(refreshPromise)return refreshPromise;refreshPromise=(async()=>{const code=courseCode();if(!code){refreshDone=true;return null}const data=await readCourseByCode(code);refreshDone=true;if(data){remoteData=data;localStorage.setItem('SP_COURSE_RELEASES',JSON.stringify(remoteData));const p=profile();p.assignments=remoteData;localStorage.setItem('SP_USER_PROFILE',JSON.stringify(p));return remoteData}return null})();return refreshPromise}
function val(obj,path){let cur=obj;for(const p of path){if(!cur||typeof cur!=='object'||!(p in cur))return undefined;cur=cur[p]}return cur}
function locked(data){return !data||data.defaultLocked!==false&&data.releaseMode!=='open'&&data.releaseMode!=='all'}
function ctxFromPath(){const p=location.pathname;let m=p.match(/\/wortschatz\/(A\d-Lektion-\d+)\/(Thema-\d+)\/(.*)$/i);if(m)return{module:'wortschatz',lesson:m[1],theme:m[2],file:(m[3]||'index.html').split('/').pop()||'index.html',kind:'task'};m=p.match(/\/wortschatz\/(A\d-Lektion-\d+)\/?(?:index\.html)?$/i);if(m)return{module:'wortschatz',lesson:m[1],theme:'',file:'index.html',kind:'lesson'};if(/\/wortschatz\/?(?:index\.html)?$/i.test(p))return{module:'wortschatz',lesson:'',theme:'',file:'index.html',kind:'module'};return{module:'',lesson:'',theme:'',file:p.split('/').pop()||'index.html',kind:''}}
function moduleReleased(ctx,data){for(const p of [['enabledModules','Wortschatz'],['enabledModules','wortschatz'],['releases','Wortschatz','enabled'],['releases','wortschatz','enabled']]){const v=val(data,p);if(v!==undefined)return v===true}return !locked(data)}
function lessonReleased(ctx,data){if(!ctx.lesson)return moduleReleased(ctx,data);for(const p of [['enabledLessons',ctx.lesson],['enabledLessons','Wortschatz/'+ctx.lesson],['enabledLessons','wortschatz/'+ctx.lesson],['releases','wortschatz','lessons',ctx.lesson,'enabled'],['releases','Wortschatz','lessons',ctx.lesson,'enabled']]){const v=val(data,p);if(v!==undefined)return v===true}return moduleReleased(ctx,data)&&!locked(data)}
function themeReleased(ctx,data){if(!ctx.theme)return lessonReleased(ctx,data);for(const p of [['enabledThemes',ctx.lesson+'/'+ctx.theme],['enabledThemes','Wortschatz/'+ctx.lesson+'/'+ctx.theme],['enabledThemes','wortschatz/'+ctx.lesson+'/'+ctx.theme],['enabledThemes',ctx.theme],['releases','wortschatz','lessons',ctx.lesson,'themes',ctx.theme,'enabled'],['releases','Wortschatz','lessons',ctx.lesson,'themes',ctx.theme,'enabled']]){const v=val(data,p);if(v!==undefined)return v===true}return lessonReleased(ctx,data)&&!locked(data)}
function taskPaths(file,ctx=ctxFromPath()){return[['enabledTasks',ctx.module+'/'+ctx.lesson+'/'+ctx.theme+'/'+file],['enabledTasks','Wortschatz/'+ctx.lesson+'/'+ctx.theme+'/'+file],['enabledTasks','wortschatz/'+ctx.lesson+'/'+ctx.theme+'/'+file],['enabledTasks',ctx.lesson+'/'+ctx.theme+'/'+file],['enabledTasks',ctx.theme+'/'+file],['enabledTasks',file],['releases',ctx.module,'lessons',ctx.lesson,'themes',ctx.theme,'tasks',file],['releases','Wortschatz','lessons',ctx.lesson,'themes',ctx.theme,'tasks',file]]}
function hasTaskControls(data,ctx=ctxFromPath()){const et=data.enabledTasks||{},pre=[ctx.module+'/'+ctx.lesson+'/'+ctx.theme+'/','Wortschatz/'+ctx.lesson+'/'+ctx.theme+'/','wortschatz/'+ctx.lesson+'/'+ctx.theme+'/',ctx.lesson+'/'+ctx.theme+'/',ctx.theme+'/'];if(Object.keys(et).some(k=>pre.some(p=>String(k).startsWith(p))))return true;return !!(val(data,['releases',ctx.module,'lessons',ctx.lesson,'themes',ctx.theme,'tasks'])||val(data,['releases','Wortschatz','lessons',ctx.lesson,'themes',ctx.theme,'tasks']))}
function taskReleased(file,ctx=ctxFromPath(),data=localData()){if(!file||/^(statistik|uebersicht)\.html$/i.test(file))return true;if(ctx.kind==='lesson'||(!ctx.theme&&file==='index.html'))return lessonReleased(ctx,data);if(file==='index.html')return themeReleased(ctx,data);if(!themeReleased(ctx,data))return false;for(const p of taskPaths(file,ctx)){const v=val(data,p);if(v!==undefined)return v===true}if(hasTaskControls(data,ctx))return false;return themeReleased(ctx,data)}
function filterTasks(tasks,ctx=ctxFromPath(),data=localData()){return(tasks||[]).filter(t=>taskReleased(Array.isArray(t)?t[0]:(t.file||t.href),ctx,data))}
function examUnlocked(tasks,percentFn,ctx=ctxFromPath(),data=localData()){const rel=filterTasks(tasks,ctx,data).filter(t=>!String(Array.isArray(t)?t[0]:(t.file||t.href)).includes('pruefung'));if(!rel.length)return true;return rel.every(t=>Number(percentFn(Array.isArray(t)?t[0]:(t.file||t.href),Array.isArray(t)?t[1]:(t.total||1)))>=100)}
function lessonCtx(lesson){return{module:'wortschatz',lesson:String(lesson||''),theme:'',file:'index.html',kind:'lesson'}}
function cleanLabel(a){return(a.textContent||'').replace('Gesperrt','').replace('Offen','').replace('🔒','').replace('✅','').trim()}
function applyLessonButtons(data=localData()){if(!/\/wortschatz\/?(?:index\.html)?$/i.test(location.pathname))return;document.querySelectorAll('.lesson-btn[data-lesson]').forEach(a=>{const clone=a.cloneNode(true),lesson=clone.dataset.lesson,label=cleanLabel(clone),open=lessonReleased(lessonCtx(lesson),data);clone.textContent=label;clone.classList.toggle('open',open);clone.classList.toggle('locked',!open);clone.dataset.releaseOpen=open?'1':'0';clone.onclick=function(e){if(clone.dataset.releaseOpen!=='1'){e.preventDefault();alert('Diese Lektion ist für deinen Kurs noch nicht freigeschaltet.')}};a.replaceWith(clone)})}
function showLoading(){const ctx=ctxFromPath();if(ctx.module!=='wortschatz'||ctx.kind==='module')return;const target=document.getElementById('area')||document.querySelector('.card')||document.querySelector('main');if(target&&!target.dataset.spReleaseLoading){target.dataset.spReleaseLoading='1';target.innerHTML='<div class="finish-box"><div class="finish-icon">⏳</div><div class="question">Freigabe wird geprüft …</div><p class="small">Bitte kurz warten.</p></div>'}}
function blockCurrentIfNeeded(data=localData(),finalCheck=false){const ctx=ctxFromPath();if(ctx.module!=='wortschatz')return;applyLessonButtons(data);if(ctx.kind==='module')return;if(!finalCheck&&!refreshDone){showLoading();return}const allowed=ctx.kind==='lesson'?lessonReleased(ctx,data):taskReleased(ctx.file,ctx,data);if(allowed){const target=document.getElementById('area')||document.querySelector('.card')||document.querySelector('main');if(target&&target.dataset.spReleaseLoading&&location.pathname.split('/').pop()!=='index.html')location.reload();return}const target=document.getElementById('area')||document.querySelector('.card')||document.querySelector('main')||document.body;const href=ctx.kind==='lesson'?'../index.html':(ctx.kind==='task'?'../index.html':'/index.html');target.innerHTML='<div class="finish-box"><div class="finish-icon">🔒</div><div class="question">Gesperrt</div><p class="small">Dieser Bereich ist für deinen Kurs nicht freigegeben.</p><div class="actions finish-actions"><a class="btn secondary" href="'+href+'">← Zurück</a></div></div>'}
window.SprachPilotRelease={refresh,ctxFromPath,taskReleased,filterTasks,examUnlocked,blockCurrentIfNeeded,localData,themeReleased,lessonReleased,moduleReleased,applyLessonButtons};
document.addEventListener('DOMContentLoaded',()=>{showLoading();refresh().then(d=>{const data=d||localData();applyLessonButtons(data);blockCurrentIfNeeded(data,true)})});
setTimeout(()=>{if(!refreshDone)showLoading()},250);
setTimeout(()=>{refresh().then(d=>{const data=d||localData();applyLessonButtons(data);blockCurrentIfNeeded(data,true)})},900);
})();