import('/js/topbar-standard.js?v=6').catch(function(){});
(function(){
  let remoteData=null;
  function safeJson(s,f){try{return JSON.parse(s||'')||f}catch(e){return f}}
  function profile(){try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||'null')||{}}catch(e){return {}}}
  function courseCode(){const p=profile();return String(p.kurs||p.kursnummer||p.courseCode||localStorage.getItem('SP_COURSE_CODE')||'').trim()}
  function localData(){const p=profile();return remoteData||p.assignments||safeJson(localStorage.getItem('SP_COURSE_RELEASES'),{})||{}}
  async function readCourseByCode(code){try{const mod=await import('/js/firebase.js');const candidates=[code,code.toUpperCase(),code.toLowerCase()].filter((v,i,a)=>v&&a.indexOf(v)===i);for(const c of candidates){const snap=await mod.getDoc(mod.doc(mod.db,'courses',String(c)));if(snap.exists())return snap.data()||{}}for(const field of ['courseCode','kurs','kursnummer','name','courseName','code']){try{const q=mod.query(mod.collection(mod.db,'courses'),mod.where(field,'==',String(code)),mod.limit(1));const s=await mod.getDocs(q);if(s&&!s.empty)return s.docs[0].data()||{}}catch(e){}}}catch(e){console.warn('Freigaben konnten nicht aktualisiert werden',e)}return null}
  async function refresh(){const code=courseCode();if(!code)return null;const data=await readCourseByCode(code);if(data){remoteData=data;localStorage.setItem('SP_COURSE_RELEASES',JSON.stringify(remoteData));const p=profile();p.assignments=remoteData;localStorage.setItem('SP_USER_PROFILE',JSON.stringify(p));return remoteData}return null}
  function val(obj,path){let cur=obj;for(const p of path){if(!cur||typeof cur!=='object'||!(p in cur))return undefined;cur=cur[p]}return cur}
  function locked(data){return !data||data.defaultLocked!==false&&data.releaseMode!=='open'&&data.releaseMode!=='all'}
  function ctxFromPath(){const p=location.pathname;let m=p.match(/\/wortschatz\/(A\d-Lektion-\d+)\/(Thema-\d+)\/(.*)$/i);if(m)return {module:'wortschatz',lesson:m[1],theme:m[2],file:(m[3]||'index.html').split('/').pop()||'index.html',kind:'task'};m=p.match(/\/wortschatz\/(A\d-Lektion-\d+)\/?(?:index\.html)?$/i);if(m)return {module:'wortschatz',lesson:m[1],theme:'',file:'index.html',kind:'lesson'};if(/\/wortschatz\/?(?:index\.html)?$/i.test(p))return {module:'wortschatz',lesson:'',theme:'',file:'index.html',kind:'module'};return {module:'',lesson:'',theme:'',file:p.split('/').pop()||'index.html',kind:''}}
  function moduleReleased(ctx,data){const keys=[['enabledModules','Wortschatz'],['enabledModules','wortschatz'],['releases','Wortschatz','enabled'],['releases','wortschatz','enabled']];for(const p of keys){const v=val(data,p);if(v!==undefined)return v===true}return !locked(data)}
  function lessonReleased(ctx,data){if(!ctx.lesson)return moduleReleased(ctx,data);const keys=[['enabledLessons',ctx.lesson],['enabledLessons','wortschatz/'+ctx.lesson],['releases','wortschatz','lessons',ctx.lesson,'enabled'],['releases','Wortschatz','lessons',ctx.lesson,'enabled']];for(const p of keys){const v=val(data,p);if(v!==undefined)return v===true}return moduleReleased(ctx,data)&&!locked(data)}
  function themeReleased(ctx,data){if(!ctx.theme)return lessonReleased(ctx,data);const keys=[['enabledThemes',ctx.lesson+'/'+ctx.theme],['enabledThemes','wortschatz/'+ctx.lesson+'/'+ctx.theme],['enabledThemes',ctx.theme],['releases','wortschatz','lessons',ctx.lesson,'themes',ctx.theme,'enabled'],['releases','Wortschatz','lessons',ctx.lesson,'themes',ctx.theme,'enabled']];for(const p of keys){const v=val(data,p);if(v!==undefined)return v===true}return lessonReleased(ctx,data)&&!locked(data)}
  function taskPaths(file,ctx=ctxFromPath()){return [['enabledTasks',ctx.module+'/'+ctx.lesson+'/'+ctx.theme+'/'+file],['enabledTasks',ctx.lesson+'/'+ctx.theme+'/'+file],['enabledTasks',ctx.theme+'/'+file],['enabledTasks',file],['releases',ctx.module,'lessons',ctx.lesson,'themes',ctx.theme,'tasks',file],['releases','Wortschatz','lessons',ctx.lesson,'themes',ctx.theme,'tasks',file]]}
  function hasTaskControls(data,ctx=ctxFromPath()){const et=data.enabledTasks||{};const prefixes=[ctx.module+'/'+ctx.lesson+'/'+ctx.theme+'/',ctx.lesson+'/'+ctx.theme+'/',ctx.theme+'/'];if(Object.keys(et).some(k=>prefixes.some(p=>String(k).startsWith(p))))return true;if(val(data,['releases',ctx.module,'lessons',ctx.lesson,'themes',ctx.theme,'tasks']))return true;if(val(data,['releases','Wortschatz','lessons',ctx.lesson,'themes',ctx.theme,'tasks']))return true;return false}
  function taskReleased(file,ctx=ctxFromPath(),data=localData()){if(!file||/^(statistik|uebersicht)\.html$/i.test(file))return true;if(ctx.kind==='lesson'||(!ctx.theme&&file==='index.html'))return lessonReleased(ctx,data);if(file==='index.html')return themeReleased(ctx,data);if(!themeReleased(ctx,data))return false;for(const p of taskPaths(file,ctx)){const v=val(data,p);if(v!==undefined)return v===true}if(hasTaskControls(data,ctx))return false;return !locked(data)}
  function filterTasks(tasks,ctx=ctxFromPath(),data=localData()){return (tasks||[]).filter(t=>taskReleased(Array.isArray(t)?t[0]:(t.file||t.href),ctx,data))}
  function examUnlocked(tasks,percentFn,ctx=ctxFromPath(),data=localData()){const rel=filterTasks(tasks,ctx,data).filter(t=>!String(Array.isArray(t)?t[0]:(t.file||t.href)).includes('pruefung'));if(!rel.length)return true;return rel.every(t=>{const file=Array.isArray(t)?t[0]:(t.file||t.href);const total=Array.isArray(t)?t[1]:(t.total||1);return Number(percentFn(file,total))>=100})}
  function lessonCtx(lesson){return {module:'wortschatz',lesson:String(lesson||''),theme:'',file:'index.html',kind:'lesson'}}
  function cleanLabel(a){return (a.textContent||'').replace('Gesperrt','').replace('Offen','').replace('🔒','').replace('✅','').trim()}
  function applyLessonButtons(data=localData()){if(!/\/wortschatz\/?(?:index\.html)?$/i.test(location.pathname))return;document.querySelectorAll('.lesson-btn[data-lesson]').forEach(a=>{const clone=a.cloneNode(true);const lesson=clone.dataset.lesson;const label=cleanLabel(clone);const open=lessonReleased(lessonCtx(lesson),data);clone.textContent=label;clone.classList.toggle('open',open);clone.classList.toggle('locked',!open);clone.dataset.releaseOpen=open?'1':'0';clone.onclick=function(e){if(clone.dataset.releaseOpen!=='1'){e.preventDefault();alert('Diese Lektion ist für deinen Kurs noch nicht freigeschaltet.')}};a.replaceWith(clone)})}
  function blockCurrentIfNeeded(data=localData()){const ctx=ctxFromPath();if(ctx.module!=='wortschatz')return;applyLessonButtons(data);if(ctx.kind==='module')return;const allowed=ctx.kind==='lesson'?lessonReleased(ctx,data):taskReleased(ctx.file,ctx,data);if(allowed)return;const target=document.getElementById('area')||document.querySelector('.card')||document.querySelector('main')||document.body;const href=ctx.kind==='lesson'?'../index.html':(ctx.kind==='task'?'../index.html':'/index.html');target.innerHTML='<div class="finish-box"><div class="finish-icon">🔒</div><div class="question">Gesperrt</div><p class="small">Dieser Bereich ist für deinen Kurs nicht freigegeben.</p><div class="actions finish-actions"><a class="btn secondary" href="'+href+'">← Zurück</a></div></div>'}
  window.SprachPilotRelease={refresh,ctxFromPath,taskReleased,filterTasks,examUnlocked,blockCurrentIfNeeded,localData,themeReleased,lessonReleased,moduleReleased,applyLessonButtons};
  document.addEventListener('DOMContentLoaded',()=>{applyLessonButtons();blockCurrentIfNeeded();refresh().then(d=>{applyLessonButtons(d||localData());blockCurrentIfNeeded(d||localData())})});
  setTimeout(()=>{applyLessonButtons();blockCurrentIfNeeded()},250);
  setTimeout(()=>{refresh().then(d=>{applyLessonButtons(d||localData());blockCurrentIfNeeded(d||localData())})},1000);
})();