import {renderSpHeader,bindSpHeader} from '/js/sp-header.js?v=theme-standard4';
const D=window.L10T2||{};const root=document.getElementById('app');
const taskId=String(new URLSearchParams(location.search).get('task')||'karteikarten').toLowerCase();
const task=(D.tasks||[]).find(x=>x.id===taskId)||D.tasks?.[0];
const TOPIC='wortschatz-a1-lektion-10-thema-2';
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(v){return String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[.,!?;:“”"'`´()]/g,'').replace(/\s+/g,' ')}
function shuffle(a){const b=a.slice();for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function profile(){try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||localStorage.getItem('SP_STUDENT_PROFILE')||'{}')||{}}catch(e){return{}}}
function owner(){const p=profile();return String(p.canonicalStudentId||p.docId||p.studentId||p.userId||p.authUid||p.uid||p.id||p.email||localStorage.getItem('SP_STUDENT_ID')||'student').trim().toLowerCase().replace(/[^a-z0-9äöüß@._-]+/gi,'_')}
function preview(){try{return ['teacher','lehrer','admin','owner','superadmin'].includes(String(localStorage.getItem('SP_LOGIN_ROLE')||localStorage.getItem('SP_ACTIVE_ROLE')||'').toLowerCase())||sessionStorage.getItem('SP_TEACHER_PREVIEW')==='1'||localStorage.getItem('SP_TEACHER_PREVIEW')==='1'}catch(e){return false}}
function run(){return Math.max(1,Math.min(3,Number(localStorage.getItem('SP_SCORE_RUN_'+TOPIC)||1)||1))}
function store(){return preview()?sessionStorage:localStorage}
function key(){return `SP_L10_${owner()}_T2_${taskId}`}
function read(total){let s={done:[],wrong:{},order:[],firstSeen:[],firstCorrect:[],_run:run(),total};try{const x=JSON.parse(store().getItem(key())||'{}');if(x&&Number(x._run||1)===run()&&Number(x.total||0)===Number(total||0))Object.assign(s,x)}catch(e){}s.done=Array.isArray(s.done)?s.done:[];s.wrong=s.wrong||{};s.order=Array.isArray(s.order)?s.order:[];s.firstSeen=Array.isArray(s.firstSeen)?s.firstSeen:[];s.firstCorrect=Array.isArray(s.firstCorrect)?s.firstCorrect:[];s.total=total;return s}
let progressSyncTimer=0,progressImporting=false;
function sendCentralProgress(payload){
 if(preview())return;
 try{
  if(window.SPProgress&&typeof window.SPProgress.recordTaskProgress==='function'){
   Promise.resolve(window.SPProgress.recordTaskProgress(payload)).catch(()=>{});
   return;
  }
  window.SP_PROGRESS_QUEUE=Array.isArray(window.SP_PROGRESS_QUEUE)?window.SP_PROGRESS_QUEUE:[];
  window.SP_PROGRESS_QUEUE.push({method:'recordTaskProgress',payload});
  if(!progressImporting){
   progressImporting=true;
   import('/js/progress.js?v=20260831-central6').catch(()=>{}).finally(()=>{progressImporting=false});
  }
 }catch(e){}
}
function syncStoredProgress(total){
 if(preview()||taskId==='pruefung')return;
 clearTimeout(progressSyncTimer);
 progressSyncTimer=setTimeout(()=>{
  try{
   const persisted=JSON.parse(store().getItem(key())||'null');
   if(!persisted||Number(persisted._run||1)!==run())return;
   const finalTotal=Math.max(0,Number(persisted.total||total||0));
   const done=Array.isArray(persisted.done)?Math.min(finalTotal,persisted.done.length):0;
   const percent=finalTotal?Math.round(done/finalTotal*100):0;
   if(percent<=0)return;
   sendCentralProgress({
    topic:TOPIC,
    file:`task.html?task=${taskId}`,
    taskKey:taskId,
    taskTitle:task?.title||taskId,
    run:run(),
    done,
    total:finalTotal,
    percent,
    completed:percent>=100
   });
  }catch(e){}
 },120);
}
function write(s){
 s._run=run();
 try{
  store().setItem(key(),JSON.stringify(s));
  const persisted=JSON.parse(store().getItem(key())||'null');
  if(persisted&&typeof persisted==='object'){
   for(const name of Object.keys(s))delete s[name];
   Object.assign(s,persisted);
  }
  syncStoredProgress(s.total);
  window.dispatchEvent(new CustomEvent('sprachpilot-progress',{detail:{lesson:10,theme:2,topic:TOPIC,task:taskId,state:s}}));
 }catch(e){}
}
function taskHead(done,total){const p=total?Math.round(done/total*100):0;return `<section class="l8-card l8-task-head"><div class="l8-task-title-block"><span class="l8-task-kicker">Aufgabe ${Math.max(1,(D.tasks||[]).findIndex(x=>x.id===taskId)+1)}</span><h1>${esc(task?.title||'Aufgabe')}</h1><p>${esc(task?.icon||'✅')} ${esc(task?.text||'')}</p></div><div class="l8-progress-row"><span>${done} von ${total} fertig</span><strong>${p}%</strong></div><div class="l8-progress"><div style="width:${p}%"></div></div></section>`}
function shell(body,done,total){const header=renderSpHeader({subtitle:'Gesundheit und Alltag · A1 Lektion 10 · Thema 2',color:{main:'#F4A3A3',dark:'#A86464',soft:'#FDF1F1',line:'#F3C9C9'}});root.innerHTML=`<div class="l10-theme-page">${header}<div class="l8-wrap">${preview()?'<div class="sp-teacher-preview-note">Lehrer-Vorschau: Teilnehmerfortschritt wird nicht verändert.</div>':''}${taskHead(done,total)}${body}<footer>© SprachPilot</footer></div></div>`;bindSpHeader(root)}
function finish(total){const s=read(total);s.done=Array.from({length:total},(_,i)=>String(i));write(s);shell(`<section class="l8-card l8-finish"><div class="l8-finish-icon">✓</div><h2>Gut gemacht!</h2><p>Du hast diese Aufgabe zu 100% abgeschlossen.</p><div class="l8-row l8-center-actions"><a class="l8-btn primary" href="./index.html">Zur Übersicht</a></div></section>`,total,total)}
function visual(c,small=false){return `<span class="sp-visual ${small?'small':''}"><img src="${esc(c.image)}" alt="" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><span class="sp-fallback" style="display:none">${esc(c.emoji||'📝')}</span></span>`}
function play(c){const sources=[c.audio,c.audioFallback].filter((x,i,a)=>x&&a.indexOf(x)===i);const trySource=i=>{if(i>=sources.length){speak(c.full||c.word);return}try{const a=new Audio(sources[i]);let failed=false;const next=()=>{if(failed)return;failed=true;trySource(i+1)};a.onerror=next;const p=a.play();if(p&&p.catch)p.catch(next)}catch(e){trySource(i+1)}};trySource(0)}
function speak(t){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='de-DE';u.rate=.84;speechSynthesis.speak(u)}catch(e){}}
function recognize(onResult,onUnavailable){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){onUnavailable?.();return}try{const r=new R();r.lang='de-DE';r.interimResults=false;r.maxAlternatives=1;r.onresult=e=>onResult(String(e.results?.[0]?.[0]?.transcript||''));r.onerror=()=>onUnavailable?.();r.start()}catch(e){onUnavailable?.()}}
function feedback(el,type,html){el.innerHTML=`<div class="l8-feedback ${type}">${html}</div>`}
function ensureOrder(items,total){const ids=items.map((_,i)=>String(i));const s=read(total);const valid=s.order.filter(id=>ids.includes(id));const missing=ids.filter(id=>!valid.includes(id));if(missing.length||valid.length!==ids.length){s.order=valid.concat(shuffle(missing));write(s)}return s}
function nextIndex(items){const s=ensureOrder(items,items.length);const id=s.order.find(x=>!s.done.includes(x));return id==null?null:Number(id)}
function markDone(i,total){const s=read(total);const id=String(i);if(!s.done.includes(id))s.done.push(id);delete s.wrong[id];write(s)}
function wrong(i,total){const s=read(total),id=String(i);s.wrong[id]=(Number(s.wrong[id])||0)+1;write(s);return s.wrong[id]}
function hint(n,answer,h=''){if(n===1)return 'Noch nicht richtig. Versuch es noch einmal.';if(n===2)return h||'Achte genau auf Person, Genus und Satzform.';return `<strong>Lösung:</strong> ${esc(answer)}`}
function renderCards(){const items=D.cards||[],i=nextIndex(items);if(i==null)return finish(items.length);const c=items[i],s=read(items.length);shell(`<section class="l8-card l8-card-stage"><div class="l8-flip-wrap"><div class="l8-flip-card" id="flip" tabindex="0"><div class="l8-flip-face l8-flip-front">${visual(c)}<div class="l8-card-translation"><span>Bedeutung</span><strong>${esc(c.meaning)}</strong></div></div><div class="l8-flip-face l8-flip-back"><div class="l8-flip-back-grid"><div class="l8-back-image">${visual(c,true)}</div><div class="l8-back-info"><div class="l8-flip-word">${esc(c.full)}</div>${c.plural?`<div class="l8-card-detail"><span>Plural</span><strong>${esc(c.plural)}</strong></div>`:''}<button class="l8-btn" id="listen">🔊 Anhören</button></div></div></div></div></div><div class="l8-row l8-center-actions l8-card-actions"><button class="l8-btn primary" id="mic">🎤 Sprechen</button><button class="l8-btn" id="writeBtn">✍️ Schreiben</button></div><div class="l8-card-write" id="writeBox" hidden><div class="l8-answer-row"><input class="l8-input" id="answer" autocomplete="off" placeholder="Wort schreiben"><button class="l8-btn primary" id="check">Prüfen</button></div></div><div id="fb"></div></section>`,s.done.length,items.length);
 const flip=document.getElementById('flip');const reveal=()=>{if(flip.classList.contains('flipped'))return;flip.classList.add('flipped');const n=wrong(i,items.length);feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,c.full,c.meaning))};flip.onclick=reveal;flip.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();reveal()}};document.getElementById('listen').onclick=e=>{e.stopPropagation();play(c)};document.getElementById('writeBtn').onclick=()=>{document.getElementById('writeBox').hidden=false;document.getElementById('answer').focus()};const check=v=>{const accepted=[c.full,c.word].filter(Boolean).map(norm);if(accepted.includes(norm(v))){markDone(i,items.length);feedback(document.getElementById('fb'),'good','Richtig!');setTimeout(renderCards,350)}else{const n=wrong(i,items.length);feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,c.full,c.meaning))}};document.getElementById('check').onclick=()=>check(document.getElementById('answer').value);document.getElementById('answer').onkeydown=e=>{if(e.key==='Enter')check(e.target.value)};document.getElementById('mic').onclick=()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){document.getElementById('writeBtn').click();return}try{const r=new R();r.lang='de-DE';r.interimResults=false;r.onresult=e=>check(e.results[0][0].transcript);r.onerror=()=>document.getElementById('writeBtn').click();r.start()}catch(e){document.getElementById('writeBtn').click()}}}
function renderMeaning(){const items=D.cards||[],i=nextIndex(items);if(i==null)return finish(items.length);const c=items[i],opts=shuffle([c,...shuffle(items.filter(x=>x.id!==c.id)).slice(0,3)]);const s=read(items.length);shell(`<section class="l8-card l8-exercise"><div class="sp-big-word">${esc(c.full)}</div><div class="l8-options">${opts.map(o=>`<button class="l8-option" data-id="${esc(o.id)}">${esc(o.meaning)}</button>`).join('')}</div><div id="fb"></div></section>`,s.done.length,items.length);document.querySelectorAll('.l8-option').forEach(b=>b.onclick=()=>{if(b.dataset.id===c.id){markDone(i,items.length);feedback(document.getElementById('fb'),'good','Richtig!');setTimeout(renderMeaning,350)}else{const n=wrong(i,items.length);feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,c.meaning,'Lies das Wort noch einmal und achte auf die genaue Bedeutung.'))}})}
function renderAudioImage(){const items=D.cards||[],i=nextIndex(items);if(i==null)return finish(items.length);const c=items[i],opts=shuffle([c,...shuffle(items.filter(x=>x.id!==c.id)).slice(0,3)]),s=read(items.length);shell(`<section class="l8-card l8-exercise"><div class="sp-listen-center"><button class="l8-btn primary sp-listen-big" id="play">🔊 Wort anhören</button></div><div class="sp-image-options">${opts.map(o=>`<button class="sp-image-option" data-id="${esc(o.id)}">${visual(o)}</button>`).join('')}</div><div id="fb"></div></section>`,s.done.length,items.length);document.getElementById('play').onclick=()=>play(c);setTimeout(()=>play(c),250);document.querySelectorAll('.sp-image-option').forEach(b=>b.onclick=()=>{if(b.dataset.id===c.id){markDone(i,items.length);feedback(document.getElementById('fb'),'good','Richtig!');setTimeout(renderAudioImage,350)}else{const n=wrong(i,items.length);feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,c.full,'Höre das Wort noch einmal.'))}})}
function renderArticlePlural(){const items=D.nouns||[],i=nextIndex(items);if(i==null)return finish(items.length);const c=items[i],s=read(items.length);shell(`<section class="l8-card l8-exercise"><div class="sp-noun-card">${visual(c,true)}<strong>${esc(c.word)}</strong></div><p><strong>1.</strong> Wähle den Artikel.</p><div class="l8-options sp-article-options">${shuffle(['der','die','das']).map(a=>`<button class="l8-option article" data-a="${a}">${a}</button>`).join('')}</div><p><strong>2.</strong> Schreibe den Plural <em>mit Artikel</em>.</p><div class="l8-answer-row"><input class="l8-input" id="plural" placeholder="z. B. die ..."><button class="l8-btn primary" id="check">Prüfen</button></div><div id="fb"></div></section>`,s.done.length,items.length);let chosen='';document.querySelectorAll('.article').forEach(b=>b.onclick=()=>{document.querySelectorAll('.article').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');chosen=b.dataset.a});document.getElementById('check').onclick=()=>{const ok=chosen===c.article&&norm(document.getElementById('plural').value)===norm(c.plural);if(ok){markDone(i,items.length);feedback(document.getElementById('fb'),'good','Richtig!');setTimeout(renderArticlePlural,400)}else{const n=wrong(i,items.length);feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,`${c.article} ${c.word} · ${c.plural}`,'Prüfe zuerst das Genus. Im Plural steht immer „die“.'))}}}
function renderTextItems(items,kind){const i=nextIndex(items);if(i==null)return finish(items.length);const x=items[i],s=read(items.length);shell(`<section class="l8-card l8-exercise"><div class="l8-note"><strong>Sprich oder schreibe:</strong> Formuliere den Satz um. Du kannst die Antwort in das Feld schreiben oder auf „Satz sprechen“ tippen.</div><div class="sp-transform"><div class="sp-source">${esc(x.q)}</div><div class="sp-arrow">↓</div><div class="l8-answer-row"><input class="l8-input" id="ans" autocomplete="off" placeholder="Neuen Satz schreiben"><button class="l8-btn primary" id="check" type="button">Prüfen</button></div><div class="l8-row l8-center-actions"><button class="l8-btn" id="speakAnswer" type="button">🎤 Satz sprechen</button></div></div><div id="fb"></div></section>`,s.done.length,items.length);const check=value=>{const v=value??document.getElementById('ans').value;if(norm(v)===norm(x.a)){markDone(i,items.length);feedback(document.getElementById('fb'),'good',`Richtig! <strong>${esc(x.a)}</strong>`);setTimeout(()=>renderTextItems(items,kind),450)}else{const n=wrong(i,items.length);const h=kind==='base'?'Achte auf ich/du/Sie und auf die passende Form von haben bzw. den Possessivartikel.':'Achte auf die Person: hat/haben/habt und mein/dein/sein/ihr/unser/euer.';feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,x.a,h))}};document.getElementById('check').onclick=()=>check();document.getElementById('ans').onkeydown=e=>{if(e.key==='Enter')check()};document.getElementById('speakAnswer').onclick=()=>recognize(text=>{document.getElementById('ans').value=text;check(text)},()=>feedback(document.getElementById('fb'),'warn','Sprechen ist in diesem Browser nicht verfügbar. Schreibe den Satz in das Feld.'))}
function renderPossTable(){const rows=D.possRows||[],s=read(rows.length);const order=ensureOrder(rows,rows.length).order.map(Number);shell(`<section class="l8-card l8-exercise"><p>Schreibe rechts die zwei Grundformen im Nominativ.</p><div class="sp-poss-table"><div class="sp-poss-head">Pronomen</div><div class="sp-poss-head">maskulin / neutral</div><div class="sp-poss-head">feminin / Plural</div>${order.map(i=>{const r=rows[i],done=s.done.includes(String(i));return `<div class="sp-pronoun">${esc(r[0])}</div><input class="l8-input poss" data-i="${i}" data-k="1" value="${done?esc(r[1]):''}" ${done?'disabled':''}><input class="l8-input poss" data-i="${i}" data-k="2" value="${done?esc(r[2]):''}" ${done?'disabled':''}>`}).join('')}</div><div class="l8-row l8-center-actions"><button class="l8-btn primary" id="check">Prüfen</button></div><div id="fb"></div></section>`,s.done.length,rows.length);document.getElementById('check').onclick=()=>{let newly=0;rows.forEach((r,i)=>{if(s.done.includes(String(i)))return;const a=document.querySelector(`.poss[data-i="${i}"][data-k="1"]`),b=document.querySelector(`.poss[data-i="${i}"][data-k="2"]`);if(a&&b&&norm(a.value)===norm(r[1])&&norm(b.value)===norm(r[2])){markDone(i,rows.length);a.classList.add('correct');b.classList.add('correct');newly++}else if((a&&a.value)||(b&&b.value)){a?.classList.add('incorrect');b?.classList.add('incorrect')}});const now=read(rows.length);if(now.done.length===rows.length)return setTimeout(()=>finish(rows.length),300);feedback(document.getElementById('fb'),newly?'good':'bad',newly?`${newly} Zeile(n) richtig. Ergänze die übrigen.`:'Noch nicht richtig. Prüfe die Person und die Endung.');setTimeout(renderPossTable,500)}}
function renderPossForm(){const items=D.possForm||[],i=nextIndex(items);if(i==null)return finish(items.length);const x=items[i],s=read(items.length);shell(`<section class="l8-card l8-exercise"><div class="sp-big-word">${esc(x.q)}</div><div class="l8-answer-row"><input class="l8-input" id="ans" autocomplete="off" placeholder="Form schreiben"><button class="l8-btn primary" id="check">Prüfen</button></div><div id="fb"></div></section>`,s.done.length,items.length);const check=()=>{if(norm(document.getElementById('ans').value)===norm(x.a)){markDone(i,items.length);feedback(document.getElementById('fb'),'good','Richtig!');setTimeout(renderPossForm,300)}else{const n=wrong(i,items.length);feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,x.a,'Maskulin und neutral haben keine Endung; feminin und Plural bekommen -e.'))}};document.getElementById('check').onclick=check;document.getElementById('ans').onkeydown=e=>{if(e.key==='Enter')check()}}
function renderFamily(){const groups=Array.isArray(D.family?.texts)?D.family.texts:[{title:'Familie',text:D.family?.text||[]}],i=nextIndex(groups);if(i==null)return finish(groups.length);const group=groups[i],s=read(groups.length),gaps=[];(group.text||[]).forEach((r,li)=>String(r[1]||'').split('|').filter(Boolean).forEach((a,gi)=>gaps.push({id:`${li}-${gi}`,li,gi,a})));const idToGap=Object.fromEntries(gaps.map((g,idx)=>[g.id,idx]));const html=(group.text||[]).map((r,li)=>{let text=esc(r[0]),gi=0;text=text.replace(/___/g,()=>{const idx=idToGap[`${li}-${gi}`];gi++;return `<input class="l8-input sp-inline-gap" data-gap="${idx}" autocomplete="off">`});return `<p class="sp-family-line">${text}</p>`}).join('');shell(`<section class="l8-card l8-exercise"><div class="l8-note"><strong>Text ${s.done.length+1} von ${groups.length}:</strong> Lies den Text in der 3. Person und ergänze alle Possessivformen.</div><div class="sp-family-text"><div class="sp-family-section"><h2>${esc(group.title||`Text ${i+1}`)}</h2>${html}</div></div><div class="l8-row l8-center-actions"><button class="l8-btn primary" id="check">Text prüfen</button></div><div id="fb"></div></section>`,s.done.length,groups.length);document.getElementById('check').onclick=()=>{let allCorrect=true;gaps.forEach((g,idx)=>{const inp=document.querySelector(`[data-gap="${idx}"]`),ok=inp&&norm(inp.value)===norm(g.a);inp?.classList.toggle('correct',ok);inp?.classList.toggle('incorrect',!ok);if(!ok)allCorrect=false});if(allCorrect){markDone(i,groups.length);feedback(document.getElementById('fb'),'good','Der ganze Text ist richtig!');setTimeout(renderFamily,450)}else{const n=wrong(i,groups.length),solution=gaps.map(g=>g.a).join(' · ');feedback(document.getElementById('fb'),n>=3?'warn':'bad',n>=3?`<strong>Lösungen:</strong> ${esc(solution)}`:'Noch nicht richtig. Prüfe alle markierten Lücken.')}}}
function renderBios(){const items=D.bios||[],i=nextIndex(items);if(i==null)return finish(items.length);const x=items[i],s=read(items.length);shell(`<section class="l8-card l8-exercise"><div class="l8-note"><strong>Aufgabe:</strong> Schreibe den ganzen Text in der 3. Person. Ändere auch alle Possessivformen.</div><div class="sp-bio-label">${esc(x.label)}</div><h2>Ausgangstext</h2><div class="sp-source sp-bio-source">${esc(x.from)}</div><h2>3. Person</h2><textarea class="l8-input sp-textarea" id="ans" rows="7" placeholder="Schreibe hier den vollständigen Text in der 3. Person."></textarea><div class="l8-row l8-center-actions"><button class="l8-btn primary" id="check">Prüfen</button></div><div id="fb"></div></section>`,s.done.length,items.length);document.getElementById('check').onclick=()=>{const v=document.getElementById('ans').value;if(norm(v)===norm(x.to)){markDone(i,items.length);feedback(document.getElementById('fb'),'good','Richtig!');setTimeout(renderBios,450)}else{const n=wrong(i,items.length);const h=x.label==='Paar'?'Bei einem Paar wird aus „wir/unsere/unser“ → „sie/ihre/ihr“.':'Ändere ich und alle Possessivformen konsequent in die 3. Person.';feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,x.to,h))}}}
function practiceComplete(){return(D.tasks||[]).filter(t=>!t.exam).every(t=>{try{const s=JSON.parse(localStorage.getItem(`SP_L10_${owner()}_T2_${t.id}`)||'null');return s&&Number(s._run||1)===run()&&Array.isArray(s.done)&&Number(s.total||0)>0&&s.done.length>=Number(s.total)}catch(e){return false}})}
function examAnswer(i,value){const items=D.examItems||[],item=items[i],s=read(items.length),id=String(i),correct=norm(value)===norm(item.a);if(!s.firstSeen.includes(id)){s.firstSeen.push(id);if(correct)s.firstCorrect.push(id)}if(!s.done.includes(id))s.done.push(id);write(s);feedback(document.getElementById('fb'),correct?'good':'bad',correct?'Richtig!':`Richtig wäre: <strong>${esc(item.a)}</strong>`);setTimeout(renderExam,650)}
function renderExam(){const items=D.examItems||[];if(!preview()&&!practiceComplete()){location.href='./index.html';return}const i=nextIndex(items);if(i==null)return finishExam(items.length);const item=items[i],s=read(items.length),body=item.type==='choice'?`<div class="sp-source">${esc(item.q)}</div><div class="l8-options">${shuffle(item.options||[]).map(x=>`<button class="l8-option" data-exam="${esc(x)}" type="button">${esc(x)}</button>`).join('')}</div>`:`<div class="sp-source">${esc(item.q)}</div><div class="l8-answer-row"><input class="l8-input" id="examAnswer" autocomplete="off" placeholder="Vollständige Antwort schreiben"><button class="l8-btn primary" id="examCheck" type="button">Prüfen</button></div>`;shell(`<section class="l8-card l8-exercise"><div class="l8-note"><strong>${esc(item.section||'Prüfung')}</strong> · Prüfungsfrage ${s.done.length+1} von ${items.length}<br>Wähle die richtige Antwort oder schreibe die vollständige Lösung. Jede Frage zählt nur beim ersten Versuch.</div>${body}<div id="fb"></div></section>`,s.done.length,items.length);document.querySelectorAll('[data-exam]').forEach(b=>b.onclick=()=>examAnswer(i,b.dataset.exam));const check=document.getElementById('examCheck');if(check){check.onclick=()=>examAnswer(i,document.getElementById('examAnswer').value);document.getElementById('examAnswer').onkeydown=e=>{if(e.key==='Enter')check.click()}}}
async function finishExam(total){const s=read(total),percent=Math.round((s.firstCorrect.length/Math.max(1,total))*100),max=run()===1?100:run()===2?200:300,points=Math.round(max*percent/100);if(!preview()&&!s.examSynced){s.examSynced=true;s.percent=percent;write(s);try{const mod=await import('/js/progress.js?v=20260831-central6');await (window.SPProgress||mod)?.recordExamResult?.({module:'wortschatz',moduleTitle:'Wortschatz',level:'A1',lesson:10,theme:2,topicId:TOPIC,title:'A1 Lektion 10 · Thema 2',file:'task.html?task=pruefung',taskKey:'pruefung',taskTitle:'Prüfung',percent,scorePercent:percent,stars:percent>=100?3:percent>=70?2:percent>=50?1:0})}catch(e){console.warn('L10T2 exam sync',e)}}shell(`<section class="l8-card l8-finish"><div class="l8-finish-icon">⭐</div><h2>Prüfung beendet</h2><div class="l8-score-total">${points} / ${max} Punkte</div><p>${s.firstCorrect.length} von ${total} Antworten waren beim ersten Versuch richtig.</p><div class="l8-row l8-center-actions"><a class="l8-btn primary" href="./index.html">Zur Übersicht</a></div></section>`,total,total)}
const renderers={karteikarten:renderCards,'wort-bedeutung':renderMeaning,'hoeren-bild':renderAudioImage,'artikel-plural':renderArticlePlural,'wehtun-schmerzen-basis':()=>renderTextItems(D.baseTransform||[],'base'),'possessiv-tabelle':renderPossTable,'possessiv-form':renderPossForm,'wehtun-schmerzen-alle':()=>renderTextItems(D.allTransform||[],'all'),'familie-luecken':renderFamily,biografien:renderBios,pruefung:renderExam};
try{(renderers[taskId]||renderMeaning)()}catch(e){console.error('L10T2',e);root.innerHTML='<div class="l8-wrap"><section class="l8-card"><h1>Aufgabe konnte nicht geladen werden.</h1><button class="l8-btn primary" onclick="location.reload()">Neu laden</button></section></div>'}
