import {renderSpHeader,bindSpHeader} from '/js/sp-header.js?v=theme-standard4';
const D=window.L10T2||{};const root=document.getElementById('app');
const taskId=String(new URLSearchParams(location.search).get('task')||'karteikarten').toLowerCase();
const task=(D.tasks||[]).find(x=>x.id===taskId)||D.tasks?.[0];
const TOPIC='wortschatz-a1-lektion-10-thema-2';
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(v){return String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[.,!?;:“”"'`´()]/g,'').replace(/\s+/g,' ')}
function shuffle(a){const b=a.slice();for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function profile(){try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||localStorage.getItem('SP_STUDENT_PROFILE')||'{}')||{}}catch(e){return{}}}
function owner(){const p=profile();return String(p.canonicalStudentId||p.docId||p.studentId||p.userId||p.authUid||p.uid||p.id||p.email||localStorage.getItem('SP_STUDENT_ID')||'student').trim().toLowerCase().replace(/[^a-z0-9äöüß@._-]+/gi,'_')}
function preview(){try{return ['teacher','lehrer','admin','owner','superadmin'].includes(String(localStorage.getItem('SP_LOGIN_ROLE')||localStorage.getItem('SP_ACTIVE_ROLE')||'').toLowerCase())||sessionStorage.getItem('SP_TEACHER_PREVIEW')==='1'||localStorage.getItem('SP_TEACHER_PREVIEW')==='1'}catch(e){return false}}
function run(){return Math.max(1,Math.min(3,Number(localStorage.getItem('SP_SCORE_RUN_'+TOPIC)||1)||1))}
function store(){return preview()?sessionStorage:localStorage}
function key(){return `SP_L10_${owner()}_T2_${taskId}`}
function read(total){let s={done:[],wrong:{},order:[],_run:run(),total};try{const x=JSON.parse(store().getItem(key())||'{}');if(x&&Number(x._run||1)===run())Object.assign(s,x)}catch(e){}s.done=Array.isArray(s.done)?s.done:[];s.wrong=s.wrong||{};s.order=Array.isArray(s.order)?s.order:[];s.total=total;return s}
function write(s){s._run=run();try{store().setItem(key(),JSON.stringify(s));window.dispatchEvent(new CustomEvent('sprachpilot-progress',{detail:{lesson:10,theme:2,topic:TOPIC,task:taskId,state:s}}))}catch(e){}}
function taskHead(done,total){const p=total?Math.round(done/total*100):0;return `<section class="l8-card l8-task-head"><div class="l8-task-title-block"><span class="l8-task-kicker">Aufgabe ${Math.max(1,(D.tasks||[]).findIndex(x=>x.id===taskId)+1)}</span><h1>${esc(task?.title||'Aufgabe')}</h1><p>${esc(task?.icon||'✅')} ${esc(task?.text||'')}</p></div><div class="l8-progress-row"><span>${done} von ${total} fertig</span><strong>${p}%</strong></div><div class="l8-progress"><div style="width:${p}%"></div></div></section>`}
function shell(body,done,total){const header=renderSpHeader({subtitle:'Gesundheit und Alltag · A1 Lektion 10 · Thema 2',color:{main:'#F4A3A3',dark:'#A86464',soft:'#FDF1F1',line:'#F3C9C9'}});root.innerHTML=`<div class="l10-theme-page">${header}<div class="l8-wrap">${preview()?'<div class="sp-teacher-preview-note">Lehrer-Vorschau: Teilnehmerfortschritt wird nicht verändert.</div>':''}${taskHead(done,total)}${body}<footer>© SprachPilot</footer></div></div>`;bindSpHeader(root)}
function finish(total){const s=read(total);s.done=Array.from({length:total},(_,i)=>String(i));write(s);shell(`<section class="l8-card l8-finish"><div class="l8-finish-icon">✓</div><h2>Gut gemacht!</h2><p>Du hast diese Aufgabe zu 100% abgeschlossen.</p><div class="l8-row l8-center-actions"><a class="l8-btn primary" href="./index.html">Zur Übersicht</a></div></section>`,total,total)}
function visual(c,small=false){return `<span class="sp-visual ${small?'small':''}"><img src="${esc(c.image)}" alt="" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><span class="sp-fallback" style="display:none">${esc(c.emoji||'📝')}</span></span>`}
function play(c){try{const a=new Audio(c.audio);a.onerror=()=>speak(c.full||c.word);const p=a.play();if(p&&p.catch)p.catch(()=>speak(c.full||c.word))}catch(e){speak(c.full||c.word)}}
function speak(t){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='de-DE';u.rate=.84;speechSynthesis.speak(u)}catch(e){}}
function feedback(el,type,html){el.innerHTML=`<div class="l8-feedback ${type}">${html}</div>`}
function ensureOrder(items,total){const ids=items.map((_,i)=>String(i));const s=read(total);const valid=s.order.filter(id=>ids.includes(id));const missing=ids.filter(id=>!valid.includes(id));if(missing.length||valid.length!==ids.length){s.order=valid.concat(shuffle(missing));write(s)}return s}
function nextIndex(items){const s=ensureOrder(items,items.length);const id=s.order.find(x=>!s.done.includes(x));return id==null?null:Number(id)}
function markDone(i,total){const s=read(total);const id=String(i);if(!s.done.includes(id))s.done.push(id);delete s.wrong[id];write(s)}
function wrong(i,total){const s=read(total),id=String(i);s.wrong[id]=(Number(s.wrong[id])||0)+1;write(s);return s.wrong[id]}
function hint(n,answer,h=''){if(n===1)return 'Noch nicht richtig. Versuch es noch einmal.';if(n===2)return h||'Achte genau auf Person, Genus und Satzform.';return `<strong>Lösung:</strong> ${esc(answer)}`}
function renderCards(){const items=D.cards||[],i=nextIndex(items);if(i==null)return finish(items.length);const c=items[i],s=read(items.length);shell(`<section class="l8-card l8-card-stage"><div class="l8-flip-wrap"><div class="l8-flip-card" id="flip" tabindex="0"><div class="l8-flip-face l8-flip-front">${visual(c)}<div class="l8-card-translation"><span>Bedeutung</span><strong>${esc(c.meaning)}</strong></div></div><div class="l8-flip-face l8-flip-back"><div class="l8-flip-back-grid"><div class="l8-back-image">${visual(c,true)}</div><div class="l8-back-info"><div class="l8-flip-word">${esc(c.full)}</div>${c.plural?`<div class="l8-card-detail"><span>Plural</span><strong>${esc(c.plural)}</strong></div>`:''}<button class="l8-btn" id="listen">🔊 Anhören</button></div></div></div></div></div><div class="l8-row l8-center-actions l8-card-actions"><button class="l8-btn primary" id="mic">🎤 Sprechen</button><button class="l8-btn" id="writeBtn">✍️ Schreiben</button></div><div class="l8-card-write" id="writeBox" hidden><div class="l8-answer-row"><input class="l8-input" id="answer" autocomplete="off" placeholder="Wort schreiben"><button class="l8-btn primary" id="check">Prüfen</button></div></div><div id="fb"></div></section>`,s.done.length,items.length);
 const flip=document.getElementById('flip');const reveal=()=>{if(flip.classList.contains('flipped'))return;flip.classList.add('flipped');const n=wrong(i,items.length);feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,c.full,c.meaning))};flip.onclick=reveal;flip.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();reveal()}};document.getElementById('listen').onclick=e=>{e.stopPropagation();play(c)};document.getElementById('writeBtn').onclick=()=>{document.getElementById('writeBox').hidden=false;document.getElementById('answer').focus()};const check=v=>{const accepted=[c.full,c.word].filter(Boolean).map(norm);if(accepted.includes(norm(v))){markDone(i,items.length);feedback(document.getElementById('fb'),'good','Richtig!');setTimeout(renderCards,350)}else{const n=wrong(i,items.length);feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,c.full,c.meaning))}};document.getElementById('check').onclick=()=>check(document.getElementById('answer').value);document.getElementById('answer').onkeydown=e=>{if(e.key==='Enter')check(e.target.value)};document.getElementById('mic').onclick=()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){document.getElementById('writeBtn').click();return}try{const r=new R();r.lang='de-DE';r.interimResults=false;r.onresult=e=>check(e.results[0][0].transcript);r.onerror=()=>document.getElementById('writeBtn').click();r.start()}catch(e){document.getElementById('writeBtn').click()}}}
function renderMeaning(){const items=D.cards||[],i=nextIndex(items);if(i==null)return finish(items.length);const c=items[i],opts=shuffle([c,...shuffle(items.filter(x=>x.id!==c.id)).slice(0,3)]);const s=read(items.length);shell(`<section class="l8-card l8-exercise"><div class="sp-big-word">${esc(c.full)}</div><div class="l8-options">${opts.map(o=>`<button class="l8-option" data-id="${esc(o.id)}">${esc(o.meaning)}</button>`).join('')}</div><div id="fb"></div></section>`,s.done.length,items.length);document.querySelectorAll('.l8-option').forEach(b=>b.onclick=()=>{if(b.dataset.id===c.id){markDone(i,items.length);feedback(document.getElementById('fb'),'good','Richtig!');setTimeout(renderMeaning,350)}else{const n=wrong(i,items.length);feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,c.meaning,'Lies das Wort noch einmal und achte auf die genaue Bedeutung.'))}})}
function renderAudioImage(){const items=D.cards||[],i=nextIndex(items);if(i==null)return finish(items.length);const c=items[i],opts=shuffle([c,...shuffle(items.filter(x=>x.id!==c.id)).slice(0,3)]),s=read(items.length);shell(`<section class="l8-card l8-exercise"><div class="sp-listen-center"><button class="l8-btn primary sp-listen-big" id="play">🔊 Wort anhören</button></div><div class="sp-image-options">${opts.map(o=>`<button class="sp-image-option" data-id="${esc(o.id)}">${visual(o)}</button>`).join('')}</div><div id="fb"></div></section>`,s.done.length,items.length);document.getElementById('play').onclick=()=>play(c);setTimeout(()=>play(c),250);document.querySelectorAll('.sp-image-option').forEach(b=>b.onclick=()=>{if(b.dataset.id===c.id){markDone(i,items.length);feedback(document.getElementById('fb'),'good','Richtig!');setTimeout(renderAudioImage,350)}else{const n=wrong(i,items.length);feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,c.full,'Höre das Wort noch einmal.'))}})}
function renderArticlePlural(){const items=D.nouns||[],i=nextIndex(items);if(i==null)return finish(items.length);const c=items[i],s=read(items.length);shell(`<section class="l8-card l8-exercise"><div class="sp-noun-card">${visual(c,true)}<strong>${esc(c.word)}</strong></div><p><strong>1.</strong> Wähle den Artikel.</p><div class="l8-options sp-article-options">${shuffle(['der','die','das']).map(a=>`<button class="l8-option article" data-a="${a}">${a}</button>`).join('')}</div><p><strong>2.</strong> Schreibe den Plural <em>mit Artikel</em>.</p><div class="l8-answer-row"><input class="l8-input" id="plural" placeholder="z. B. die ..."><button class="l8-btn primary" id="check">Prüfen</button></div><div id="fb"></div></section>`,s.done.length,items.length);let chosen='';document.querySelectorAll('.article').forEach(b=>b.onclick=()=>{document.querySelectorAll('.article').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');chosen=b.dataset.a});document.getElementById('check').onclick=()=>{const ok=chosen===c.article&&norm(document.getElementById('plural').value)===norm(c.plural);if(ok){markDone(i,items.length);feedback(document.getElementById('fb'),'good','Richtig!');setTimeout(renderArticlePlural,400)}else{const n=wrong(i,items.length);feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,`${c.article} ${c.word} · ${c.plural}`,'Prüfe zuerst das Genus. Im Plural steht immer „die“.'))}}}
function renderTextItems(items,kind){const i=nextIndex(items);if(i==null)return finish(items.length);const x=items[i],s=read(items.length);shell(`<section class="l8-card l8-exercise"><div class="sp-transform"><div class="sp-source">${esc(x.q)}</div><div class="sp-arrow">↓</div><div class="l8-answer-row"><input class="l8-input" id="ans" autocomplete="off" placeholder="Schreibe den neuen Satz."><button class="l8-btn primary" id="check">Prüfen</button></div></div><div id="fb"></div></section>`,s.done.length,items.length);const check=()=>{const v=document.getElementById('ans').value;if(norm(v)===norm(x.a)){markDone(i,items.length);feedback(document.getElementById('fb'),'good','Richtig!');setTimeout(()=>renderTextItems(items,kind),350)}else{const n=wrong(i,items.length);const h=kind==='base'?'Achte auf ich/du/Sie und auf die passende Form von haben bzw. den Possessivartikel.':'Achte auf die Person: hat/haben/habt und mein/dein/sein/ihr/unser/euer.';feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,x.a,h))}};document.getElementById('check').onclick=check;document.getElementById('ans').onkeydown=e=>{if(e.key==='Enter')check()}}
function renderPossTable(){const rows=D.possRows||[],s=read(rows.length);const order=ensureOrder(rows,rows.length).order.map(Number);shell(`<section class="l8-card l8-exercise"><p>Schreibe rechts die zwei Grundformen im Nominativ.</p><div class="sp-poss-table"><div class="sp-poss-head">Pronomen</div><div class="sp-poss-head">maskulin / neutral</div><div class="sp-poss-head">feminin / Plural</div>${order.map(i=>{const r=rows[i],done=s.done.includes(String(i));return `<div class="sp-pronoun">${esc(r[0])}</div><input class="l8-input poss" data-i="${i}" data-k="1" value="${done?esc(r[1]):''}" ${done?'disabled':''}><input class="l8-input poss" data-i="${i}" data-k="2" value="${done?esc(r[2]):''}" ${done?'disabled':''}>`}).join('')}</div><div class="l8-row l8-center-actions"><button class="l8-btn primary" id="check">Prüfen</button></div><div id="fb"></div></section>`,s.done.length,rows.length);document.getElementById('check').onclick=()=>{let newly=0;rows.forEach((r,i)=>{if(s.done.includes(String(i)))return;const a=document.querySelector(`.poss[data-i="${i}"][data-k="1"]`),b=document.querySelector(`.poss[data-i="${i}"][data-k="2"]`);if(a&&b&&norm(a.value)===norm(r[1])&&norm(b.value)===norm(r[2])){markDone(i,rows.length);a.classList.add('correct');b.classList.add('correct');newly++}else if((a&&a.value)||(b&&b.value)){a?.classList.add('incorrect');b?.classList.add('incorrect')}});const now=read(rows.length);if(now.done.length===rows.length)return setTimeout(()=>finish(rows.length),300);feedback(document.getElementById('fb'),newly?'good':'bad',newly?`${newly} Zeile(n) richtig. Ergänze die übrigen.`:'Noch nicht richtig. Prüfe die Person und die Endung.');setTimeout(renderPossTable,500)}}
function renderPossForm(){const items=D.possForm||[],i=nextIndex(items);if(i==null)return finish(items.length);const x=items[i],s=read(items.length);shell(`<section class="l8-card l8-exercise"><div class="sp-big-word">${esc(x.q)}</div><div class="l8-answer-row"><input class="l8-input" id="ans" autocomplete="off" placeholder="Form schreiben"><button class="l8-btn primary" id="check">Prüfen</button></div><div id="fb"></div></section>`,s.done.length,items.length);const check=()=>{if(norm(document.getElementById('ans').value)===norm(x.a)){markDone(i,items.length);feedback(document.getElementById('fb'),'good','Richtig!');setTimeout(renderPossForm,300)}else{const n=wrong(i,items.length);feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,x.a,'Maskulin und neutral haben keine Endung; feminin und Plural bekommen -e.'))}};document.getElementById('check').onclick=check;document.getElementById('ans').onkeydown=e=>{if(e.key==='Enter')check()}}
function renderFamily(){const lines=D.family?.text||[];const gaps=[];lines.forEach((r,li)=>{const ans=String(r[1]||'').split('|').filter(Boolean);ans.forEach((a,gi)=>gaps.push({id:`${li}-${gi}`,li,gi,a}))});const total=gaps.length,s=read(total);const idToIndex=Object.fromEntries(gaps.map((g,i)=>[g.id,i]));const html=lines.map((r,li)=>{let text=esc(r[0]),answers=String(r[1]||'').split('|').filter(Boolean),gi=0;text=text.replace(/___/g,()=>{const id=`${li}-${gi}`,idx=idToIndex[id],done=s.done.includes(String(idx)),val=done?answers[gi]:'';gi++;return `<input class="l8-input sp-inline-gap" data-idx="${idx}" value="${esc(val)}" ${done?'disabled':''}>`});return `<p class="sp-family-line">${text}</p>`}).join('');shell(`<section class="l8-card l8-exercise"><div class="sp-family-text">${html}</div><div class="l8-row l8-center-actions"><button class="l8-btn primary" id="check">Prüfen</button></div><div id="fb"></div></section>`,s.done.length,total);document.getElementById('check').onclick=()=>{let correct=0;gaps.forEach((g,i)=>{if(s.done.includes(String(i)))return;const inp=document.querySelector(`[data-idx="${i}"]`);if(inp&&norm(inp.value)===norm(g.a)){markDone(i,total);inp.classList.add('correct');correct++}else if(inp&&inp.value)inp.classList.add('incorrect')});const now=read(total);if(now.done.length===total)return setTimeout(()=>finish(total),350);feedback(document.getElementById('fb'),correct?'good':'bad',correct?`${correct} Lücke(n) richtig. Mach weiter.`:'Noch nicht richtig. Frage: Zu wem gehört die Person oder Sache?');setTimeout(renderFamily,650)}}
function renderBios(){const items=D.bios||[],i=nextIndex(items);if(i==null)return finish(items.length);const x=items[i],s=read(items.length);shell(`<section class="l8-card l8-exercise"><div class="sp-bio-label">${esc(x.label)}</div><h2>Ausgangstext</h2><div class="sp-source sp-bio-source">${esc(x.from)}</div><h2>3. Person</h2><textarea class="l8-input sp-textarea" id="ans" rows="7" placeholder="Schreibe den ganzen Text um."></textarea><div class="l8-row l8-center-actions"><button class="l8-btn primary" id="check">Prüfen</button></div><div id="fb"></div></section>`,s.done.length,items.length);document.getElementById('check').onclick=()=>{const v=document.getElementById('ans').value;if(norm(v)===norm(x.to)){markDone(i,items.length);feedback(document.getElementById('fb'),'good','Richtig!');setTimeout(renderBios,450)}else{const n=wrong(i,items.length);const h=x.label==='Paar'?'Bei einem Paar wird aus „wir/unsere/unser“ → „sie/ihre/ihr“.':'Ändere ich und alle Possessivformen konsequent in die 3. Person.';feedback(document.getElementById('fb'),n>=3?'warn':'bad',hint(n,x.to,h))}}}
const renderers={karteikarten:renderCards,'wort-bedeutung':renderMeaning,'hoeren-bild':renderAudioImage,'artikel-plural':renderArticlePlural,'wehtun-schmerzen-basis':()=>renderTextItems(D.baseTransform||[],'base'),'possessiv-tabelle':renderPossTable,'possessiv-form':renderPossForm,'wehtun-schmerzen-alle':()=>renderTextItems(D.allTransform||[],'all'),'familie-luecken':renderFamily,biografien:renderBios};
try{(renderers[taskId]||renderMeaning)()}catch(e){console.error('L10T2',e);root.innerHTML='<div class="l8-wrap"><section class="l8-card"><h1>Aufgabe konnte nicht geladen werden.</h1><button class="l8-btn primary" onclick="location.reload()">Neu laden</button></section></div>'}
