import {renderSpHeader,bindSpHeader} from '/js/sp-header.js?v=theme-standard4';
const D=window.L11T1||{cards:[],phrases:[],tasks:[]};
const M=window.L11T1SourceMode;
const root=document.getElementById('app');
const taskId=String(new URLSearchParams(location.search).get('task')||'karteikarten').toLowerCase();
const task=D.tasks.find(t=>t.id===taskId)||D.tasks.find(t=>t.id==='karteikarten');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
const activeCards=()=>M?.activeCards?.()||D.cards;
const activeIds=()=>new Set(activeCards().map(x=>x.id));
const mode=()=>M?.mode?.()||'all';
const progressKey=id=>'SP_L11_T1_'+id+'_'+mode();
const placeIds=new Set(['werkstatt','tankstelle','museum','bahnhof','metzgerei','post','hotel','buecherei','baumarkt','bushaltestelle','schule','apotheke','kindergarten','kino','supermarkt','geschaeft','bank','restaurant','polizei','krankenhaus','spielplatz','fussballplatz','praxis','cafe','markt','baeckerei']);
const nouns=()=>activeCards().filter(w=>w.article),places=()=>activeCards().filter(w=>placeIds.has(w.id));
const LANGS=[['en','Englisch',['en','english','englisch']],['ru','Russisch',['ru','russian','russisch']],['tr','Türkisch',['tr','turkish','türkisch','tuerkisch']],['uk','Ukrainisch',['uk','ua','ukrainian','ukrainisch']],['ar','Arabisch',['ar','arabic','arabisch']],['ja','Japanisch',['ja','japanese','japanisch']],['ro','Rumänisch',['ro','romanian','rumänisch','rumaenisch']],['pl','Polnisch',['pl','polish','polnisch']],['ku','Kurdisch',['ku','kurdish','kurdisch','kurmanci']],['fa','Persisch',['fa','farsi','persisch']],['fr','Französisch',['fr','french','französisch','franzoesisch']],['es','Spanisch',['es','spanish','spanisch']],['it','Italienisch',['it','italian','italienisch']]];
const norm=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function language(){let p={};try{p=JSON.parse(localStorage.getItem('SP_USER_PROFILE')||localStorage.getItem('SP_STUDENT_PROFILE')||'{}')||{}}catch(e){}const raw=norm(p.motherLanguageCode||p.muttersprache||p.motherLanguage||p.language||localStorage.getItem('SP_MOTHER_LANGUAGE')||'en');for(const [code,label,keys] of LANGS)if(keys.some(k=>raw===norm(k)||raw.includes(norm(k))))return{code,label};return{code:'en',label:'Englisch'}}
function tr(w){const l=language();return{label:l.label,text:w?.translations?.[l.code]||w?.translations?.en||''}}
function markDone(){try{localStorage.setItem(progressKey(taskId),'100');localStorage.setItem('SP_L11_LAST_TASK_T1',taskId);sessionStorage.setItem('SP_L11_LAST_TASK_T1',taskId)}catch(e){}}
function frame(body){const idx=Math.max(0,D.tasks.findIndex(t=>t.id===task.id));root.innerHTML=`<div class="l10-theme-page">${renderSpHeader({subtitle:`${task.title} · A1 Lektion 11 · Thema 1`,color:{main:'#F6D78B',dark:'#A88633',soft:'#FDF8EC',line:'#F3E2B7'}})}<div class="l8-wrap"><section class="l8-card l8-task-head"><div class="l8-task-title-block"><span class="l8-task-kicker">Aufgabe ${idx+1}</span><h1>${esc(task.title)}</h1><p>${esc(task.icon||'✅')} ${esc(task.cardText||'Bearbeite die Aufgabe.')}</p></div><div class="l8-progress-row"><span>Aufgabe</span><strong>0%</strong></div><div class="l8-progress"><div style="width:0%"></div></div></section>${body}</div></div>`;bindSpHeader(root);document.querySelectorAll('.sp-header__nav-link').forEach(a=>{if(String(a.textContent||'').trim()==='Übersicht')a.href='uebersicht.html'})}
function finish(score,total){const pct=Math.round(score/Math.max(1,total)*100);if(pct===100)markDone();document.querySelector('#exercise').innerHTML=`<section class="l8-card l8-card-stage"><h2>${pct===100?'Gut gemacht!':'Fertig'}</h2><p>${score} / ${total} richtig · ${pct}%</p><div class="l11-controls"><a class="l11-btn primary" href="index.html">Zur Themenübersicht</a><button class="l11-btn" onclick="location.reload()">Noch einmal</button></div></section>`;const strong=document.querySelector('.l8-progress-row strong');const bar=document.querySelector('.l8-progress>div');if(strong)strong.textContent=pct+'%';if(bar)bar.style.width=pct+'%'}
function quiz(items){let pos=0,score=0;const render=()=>{if(pos>=items.length)return finish(score,items.length);const it=items[pos],opts=shuffle(it.options);document.querySelector('#exercise').innerHTML=`<section class="l8-card l8-card-stage">${it.image?`<img class="l11-card-image" src="${it.image}" alt="" onerror="this.style.display='none'">`:''}<div class="l11-question">${esc(it.q)}</div><div class="l11-options">${opts.map(o=>`<button class="l11-option" data-v="${esc(o)}">${esc(o)}</button>`).join('')}</div><div class="l11-feedback" id="fb"></div></section>`;const strong=document.querySelector('.l8-progress-row strong');const bar=document.querySelector('.l8-progress>div');const p=Math.round(pos/Math.max(1,items.length)*100);if(strong)strong.textContent=p+'%';if(bar)bar.style.width=p+'%';document.querySelectorAll('.l11-option').forEach(b=>b.onclick=()=>{document.querySelectorAll('.l11-option').forEach(x=>x.disabled=true);const ok=b.dataset.v===it.a;b.classList.add(ok?'correct':'wrong');if(ok)score++;else document.querySelectorAll('.l11-option').forEach(x=>{if(x.dataset.v===it.a)x.classList.add('correct')});document.querySelector('#fb').textContent=ok?'Richtig!':`Richtig: ${it.a}`;setTimeout(()=>{pos++;render()},650)});};frame('<div id="exercise"></div>');render()}
function flashcards(){const arr=shuffle(activeCards()),state={i:0};frame('<div id="exercise"></div>');const render=()=>{const w=arr[state.i],translation=tr(w);const p=Math.round(state.i/Math.max(1,arr.length)*100);const strong=document.querySelector('.l8-progress-row strong');const bar=document.querySelector('.l8-progress>div');if(strong)strong.textContent=p+'%';if(bar)bar.style.width=p+'%';document.querySelector('#exercise').innerHTML=`<section class="l8-card l8-card-stage"><img class="l11-card-image" src="${w.image}" alt="" onerror="this.style.display='none'"><div class="l11-flash">${esc(w.full)}</div>${w.plural?`<div style="text-align:center"><b>Plural:</b> ${esc(w.plural)}</div>`:''}${translation.text?`<div style="text-align:center;margin-top:10px"><b>${esc(translation.label)}:</b> ${esc(translation.text)}</div>`:''}<div class="l11-controls" style="justify-content:center"><button class="l11-btn" id="audio">🔊 Hören</button><button class="l11-btn primary" id="next">${state.i===arr.length-1?'Fertig':'Weiter'}</button></div><div class="l11-small" style="text-align:center">${state.i+1} / ${arr.length}</div></section>`;document.querySelector('#audio').onclick=()=>new Audio(w.audio).play().catch(()=>{});document.querySelector('#next').onclick=()=>{if(state.i===arr.length-1){markDone();finish(arr.length,arr.length)}else{state.i++;render()}}};render()}
function articlePlural(){const items=shuffle(nouns()).slice(0,20).map(w=>({q:`Welcher Artikel passt zu „${w.full.replace(/^(der|die|das) /,'')}“?`,a:w.article,options:['der','die','das']}));quiz(items)}
function imageWord(){const pool=shuffle(activeCards().filter(w=>!['links','rechts','geradeaus','fremd','fliegen','abbiegen','in_der_naehe','erste','zweite','dritte','vierte'].includes(w.id))).slice(0,16);quiz(pool.map(w=>{const distract=shuffle(pool.filter(x=>x.id!==w.id)).slice(0,3).map(x=>x.full);return{q:'Welches Wort passt zum Bild?',a:w.full,options:[w.full,...distract],image:w.image}}))}
function placesQuiz(){const available=new Set(places().map(x=>x.full));const cases=[['Wo kauft man Medikamente?','die Apotheke'],['Wo kauft man Brot und Brötchen?','die Bäckerei'],['Wo fährt ein Zug ab?','der Bahnhof'],['Wo repariert man ein Auto?','die Werkstatt'],['Wo tankt man Benzin?','die Tankstelle'],['Wo sieht man einen Film?','das Kino'],['Wo bekommt man medizinische Hilfe im Notfall?','das Krankenhaus'],['Wo kann man Geld abheben?','die Bank'],['Wo wartet man auf den Bus?','die Bushaltestelle'],['Wo spielen Kinder draußen?','der Spielplatz'],['Wo kauft man Fleisch?','die Metzgerei'],['Wo schickt man einen Brief?','die Post']].filter(([,a])=>available.has(a));const names=places().map(x=>x.full);quiz(shuffle(cases).map(([q,a])=>({q,a,options:[a,...shuffle(names.filter(x=>x!==a)).slice(0,3)]})))}
function orientation(){const p=D.phrases||[];const items=[{q:'Du willst höflich fragen, wo ein Ort ist.',a:'Entschuldigung, wo ist …?'},{q:'Du sagst, dass du einen Ort suchst.',a:'Ich suche …'},{q:'Du möchtest wissen, wo du einen Ort findest.',a:'Wo finde ich …?'},{q:'Du möchtest wissen, ob ein Ort in der Nähe ist.',a:'Ist hier … in der Nähe?'},{q:'Du fragst, ob es einen Ort in der Nähe gibt.',a:'Gibt es hier … in der Nähe?'}].map(x=>({...x,options:p.slice()}));quiz(shuffle(items))}
function directions(){const ids=activeIds();const words=['geradeaus','links','rechts',...(ids.has('abbiegen')?['abbiegen']:[]),...(ids.has('in_der_naehe')?['in der Nähe']:[])];const items=[{q:'⬆️',a:'geradeaus',options:words},{q:'⬅️',a:'links',options:words},{q:'➡️',a:'rechts',options:words}];if(ids.has('zweite'))items.push({q:'„Nehmen Sie die ___ Straße links.” Es ist Straße Nummer 2.',a:'zweite',options:['erste','zweite','dritte','vierte']});if(ids.has('abbiegen'))items.push({q:'„Biegen Sie rechts ___.”',a:'ab',options:['ab','an','aus','zu']});quiz(shuffle(items))}
function exam(){const ids=activeIds();const a=shuffle(nouns()).slice(0,8).map(w=>({q:`Artikel: ${w.full.replace(/^(der|die|das) /,'')}`,a:w.article,options:['der','die','das']}));const available=new Set(places().map(x=>x.full));const b=[{q:'Wo kauft man Medikamente?',a:'die Apotheke',options:['die Apotheke','die Bank','das Kino','die Schule']},{q:'Wo fährt der Zug ab?',a:'der Bahnhof',options:['der Bahnhof','der Markt','das Café','die Praxis']}].filter(x=>available.has(x.a));b.push({q:'⬅️ bedeutet …',a:'links',options:['links','rechts','geradeaus','fremd']},{q:'➡️ bedeutet …',a:'rechts',options:['rechts','links','geradeaus','fremd']},{q:'Du suchst einen Ort. Welche Frage passt?',a:'Wo finde ich …?',options:D.phrases.slice()});if(ids.has('abbiegen'))b.push({q:'Welche Form ist richtig?',a:'Biegen Sie links ab.',options:['Biegen Sie links ab.','Biegen Sie links an.','Biegen Sie links aus.','Biegen links Sie ab.']});quiz(shuffle([...a,...shuffle(b).slice(0,6)]))}
switch(taskId){case'karteikarten':flashcards();break;case'bild-wort':imageWord();break;case'artikel-plural':articlePlural();break;case'orte-zuordnen':placesQuiz();break;case'orientierung':orientation();break;case'wegbeschreibung':directions();break;case'pruefung':exam();break;default:flashcards();}