import {renderSpHeader,bindSpHeader} from '/js/sp-header.js?v=theme-standard4';
const D=window.L11T1||{cards:[],phrases:[],tasks:[]};
const root=document.getElementById('app');
const taskId=String(new URLSearchParams(location.search).get('task')||'karteikarten').toLowerCase();
const task=D.tasks.find(t=>t.id===taskId)||D.tasks.find(t=>t.id==='karteikarten');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
const nouns=D.cards.filter(w=>w.article),places=D.cards.filter(w=>['werkstatt','tankstelle','museum','bahnhof','metzgerei','post','hotel','buecherei','baumarkt','bushaltestelle','schule','apotheke','kindergarten','kino','laden','supermarkt','geschaeft','bank','restaurant','polizei','krankenhaus','spielplatz','fussballplatz','praxis','cafe','markt','baeckerei'].includes(w.id));
function markDone(){try{localStorage.setItem('SP_L11_T1_'+taskId,'100');localStorage.setItem('SP_L11_LAST_TASK_T1',taskId);sessionStorage.setItem('SP_L11_LAST_TASK_T1',taskId)}catch(e){}}
function frame(body){const idx=Math.max(0,D.tasks.findIndex(t=>t.id===task.id));root.innerHTML=`<div class="l10-theme-page">${renderSpHeader({subtitle:`${task.title} · A1 Lektion 11 · Thema 1`,color:{main:'#F6D78B',dark:'#A88633',soft:'#FDF8EC',line:'#F3E2B7'}})}<div class="l8-wrap"><section class="l8-card l8-task-head"><div class="l8-task-title-block"><span class="l8-task-kicker">Aufgabe ${idx+1}</span><h1>${esc(task.title)}</h1><p>${esc(task.icon||'✅')} ${esc(task.cardText||'Bearbeite die Aufgabe.')}</p></div><div class="l8-progress-row"><span>Aufgabe</span><strong>0%</strong></div><div class="l8-progress"><div style="width:0%"></div></div></section>${body}</div></div>`;bindSpHeader(root);document.querySelectorAll('.sp-header__nav-link').forEach(a=>{if(String(a.textContent||'').trim()==='Übersicht')a.href='uebersicht.html'})}
function finish(score,total){const pct=Math.round(score/Math.max(1,total)*100);if(pct===100)markDone();document.querySelector('#exercise').innerHTML=`<section class="l8-card l8-card-stage"><h2>${pct===100?'Gut gemacht!':'Fertig'}</h2><p>${score} / ${total} richtig · ${pct}%</p><div class="l11-controls"><a class="l11-btn primary" href="index.html">Zur Themenübersicht</a><button class="l11-btn" onclick="location.reload()">Noch einmal</button></div></section>`;const strong=document.querySelector('.l8-progress-row strong');const bar=document.querySelector('.l8-progress>div');if(strong)strong.textContent=pct+'%';if(bar)bar.style.width=pct+'%'}
function quiz(items){let pos=0,score=0;const render=()=>{if(pos>=items.length)return finish(score,items.length);const it=items[pos],opts=shuffle(it.options);document.querySelector('#exercise').innerHTML=`<section class="l8-card l8-card-stage">${it.image?`<img class="l11-card-image" src="${it.image}" alt="" onerror="this.style.display='none'">`:''}<div class="l11-question">${esc(it.q)}</div><div class="l11-options">${opts.map(o=>`<button class="l11-option" data-v="${esc(o)}">${esc(o)}</button>`).join('')}</div><div class="l11-feedback" id="fb"></div></section>`;const strong=document.querySelector('.l8-progress-row strong');const bar=document.querySelector('.l8-progress>div');const p=Math.round(pos/Math.max(1,items.length)*100);if(strong)strong.textContent=p+'%';if(bar)bar.style.width=p+'%';document.querySelectorAll('.l11-option').forEach(b=>b.onclick=()=>{document.querySelectorAll('.l11-option').forEach(x=>x.disabled=true);const ok=b.dataset.v===it.a;b.classList.add(ok?'correct':'wrong');if(ok)score++;else document.querySelectorAll('.l11-option').forEach(x=>{if(x.dataset.v===it.a)x.classList.add('correct')});document.querySelector('#fb').textContent=ok?'Richtig!':`Richtig: ${it.a}`;setTimeout(()=>{pos++;render()},650)});};frame('<div id="exercise"></div>');render()}
function flashcards(){const arr=shuffle(D.cards),state={i:0};frame('<div id="exercise"></div>');const render=()=>{const w=arr[state.i];const p=Math.round(state.i/Math.max(1,arr.length)*100);const strong=document.querySelector('.l8-progress-row strong');const bar=document.querySelector('.l8-progress>div');if(strong)strong.textContent=p+'%';if(bar)bar.style.width=p+'%';document.querySelector('#exercise').innerHTML=`<section class="l8-card l8-card-stage"><img class="l11-card-image" src="${w.image}" alt="" onerror="this.style.display='none'"><div class="l11-flash">${esc(w.full)}</div>${w.plural?`<div style="text-align:center">${esc(w.plural)}</div>`:''}<div class="l11-controls" style="justify-content:center"><button class="l11-btn" id="audio">🔊 Hören</button><button class="l11-btn primary" id="next">${state.i===arr.length-1?'Fertig':'Weiter'}</button></div><div class="l11-small" style="text-align:center">${state.i+1} / ${arr.length}</div></section>`;document.querySelector('#audio').onclick=()=>new Audio(w.audio).play().catch(()=>{});document.querySelector('#next').onclick=()=>{if(state.i===arr.length-1){markDone();finish(arr.length,arr.length)}else{state.i++;render()}}};render()}
function articlePlural(){const items=shuffle(nouns).slice(0,20).map(w=>({q:`Welcher Artikel passt zu „${w.full.replace(/^(der|die|das) /,'')}“?`,a:w.article,options:['der','die','das']}));quiz(items)}
function imageWord(){const pool=shuffle(D.cards.filter(w=>!['links','rechts','geradeaus','fremd','fliegen','abbiegen','in_der_naehe','erste_strasse','zweite_strasse','dritte_strasse','vierte_strasse'].includes(w.id))).slice(0,16);quiz(pool.map(w=>{const distract=shuffle(pool.filter(x=>x.id!==w.id)).slice(0,3).map(x=>x.full);return{q:'Welches Wort passt zum Bild?',a:w.full,options:[w.full,...distract],image:w.image}}))}
function placesQuiz(){const cases=[['Wo kauft man Medikamente?','die Apotheke'],['Wo kauft man Brot und Brötchen?','die Bäckerei'],['Wo fährt ein Zug ab?','der Bahnhof'],['Wo repariert man ein Auto?','die Werkstatt'],['Wo tankt man Benzin?','die Tankstelle'],['Wo sieht man einen Film?','das Kino'],['Wo bekommt man medizinische Hilfe im Notfall?','das Krankenhaus'],['Wo kann man Geld abheben?','die Bank'],['Wo wartet man auf den Bus?','die Bushaltestelle'],['Wo spielen Kinder draußen?','der Spielplatz'],['Wo kauft man Fleisch?','die Metzgerei'],['Wo schickt man einen Brief?','die Post']];const names=places.map(x=>x.full);quiz(shuffle(cases).map(([q,a])=>({q,a,options:[a,...shuffle(names.filter(x=>x!==a)).slice(0,3)]})))}
function orientation(){const items=[{q:'Du willst höflich nach einem Ort fragen.',a:'Entschuldigung, wo ist …?',options:['Entschuldigung, wo ist …?','Fahren Sie geradeaus.','Biegen Sie rechts ab.','Ich bin fremd.']},{q:'Du suchst einen bestimmten Ort.',a:'Wo finde ich …?',options:['Wo finde ich …?','Gehen Sie geradeaus.','An der Ampel rechts.','Nehmen Sie die zweite Straße links.']},{q:'Du willst wissen, ob etwas nicht weit weg ist.',a:'Ist hier … in der Nähe?',options:['Ist hier … in der Nähe?','Wo ist die Autobahn?','Fahren Sie nach links.','Ich suche den Schlüssel.']},{q:'Welche Anweisung bedeutet: nicht links und nicht rechts?',a:'Fahren Sie geradeaus.',options:['Fahren Sie geradeaus.','Fahren Sie nach links.','Fahren Sie nach rechts.','Biegen Sie links ab.']},{q:'Welche Anweisung passt zu einer Abbiegung nach links?',a:'Biegen Sie links ab.',options:['Biegen Sie links ab.','Gehen Sie geradeaus.','An der Ampel rechts.','Fahren Sie nach rechts.']}];quiz(shuffle(items))}
function directions(){const items=[{q:'⬆️',a:'geradeaus',options:['geradeaus','links','rechts','abbiegen']},{q:'⬅️',a:'links',options:['links','rechts','geradeaus','in der Nähe']},{q:'➡️',a:'rechts',options:['rechts','links','geradeaus','fremd']},{q:'„An der Ampel ___.” Du sollst nach links fahren.',a:'links',options:['links','rechts','geradeaus','fremd']},{q:'„Nehmen Sie die ___ Straße links.” Es ist Straße Nummer 2.',a:'zweite',options:['erste','zweite','dritte','vierte']},{q:'„Biegen Sie rechts ___.”',a:'ab',options:['ab','an','aus','zu']}];quiz(shuffle(items))}
function exam(){const a=shuffle(D.cards.filter(w=>w.article)).slice(0,8).map(w=>({q:`Artikel: ${w.full.replace(/^(der|die|das) /,'')}`,a:w.article,options:['der','die','das']}));const b=shuffle([{q:'Wo kauft man Medikamente?',a:'die Apotheke',options:['die Apotheke','die Bank','das Kino','die Schule']},{q:'Wo fährt der Zug ab?',a:'der Bahnhof',options:['der Bahnhof','der Markt','das Café','die Praxis']},{q:'⬅️ bedeutet …',a:'links',options:['links','rechts','geradeaus','fremd']},{q:'➡️ bedeutet …',a:'rechts',options:['rechts','links','geradeaus','fremd']},{q:'Du suchst einen Ort. Welche Frage passt?',a:'Wo finde ich …?',options:['Wo finde ich …?','Fahren Sie geradeaus.','Biegen Sie ab.','An der Ampel links.']},{q:'Welche Form ist richtig?',a:'Biegen Sie links ab.',options:['Biegen Sie links ab.','Biegen Sie links an.','Biegen Sie links aus.','Biegen links Sie ab.']}]).slice(0,6);quiz(shuffle([...a,...b]))}
switch(taskId){case'karteikarten':flashcards();break;case'bild-wort':imageWord();break;case'artikel-plural':articlePlural();break;case'orte-zuordnen':placesQuiz();break;case'orientierung':orientation();break;case'wegbeschreibung':directions();break;case'pruefung':exam();break;default:flashcards();}
