import{requireLogin,getActiveProfile,getActiveRole,dashboardHref,logout}from'/js/auth.js?v=login-main-4';
import{loadCourseRelease,moduleOpen,releasedVerbs}from'/js/course-releases.js?v=verb-groups-2';

const BASE=window.VerbGroupsEngine;
const app=document.querySelector('#app'),topbar=document.querySelector('#topbar');
const TASKS=[
 ['cards','Aa','Karteikarten'],['inf-perfect','→','Infinitiv → Perfekt'],['perfect-inf','←','Perfekt → Infinitiv'],
 ['listen','🔊','Hören'],['image-perfect','▣','Bild → Perfekt'],['build','+','Perfekt bilden'],
 ['auxiliary','hat/ist','Hilfsverb'],['write','✎','Perfekt schreiben'],['speak','🎙','Perfekt sprechen'],
 ['sentence','…','Satz im Perfekt'],['exam','★','Gruppenprüfung']
];
const LEARN=TASKS.slice(0,-1).map(x=>x[0]),TITLE=Object.fromEntries(TASKS.map(x=>[x[0],x[2]]));
const SPECIAL={
 'sein':'gewesen','haben':'gehabt','beginnen':'begonnen','bekommen':'bekommen','begraben':'begraben','werden':'geworden','tun':'getan','wissen':'gewusst','kommen':'gekommen','gehen':'gegangen','bringen':'gebracht','denken':'gedacht','schreiben':'geschrieben','verstehen':'verstanden','schwimmen':'geschwommen','gewinnen':'gewonnen','springen':'gesprungen','verlieren':'verloren','unterschreiben':'unterschrieben','trinken':'getrunken','beißen':'gebissen','gießen':'gegossen','reißen':'gerissen','genießen':'genossen','singen':'gesungen','schließen':'geschlossen','rennen':'gerannt','finden':'gefunden','wiederholen':'wiederholt','schneiden':'geschnitten','streiten':'gestritten','essen':'gegessen','sprechen':'gesprochen','fahren':'gefahren','schlafen':'geschlafen','sehen':'gesehen','lesen':'gelesen','rufen':'gerufen','schreien':'geschrien','schieben':'geschoben','ziehen':'gezogen','stehen':'gestanden','empfehlen':'empfohlen','geben':'gegeben','backen':'gebacken','reiten':'geritten','greifen':'gegriffen','kennen':'gekannt','befehlen':'befohlen','helfen':'geholfen','braten':'gebraten','waschen':'gewaschen','nehmen':'genommen','stehlen':'gestohlen','tragen':'getragen','brechen':'gebrochen','laufen':'gelaufen','vergessen':'vergessen','messen':'gemessen','fressen':'gefressen','graben':'gegraben','schlagen':'geschlagen','sterben':'gestorben','treffen':'getroffen','werfen':'geworfen','fangen':'gefangen','blasen':'geblasen','fallen':'gefallen','saufen':'gesoffen','halten':'gehalten','laden':'geladen','lassen':'gelassen','wachsen':'gewachsen','werben':'geworben','raten':'geraten','stechen':'gestochen','gefallen':'gefallen','bleiben':'geblieben','verbiegen':'verbogen','heißen':'geheißen','sitzen':'gesessen','liegen':'gelegen','hängen':'gehangen','können':'gekonnt','müssen':'gemusst','wollen':'gewollt','dürfen':'gedurft','sollen':'gesollt','möchten':'gemocht','mögen':'gemocht','biegen':'gebogen','lügen':'gelogen','versprechen':'versprochen','vergeben':'vergeben','verbringen':'verbracht','entscheiden':'entschieden','sich benehmen':'benommen','benehmen':'benommen','riechen':'gerochen','stinken':'gestunken','schweigen':'geschwiegen','steigen':'gestiegen','sinken':'gesunken',
 'aufräumen':'aufgeräumt','einkaufen':'eingekauft','anrufen':'angerufen','fernsehen':'ferngesehen','anfangen':'angefangen','aussterben':'ausgestorben','mitgeben':'mitgegeben','mitnehmen':'mitgenommen','aufstehen':'aufgestanden','anziehen':'angezogen','ausziehen':'ausgezogen','einsteigen':'eingestiegen','aussteigen':'ausgestiegen','umsteigen':'umgestiegen','ankommen':'angekommen','abfahren':'abgefahren','mitkommen':'mitgekommen','zurückkommen':'zurückgekommen','abbiegen':'abgebogen','ausleihen':'ausgeliehen','vorhaben':'vorgehabt','aufgeben':'aufgegeben','zusehen':'zugesehen','abschreiben':'abgeschrieben','vorlesen':'vorgelesen','verschlafen':'verschlafen','kennenlernen':'kennengelernt','einladen':'eingeladen','ausfallen':'ausgefallen','aufbacken':'aufgebacken','abraten':'abgeraten','beraten':'beraten','vorschlagen':'vorgeschlagen','losfahren':'losgefahren','dabeihaben':'dabeigehabt','leidtun':'leidgetan',
 'bieten':'geboten','bitten':'gebeten','nennen':'genannt','treiben':'getrieben','binden':'gebunden','brennen':'gebrannt','erschrecken':'erschrocken','fliehen':'geflohen','fließen':'geflossen','frieren':'gefroren','gelingen':'gelungen','gelten':'gegolten','geschehen':'geschehen','passieren':'passiert','gleichen':'geglichen','heben':'gehoben','klingen':'geklungen','leiden':'gelitten','leihen':'geliehen','meiden':'gemieden','reiben':'gerieben','schaffen':'geschaffen','scheiden':'geschieden','scheinen':'geschienen','schießen':'geschossen','schmeißen':'geschmissen','treten':'getreten','verzeihen':'verziehen','weisen':'gewiesen','hinweisen':'hingewiesen','auffallen':'aufgefallen','einfallen':'eingefallen','wiegen':'gewogen','zwingen':'gezwungen','hinzufügen':'hinzugefügt','spazieren gehen':'spazieren gegangen',
 'sich bewegen':'bewegt','sich konzentrieren':'konzentriert','sich kümmern':'gekümmert','sich interessieren':'interessiert','sich erinnern':'erinnert','sich anziehen':'angezogen','sich ausziehen':'ausgezogen','sich umziehen':'umgezogen','sich duschen':'geduscht','sich freuen':'gefreut','sich ärgern':'geärgert','sich beschweren':'beschwert','sich überlegen':'überlegt'
};
const SEP=new Set(['aufräumen','einkaufen','anrufen','fernsehen','anfangen','aussterben','aufmachen','zumachen','mitgeben','mitnehmen','aufstehen','anziehen','ausziehen','einsteigen','aussteigen','umsteigen','ankommen','abfahren','ausfüllen','anmelden','mitkommen','zurückkommen','abbiegen','abholen','ausleihen','vorhaben','aufgeben','zuhören','zusehen','abschreiben','vorlesen','ausfallen','aufbacken','austauschen','ablenken','absagen','abraten','vorschlagen','aussuchen','sich vorstellen','losfahren','dabeihaben','leidtun','kennenlernen','einladen','hinweisen','auffallen','einfallen','hinzufügen','sich anziehen','sich ausziehen','sich umziehen','spazieren gehen']);
const SEIN=new Set(['sein','werden','kommen','gehen','schwimmen','springen','reisen','fahren','laufen','reiten','rennen','sterben','fallen','wachsen','bleiben','aussterben','aufstehen','einsteigen','aussteigen','umsteigen','ankommen','abfahren','abbiegen','mitkommen','zurückkommen','ausfallen','steigen','sinken','wandern','losfahren','fliehen','fließen','gelingen','geschehen','passieren','auffallen','einfallen','erschrecken','spazieren gehen']);
const NO_GE=new Set(['unterschreiben','wiederholen','überqueren','sich überlegen']);
const INSEP=/^(be|emp|ent|er|ge|miss|ver|zer)/;
const CATEGORY_ORDER=[];
let profile={},preview=false,locked=false,VERBS=[],GROUPS=[],state=null,currentQuestion=null,rec=null,cardRevealed=false,cardSolved=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[.,!?;:"'`´()]/g,'').replace(/\s+/g,' ');
const answerNorm=v=>norm(v).replace(/\s+/g,'');
const shuffle=a=>{a=[...(a||[])];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const bare=v=>String(v).replace(/^sich\s+/,''),stem=v=>v.endsWith('en')?v.slice(0,-2):v.endsWith('n')?v.slice(0,-1):v;
function regularPart(v,withGe=true){const s=stem(v),e=/[td]$|chn$|ffn$|gn$|tm$/.test(s),part=s+(e?'et':'t');return(withGe?'ge':'')+part}
const SEPARABLE_PARTICIPLES={
 'aufräumen':'aufgeräumt','einkaufen':'eingekauft','anrufen':'angerufen','fernsehen':'ferngesehen','anfangen':'angefangen',
 'aussterben':'ausgestorben','aufmachen':'aufgemacht','zumachen':'zugemacht','mitgeben':'mitgegeben','mitnehmen':'mitgenommen',
 'aufstehen':'aufgestanden','anziehen':'angezogen','ausziehen':'ausgezogen','einsteigen':'eingestiegen','aussteigen':'ausgestiegen',
 'umsteigen':'umgestiegen','ankommen':'angekommen','abfahren':'abgefahren','ausfüllen':'ausgefüllt','anmelden':'angemeldet',
 'mitkommen':'mitgekommen','zurückkommen':'zurückgekommen','abbiegen':'abgebogen','abholen':'abgeholt','ausleihen':'ausgeliehen',
 'vorhaben':'vorgehabt','aufgeben':'aufgegeben','zuhören':'zugehört','zusehen':'zugesehen','abschreiben':'abgeschrieben',
 'vorlesen':'vorgelesen','ausfallen':'ausgefallen','aufbacken':'aufgebacken','austauschen':'ausgetauscht','ablenken':'abgelenkt',
 'absagen':'abgesagt','abraten':'abgeraten','vorschlagen':'vorgeschlagen','aussuchen':'ausgesucht','vorstellen':'vorgestellt',
 'losfahren':'losgefahren','dabeihaben':'dabeigehabt','leidtun':'leidgetan','kennenlernen':'kennengelernt','einladen':'eingeladen',
 'hinweisen':'hingewiesen','auffallen':'aufgefallen','einfallen':'eingefallen','hinzufügen':'hinzugefügt','umziehen':'umgezogen',
 'spazieren gehen':'spazieren gegangen'
};
const SEPARABLE_PREFIXES=['spazieren ','zurück','zusammen','dabei','kennen','hinzu','heraus','hinein','herüber','hinüber','weiter','wieder','vorbei','fest','statt','teil','fern','auf','aus','ein','an','ab','mit','vor','zu','um','los','hin','her','weg','über','unter','durch','leid'];
function baseParticiple(v){if(SPECIAL[v])return SPECIAL[v];if(v.endsWith('ieren'))return regularPart(v,false);if(INSEP.test(v)||NO_GE.has(v)||/^(über|unter)/.test(v))return regularPart(v,false);return regularPart(v,true)}
function participle(v){
 if(SPECIAL[v])return SPECIAL[v];
 const b=bare(v);
 if(SPECIAL[b])return SPECIAL[b];
 if(SEPARABLE_PARTICIPLES[b])return SEPARABLE_PARTICIPLES[b];
 const label=BASE?.groupLabel?.(v)||BASE?.groupLabel?.(b);
 if(SEP.has(v)||SEP.has(b)||label==='Trennbar'){
  const prefix=SEPARABLE_PREFIXES.find(part=>b.startsWith(part)&&b.length>part.length);
  if(prefix)return prefix+baseParticiple(b.slice(prefix.length))
 }
 return baseParticiple(b)
}
function auxiliary(v){return SEIN.has(v)?'ist':'hat'}
function perfect(v){return`${auxiliary(v)} ${v.startsWith('sich ')?'sich ':''}${participle(v)}`}
function imageUrl(v){return(typeof window.SP_VERB_IMAGE_OVERRIDE==='function'&&window.SP_VERB_IMAGE_OVERRIDE(v))||BASE?.imageUrl?.(v)||`https://sprachpilot.b-cdn.net/${encodeURIComponent(norm(v).replace(/\s+/g,'_'))}.webp`}
function meaning(v){return BASE?.meaning?.(v)||window.SP_VERB_ENGLISH?.[v]||v}
function sentence(v){return window.SP_VERB_SENTENCES?.[v]||`Ich lerne das Verb „${v}“.`}
function category(v){
 const b=bare(v),label=BASE?.groupLabel?.(v);
 if(SEP.has(v)||SEP.has(b)||label==='Trennbar')return'separable';
 if((b.endsWith('ieren')&&b!=='verlieren')||INSEP.test(b)||NO_GE.has(v)||NO_GE.has(b))return'middle';
 if(label==='Unregelmäßig'||SPECIAL[v]&&['trennen','teilen','schauen','senden','passieren'].indexOf(v)<0||SPECIAL[b]&&['trennen','teilen','schauen','senden','passieren'].indexOf(b)<0)return'strong';
 return'regular'
}
function perfektBuckets(){
 const buckets={regular:[],strong:[],middle:[],separable:[]};
 for(const v of VERBS)buckets[category(v)].push(v);
 return buckets
}
function rebuildGroups(){
 GROUPS=[];
 const buckets=perfektBuckets();
 const titles={regular:'Regelmäßige Verben',strong:'Starke / unregelmäßige Verben',middle:'Nicht trennbare Verben / Verben auf -ieren',separable:'Trennbare Verben'};
 for(const key of ['regular','strong','middle','separable']){
  const list=buckets[key];
  for(let i=0;i<list.length;i+=20){
   const verbs=list.slice(i,i+20),number=GROUPS.length+1;
   GROUPS.push({id:number,category:key,title:titles[key],verbs,signature:key+'|'+verbs.join('|')})
  }
 }
}
const userSlug=()=>[profile.email,profile.courseCode,profile.kurs,profile.kursnummer,profile.vorname,profile.nachname].filter(Boolean).join('_').toLowerCase().replace(/[^a-z0-9äöüß]+/gi,'_')||'student';
const storageKey=()=>`SP_PERFEKT_STABLE_${userSlug()}`;
const blankTask=total=>({total,done:[],queue:[],current:null,tries:0,hadWrong:false});
const blankRun=()=>({tasks:{},exam:{bestPercent:0,stars:0,session:null},awards:{tasks:{},examPoints:0},completed:false});
const blankGroup=sig=>({signature:sig,currentRun:1,runs:{'1':blankRun()}});
const blankState=()=>({version:1,selectedGroup:1,groups:{}});
function normalizeRun(run,g){run={...blankRun(),...(run||{})};run.tasks=run.tasks||{};for(const t of LEARN){const x=run.tasks[t]||blankTask(g.verbs.length);x.total=g.verbs.length;x.done=[...new Set((x.done||[]).filter(v=>g.verbs.includes(v)))];x.queue=[...new Set((x.queue||[]).filter(v=>g.verbs.includes(v)&&!x.done.includes(v)))];x.current=x.current&&g.verbs.includes(x.current)&&!x.done.includes(x.current)?x.current:null;x.tries=Number(x.tries)||0;x.hadWrong=!!x.hadWrong;run.tasks[t]=x}run.exam={bestPercent:0,stars:0,session:null,...(run.exam||{})};run.awards={tasks:{},examPoints:0,...(run.awards||{})};run.awards.tasks=run.awards.tasks||{};return run}
function groupState(id){const g=GROUPS[id-1];if(!g)return null;let gs=state.groups[g.signature];if(!gs)gs=state.groups[g.signature]=blankGroup(g.signature);gs.currentRun=Math.max(1,Math.min(3,Number(gs.currentRun)||1));gs.runs=gs.runs||{};for(let r=1;r<=gs.currentRun;r++)gs.runs[String(r)]=normalizeRun(gs.runs[String(r)],g);return gs}
const currentRun=id=>{const gs=groupState(id);return gs?.runs?.[String(gs.currentRun)]||null};
function load(){try{state=JSON.parse(localStorage.getItem(storageKey())||'null')||blankState()}catch{state=blankState()}state.groups=state.groups||{};GROUPS.forEach(g=>groupState(g.id))}
function save(){if(preview)return;try{localStorage.setItem(storageKey(),JSON.stringify(state))}catch{}}
const taskState=(id,t)=>currentRun(id)?.tasks?.[t],taskPercent=(id,t)=>{const x=taskState(id,t);return x?.total?Math.round(x.done.length/x.total*100):0},taskDone=(id,t)=>taskPercent(id,t)>=100,learnDone=id=>LEARN.every(t=>taskDone(id,t));
function taskPoints(id){return(groupState(id)?.currentRun||1)*5}
function groupPoints(id){const gs=groupState(id);if(!gs)return 0;return Object.values(gs.runs||{}).reduce((sum,r)=>sum+Object.values(r.awards?.tasks||{}).reduce((s,n)=>s+(Number(n)||0),0)+(Number(r.awards?.examPoints)||0),0)}
const totalPoints=()=>GROUPS.reduce((s,g)=>s+groupPoints(g.id),0);
function nextVerb(id,t){const x=taskState(id,t),g=GROUPS[id-1];if(!x||!g)return null;if(x.current&&!x.done.includes(x.current))return x.current;if(!x.queue.length)x.queue=shuffle(g.verbs.filter(v=>!x.done.includes(v)));x.current=x.queue.shift()||null;x.tries=0;x.hadWrong=false;save();return x.current}
function markWrong(id,t){const x=taskState(id,t);if(!x)return 0;x.tries++;x.hadWrong=true;save();return x.tries}
function markRight(id,t){const x=taskState(id,t),v=x?.current;if(!x||!v)return;if(x.hadWrong||x.tries>0){if(!x.done.includes(v)&&!x.queue.includes(v))x.queue.push(v)}else if(!x.done.includes(v))x.done.push(v);x.current=null;x.tries=0;x.hadWrong=false;if(taskDone(id,t)&&!currentRun(id).awards.tasks[t])currentRun(id).awards.tasks[t]=taskPoints(id);save()}
function resetGroup(id){const g=GROUPS[id-1],gs=groupState(id);if(!g||!gs)return;const awards={};for(const[r,run]of Object.entries(gs.runs||{}))awards[r]=run.awards;state.groups[g.signature]=blankGroup(g.signature);for(const[r,a]of Object.entries(awards)){state.groups[g.signature].runs[r]=normalizeRun(blankRun(),g);state.groups[g.signature].runs[r].awards=a}save()}
function canRepeat(id){const gs=groupState(id),run=currentRun(id);return!!gs&&gs.currentRun<3&&learnDone(id)&&Number(run.exam.bestPercent||0)>=100}
function nextRun(id){const gs=groupState(id),g=GROUPS[id-1];if(!canRepeat(id))return false;gs.currentRun++;gs.runs[String(gs.currentRun)]=normalizeRun(blankRun(),g);save();return true}
function options(answer,pool,count=4){const seen=new Set([norm(answer)]),others=[];shuffle(pool).forEach(x=>{if(x!=null&&!seen.has(norm(x))){seen.add(norm(x));others.push(x)}});return shuffle([answer,...others.slice(0,count-1)])}
function question(id,t,v){const g=GROUPS[id-1],full=perfect(v),forms=g.verbs.map(perfect);if(t==='inf-perfect')return{kind:'input',prompt:`Bilde das Perfekt: ${v}`,answer:full,placeholder:'hat/ist + Partizip II'};if(t==='perfect-inf')return{kind:'mc',prompt:full,answer:v,options:options(v,g.verbs)};if(t==='listen')return{kind:'mc',prompt:'Höre die Perfektform.',answer:v,options:options(v,g.verbs),audio:full};if(t==='image-perfect')return{kind:'input',prompt:`Bilde das Perfekt von „${v}“.`,answer:full,image:v,placeholder:'hat/ist + Partizip II'};if(t==='build')return{kind:'mc',prompt:`Welche Form ist richtig? „${v}“`,answer:full,options:options(full,forms)};if(t==='auxiliary')return{kind:'mc',prompt:`Welches Hilfsverb hat „${v}“?`,answer:auxiliary(v),options:['hat','ist']};if(t==='write')return{kind:'input',prompt:`Schreibe die Perfektform: ${v}`,answer:full,placeholder:'hat/ist + Partizip II'};if(t==='speak')return{kind:'speech',prompt:`Sprich die Perfektform von „${v}“.`,answer:full,writeAnswer:full};if(t==='sentence')return{kind:'input',prompt:`Gestern … (${v})`,answer:full,placeholder:'hat/ist + Partizip II'};return{kind:'input',prompt:v,answer:full}}
function examItems(id){const g=GROUPS[id-1],kinds=LEARN.filter(t=>t!=='cards'),items=[];const verbs=shuffle(g.verbs);for(let i=0;i<20;i++)items.push({v:verbs[i%verbs.length],task:kinds[i%kinds.length]});return items}
const route=()=>{const q=new URLSearchParams(location.search),group=Math.max(0,Math.min(GROUPS.length,Number(q.get('group'))||0)),task=q.get('task')||'',view=q.get('view')||'';return{group,task:TASKS.some(x=>x[0]===task)?task:'',view:view==='overview'?'overview':''}};
const href=(group=0,task='',view='')=>{const q=new URLSearchParams();if(group)q.set('group',group);if(task)q.set('task',task);if(view)q.set('view',view);return'/perfekt/'+(q.toString()?'?'+q.toString():'')};
const go=o=>{history.pushState(null,'',href(o.group,o.task,o.view));render()};
function image(v,compact=false){return`<div class="verb-image ${compact?'compact':''}"><img src="${esc(imageUrl(v))}" alt="Bild zu ${esc(v)}" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="image-fallback" hidden><strong>${esc(v)}</strong></div></div>`}
const RECORDED_AUDIO_BASE='https://sprachpilot.b-cdn.net/audio/';
const RECORDED_AUDIO_SPECIAL={'hat gefallen':'hat_gefallen.mp3','ist gefallen':'ist_gefallen.mp3','hat vergessen':'hat_vergessen.mp3'};
let activeRecordedAudio=null;
const audioSlug=value=>String(value||'').toLowerCase().trim().replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'');
function computerSpeak(text,slow=false){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='de-DE';u.rate=slow?.55:.92;speechSynthesis.speak(u)}
function recordedAudioFile(text){const raw=String(text||'').trim(),key=norm(raw);if(RECORDED_AUDIO_SPECIAL[key])return RECORDED_AUDIO_SPECIAL[key];const word=raw.replace(/^(hat|ist)\s+/i,'').replace(/^sich\s+/i,'');const slug=audioSlug(word);return slug?slug+'.mp3':''}
function speak(text,slow=false){
 const raw=String(text||'').trim();if(!raw)return;
 const file=recordedAudioFile(raw);if(!file)return computerSpeak(raw,slow);
 try{activeRecordedAudio?.pause()}catch{}
 const audio=new Audio(RECORDED_AUDIO_BASE+encodeURIComponent(file));activeRecordedAudio=audio;audio.preload='auto';audio.playbackRate=slow?.75:1;
 let usedFallback=false;
 const fallback=()=>{if(usedFallback)return;usedFallback=true;try{audio.pause()}catch{}if(activeRecordedAudio===audio)activeRecordedAudio=null;computerSpeak(raw,slow)};
 audio.onerror=fallback;audio.onended=()=>{if(activeRecordedAudio===audio)activeRecordedAudio=null};
 const playResult=audio.play();if(playResult&&typeof playResult.catch==='function')playResult.catch(fallback)
}
function stopMic(){if(rec)try{rec.abort()}catch{}rec=null}
function header(r){const name=[profile.vorname||profile.firstName,profile.nachname||profile.lastName].filter(Boolean).join(' ')||(preview?'Lehrer-Vorschau':'Schüler');topbar.innerHTML=`<div class="topbar-main"><a class="brand" href="/index.html"><img src="/assets/logo/sprachpilot-logo.png" alt="SprachPilot"><div><h1>Perfekt</h1><p>${VERBS.length} freigegeben · ${GROUPS.length} Gruppen</p></div></a><div class="account-actions"><span class="account-pill">${esc(name)}</span><a class="btn secondary" href="${esc(dashboardHref())}">Dashboard</a><button class="btn secondary" data-action="logout">Abmelden</button></div></div><nav class="topnav"><a class="btn secondary" href="/index.html">← Startseite</a><button class="btn secondary ${r.view==='overview'?'active-nav':''}" data-action="overview">Übersicht</button>${r.group?`<button class="btn secondary" data-action="group" data-group="${r.group}">Aufgaben</button><button class="btn danger-btn" data-action="reset-group" data-group="${r.group}">Fortschritt löschen</button>`:''}</nav>`}
const previewNote=()=>preview?'<div class="preview-note">Lehrer-Vorschau · nichts wird gespeichert</div>':'';
function scoreCard(id=0){if(preview)return'';if(!id)return`<section class="card score-card compact-score"><h2>${totalPoints()} Punkte</h2><span>gesamt</span></section>`;const gs=groupState(id),run=currentRun(id);return`<section class="card score-card"><div><p class="eyebrow">Gruppe ${id}</p><h2>Runde ${gs.currentRun} von 3</h2><p>${Object.values(run.awards.tasks||{}).reduce((s,n)=>s+(Number(n)||0),0)} Aufgabenpunkte · ${Number(run.awards.examPoints)||0} Prüfungspunkte</p>${canRepeat(id)?`<button class="btn" data-action="next-run" data-group="${id}">Runde ${gs.currentRun+1} starten</button>`:''}</div><div class="score-total">${groupPoints(id)}<span>Punkte</span></div></section>`}
function taskCards(id){const run=currentRun(id);return TASKS.map((t,i)=>{const exam=t[0]==='exam',open=!exam||learnDone(id),p=exam?Number(run.exam.bestPercent)||0:taskPercent(id,t[0]);return`<button class="task-card ${p>=100?'done-card':''} ${!open?'locked-task':''}" data-action="task" data-group="${id}" data-task="${t[0]}" ${open?'':'disabled'}><span class="task-number">${i+1}</span><span class="task-icon">${open?t[1]:'🔒'}</span><span class="task-title">${t[2]}</span><div class="task-mini-progress"><span style="width:${p}%"></span></div><span class="task-status">${open?(p>=100?'Fertig':p?`${p}%`:'Starten'):'Gesperrt'}</span></button>`}).join('')}
function renderHome(selected=0){if(!GROUPS.length){app.innerHTML=`${previewNote()}<section class="card empty-state"><h2>Noch keine Verben freigegeben</h2><p>Die Lehrkraft wählt die Verben im Lehrer-Dashboard aus.</p></section>`;return}const panels=GROUPS.map(g=>{const gs=groupState(g.id),done=LEARN.filter(t=>taskDone(g.id,t)).length,exam=Number(currentRun(g.id).exam.bestPercent)||0;return`<details class="group-panel" ${selected===g.id?'open':''}><summary data-action="group" data-group="${g.id}"><span class="group-number">Gruppe ${g.id}</span><span>${esc(g.title)}</span><span>${g.verbs.length} Verben</span><span>Runde ${gs.currentRun}/3 · ${done}/${LEARN.length} · Prüfung ${exam}%</span></summary><div class="group-body"><div class="task-grid">${taskCards(g.id)}</div></div></details>`}).join('');app.innerHTML=`${previewNote()}${scoreCard(selected)}<section class="card"><div class="section-head"><h2>Gruppen</h2><span class="overview-total">${VERBS.length} Verben</span></div><div class="groups-accordion">${panels}</div></section>`}
function renderOverview(){const cards=VERBS.map(v=>`<article class="overview-verb-card">${image(v,true)}<div class="overview-verb-text"><h3>${esc(v)}</h3><p><strong>${esc(perfect(v))}</strong></p><p>${esc(meaning(v))}</p><button class="audio-mini" data-action="audio" data-text="${esc(perfect(v))}">🔊</button></div></article>`).join('');app.innerHTML=`${previewNote()}<section class="card"><div class="section-head"><h2>Übersicht</h2><span class="overview-total">${VERBS.length} Verben</span></div><div class="overview-grid">${cards}</div></section>`}
function progress(id,t){const x=taskState(id,t),p=taskPercent(id,t);return`<div class="task-progress-row"><span>${x.done.length} richtig · ${x.total-x.done.length} übrig</span><strong>${p}%</strong></div><div class="mini-progress"><div style="width:${p}%"></div></div>`}
function feedback(text,ok=false){const e=document.querySelector('#feedback');if(e){e.className='feedback '+(ok?'ok':'no');e.innerHTML=text}}
function body(q){const media=q.image?image(q.image):q.audio?`<div class="listen-box"><button class="btn" data-action="audio" data-text="${esc(q.audio)}">🔊 Hören</button><button class="btn secondary" data-action="audio-slow" data-text="${esc(q.audio)}">Langsam</button></div>`:'';let answer='';if(q.kind==='mc')answer=`<div class="option-grid">${q.options.map(o=>`<button class="option" data-action="answer" data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div>`;if(q.kind==='input')answer=`<div class="answer-form"><div class="answer-row"><input id="answerInput" autocomplete="off" placeholder="${esc(q.placeholder||'Antwort schreiben')}"><button class="btn" data-action="check-input">Kontrollieren</button></div></div>`;if(q.kind==='speech')answer=`<div class="speech-box"><div class="actions"><button class="btn" data-action="mic">🎤 Sprechen</button><button class="btn secondary" data-action="write-fallback">✍️ Schreiben</button></div><div id="micStatus" class="small"></div><div id="writeFallback" class="answer-form hidden"><div class="answer-row"><input id="answerInput" autocomplete="off" placeholder="hat/ist + Partizip II"><button class="btn" data-action="check-input">Kontrollieren</button></div></div></div>`;return`${media}<div class="question">${esc(q.prompt)}</div>${answer}<div id="feedback"></div>`}
function renderCards(id){const v=nextVerb(id,'cards');if(!v)return finishTask(id,'cards');currentQuestion={answer:v};cardRevealed=false;cardSolved=false;app.innerHTML=`<section class="card task-page"><div class="task-page-head"><div><p class="eyebrow">Gruppe ${id}</p><h2>Karteikarten</h2></div><button class="btn secondary" data-action="group" data-group="${id}">Aufgaben</button></div>${progress(id,'cards')}<div class="flip-wrap"><div id="verbFlipCard" class="flip-card" role="button" tabindex="0"><div class="flip-face flip-front">${image(v)}</div><div class="flip-face flip-back"><div class="flip-word">${esc(perfect(v))}</div><p>${esc(sentence(v))}</p><button type="button" class="btn secondary" id="cardListenBtn">🔊 Anhören</button></div></div></div><div class="hint card-translation">Infinitiv: <b>${esc(v)}</b> · ${esc(meaning(v))}</div><div class="actions"><button id="cardMicBtn" class="btn">Sprechen</button><button id="cardWriteBtn" class="btn secondary">Schreiben</button></div><div id="cardMicStatus" class="small"></div><div id="cardAnswerBox" class="answer-form" hidden><div class="answer-row"><input id="cardAnswerInput" autocomplete="off" placeholder="hat/ist + Partizip II"><button id="cardCheckBtn" class="btn">Kontrollieren</button></div></div><div id="cardFeedback"></div><div id="cardAfter" class="actions"></div></section>`;document.querySelector('#verbFlipCard').addEventListener('click',()=>revealCard(id));document.querySelector('#cardListenBtn').addEventListener('click',e=>{e.stopPropagation();speak(perfect(v))});document.querySelector('#cardWriteBtn').addEventListener('click',()=>openCardWrite());document.querySelector('#cardMicBtn').addEventListener('click',()=>startCardMic(id));document.querySelector('#cardCheckBtn').addEventListener('click',()=>checkCard(id,document.querySelector('#cardAnswerInput').value));document.querySelector('#cardAnswerInput').addEventListener('keydown',e=>{if(e.key==='Enter')checkCard(id,e.target.value)})}
function revealCard(id){if(cardSolved)return;document.querySelector('#verbFlipCard')?.classList.add('flipped');if(!cardRevealed){cardRevealed=true;markWrong(id,'cards');document.querySelector('#cardAfter').innerHTML='<button class="btn" id="cardNext">Weiter</button>';document.querySelector('#cardNext').onclick=()=>{markRight(id,'cards');renderCards(id)}}}
function openCardWrite(msg=''){document.querySelector('#cardAnswerBox').hidden=false;if(msg)document.querySelector('#cardMicStatus').textContent=msg;setTimeout(()=>document.querySelector('#cardAnswerInput')?.focus(),20)}
function checkCard(id,value){if(cardSolved)return;const answer=perfect(taskState(id,'cards').current);if(answerNorm(value)===answerNorm(answer)){cardSolved=true;document.querySelector('#verbFlipCard')?.classList.add('flipped');document.querySelector('#cardFeedback').className='feedback ok';document.querySelector('#cardFeedback').textContent='Richtig!';markRight(id,'cards');document.querySelector('#cardAfter').innerHTML='<button class="btn" id="cardNext">Weiter</button>';document.querySelector('#cardNext').onclick=()=>renderCards(id)}else{const tries=markWrong(id,'cards');document.querySelector('#cardFeedback').className='feedback no';document.querySelector('#cardFeedback').innerHTML=hint(tries,answer)}}
function hint(tries,answer){if(tries>=3)return`Lösung: <strong>${esc(answer)}</strong>`;if(tries===2){const bits=String(answer).split(/\s+/);if((bits[0]==='hat'||bits[0]==='ist')&&bits.length>1)return`Tipp: Hilfsverb <strong>${esc(bits[0])}</strong>, Partizip beginnt mit <strong>${esc(bits[bits.length-1].slice(0,3))}…</strong>`;return`Tipp: Die Lösung beginnt mit <strong>${esc(String(answer).slice(0,3))}…</strong>`}return'Noch nicht richtig. Achte auf Hilfsverb und Partizip II.'}
function renderTask(id,t){if(t==='exam')return renderExam(id);if(taskDone(id,t))return finishTask(id,t);if(t==='cards')return renderCards(id);const v=nextVerb(id,t);if(!v)return finishTask(id,t);currentQuestion=question(id,t,v);app.innerHTML=`<section class="card task-page"><div class="task-page-head"><div><p class="eyebrow">Gruppe ${id}</p><h2>${esc(TITLE[t])}</h2></div><button class="btn secondary" data-action="group" data-group="${id}">Aufgaben</button></div>${progress(id,t)}<div class="question-card">${body(currentQuestion)}</div></section>`;setTimeout(()=>document.querySelector('#answerInput')?.focus(),50)}
function finishTask(id,t){const gs=groupState(id),pts=Number(currentRun(id).awards.tasks[t])||0,next=LEARN[LEARN.indexOf(t)+1]||'exam';app.innerHTML=`<section class="card"><div class="finish-box"><div class="finish-icon">✓</div><h2>Fertig</h2><p>${pts} Punkte · Runde ${gs.currentRun}</p><div class="actions"><button class="btn" data-action="task" data-group="${id}" data-task="${next}">Weiter</button><button class="btn secondary" data-action="group" data-group="${id}">Aufgaben</button></div></div></section>`}
function isCorrect(value,q){return answerNorm(value)===answerNorm(q.answer)}
function checkTask(value){const r=route(),q=currentQuestion;if(!r.group||!r.task||!q)return;if(isCorrect(value,q)){feedback('Richtig.',true);markRight(r.group,r.task);setTimeout(()=>renderTask(r.group,r.task),450)}else{const tries=markWrong(r.group,r.task);feedback(hint(tries,q.answer))}}
function openWriteFallback(msg='Bitte schreibe die Antwort.'){document.querySelector('#writeFallback')?.classList.remove('hidden');const s=document.querySelector('#micStatus');if(s)s.textContent=msg;setTimeout(()=>document.querySelector('#answerInput')?.focus(),20)}
function startMic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){openWriteFallback();return}try{stopMic();rec=new SR();rec.lang='de-DE';rec.interimResults=false;rec.continuous=false;const s=document.querySelector('#micStatus');if(s)s.textContent='Ich höre zu …';rec.onresult=e=>{const text=e.results?.[0]?.[0]?.transcript||'';if(!text){openWriteFallback();return}route().task==='exam'?checkExam(text):checkTask(text)};rec.onerror=()=>openWriteFallback('Mikrofon hat nicht funktioniert. Bitte schreiben.');rec.onnomatch=()=>openWriteFallback();rec.onend=()=>{rec=null};rec.start()}catch{openWriteFallback()}}
function startCardMic(id){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){openCardWrite('Mikrofon wird hier nicht unterstützt. Bitte schreiben.');return}try{stopMic();rec=new SR();rec.lang='de-DE';rec.onresult=e=>{const text=e.results?.[0]?.[0]?.transcript||'';openCardWrite();document.querySelector('#cardAnswerInput').value=text;checkCard(id,text)};rec.onerror=()=>openCardWrite('Mikrofon hat nicht funktioniert. Bitte schreiben.');rec.onend=()=>{rec=null};rec.start()}catch{openCardWrite('Mikrofon konnte nicht gestartet werden.')}}
function renderExam(id){if(!learnDone(id)){app.innerHTML=`<section class="card locked-card"><h2>Prüfung gesperrt</h2><button class="btn" data-action="group" data-group="${id}">Aufgaben</button></section>`;return}const run=currentRun(id),ex=run.exam;if(!ex.session){app.innerHTML=`<section class="card"><div class="finish-box"><div class="finish-icon">★</div><h2>Gruppenprüfung</h2><p>Bester Stand: ${ex.bestPercent||0}%</p><button class="btn" data-action="start-exam" data-group="${id}">Starten</button><button class="btn secondary" data-action="group" data-group="${id}">Aufgaben</button></div></section>`;return}if(ex.session.index>=ex.session.items.length)return finishExam(id);const item=ex.session.items[ex.session.index];currentQuestion=question(id,item.task,item.v);const p=Math.round(ex.session.index/ex.session.items.length*100);app.innerHTML=`<section class="card task-page"><div class="task-page-head"><div><p class="eyebrow">Gruppe ${id}</p><h2>Gruppenprüfung</h2></div><button class="btn secondary" data-action="group" data-group="${id}">Abbrechen</button></div><div class="task-progress-row"><span>${ex.session.index+1}/${ex.session.items.length}</span><strong>${p}%</strong></div><div class="mini-progress"><div style="width:${p}%"></div></div><div class="question-card">${body(currentQuestion)}</div></section>`}
function startExam(id){currentRun(id).exam.session={items:examItems(id),index:0,correct:0};save();renderExam(id)}
function checkExam(value){const r=route(),ex=currentRun(r.group).exam,q=currentQuestion;if(!ex.session||!q)return;const good=isCorrect(value,q);if(good)ex.session.correct++;feedback(good?'Richtig.':`Lösung: <strong>${esc(q.answer)}</strong>`,good);ex.session.index++;save();setTimeout(()=>renderExam(r.group),500)}
function finishExam(id){const run=currentRun(id),session=run.exam.session,total=session?.items?.length||1,correct=session?.correct||0,p=Math.round(correct/total*100),stars=p>=100?3:p>=70?2:p>=50?1:0;run.exam.session=null;run.exam.bestPercent=Math.max(Number(run.exam.bestPercent)||0,p);run.exam.stars=Math.max(Number(run.exam.stars)||0,stars);const max=groupState(id).currentRun*100,earned=Math.round(max*p/100);run.awards.examPoints=Math.max(Number(run.awards.examPoints)||0,earned);run.completed=learnDone(id)&&run.exam.bestPercent>=100;save();app.innerHTML=`<section class="card"><div class="finish-box"><div class="finish-icon">✓</div><h2>${p}%</h2><div class="stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>${correct}/${total} richtig</p><div class="actions"><button class="btn" data-action="start-exam" data-group="${id}">Noch einmal</button><button class="btn secondary" data-action="group" data-group="${id}">Aufgaben</button>${canRepeat(id)?`<button class="btn" data-action="next-run" data-group="${id}">Runde ${groupState(id).currentRun+1}</button>`:''}</div></div></section>`}
function answerFromInput(){const value=document.querySelector('#answerInput')?.value||'';route().task==='exam'?checkExam(value):checkTask(value)}
function render(){stopMic();const r=route();header(r);if(locked){app.innerHTML='<section class="card locked-card"><h2>Perfekt ist gesperrt</h2><a class="btn" href="/index.html">Zur Startseite</a></section>';return}if(r.view==='overview')return renderOverview();if(r.group&&r.task)return renderTask(r.group,r.task);renderHome(r.group)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,g=Number(b.dataset.group)||0,t=b.dataset.task||'';if(a==='logout')return logout();if(a==='overview')return go({view:'overview'});if(a==='group')return go({group:g});if(a==='task')return go({group:g,task:t});if(a==='reset-group'){if(!preview&&confirm(`Fortschritt von Gruppe ${g} löschen? Bereits verdiente Punkte bleiben erhalten.`)){resetGroup(g);render()}return}if(a==='next-run'){if(confirm(`Runde ${groupState(g).currentRun+1} starten?`)&&nextRun(g))go({group:g});return}if(a==='audio')return speak(b.dataset.text||'');if(a==='audio-slow')return speak(b.dataset.text||'',true);if(a==='answer')return route().task==='exam'?checkExam(b.dataset.answer||''):checkTask(b.dataset.answer||'');if(a==='check-input')return answerFromInput();if(a==='mic')return startMic();if(a==='write-fallback')return openWriteFallback();if(a==='start-exam'){go({group:g,task:'exam'});return startExam(g)}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target?.id==='answerInput'){e.preventDefault();answerFromInput()}});window.addEventListener('popstate',render);

async function init(){const user=requireLogin();if(!user)return;profile=getActiveProfile()||{};const role=String(getActiveRole()||'').toLowerCase();preview=role==='teacher';try{const raw=sessionStorage.getItem('SP_TEACHER_PREVIEW');if(raw==='1'||JSON.parse(raw||'null')?.teacherPreview===true)preview=true}catch{}const all=[...new Set((window.SP_VERB_GROUP_DATA?.verbs||BASE?.ALL||[]).filter(Boolean))];try{const assignments=await loadCourseRelease(profile);locked=!preview&&!moduleOpen(assignments,'Verben');VERBS=preview?all:releasedVerbs(assignments,all)}catch{VERBS=preview?all:[];locked=!preview}rebuildGroups();load();render()}
init().catch(error=>{console.error(error);app.innerHTML='<section class="card"><h2>Perfekt konnte nicht geladen werden</h2><p>Bitte lade die Seite neu.</p><button class="btn" onclick="location.reload()">Neu laden</button></section>'});