import {renderSpHeader,bindSpHeader} from '/js/sp-header.js?v=theme-standard4';
const D=window.L10T3||{},root=document.getElementById('app'),taskId=String(new URLSearchParams(location.search).get('task')||'karteikarten').toLowerCase(),task=(D.tasks||[]).find(x=>x.id===taskId)||D.tasks?.[0],TOPIC='wortschatz-a1-lektion-10-thema-3';
try{sessionStorage.setItem('SP_L10_LAST_TASK_T3',taskId);localStorage.setItem('SP_L10_LAST_TASK_T3',taskId)}catch(e){}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[.,!?;:“”"'`´()]/g,'').replace(/\s+/g,' ');
function shuffle(a){const b=a.slice();for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function profile(){try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||localStorage.getItem('SP_STUDENT_PROFILE')||'{}')||{}}catch(e){return{}}}
function owner(){const p=profile();return String(p.canonicalStudentId||p.docId||p.studentId||p.userId||p.authUid||p.uid||p.id||p.email||localStorage.getItem('SP_STUDENT_ID')||'student').trim().toLowerCase().replace(/[^a-z0-9äöüß@._-]+/gi,'_')}
function preview(){try{return ['teacher','lehrer','admin','owner','superadmin'].includes(String(localStorage.getItem('SP_LOGIN_ROLE')||localStorage.getItem('SP_ACTIVE_ROLE')||profile().role||'').toLowerCase())||sessionStorage.getItem('SP_TEACHER_PREVIEW')==='1'||localStorage.getItem('SP_TEACHER_PREVIEW')==='1'}catch(e){return false}}
function run(){return Math.max(1,Math.min(3,Number(localStorage.getItem('SP_SCORE_RUN_'+TOPIC)||1)||1))}
function store(){return preview()?sessionStorage:localStorage}function key(){return`SP_L10_${owner()}_T3_${taskId}`}
function read(total){let s={done:[],wrong:{},revealed:{},order:[],firstSeen:[],firstCorrect:[],_run:run(),total};try{const x=JSON.parse(store().getItem(key())||'{}');if(x&&Number(x._run||1)===run()&&Number(x.total||0)===Number(total||0))Object.assign(s,x)}catch(e){}s.done=Array.isArray(s.done)?s.done:[];s.wrong=s.wrong||{};s.revealed=s.revealed||{};s.order=Array.isArray(s.order)?s.order:[];s.firstSeen=Array.isArray(s.firstSeen)?s.firstSeen:[];s.firstCorrect=Array.isArray(s.firstCorrect)?s.firstCorrect:[];s.total=total;return s}
function write(s){s._run=run();store().setItem(key(),JSON.stringify(s));if(!preview()&&taskId!=='pruefung'){const done=s.done.length,total=s.total,percent=total?Math.round(done/total*100):0;import('/js/progress.js?v=20260831-central6').then(m=>(window.SPProgress||m)?.recordTaskProgress?.({module:'wortschatz',moduleTitle:'Wortschatz',level:'A1',lesson:10,theme:3,topic:TOPIC,topicId:TOPIC,title:'A1 Lektion 10 · Thema 3',file:`task.html?task=${taskId}`,taskKey:taskId,taskTitle:task?.title||taskId,run:run(),done,total,percent,completed:percent>=100})).catch(()=>{})}window.dispatchEvent(new CustomEvent('sprachpilot-progress',{detail:{lesson:10,theme:3,topic:TOPIC,task:taskId,state:s}}))}
function ensureOrder(items){const ids=items.map((_,i)=>String(i)),s=read(items.length),valid=s.order.filter(x=>ids.includes(x)),missing=ids.filter(x=>!valid.includes(x));if(missing.length||valid.length!==ids.length){s.order=valid.concat(shuffle(missing));write(s)}return s}
function next(items){const s=ensureOrder(items),id=s.order.find(x=>!s.done.includes(x));return id==null?null:Number(id)}
function mark(i,total,force=false){const s=read(total),id=String(i);if(!force&&(Number(s.wrong[id])>0||s.revealed[id])){s.order=s.order.filter(x=>x!==id);s.order.push(id);delete s.wrong[id];delete s.revealed[id];write(s);return false}if(!s.done.includes(id))s.done.push(id);delete s.wrong[id];delete s.revealed[id];write(s);return true}
function wrong(i,total){const s=read(total),id=String(i);s.wrong[id]=(Number(s.wrong[id])||0)+1;write(s);return s.wrong[id]}
function useHelp(i,total){const s=read(total),id=String(i);if(!s.revealed[id]){s.revealed[id]=true;s.wrong[id]=(Number(s.wrong[id])||0)+1;write(s)}}
function feedback(type,html){document.getElementById('fb').innerHTML=`<div class="l8-feedback ${type}">${html}</div>`}
function hint(n,a,h=''){return n===1?'Noch nicht richtig. Versuch es noch einmal.':n===2?(h||'Lies die Aufgabe noch einmal.'):`<strong>Lösung:</strong> ${esc(a)}`}
function head(done,total){const p=total?Math.round(done/total*100):0;return`<section class="l8-card l8-task-head"><div class="l8-task-title-block"><span class="l8-task-kicker">Aufgabe ${Math.max(1,(D.tasks||[]).findIndex(x=>x.id===taskId)+1)}</span><h1>${esc(task?.title||'Aufgabe')}</h1><p>${esc(task?.icon||'✅')} ${esc(task?.text||'')}</p></div><div class="l8-progress-row"><span>${done} von ${total} fertig</span><strong>${p}%</strong></div><div class="l8-progress"><div style="width:${p}%"></div></div></section>`}
function example(){return task?.example?`<div class="l8-note"><strong>Beispiel:</strong> ${esc(task.example)}</div>`:''}
function polishHeader(){document.querySelectorAll('.sp-header__nav-link').forEach(a=>{if(String(a.textContent||'').trim()==='Übersicht')a.setAttribute('href','uebersicht.html')})}
function shell(body,done,total){const header=renderSpHeader({subtitle:'Arzt, Arbeit und Krankmeldung · A1 Lektion 10 · Thema 3',color:{main:'#F4A3A3',dark:'#A86464',soft:'#FDF1F1',line:'#F3C9C9'}});root.innerHTML=`<div class="l10-theme-page">${header}<div class="l8-wrap">${preview()?'<div class="sp-teacher-preview-note">Lehrer-Vorschau: Teilnehmerfortschritt wird nicht verändert.</div>':''}${head(done,total)}${body}<footer>© SprachPilot</footer></div></div>`;bindSpHeader(root);polishHeader()}
function resetTask(){store().removeItem(key());location.reload()}
function nextTaskHref(){const list=(D.tasks||[]).filter(x=>!x.exam),p=list.findIndex(x=>x.id===taskId),n=list[p+1];return n?`task.html?task=${encodeURIComponent(n.id)}`:'./index.html'}
function finish(total){const s=read(total);s.done=Array.from({length:total},(_,i)=>String(i));write(s);shell(`<section class="l8-card l8-finish"><div class="l8-finish-icon">✓</div><h2>Gut gemacht!</h2><p>Du hast die Aufgabe abgeschlossen.</p><div class="l8-row l8-center-actions"><button class="l8-btn" id="resetTask">Nochmal üben</button><a class="l8-btn primary" href="${nextTaskHref()}">Weiter</a><a class="l8-btn" href="./index.html">Zur Themenübersicht</a></div></section>`,total,total);document.getElementById('resetTask').onclick=resetTask}
function speak(t){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='de-DE';u.rate=.84;speechSynthesis.speak(u)}catch(e){}}
function play(c){const srcs=[c.audio,c.audioFallback].filter(Boolean);const go=i=>{if(i>=srcs.length)return speak(c.full||c.word);try{const a=new Audio(srcs[i]);let used=false,next=()=>{if(!used){used=true;go(i+1)}};a.onerror=next;a.play().catch(next)}catch(e){go(i+1)}};go(0)}
function recognize(answers,done,fail=()=>{}){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){feedback('warn','Spracherkennung ist hier nicht verfügbar. Schreibe die Antwort.');return}const accepted=(Array.isArray(answers)?answers:[answers]).map(norm),r=new SR();r.lang='de-DE';r.interimResults=false;r.maxAlternatives=3;feedback('good','Sprich jetzt.');r.onresult=e=>{const heard=[...e.results[0]].map(x=>norm(x.transcript));if(heard.some(x=>accepted.includes(x)))done();else{fail();feedback('bad',`Gehört: <strong>${esc(e.results[0][0].transcript)}</strong>. Versuch es noch einmal oder schreibe die Antwort.`)}};r.onerror=()=>feedback('warn','Ich konnte dich nicht verstehen. Versuch es noch einmal oder schreibe die Antwort.');r.start()}
function visual(c,small=false){return`<span class="sp-visual ${small?'small':''}"><img src="${esc(c.image)}" alt="" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><span class="sp-fallback" style="display:none">${esc(c.emoji)}</span></span>`}
function checkInput(items,render,question,answerOf,placeholder='Antwort schreiben',allowSpeech=false){const i=next(items);if(i==null)return finish(items.length);const x=items[i],s=read(items.length),a=answerOf(x),answers=Array.isArray(a)?a:[a];shell(`<section class="l8-card l8-exercise">${example()}${question(x)}${allowSpeech?'<div class="l8-row l8-center-actions"><button class="l8-btn" id="speakAnswer">🎤 Sprechen</button><span>oder</span></div>':''}<div class="l8-answer-row"><input class="l8-input" id="ans" autocomplete="off" placeholder="${placeholder}"><button class="l8-btn primary" id="check">Prüfen</button></div><div id="fb"></div></section>`,s.done.length,items.length);const success=()=>{const mastered=mark(i,items.length);feedback('good',mastered?'Richtig!':'Richtig. Diese Aufgabe kommt am Ende noch einmal.');setTimeout(render,500)},check=()=>{if(answers.map(norm).includes(norm(document.getElementById('ans').value)))success();else{const n=wrong(i,items.length);feedback(n>=3?'warn':'bad',hint(n,answers[0]))}};document.getElementById('check').onclick=check;document.getElementById('ans').onkeydown=e=>{if(e.key==='Enter')check()};if(allowSpeech)document.getElementById('speakAnswer').onclick=()=>recognize(answers,success,()=>wrong(i,items.length))}
function renderCards(){const items=D.cards||[],i=next(items);if(i==null)return finish(items.length);const c=items[i],s=read(items.length);shell(`<section class="l8-card l8-card-stage"><div class="l8-flip-wrap"><div class="l8-flip-card" id="flip"><div class="l8-flip-face l8-flip-front">${visual(c)}<div class="l8-card-translation"><strong>${esc(c.translation||c.meaning)}</strong></div><small>Tippe auf die Karte für Hilfe.</small></div><div class="l8-flip-face l8-flip-back"><div class="l8-flip-back-grid"><div>${visual(c,true)}</div><div class="l8-back-info"><div class="l8-flip-word">${esc(c.full)}</div>${c.plural?`<div class="l8-card-detail"><span>Plural</span><strong>${esc(c.plural)}</strong></div>`:''}<button class="l8-btn" id="listen">🔊 Anhören</button></div></div></div></div></div><div class="l8-row l8-center-actions"><button class="l8-btn" id="speak">🎤 Sprechen</button><button class="l8-btn" id="writeMode">✍️ Schreiben</button></div><div class="l8-answer-row" id="writeRow" hidden><input class="l8-input" id="ans" placeholder="Deutsches Wort"><button class="l8-btn primary" id="check">Prüfen</button></div><div id="fb"></div></section>`,s.done.length,items.length);document.getElementById('flip').onclick=()=>{useHelp(i,items.length);document.getElementById('flip').classList.add('flipped');feedback('warn','Die Lösung wurde gezeigt. Das Wort kommt später noch einmal.')};document.getElementById('listen').onclick=e=>{e.stopPropagation();play(c)};const success=()=>{const mastered=mark(i,items.length);feedback('good',mastered?'Richtig!':'Richtig. Das Wort kommt am Ende noch einmal.');setTimeout(renderCards,500)};const check=()=>{if([c.full,c.word].map(norm).includes(norm(document.getElementById('ans').value)))success();else{const n=wrong(i,items.length);feedback(n>=3?'warn':'bad',hint(n,c.full,c.meaning))}};document.getElementById('speak').onclick=()=>recognize([c.full,c.word],success,()=>wrong(i,items.length));document.getElementById('writeMode').onclick=()=>{document.getElementById('writeRow').hidden=false;document.getElementById('ans').focus()};document.getElementById('check').onclick=check;document.getElementById('ans').onkeydown=e=>{if(e.key==='Enter')check()}}
function renderMeaning(){const items=D.cards||[],i=next(items);if(i==null)return finish(items.length);const c=items[i],s=read(items.length),opts=shuffle([c,...shuffle(items.filter(x=>x.id!==c.id)).slice(0,3)]);shell(`<section class="l8-card l8-exercise"><div class="sp-big-word">${esc(c.full)}</div><div class="l8-options">${opts.map(o=>`<button class="l8-option" data-id="${o.id}">${esc(o.meaning)}</button>`).join('')}</div><div id="fb"></div></section>`,s.done.length,items.length);document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{if(b.dataset.id===c.id){mark(i,items.length);feedback('good','Richtig!');setTimeout(renderMeaning,350)}else feedback('bad',hint(wrong(i,items.length),c.meaning))})}
function renderAudio(){const items=D.cards||[],i=next(items);if(i==null)return finish(items.length);const c=items[i],s=read(items.length),opts=shuffle([c,...shuffle(items.filter(x=>x.id!==c.id)).slice(0,3)]);shell(`<section class="l8-card l8-exercise"><div class="sp-listen-center"><button class="l8-btn primary" id="listen">🔊 Wort anhören</button></div><div class="sp-image-options">${opts.map(o=>`<button class="sp-image-option" data-id="${o.id}">${visual(o)}</button>`).join('')}</div><div id="fb"></div></section>`,s.done.length,items.length);document.getElementById('listen').onclick=()=>play(c);document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{if(b.dataset.id===c.id){mark(i,items.length);feedback('good','Richtig!');setTimeout(renderAudio,350)}else feedback('bad',hint(wrong(i,items.length),c.full))});setTimeout(()=>play(c),250)}
function renderArticle(){const items=D.nouns||[],i=next(items);if(i==null)return finish(items.length);const c=items[i],s=read(items.length);shell(`<section class="l8-card l8-exercise"><div class="sp-noun-card">${visual(c,true)}<strong>${esc(c.word)}</strong></div><div class="l8-options sp-article-options">${shuffle(['der','die','das']).map(a=>`<button class="l8-option article" data-a="${a}">${a}</button>`).join('')}</div><div class="l8-answer-row"><input class="l8-input" id="plural" placeholder="Plural mit Artikel"><button class="l8-btn primary" id="check">Prüfen</button></div><div id="fb"></div></section>`,s.done.length,items.length);let chosen='';document.querySelectorAll('.article').forEach(b=>b.onclick=()=>{chosen=b.dataset.a;document.querySelectorAll('.article').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});document.getElementById('check').onclick=()=>{if(chosen===c.article&&norm(document.getElementById('plural').value)===norm(c.plural)){mark(i,items.length);feedback('good','Richtig!');setTimeout(renderArticle,350)}else feedback('bad',hint(wrong(i,items.length),`${c.article} ${c.word} · ${c.plural}`))}}
function renderSollenTable(){const rows=D.sollenRows||[],s=read(rows.length);shell(`<section class="l8-card l8-exercise"><div class="sp-poss-table">${rows.map((r,i)=>`<div class="sp-pronoun">${esc(r[0])}</div><input class="l8-input poss" data-i="${i}" value="${s.done.includes(String(i))?esc(r[1]):''}" ${s.done.includes(String(i))?'disabled':''}>`).join('')}</div><div class="l8-row l8-center-actions"><button class="l8-btn primary" id="check">Prüfen</button></div><div id="fb"></div></section>`,s.done.length,rows.length);document.getElementById('check').onclick=()=>{let good=0;rows.forEach((r,i)=>{if(s.done.includes(String(i)))return;const inp=document.querySelector(`[data-i="${i}"]`);if(norm(inp.value)===norm(r[1])){mark(i,rows.length);good++}else inp.classList.add('incorrect')});if(read(rows.length).done.length===rows.length)setTimeout(()=>finish(rows.length),300);else feedback(good?'good':'bad',good?`${good} Form(en) richtig.`:'Noch nicht richtig.')}}
const renderSollen=()=>checkInput(D.sollenSentences||[],renderSollen,x=>`<div class="sp-source">${esc(x.q)}</div>`,x=>x.a,'Form von sollen',true);
const renderRecommendations=()=>checkInput(D.recommendations||[],renderRecommendations,x=>`<div class="sp-source">${esc(x.q)}</div>`,x=>x.a,'Satz mit sollen',true);
function renderTips(){const items=D.tips||[],i=next(items);if(i==null)return finish(items.length);const x=items[i],s=read(items.length);shell(`<section class="l8-card l8-exercise"><div class="sp-big-word">${esc(x.q)}</div><div class="l8-options">${shuffle(x.options).map(o=>`<button class="l8-option" data-a="${esc(o)}">${esc(o)}</button>`).join('')}</div><div id="fb"></div></section>`,s.done.length,items.length);document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{if(norm(b.dataset.a)===norm(x.a)){mark(i,items.length);feedback('good','Richtig!');setTimeout(renderTips,350)}else feedback('bad',hint(wrong(i,items.length),x.a))})}
const renderPharmacy=()=>checkInput(D.pharmacy||[],renderPharmacy,x=>`<div class="sp-source">${esc(x.q)}</div>`,x=>x.a);
function renderLetterParts(){const items=D.letterParts||[],i=next(items);if(i==null)return finish(items.length);const x=items[i],s=read(items.length),all=items.map(y=>y.a),opts=shuffle([x.a,...shuffle(all.filter(a=>a!==x.a)).slice(0,3)]);shell(`<section class="l8-card l8-exercise"><div class="sp-source">${esc(x.q)}</div><div class="l8-options">${opts.map(o=>`<button class="l8-option" data-a="${esc(o)}">${esc(o)}</button>`).join('')}</div><div id="fb"></div></section>`,s.done.length,items.length);document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{if(norm(b.dataset.a)===norm(x.a)){mark(i,items.length);feedback('good','Richtig!');setTimeout(renderLetterParts,350)}else feedback('bad',hint(wrong(i,items.length),x.a))})}
function renderSickNotes(){const items=D.sickNotes||[],i=next(items);if(i==null)return finish(items.length);const x=items[i],s=read(items.length);shell(`<section class="l8-card l8-exercise">${example()}<div class="sp-bio-label">${esc(x.label)}</div><div class="sp-source sp-bio-source">${esc(x.prompt)}</div><textarea class="l8-input sp-textarea" id="ans" rows="8" placeholder="Krankmeldung schreiben"></textarea><div class="l8-row l8-center-actions"><button class="l8-btn primary" id="check">Prüfen</button></div><div id="fb"></div></section>`,s.done.length,items.length);document.getElementById('check').onclick=()=>{const v=norm(document.getElementById('ans').value),ok=x.need.every(k=>v.includes(norm(k)));if(ok){mark(i,items.length);feedback('good','Alle wichtigen Informationen sind enthalten.');setTimeout(renderSickNotes,450)}else feedback('bad',hint(wrong(i,items.length),x.sample,'Prüfe alle Punkte der Aufgabe.'))}}
function practiceComplete(){return(D.tasks||[]).filter(t=>!t.exam).every(t=>{try{const s=JSON.parse(localStorage.getItem(`SP_L10_${owner()}_T3_${t.id}`)||'null');return s&&Number(s._run||1)===run()&&Array.isArray(s.done)&&s.done.length>=Number(s.total||0)&&Number(s.total)>0}catch(e){return false}})}
function examAnswer(i,v){if(window.__l10t3ExamLocked)return;const items=D.examItems||[],x=items[i];if(!norm(v))return feedback('warn','Schreibe zuerst eine Antwort.');window.__l10t3ExamLocked=true;const s=read(items.length),id=String(i),ok=norm(v)===norm(x.a);if(!s.firstSeen.includes(id)){s.firstSeen.push(id);if(ok)s.firstCorrect.push(id)}if(!s.done.includes(id))s.done.push(id);write(s);document.querySelectorAll('button,input').forEach(el=>el.disabled=true);feedback(ok?'good':'bad',`${ok?'Richtig!':`Richtig wäre: <strong>${esc(x.a)}</strong>`}<div class="l8-row l8-center-actions"><button class="l8-btn primary" id="examNext">Weiter</button></div>`);const nextButton=document.getElementById('examNext');nextButton.disabled=false;nextButton.onclick=()=>{window.__l10t3ExamLocked=false;renderExam()}}
function renderExam(){const items=D.examItems||[];if(!preview()&&!practiceComplete())return location.href='./index.html';const i=next(items);if(i==null)return finishExam(items.length);const x=items[i],s=read(items.length),body=x.type==='choice'?`<div class="sp-source">${esc(x.q)}</div><div class="l8-options">${shuffle(x.options).map(o=>`<button class="l8-option" data-a="${esc(o)}">${esc(o)}</button>`).join('')}</div>`:`<div class="sp-source">${esc(x.q)}</div><div class="l8-answer-row"><input class="l8-input" id="ans" placeholder="Antwort schreiben"><button class="l8-btn primary" id="check">Prüfen</button></div>`;shell(`<section class="l8-card l8-exercise"><div class="l8-note"><strong>Prüfungsfrage ${s.done.length+1} von ${items.length}</strong> · ${esc(x.section)}</div>${body}<div id="fb"></div></section>`,s.done.length,items.length);document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>examAnswer(i,b.dataset.a));if(document.getElementById('check'))document.getElementById('check').onclick=()=>examAnswer(i,document.getElementById('ans').value)}
async function finishExam(total){const s=read(total),pct=Math.round(s.firstCorrect.length/Math.max(1,total)*100),max=run()*100,points=Math.round(max*pct/100);if(!preview()&&!s.examSynced){s.examSynced=true;write(s);try{const m=await import('/js/progress.js?v=20260831-central6');await(window.SPProgress||m)?.recordExamResult?.({module:'wortschatz',moduleTitle:'Wortschatz',level:'A1',lesson:10,theme:3,topicId:TOPIC,title:'A1 Lektion 10 · Thema 3',file:'task.html?task=pruefung',taskKey:'pruefung',taskTitle:'Prüfung',percent:pct,scorePercent:pct,stars:pct>=100?3:pct>=70?2:pct>=50?1:0})}catch(e){}}shell(`<section class="l8-card l8-finish"><div class="l8-finish-icon">⭐</div><h2>Prüfung beendet</h2><div class="l8-score-total">${points} / ${max} Punkte</div><p>${s.firstCorrect.length} von ${total} Antworten waren richtig.</p><a class="l8-btn primary" href="./index.html">Zur Übersicht</a></section>`,total,total)}
const renderers={karteikarten:renderCards,'wort-bedeutung':renderMeaning,'hoeren-bild':renderAudio,'artikel-plural':renderArticle,'sollen-tabelle':renderSollenTable,'sollen-saetze':renderSollen,'arzt-empfehlungen':renderRecommendations,gesundheitstipps:renderTips,'apotheke-dialoge':renderPharmacy,briefteile:renderLetterParts,'krankmeldung-schreiben':renderSickNotes,pruefung:renderExam};
try{(renderers[taskId]||renderMeaning)()}catch(e){console.error('L10T3',e);root.innerHTML='<div class="l8-wrap"><section class="l8-card"><h1>Aufgabe konnte nicht geladen werden.</h1><button class="l8-btn primary" onclick="location.reload()">Neu laden</button></section></div>'}
