(function(){
'use strict';
const D=window.L9T4,root=document.getElementById('app');
if(!D||!root||String(new URLSearchParams(location.search).get('task')||'')!=='nomen-verb-verbindungen')return;
const TASK='nomen-verb-verbindungen',pairs=D.nounVerbPairs||[],valid=pairs.map(x=>x.id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{const b=[...(a||[])];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
function profile(){try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||localStorage.getItem('SP_STUDENT_PROFILE')||'{}')}catch(e){return{}}}
function pid(){const p=profile();return String(p.canonicalStudentId||p.studentId||p.uid||p.email||localStorage.getItem('SP_STUDENT_ID')||'student').toLowerCase().replace(/[^a-z0-9äöüß@._-]+/gi,'_')}
function preview(){const r=String(localStorage.getItem('SP_LOGIN_ROLE')||localStorage.getItem('SP_ACTIVE_ROLE')||'').toLowerCase();return['teacher','lehrer','admin','owner','superadmin'].includes(r)||localStorage.getItem('SP_TEACHER_PREVIEW')==='1'||sessionStorage.getItem('SP_TEACHER_PREVIEW')==='1'}
function store(){return preview()?sessionStorage:localStorage}
const key=()=>`SP_L9_${pid()}_T4_${TASK}`;
function read(){let s={done:[],wrong:{},review:{},nounOrder:[],verbOrder:[]};try{s={...s,...JSON.parse(store().getItem(key())||'{}')}}catch(e){}s.done=[...new Set((s.done||[]).filter(x=>valid.includes(x)))];s.wrong=s.wrong||{};s.review=s.review||{};s.nounOrder=Array.isArray(s.nounOrder)?s.nounOrder.filter(x=>valid.includes(x)):[];s.verbOrder=Array.isArray(s.verbOrder)?s.verbOrder.filter(x=>valid.includes(x)):[];if(s.nounOrder.length!==valid.length)s.nounOrder=shuffle(valid);if(s.verbOrder.length!==valid.length)s.verbOrder=shuffle(valid);write(s,false);return s}
function write(s,emit=true){try{store().setItem(key(),JSON.stringify(s));if(emit)window.dispatchEvent(new CustomEvent('sprachpilot-progress',{detail:{lesson:9,theme:4,task:TASK,state:s}}))}catch(e){}}
function pct(){return Math.round(read().done.length/Math.max(1,valid.length)*100)}
function taskDef(){return(D.tasks||[]).find(x=>x.id===TASK)||{title:'Nomen-Verb-Verbindungen',description:'Ziehe die passenden Verben zu den Nomen.',icon:'🔗'}}
function itemNo(){const i=(D.tasks||[]).findIndex(x=>x.id===TASK);return i>=0?i+1:''}
function head(){const s=read(),t=taskDef(),p=pct();return`<section class="l8-card l8-task-head"><div class="l8-task-title-block"><span class="l8-task-kicker">Aufgabe ${itemNo()}</span><h1>${esc(t.title)}</h1><p>${esc(t.icon||'🔗')} ${esc(t.description)}</p></div><div class="l8-progress-row"><span>${s.done.length} von ${valid.length} Paaren fertig</span><strong>${p}%</strong></div><div class="l8-progress"><div style="width:${p}%"></div></div></section>`}
function previewNote(){return preview()?'<div class="sp-teacher-preview-note">Lehrer-Vorschau: Teilnehmerfortschritt wird nicht gespeichert.</div>':''}
async function sync(){if(preview())return;try{await import('/js/progress.js?v=20260831-central6');const api=window.SPProgress;if(!api?.recordTaskProgress)return;const s=read(),percent=pct(),t=taskDef();await api.recordTaskProgress({module:'wortschatz',moduleTitle:'Wortschatz',level:'A1',lesson:9,theme:4,topicId:'wortschatz-a1-lektion-9-thema-4',title:'A1 Lektion 9 · Thema 4',file:`task.html?task=${TASK}`,taskTitle:t.title,percent,completed:percent>=100,total:valid.length,done:s.done.length})}catch(e){console.warn('L9T4 Nomen-Verb progress',e)}}
function pairBy(id){return pairs.find(x=>x.id===id)}
let selectedVerb=null,selectedNoun=null,dragGhost=null,dragMoved=false,startX=0,startY=0;
function style(){if(document.getElementById('l9t4NvStyle'))return;const st=document.createElement('style');st.id='l9t4NvStyle';st.textContent=`
.l9nv-help{margin:0 0 16px;padding:12px 14px;border:1px solid var(--lesson-line);border-radius:14px;background:var(--lesson-soft);font-weight:750}
.l9nv-board{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(180px,.75fr);gap:18px;align-items:start}
.l9nv-col-title{font-weight:950;color:var(--lesson-main-dark);margin:0 0 9px;font-size:18px}
.l9nv-nouns,.l9nv-verbs{display:grid;gap:10px}
.l9nv-noun{min-height:56px;border:2px solid var(--lesson-line);border-radius:15px;background:#fff;padding:10px 12px;display:flex;align-items:center;justify-content:space-between;gap:10px;font-weight:900;transition:.15s}
.l9nv-noun.selected,.l9nv-noun.drag-over{border-color:var(--lesson-main);box-shadow:0 0 0 3px color-mix(in srgb,var(--lesson-main) 18%,transparent)}
.l9nv-noun.done{background:var(--lesson-soft);border-color:var(--lesson-main)}
.l9nv-noun-text{min-width:0}
.l9nv-match{flex:0 0 auto;padding:7px 10px;border-radius:11px;background:var(--lesson-main);color:#fff;font-weight:950}
.l9nv-drop-hint{font-size:12px;color:#6b7280;font-weight:750;white-space:nowrap}
.l9nv-verb{width:100%;min-height:50px;border:2px solid var(--lesson-line);border-radius:14px;background:#fff;padding:9px 12px;font:inherit;font-weight:900;cursor:grab;touch-action:none;color:inherit}
.l9nv-verb:active{cursor:grabbing}.l9nv-verb.selected{border-color:var(--lesson-main);background:var(--lesson-soft)}
.l9nv-feedback{min-height:48px;margin-top:14px}.l9nv-feedback .l8-feedback{display:block}
.l9nv-ghost{position:fixed;z-index:99999;pointer-events:none;padding:10px 14px;border-radius:13px;background:#fff;border:2px solid var(--lesson-main);font-weight:950;box-shadow:0 10px 30px rgba(0,0,0,.18);transform:translate(-50%,-50%)}
@media(max-width:640px){.l9nv-board{grid-template-columns:minmax(0,1.1fr) minmax(125px,.9fr);gap:10px}.l9nv-noun{padding:8px;min-height:52px;align-items:flex-start;flex-direction:column}.l9nv-match{width:100%;text-align:center}.l9nv-drop-hint{white-space:normal;font-size:11px}.l9nv-verb{padding:8px 7px;font-size:14px}.l9nv-col-title{font-size:16px}}
`;document.head.appendChild(st)}
function feedback(type,text){const b=document.getElementById('nvFeedback');if(b)b.innerHTML=`<div class="l8-feedback ${type}">${esc(text)}</div>`}
function clearSelections(){selectedVerb=null;selectedNoun=null;document.querySelectorAll('.l9nv-verb.selected,.l9nv-noun.selected,.l9nv-noun.drag-over').forEach(x=>x.classList.remove('selected','drag-over'))}
function attempt(nounId,verbId){if(!nounId||!verbId)return;const target=pairBy(nounId),verbPair=pairBy(verbId);if(!target||!verbPair)return;const s=read();if(s.done.includes(nounId))return;if(nounId===verbId){if(!s.done.includes(nounId))s.done.push(nounId);if(s.review[nounId])delete s.review[nounId];delete s.wrong[nounId];write(s);feedback('good',`${target.noun} – ${target.verb} ✓`);sync();clearSelections();setTimeout(()=>{if(pct()>=100)finish();else renderBoard()},360)}else{s.wrong[nounId]=(Number(s.wrong[nounId])||0)+1;s.review[nounId]=true;write(s);feedback('bad',`„${verbPair.verb}“ passt nicht zu „${target.noun}“. Das Verb geht zurück.`);clearSelections()}}
function bindNative(){document.querySelectorAll('.l9nv-verb').forEach(btn=>{btn.draggable=true;btn.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',btn.dataset.verbId);e.dataTransfer.effectAllowed='move'});btn.addEventListener('click',()=>{selectedVerb=btn.dataset.verbId;selectedNoun=null;document.querySelectorAll('.l9nv-verb').forEach(x=>x.classList.toggle('selected',x===btn));document.querySelectorAll('.l9nv-noun').forEach(x=>x.classList.remove('selected'))})});document.querySelectorAll('.l9nv-noun:not(.done)').forEach(n=>{n.addEventListener('dragover',e=>{e.preventDefault();n.classList.add('drag-over')});n.addEventListener('dragleave',()=>n.classList.remove('drag-over'));n.addEventListener('drop',e=>{e.preventDefault();n.classList.remove('drag-over');attempt(n.dataset.nounId,e.dataTransfer.getData('text/plain'))});n.addEventListener('click',()=>{if(selectedVerb)return attempt(n.dataset.nounId,selectedVerb);selectedNoun=n.dataset.nounId;document.querySelectorAll('.l9nv-noun').forEach(x=>x.classList.toggle('selected',x===n));document.querySelectorAll('.l9nv-verb').forEach(x=>x.classList.remove('selected'))})})}
function removeGhost(){dragGhost?.remove();dragGhost=null;document.querySelectorAll('.l9nv-noun.drag-over').forEach(x=>x.classList.remove('drag-over'))}
function bindPointer(){document.querySelectorAll('.l9nv-verb').forEach(btn=>{btn.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse')return;selectedVerb=btn.dataset.verbId;dragMoved=false;startX=e.clientX;startY=e.clientY;dragGhost=document.createElement('div');dragGhost.className='l9nv-ghost';dragGhost.textContent=pairBy(selectedVerb)?.verb||'';document.body.appendChild(dragGhost);dragGhost.style.left=e.clientX+'px';dragGhost.style.top=e.clientY+'px';try{btn.setPointerCapture(e.pointerId)}catch(_){};e.preventDefault()});btn.addEventListener('pointermove',e=>{if(!dragGhost||!selectedVerb)return;if(Math.hypot(e.clientX-startX,e.clientY-startY)>7)dragMoved=true;dragGhost.style.left=e.clientX+'px';dragGhost.style.top=e.clientY+'px';document.querySelectorAll('.l9nv-noun.drag-over').forEach(x=>x.classList.remove('drag-over'));const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest?.('.l9nv-noun:not(.done)');if(hit)hit.classList.add('drag-over');e.preventDefault()});btn.addEventListener('pointerup',e=>{if(!dragGhost)return;const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest?.('.l9nv-noun:not(.done)');const v=selectedVerb;removeGhost();if(hit&&dragMoved){attempt(hit.dataset.nounId,v);return}document.querySelectorAll('.l9nv-verb').forEach(x=>x.classList.toggle('selected',x===btn));selectedVerb=v;e.preventDefault()});btn.addEventListener('pointercancel',()=>{removeGhost();clearSelections()})})}
function renderBoard(){style();const s=read();const nouns=s.nounOrder.map(pairBy).filter(Boolean),verbs=s.verbOrder.map(pairBy).filter(x=>x&&!s.done.includes(x.id));root.innerHTML=`<div class="l8-wrap">${previewNote()}${head()}<section class="l8-card l8-exercise"><div class="l9nv-help">Ziehe ein Verb von rechts zum passenden Nomen links. Richtige Paare bleiben nebeneinander stehen.</div><div class="l9nv-board"><div><div class="l9nv-col-title">Nomen</div><div class="l9nv-nouns">${nouns.map(p=>{const done=s.done.includes(p.id);return`<div class="l9nv-noun ${done?'done':''}" data-noun-id="${p.id}"><span class="l9nv-noun-text">${esc(p.noun)}</span>${done?`<span class="l9nv-match">${esc(p.verb)}</span>`:'<span class="l9nv-drop-hint">Verb hierher ziehen</span>'}</div>`}).join('')}</div></div><div><div class="l9nv-col-title">Verben</div><div class="l9nv-verbs">${verbs.map(p=>`<button class="l9nv-verb" type="button" data-verb-id="${p.id}">${esc(p.verb)}</button>`).join('')}</div></div></div><div class="l9nv-feedback" id="nvFeedback"></div></section><footer>© SprachPilot</footer></div>`;bindNative();bindPointer();setTimeout(()=>window.SPTaskAutoScroll?.schedule?.(0,'auto'),30)}
function finish(){sync();root.innerHTML=`<div class="l8-wrap">${previewNote()}${head()}<section class="l8-card l8-finish"><div class="l8-finish-icon">✓</div><h2>Gut gemacht!</h2><p>Du hast alle Nomen-Verb-Verbindungen richtig zugeordnet.</p><div class="l8-row l8-center-actions"><a class="l8-btn" href="index.html">Zur Übersicht</a><a class="l8-btn primary" href="task.html?task=pruefung">Weiter</a></div></section><footer>© SprachPilot</footer></div>`}
try{if(pct()>=100)finish();else renderBoard();window.__L9T4_NV_OK=true}catch(e){console.error('L9T4 Nomen-Verb',e);root.innerHTML='<div class="l8-wrap"><section class="l8-card"><h2>Die Aufgabe konnte nicht gestartet werden.</h2><button class="l8-btn primary" onclick="location.reload()">Neu laden</button></section></div>'}
})();
