(function(){
'use strict';
let stateV2Promise=null,startAttempts=0;const CONTENT_WAIT_MS=3500,RETRY_MS=120,MAX_PENDING_RETRIES=35,MAX_CORE_RETRIES=60;
function readJson(key){try{return JSON.parse(localStorage.getItem(key)||'null')||{}}catch(e){return{}}}
function teacherAccess(){const roles=['teacher','lehrer','admin','owner','superadmin'],stored=['SP_LOGIN_ROLE','SP_ACTIVE_ROLE','SP_USER_ROLE','SP_AUTH_ROLE'].map(k=>String(localStorage.getItem(k)||'').trim().toLowerCase());if(stored.some(v=>roles.includes(v)))return true;const access=String(window.SP_SECURE_ACCESS?.type||'').toLowerCase();if(access==='teacher'||access==='teacher-preview'||window.spTeacherCanSeeAll===true)return true;return[readJson('SP_TEACHER_PROFILE'),readJson('SP_USER_PROFILE')].some(p=>p?.isTeacher===true||p?.teacher===true||p?.admin===true||p?.owner===true||roles.includes(String(p?.role||p?.loginRole||p?.type||p?.accountType||'').toLowerCase()))}
function installTeacherExamAccess(){if(!teacherAccess()||!window.L8S)return false;try{window.L8S.preview=()=>true}catch(e){}try{window.L8S.allDone=()=>true}catch(e){}try{window.spTeacherCanSeeAll=true}catch(e){}return true}
function ensureTeacherExamReader(){if(!teacherAccess())return;import('/js/sp-teacher-exam-reader.js?v=20260902-1').then(()=>setTimeout(()=>window.SPTeacherExamReader?.run?.(),0)).catch(()=>{})}
function ensureTaskAutoscroll(){if(document.body?.dataset?.page!=='task'||window.__SP_L8_TASK_AUTOSCROLL_V4)return;const existing=[...document.scripts].some(s=>String(s.src||'').includes('l8-task-autoscroll.js?v=20260902-4'));if(existing)return;const s=document.createElement('script');s.src='../shared/l8-task-autoscroll.js?v=20260902-4';document.body.appendChild(s)}
function ensureStateV2(){if(window.__SP_L8_STATE_V2&&window.L8S?.stateSchema===2&&typeof window.L8S?.runNo==='function')return Promise.resolve();if(stateV2Promise)return stateV2Promise;stateV2Promise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='../shared/l8-state-v2.js?v=20260902-unified1';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});return stateV2Promise}
function waitWithTimeout(gate,label){if(!gate||typeof gate.then!=='function')return Promise.resolve();let timer=null;return Promise.race([Promise.resolve(gate).catch(e=>console.error(label,e)),new Promise(resolve=>{timer=setTimeout(()=>{console.warn(`${label}: Zeitlimit erreicht; Seite startet mit dem bereits vorbereiteten Stand.`);resolve()},CONTENT_WAIT_MS)})]).finally(()=>{if(timer)clearTimeout(timer)})}
async function waitForFinalContent(){const first=window.L8_CONTENT_READY;await waitWithTimeout(first,'L8 Inhalte konnten nicht vollständig vorbereitet werden');const latest=window.L8_CONTENT_READY;if(latest&&latest!==first)await waitWithTimeout(latest,'L8 finale Inhalte konnten nicht vollständig vorbereitet werden')}
function reinstallSafeAudio(){try{window.L8AudioCoreSafeV3?.install?.()}catch(e){console.error('L8 sichere Audiofunktion konnte nicht installiert werden',e)}}
function norm(v){return String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,' ').trim()}
function resolveThemeNumber(){return Number(document.body?.dataset?.theme||0)||Number(location.pathname.match(/\/Thema-(\d+)\//i)?.[1]||0)||Number(window.L8_THEME?.number||0)||0}
function normalizeThemeIdentity(){const n=resolveThemeNumber();if(!n)return null;const all=window.L8_ALL_THEMES||{},theme=all[n]||all[String(n)]||(Array.isArray(all)?all.find(t=>Number(t?.number)===n):null)||window.L8_THEME;if(!theme)return null;theme.number=n;if(!theme.title)theme.title=`Thema ${n}`;window.L8_THEME=theme;return theme}
function finalizeCardMedia(theme){if(!theme)return;try{window.L8CardBunnyStandardV4?.patchTheme?.(theme)}catch(e){console.error('L8 Bunny-Medien konnten nicht finalisiert werden',e)}}
function oldClean(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9äöüß@._-]+/gi,'_').replace(/^_+|_+$/g,'')}
function oldPid(){const p=readJson('SP_USER_PROFILE')||readJson('SP_STUDENT_PROFILE')||{};return oldClean(p.authUid||p.canonicalStudentId||p.docId||p.studentId||p.uid||p.userId||p.id||p.email||[p.kurs||p.kursnummer||p.courseCode,p.vorname||p.firstName,p.nachname||p.lastName].filter(Boolean).join('_'))||'student'}
function migrateOldProgress(theme){if(!theme||!window.L8S?.key||window.L8S?.preview?.())return;const n=Number(theme.number);for(const task of theme.tasks||[]){if(!task?.id)continue;const nextKey=window.L8S.key(n,task.id);if(localStorage.getItem(nextKey))continue;const oldKey=`SP_L8_${oldPid()}_T${n}_${task.id}`,raw=localStorage.getItem(oldKey);if(!raw)continue;try{const state=JSON.parse(raw)||{};state.schema=2;state.total=Array.isArray(task.items)?task.items.length:Number(state.total)||0;localStorage.setItem(nextKey,JSON.stringify(state))}catch(e){}}}
const lastKey=n=>`SP_L8_LAST_TASK_T${Number(n)}`;
function rememberTask(){if(document.body?.dataset?.page!=='task')return;const n=resolveThemeNumber(),id=new URLSearchParams(location.search).get('task');if(!n||!id)return;try{sessionStorage.setItem(lastKey(n),id);localStorage.setItem(lastKey(n),id)}catch(e){}}
let returned=false;
function returnToLastTask(){if(document.body?.dataset?.page!=='theme'||returned)return false;const n=resolveThemeNumber();let id='';try{id=sessionStorage.getItem(lastKey(n))||localStorage.getItem(lastKey(n))||''}catch(e){}if(!id)return false;const link=[...document.querySelectorAll('a.l8-task-card')].find(a=>{try{return new URL(a.href,location.href).searchParams.get('task')===id}catch(e){return false}});if(!link)return false;returned=true;link.style.scrollMarginTop='18px';requestAnimationFrame(()=>requestAnimationFrame(()=>link.scrollIntoView({behavior:'auto',block:'center'})));return true}
function taskText(task){const items=(Array.isArray(task?.items)?task.items:[]).slice(0,6).map(i=>`${i?.type||''} ${i?.prompt||''} ${i?.context||''} ${i?.hint||''}`).join(' ');return norm(`${task?.id||''} ${task?.title||''} ${task?.kind||''} ${task?.instruction||''} ${task?.intro||''} ${items}`)}
function taskEmoji(task){const text=taskText(task),types=new Set((task?.items||[]).map(i=>String(i?.type||'').toLowerCase()));if(task?.exam||/prufung|exam/.test(text))return'⭐';const explicit=String(task?.emoji||task?.icon||'').trim();if(explicit)return explicit;if(/karte|card/.test(text)||task?.kind==='cards')return'📚';if(/memory/.test(text))return'🧠';if(/hor|listen|audio/.test(text)||(task?.items||[]).some(i=>i?.audio||i?.audioFile))return'🎧';if(/lesen|reading|leseversteh/.test(text))return'📖';if(/grammatik|grammar|satzteil/.test(text))return'🧲';if(/konjug|\bsein\b|\bhaben\b/.test(text))return'🔤';if(/sort|zuord/.test(text))return'📦';if(/ordnen|order|reihenfolge/.test(text)||types.has('order'))return'🧩';if(/schreib|write|lucke|text|plural/.test(text)||types.has('input')||types.has('free'))return'✍️';return'✅'}
function polishHeader(){const t=normalizeThemeIdentity();if(!t)return;const n=resolveThemeNumber(),taskId=new URLSearchParams(location.search).get('task'),task=(t.tasks||[]).find(x=>x.id===taskId),subtitle=document.querySelector('.sp-header__subtitle');if(subtitle)subtitle.textContent=task?`${task.title} · A1 Lektion 8 · Thema ${n}`:`${t.title} · A1 Lektion 8 · Thema ${n}`;document.querySelectorAll('.sp-header__nav-link').forEach(link=>{if(String(link.textContent||'').trim()==='Übersicht'&&link.tagName==='A')link.setAttribute('href','uebersicht.html')})}
function polishTaskEmojis(){const t=normalizeThemeIdentity();if(!t||!Array.isArray(t.tasks))return;if(document.body.dataset.page==='theme'){document.querySelectorAll('.l8-task-card').forEach((card,i)=>{const node=card.querySelector('.emoji'),task=t.tasks[i];if(node&&task)node.textContent=taskEmoji(task)});return}const id=new URLSearchParams(location.search).get('task'),task=t.tasks.find(x=>String(x?.id)===String(id)),line=document.querySelector('.l8-task-title-block p');if(task&&line)line.textContent=`${taskEmoji(task)} ${task.instruction||''}`}
function renderLoadError(){const root=document.getElementById('app');if(root)root.innerHTML='<div class="l8-wrap"><section class="l8-card"><h2>Die Aufgabe konnte nicht vollständig geladen werden.</h2><button class="l8-btn" type="button" onclick="location.reload()">Neu laden</button></section></div>'}
function scheduleRetry(){setTimeout(start,RETRY_MS)}
async function start(){startAttempts++;rememberTask();try{await ensureStateV2()}catch(e){console.error('L8 Fortschrittssystem konnte nicht geladen werden',e)}installTeacherExamAccess();reinstallSafeAudio();await waitForFinalContent();const theme=normalizeThemeIdentity();installTeacherExamAccess();const coreMissing=!theme||!window.L8S||!window.L8UI||window.L8S.stateSchema!==2,contentPending=!!(window.L8_T2_TIME_REVIEW_PENDING||window.L8_T2_QUALITY_PENDING||window.L8_T2_VOCAB_PENDING||window.L8_T2_VOCAB_FINAL_PENDING);if(coreMissing){if(startAttempts<MAX_CORE_RETRIES){scheduleRetry();return}renderLoadError();return}if(contentPending&&startAttempts<MAX_PENDING_RETRIES){scheduleRetry();return}migrateOldProgress(theme);finalizeCardMedia(theme);reinstallSafeAudio();installTeacherExamAccess();if(document.body.dataset.page==='theme')window.L8UI.themeOverview();else window.L8UI.taskPage();ensureTaskAutoscroll();ensureTeacherExamReader();[0,80,250,700,1500].forEach(ms=>setTimeout(()=>{const t=normalizeThemeIdentity();finalizeCardMedia(t);reinstallSafeAudio();installTeacherExamAccess();ensureTaskAutoscroll();polishHeader();polishTaskEmojis();returnToLastTask();window.SPTeacherExamReader?.run?.()},ms))}
window.L8TaskEmoji=taskEmoji;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();