(function(){'use strict';
const S=()=>window.L8S,T=()=>window.L8_THEME;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function previewNote(){return S().preview()?'<div class="sp-teacher-preview-note">Lehrer-Vorschau: Es werden keine Teilnehmerpunkte und keine Teilnehmerfortschritte gespeichert.</div>':''}
function taskNumber(task){const i=(T().tasks||[]).findIndex(x=>x.id===task.id);return i>=0?i+1:''}
function taskHead(task,state){const pct=Math.round((state.done?.length||0)/Math.max(1,task.items.length)*100);return`<section class="l8-card l8-task-head"><div class="l8-task-title-block"><span class="l8-task-kicker">Aufgabe ${taskNumber(task)}</span><h1>${esc(task.title)}</h1><p>${task.emoji} ${esc(task.instruction)}</p></div><div class="l8-progress-row"><span>${state.done.length} von ${task.items.length} fertig</span><strong>${pct}%</strong></div><div class="l8-progress"><div style="width:${pct}%"></div></div></section>`}
function scorePanel(theme){
 if(S().preview())return'<div class="l8-score-panel"><div class="l8-score-label">Punkte</div><div class="l8-score-total">Vorschau</div><div class="l8-small">Keine Teilnehmerpunkte</div></div>';
 const s=window.L8ThemeScore?.summary?.(theme)||{run:1,lifetime:0,taskPoints:0,examPoints:0,examBest:0,pending:0};
 return`<div class="l8-score-panel"><div class="l8-score-label">${s.run===1?'Versuch 1 von 3':`Wiederholung ${s.run} von 3`}</div><div class="l8-score-total">${Number(s.lifetime||0)} Punkte</div><div class="l8-small">Aufgaben: ${Number(s.taskPoints||0)} · Prüfung: ${Number(s.examPoints||0)}${s.examBest?` · bestes Ergebnis ${Number(s.examBest)}%`:''}</div>${s.pending?'<div class="l8-small l8-score-sync">Synchronisierung läuft …</div>':''}</div>`
}
function dictate(target){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){feedback('warn','Das Mikrofon wird auf diesem Gerät nicht unterstützt. Bitte schreibe deine Antwort.');return}let r;try{r=new R()}catch(e){feedback('warn','Das Mikrofon konnte nicht gestartet werden. Bitte schreibe deine Antwort.');return}r.lang='de-DE';r.interimResults=false;r.maxAlternatives=3;feedback('warn','Ich höre zu …');r.onresult=e=>{const text=Array.from(e.results?.[0]||[]).map(x=>x.transcript).filter(Boolean)[0]||'';if(text){const old=target.value.trim();target.value=(old?old+' ':'')+text.trim();target.dispatchEvent(new Event('input',{bubbles:true}));feedback('good','Gesprochenen Text übernommen. Prüfe ihn und ergänze ihn bei Bedarf.')}else feedback('warn','Ich konnte nichts erkennen. Bitte schreibe deine Antwort.')};r.onerror=()=>feedback('warn','Das Mikrofon ist blockiert oder hat nicht funktioniert. Bitte schreibe deine Antwort.');try{r.start()}catch(e){feedback('warn','Das Mikrofon konnte nicht gestartet werden. Bitte schreibe deine Antwort.')}}
function themeOverview(){
 const t=T(),root=document.getElementById('app');if(!root)return;
 window.resetThemeProgress=()=>S().reset(t.number);
 Promise.resolve(window.L8ThemeScore?.initOverview?.(t.number)).finally(()=>{
  const tasks=t.tasks||[],normal=tasks.filter(x=>!x.exam),avg=Math.round(normal.reduce((a,x)=>a+S().pct(t.number,x.id,x.items.length),0)/Math.max(1,normal.length)),completed=normal.filter(x=>S().pct(t.number,x.id,x.items.length)>=100).length,examOpen=S().allDone(t.number);
  root.innerHTML=`<div class="l8-wrap">${previewNote()}<section class="l8-card l8-progress-card"><div class="l8-progress-circle">${avg}%</div><div class="l8-progress-main"><h2>Dein Fortschritt</h2><p class="l8-small">${completed} / ${normal.length} Aufgaben abgeschlossen</p><div class="l8-progress"><div style="width:${avg}%"></div></div><p class="l8-small l8-theme-subtitle">${esc(t.subtitle||t.title)}</p><div class="l8-tags">${(t.chips||[]).map(x=>`<span class="l8-tag">${esc(x)}</span>`).join('')}</div></div><div class="l8-score-slot">${scorePanel(t.number)}</div></section><section class="l8-grid">${tasks.map((task,index)=>{const locked=task.exam&&!examOpen,pct=S().pct(t.number,task.id,task.items.length);return locked?`<div class="l8-card l8-task-card locked" aria-disabled="true"><div class="l8-task-number">${index+1}. ${esc(task.title)}</div><div class="emoji">⭐</div><p>${esc(task.instruction)}</p><div class="l8-progress"><div style="width:0%"></div></div><div class="l8-small">gesperrt</div><div class="l8-task-start">Prüfung gesperrt</div></div>`:`<a class="l8-card l8-task-card ${pct>=100?'done':''}" href="task.html?task=${encodeURIComponent(task.id)}"><div class="l8-task-number">${index+1}. ${esc(task.title)}</div><div class="emoji">${task.exam?'⭐':task.emoji}</div><p>${esc(task.instruction)}</p><div class="l8-progress"><div style="width:${pct}%"></div></div><div class="l8-small">${pct}%</div><div class="l8-task-start">${pct>=100?'Fertig':'Starten'}</div></a>`}).join('')}</section><footer>© SprachPilot</footer></div>`;
 });
}
function currentTask(){const id=new URLSearchParams(location.search).get('task');return T().tasks.find(x=>x.id===id)}
function nextUndone(task,state){for(let i=0;i<task.items.length;i++)if(!state.done.includes(i)&&Number(state.review?.[i]||0)!==2)return i;for(let i=0;i<task.items.length;i++)if(!state.done.includes(i))return i;return -1}
function taskPage(){const task=currentTask(),root=document.getElementById('app');if(!root)return;window.resetThemeProgress=()=>S().reset(T().number);if(!task){root.innerHTML=`<div class="l8-wrap"><section class="l8-card"><h2>Aufgabe nicht gefunden</h2><a class="l8-btn" href="index.html">Zur Übersicht</a></section></div>`;return}if(task.exam&&!S().allDone(T().number)){location.href='index.html';return}if(task.kind==='cards')return renderCards(task,root);renderExercise(task,root)}
function renderCards(task,root){let state=S().load(T().number,task.id,task.items.length),idx=nextUndone(task,state);if(idx<0)return finish(task,root);const card=task.items[idx];const img=`https://sprachpilot.b-cdn.net/${encodeURIComponent(card.image||'')}`;root.innerHTML=`<div class="l8-wrap">${previewNote()}${taskHead(task,state)}<section class="l8-card l8-cardword"><img src="${img}" alt="${esc(card.term)}" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><div class="l8-context" style="display:none">Bild wird später über Bunny Storage ergänzt.</div><h2>${esc(card.term)}</h2><div class="l8-tag">${esc(card.detail)}</div><p>${esc(card.example)}</p><div class="l8-row l8-center-actions"><button class="l8-btn l8-audio" id="listen">🔊 Hören</button><button class="l8-btn primary" id="learned">Gelernt ✓</button></div></section></div>`;document.getElementById('listen').onclick=()=>S().say(`${card.term}. ${card.example}`,card.audio);document.getElementById('learned').onclick=()=>{S().completeFree(T().number,task.id,task.items.length,idx,'seen');renderCards(task,root)}}
function renderExercise(task,root){let state=S().load(T().number,task.id,task.items.length);let idx=nextUndone(task,state);if(idx<0)return finish(task,root);const item=task.items[idx];root.innerHTML=`<div class="l8-wrap">${previewNote()}${taskHead(task,state)}${task.intro?`<div class="l8-note">${esc(task.intro)}</div>`:''}<section class="l8-card l8-exercise" id="exercise">${item.context?`<div class="l8-context">${esc(item.context).replace(/\n/g,'<br>')}</div>`:''}${item.audio?`<button class="l8-btn l8-audio" id="listen">🔊 Hör zu</button>`:''}<div class="l8-prompt">${esc(item.prompt)}</div><div id="answerArea"></div><div id="feedback"></div></section></div>`;if(item.audio)document.getElementById('listen').onclick=()=>S().say(item.audio,item.audioFile);renderAnswer(task,item,idx,root)}
function renderAnswer(task,item,idx,root){const area=document.getElementById('answerArea');if(item.type==='choice'){area.innerHTML=`<div class="l8-options">${item.options.map(o=>`<button class="l8-option" data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div>`;area.querySelectorAll('button').forEach(b=>b.onclick=()=>check(task,item,idx,b.dataset.answer,root))}else if(item.type==='input'){area.innerHTML=`<div class="l8-answer-row"><input class="l8-input" id="textAnswer" autocomplete="off" placeholder="Antwort"><button class="l8-btn primary" id="check">Prüfen</button></div>`;document.getElementById('check').onclick=()=>check(task,item,idx,document.getElementById('textAnswer').value,root);document.getElementById('textAnswer').addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('check').click()})}else if(item.type==='order'){const shuffled=[...item.tokens].sort(()=>Math.random()-.5);area.innerHTML=`<div class="l8-built" id="built"></div><div class="l8-row" id="tokens">${shuffled.map((x,i)=>`<button class="l8-token" data-i="${i}" data-token="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="l8-three-actions"><button class="l8-btn primary" id="check">Prüfen</button><button class="l8-btn" id="clear">Neu</button><button class="l8-btn" id="backOrder">Zurück</button></div>`;let built=[];area.querySelectorAll('.l8-token').forEach(b=>b.onclick=()=>{if(b.disabled)return;built.push({token:b.dataset.token,button:b});b.disabled=true;document.getElementById('built').textContent=built.map(x=>x.token).join(' ')});document.getElementById('clear').onclick=()=>renderAnswer(task,item,idx,root);document.getElementById('backOrder').onclick=()=>{const last=built.pop();if(last)last.button.disabled=false;document.getElementById('built').textContent=built.map(x=>x.token).join(' ')};document.getElementById('check').onclick=()=>check(task,item,idx,built.map(x=>x.token).join(' '),root)}else if(item.type==='free'){const saved=S().load(T().number,task.id,task.items.length).answers[idx]||item.starter||'';area.innerHTML=`<div class="l8-free"><textarea class="l8-input" id="freeText">${esc(saved)}</textarea><div class="l8-small" style="margin:8px 0">Sprich oder schreibe mindestens ${item.min||1} vollständige Sätze. Deine Antwort wird gespeichert.</div><div class="l8-row"><button class="l8-btn" id="dictate">🎤 Sprechen</button><button class="l8-btn primary" id="saveFree">Speichern und fertig</button></div></div>`;document.getElementById('dictate').onclick=()=>dictate(document.getElementById('freeText'));document.getElementById('saveFree').onclick=()=>{const text=document.getElementById('freeText').value.trim(),sentences=text.split(/[.!?]+/).map(x=>x.trim()).filter(Boolean);if(sentences.length<(item.min||1)){feedback('bad',`Schreibe oder sprich noch etwas mehr: mindestens ${item.min||1} vollständige Sätze.`);return}S().completeFree(T().number,task.id,task.items.length,idx,text);renderExercise(task,root)}}}
function feedback(type,text){const box=document.getElementById('feedback');if(box)box.innerHTML=`<div class="l8-feedback ${type}">${esc(text)}</div>`}
function solution(item){return Array.isArray(item.answer)?item.answer[0]:item.answer}
function check(task,item,idx,answer,root){const ok=S().equal(answer,item.answer);if(ok){const r=S().right(T().number,task.id,task.items.length,idx,answer);feedback('good',r.needsReview?'Richtig. Dieses Item kommt am Ende noch einmal.':'Richtig!');setTimeout(()=>renderExercise(task,root),650)}else{const r=S().wrong(T().number,task.id,task.items.length,idx,answer),n=r.tries;if(n===1)feedback('bad','Noch nicht richtig.');else if(n===2)feedback('warn',item.hint||'Achte genau auf die Form und den Satz.');else feedback('warn',`Lösung: ${solution(item)}. Gib die richtige Antwort jetzt selbst ein.`)}}
function finish(task,root){const state=S().load(T().number,task.id,task.items.length),exam=task.exam;const score=exam?Math.round((state.firstCorrect||0)/Math.max(1,state.total)*100):100;root.innerHTML=`<div class="l8-wrap">${previewNote()}<section class="l8-card l8-finish"><div class="l8-finish-icon">✓</div><h2>Aufgabe abgeschlossen</h2>${exam?`<div class="l8-score-total">${score}%</div><p>Ergebnis des Erstversuchs. Dein bestes Prüfungsergebnis wird gespeichert.</p>`:`<p>Du hast die Aufgabe zu 100 % abgeschlossen.</p>`}<div class="l8-row l8-center-actions"><a class="l8-btn primary" href="index.html">Zur Themenübersicht</a></div></section></div>`}
window.L8UI={themeOverview,taskPage};
})();