(function(){
'use strict';
if(window.__SP_L8T2_QUALITY_V1)return;window.__SP_L8T2_QUALITY_V1=true;window.L8_T2_QUALITY_PENDING=true;
const blocked=new Set(['was bist du von beruf','was sind sie von beruf','was machst du beruflich','was machen sie beruflich','eigen','eigene','eigenes','arbeiten als','arbeiten bei']);
const norm=v=>String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,' ').trim(),term=item=>String(item?.term||item?.full||item?.word||'').trim(),clone=value=>JSON.parse(JSON.stringify(value)),escRe=value=>String(value||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const cardTask=theme=>(theme?.tasks||[]).find(task=>task?.kind==='cards'||task?.id==='karteikarten'||/karteikart/i.test(task?.title||''));
function icon(task){const text=norm(`${task?.id||''} ${task?.title||''} ${task?.kind||''}`);if(task?.exam||/prufung|exam/.test(text))return'⭐';if(/karte|card/.test(text))return'📚';if(/memory/.test(text))return'🧠';if(/hor|listen|audio/.test(text))return'🎧';if(/lesen|reading|text versteh/.test(text))return'📖';if(/grammatik|grammar|satzteil/.test(text))return'🧲';if(/konjug| sein | haben /.test(' '+text+' '))return'🔤';if(/endung|gruppe|sort|zuord/.test(text))return'📦';if(/ordnen|order|reihenfolge|redemittel/.test(text))return'🧩';if(/schreib|write|lucke|text|brief|information|markier|plural/.test(text))return'✍️';return'✅'}
const excludedJobs=new Set(['die firma','der job','die stelle','die geschichte','das interview','das fernsehen','das thema','die ausbildung','die arbeit','der beruf','die berufserfahrung','das cafe','der stress','das restaurant','die zeitung']);
function professions(t1){const cards=(cardTask(t1)?.items||[]).filter(Boolean),out=[];for(const item of cards){const value=term(item);if(!/^(der|die)\s+/i.test(value)||blocked.has(norm(value))||excludedJobs.has(norm(value)))continue;if(/firma|stelle|geschichte|interview|thema|ausbildung|arbeitserfahrung|zeitung/.test(norm(value)))continue;if(!out.some(x=>norm(term(x))===norm(value)))out.push(item)}return out}
function pluralFrom(card){const text=String(card?.plural||card?.detail||''),m=text.match(/(?:plural\s*:?\s*)(.+)$/i);return String(card?.plural||m?.[1]||'').trim()}
const EXTRA_NOUNS=[['die Schule','die Schulen'],['die Klasse','die Klassen'],['der Arzt','die Ärzte'],['die Ärztin','die Ärztinnen'],['der Ausflug','die Ausflüge'],['der Eintritt','die Eintritte'],['die Grundschule','die Grundschulen'],['das Schwimmbad','die Schwimmbäder'],['der Tag','die Tage'],['die Woche','die Wochen'],['der Monat','die Monate'],['das Jahr','die Jahre'],['die Firma','die Firmen'],['der Termin','die Termine'],['die Bibliothek','die Bibliotheken']];
function articleItems(jobCards,timeCards){const rows=[],seen=new Set(),add=(singular,plural='')=>{singular=String(singular||'').trim();if(!/^(der|die|das)\s+/i.test(singular)||seen.has(norm(singular)))return;seen.add(norm(singular));const article=singular.split(/\s+/)[0],noun=singular.replace(/^(der|die|das)\s+/i,'');rows.push({type:'choice',prompt:`___ ${noun}`,options:['der','die','das'],answer:article,hint:`Lerne das Nomen mit Artikel: ${singular}.`});if(plural&&norm(plural)!==norm(singular)){const distractor=`die ${noun}s`;rows.push({type:'choice',prompt:`Plural von „${singular}“`,options:[plural,singular,distractor].filter((v,i,a)=>v&&a.indexOf(v)===i),answer:plural,hint:`Der Plural lautet: ${plural}.`})}};jobCards.forEach(card=>add(term(card),pluralFrom(card)));timeCards.forEach(card=>add(term(card),pluralFrom(card)));EXTRA_NOUNS.forEach(([s,p])=>add(s,p));return rows}
function jobContext(card){const value=term(card).replace(/^(der|die|das)\s+/i,'');return value?`Die Person arbeitet als ${value}.`:''}
function ensureMinimum(task,min,jobCards,useAllJobs=false){if(!task||task.exam||task.kind==='cards')return;task.items=Array.isArray(task.items)?task.items:[];if(!task.items.length)return;const wanted=Math.max(min,useAllJobs?jobCards.length:0),base=task.items.map(clone);let n=0;while(task.items.length<wanted){const item=clone(base[n%base.length]),card=jobCards[n%Math.max(1,jobCards.length)];if(card){const ctx=jobContext(card);item.context=[ctx,item.context].filter(Boolean).join('\n')}item.__spExpanded=true;task.items.push(item);n++}if(useAllJobs&&jobCards.length)task.items.forEach((item,index)=>{const ctx=jobContext(jobCards[index%jobCards.length]);if(ctx&&!String(item.context||'').includes(ctx))item.context=[ctx,item.context].filter(Boolean).join('\n')})}
function makeAllWords(t1,t2){const cards=[...(cardTask(t1)?.items||[]),...(cardTask(t2)?.items||[])].filter(card=>term(card)&&!blocked.has(norm(term(card)))),unique=[];for(const card of cards)if(!unique.some(x=>norm(term(x))===norm(term(card))))unique.push(card);return unique.map((card,index)=>{const answer=term(card),word=answer.replace(/^(der|die|das)\s+/i,''),example=String(card.example||'').trim(),detail=String(card.detail||'').trim();let clue=example;if(word&&clue)clue=clue.replace(new RegExp(escRe(word),'ig'),'_____');if(!clue||clue===example&&!detail)clue=`Wort aus dem Wortschatz: ${answer.charAt(0)}…`;else if(clue===example&&detail)clue=detail;const other=unique.filter(x=>norm(term(x))!==norm(answer)),options=[answer,term(other[(index+3)%Math.max(1,other.length)]),term(other[(index+7)%Math.max(1,other.length)])].filter((v,i,a)=>v&&a.indexOf(v)===i);for(const fallback of['die Schule','der Termin','die Woche'])if(options.length<3&&!options.includes(fallback))options.push(fallback);return{type:'choice',context:clue,prompt:'Welches Wort passt?',options,answer,hint:`Das gesuchte Wort ist „${answer}“.`}})}
window.L8_T2_QUALITY_READY=(async()=>{await window.L8_CONTENT_READY;if(window.L8_T2_TIME_REVIEW_READY)await window.L8_T2_TIME_REVIEW_READY;const all=window.L8_ALL_THEMES||{},t1=all[1]||all['1'],t2=all[2]||all['2'];if(!t2||!Array.isArray(t2.tasks))return t2;const jobs=professions(t1),practice=t2.tasks.filter(task=>!task?.exam),timeCards=cardTask(t2)?.items||[],task2=practice[1];if(task2){task2.title='Artikel und Plural';task2.instruction='Wähle Artikel und Plural. Nutze Wörter aus Lektion 3 bis 8.';task2.intro='Wiederhole bekannte Nomen aus Lektion 3–8 und die Berufe aus Lektion 8.';task2.items=articleItems(jobs,timeCards)}const p=t2.tasks.filter(task=>!task?.exam),task3=p[2],task4=p[3],task5=p[4],task6=p[5];[task2,task3,task4,task6].forEach(task=>ensureMinimum(task,10,jobs,true));if(task5){const allWords=makeAllWords(t1,t2);if(allWords.length>=10){task5.title='Alle Wörter wiederholen';task5.instruction='Wähle zu jedem Beispiel das passende Wort.';task5.intro='Hier kommen die Wörter aus den bisherigen Karteikarten noch einmal vor.';task5.kind='choice';task5.items=allWords}else ensureMinimum(task5,10,jobs,false)}t2.tasks.filter(task=>!task?.exam).forEach(task=>ensureMinimum(task,10,jobs,false));t2.tasks.forEach(task=>{task.emoji=icon(task)});t2.contentRevision='l8t2-quality-20260825-v1';if(Number(document.body?.dataset?.theme)===2)window.L8_THEME=t2;return t2})().catch(error=>{console.error('L8T2 Qualitätsstandard',error);return null}).finally(()=>{window.L8_T2_QUALITY_PENDING=false;window.L8_T2_QUALITY_DONE=true});
})();