(function(){
'use strict';
const VERSION='l7t1-full1',THEME=1,CDN='https://sprachpilot.b-cdn.net/';
function load(src){return new Promise((ok,bad)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=bad;document.body.appendChild(s)})}
Promise.resolve(window.L7_THEME_READY).then(()=>load(`../shared/l7-state.js?v=${VERSION}`)).then(start).catch(fail);
function fail(error){console.error(error);document.getElementById('app').innerHTML='<div class="container"><section class="card finish-box"><h2>Die Inhalte konnten nicht geladen werden.</h2><button class="btn" onclick="location.reload()">Neu laden</button></section></div>'}
function start(){
 const S=window.L7S,T=window.L7_THEME,root=document.getElementById('app');let R=null,order=[],writeOpen=false,recognition=null,revealed=false;
 const esc=S.esc,norm=S.norm;
 const profile=()=>S.profile()||{};
 const role=()=>String(localStorage.getItem('SP_LOGIN_ROLE')||localStorage.getItem('SP_ACTIVE_ROLE')||'').toLowerCase();
 const dashboard=()=>role()==='teacher'?'/teacher/index.html':'/student-dashboard/index.html';
 const accepted=i=>[i?.answer,i?.word,...(i?.answers||[])].filter(Boolean);
 const taskNumber=t=>Math.max(1,T.tasks.indexOf(t)+1);
 const taskFile=t=>t.external||`task.html?task=${encodeURIComponent(t.id)}&v=${VERSION}`;
 const taskKey=t=>t.id;
 function header(title,reset=false,taskPage=false){const p=profile(),name=[p.vorname||p.firstName,p.nachname||p.lastName].filter(Boolean).join(' ')||(S.preview()?'Lehrer-Vorschau':'Schüler/in');return`<header class="topbar"><div class="topbar-main"><a class="brand" href="/index.html"><div class="logo"><img src="/assets/logo/sprachpilot-logo.png" alt="SprachPilot"></div><div><h1>SprachPilot</h1><div class="subtitle">${esc(title)} · A1 Lektion 7 · Thema 1</div></div></a><div class="account-tools"><span class="account-pill">${esc(name)}</span><a class="account-link" href="${dashboard()}">Dashboard</a><a class="account-link" href="/profile/index.html">Profil</a></div></div><nav class="nav"><a class="btn secondary" href="${taskPage?'index.html':'../index.html'}">← Zurück</a><a class="btn secondary" href="index.html">Übersicht</a>${reset?'<button class="btn danger-btn" id="resetTheme">Fortschritte löschen</button>':''}</nav></header>`}
 const note=()=>S.preview()?'<div class="preview-note">Lehrer-Vorschau: Es werden keine Teilnehmerpunkte und keine Teilnehmerfortschritte gespeichert.</div>':'';
 function progress(t){const st=S.load(THEME,t.id,t.items.length),p=S.pct(THEME,t.id,t.items.length);return`<div class="task-progress-row"><span>${st.done.length} fehlerfrei · ${t.items.length-st.done.length} übrig</span><strong>${p}%</strong></div><div class="progress"><div class="bar" style="width:${p}%"></div></div>`}
 function overview(){const tasks=T.tasks||[],avg=Math.round(tasks.reduce((sum,t)=>sum+S.pct(THEME,t.id,t.items.length),0)/Math.max(1,tasks.length)),finished=tasks.filter(t=>S.pct(THEME,t.id,t.items.length)>=100).length;root.innerHTML=`<div class="container">${header(T.title||'Lektion 7 · Thema 1',true)}${note()}<section class="card progress-card"><div class="circle">${avg}%</div><div><h2>Dein Fortschritt</h2><p class="small">${finished} / ${tasks.length} Aufgaben abgeschlossen</p><div class="progress"><div class="bar" style="width:${avg}%"></div></div><p class="small">${esc(T.goal||'Übe Wortschatz, Modalverben, Fragen, Antworten und Hörverstehen.')}</p></div></section><section id="taskGrid"><div class="grid">${tasks.map((t,i)=>{const p=S.pct(THEME,t.id,t.items.length),locked=t.exam&&!S.allDone(THEME),done=p>=100,href=locked?'':taskFile(t);return`<a class="module ${locked?'exam-locked':''}" ${href?`href="${esc(href)}"`:''} ${locked?'aria-disabled="true"':''}><div class="num">${i+1}. ${esc(t.title)}</div><div class="big-icon">${t.icon||'▶'}</div><p class="small">${esc(locked?'Die Prüfung wird geöffnet, wenn alle vorherigen Aufgaben 100% erreicht haben.':shortDescription(t))}</p><div class="progress"><div class="bar" style="width:${p}%"></div></div><div class="small">${p}%</div><div class="start">${locked?'Gesperrt':done?'Fertig':'Starten'}</div></a>`}).join('')}</div></section><footer>© SprachPilot</footer></div>`;document.getElementById('resetTheme')?.addEventListener('click',()=>S.reset(THEME));if(location.hash)setTimeout(()=>document.querySelector(location.hash)?.scrollIntoView({behavior:'smooth',block:'center'}),80)}
 function shortDescription(t){const kind=t.kind||t.items?.[0]?.kind||'';if(t.exam)return'Zeige, was du gelernt hast.';if(kind==='cards')return'Lerne die Wörter.';if(kind==='order')return'Bringe die Wörter in die richtige Reihenfolge.';if(kind==='input')return'Schreibe die richtige Antwort.';if(kind==='speak')return'Sprich oder schreibe die Antwort.';if(kind==='free')return'Schreibe vollständige Sätze.';return t.description||'Wähle die passende Antwort.'}
 function taskPage(id){const t=T.tasks.find(x=>x.id===id);if(!t)return notFound();if(t.external&&!location.pathname.endsWith('/hoeren-erkennen.html')){location.replace(t.external);return}if(t.exam&&!S.allDone(THEME)){root.innerHTML=`<div class="container">${header(t.title,false,true)}<section class="card finish-box"><div class="finish-icon">🔒</div><h2>Prüfung gesperrt</h2><p>Schließe zuerst alle anderen Aufgaben mit 100% ab.</p><a class="btn" href="index.html">Zur Übersicht</a></section></div>`;return}const st=S.load(THEME,t.id,t.items.length);if(st.done.length>=t.items.length)return finish(t);R={t,index:S.index(THEME,t.id,t.items.length)};order=[];writeOpen=false;revealed=false;render()}
 function notFound(){root.innerHTML=`<div class="container">${header('Aufgabe',false,true)}<section class="card finish-box"><h2>Aufgabe nicht gefunden</h2><a class="btn" href="index.html">Zur Übersicht</a></section></div>`}
 function current(){return R.t.items[R.index]}
 function instruction(t,item){const kind=t.kind||item.kind||'choice';if(kind==='cards')return'Sieh dir das Bild und die Bedeutung an. Drehe die Karte um. Sprich oder schreibe das Wort.';if(kind==='order')return'Bringe die Wörter in die richtige Reihenfolge.';if(kind==='input')return'Schreibe die vollständige Antwort.';if(kind==='speak')return'Sprich die Antwort. Du kannst stattdessen schreiben.';if(kind==='free')return'Schreibe vollständige Sätze.';return t.description||'Wähle die passende Antwort.'}
 function top(t,item){return`<div class="task-title-block"><span class="task-number">Aufgabe ${taskNumber(t)}</span><h1>${esc(t.title)}</h1></div>${progress(t)}<div class="task-instruction">${esc(instruction(t,item))}</div>`}
 function image(file,alt='Bild'){if(!file)return'';return`<div class="task-img-box"><img src="${CDN+String(file).split('/').map(encodeURIComponent).join('/')}" alt="${esc(alt)}" onerror="this.hidden=true"></div>`}
 function audio(item){if(item.audioFile)return`<div class="audio-file-panel"><audio controls preload="metadata" src="${CDN+encodeURIComponent(item.audioFile)}"></audio><div class="audio-load-error" hidden>Die Audiodatei konnte nicht geladen werden.</div></div>`;if(item.audio)return`<div class="audio-panel"><button type="button" class="btn secondary" data-action="audio" data-audio="${esc(item.audio)}">🔊 Anhören</button></div>`;return''}
 function hint(item){const st=S.load(THEME,R.t.id,R.t.items.length),tries=st.tries||0;if(tries===1)return'<div class="no">Noch nicht richtig. Versuche es noch einmal.</div>';if(tries===2)return`<div class="hint"><strong>Hinweis:</strong> ${esc(item.hint||genericHint(item))}</div>`;if(tries>=3)return`<div class="no"><strong>Lösung:</strong> ${esc(item.answer||item.word||'')}<br>Gib die richtige Antwort jetzt selbst ein. Die Aufgabe kommt später noch einmal.</div>`;return''}
 function genericHint(item){const a=String(item.answer||item.word||'');if((R.t.kind||item.kind)==='order')return'Achte auf die Verbposition und auf das Satzende.';return a?`Die Lösung beginnt mit „${a.charAt(0)}“.`:'Lies die Aufgabe noch einmal.'}
 function input(label='Schreibe deine Antwort.',hidden=false){return`<div class="answer-area" ${hidden?'hidden':''}><label for="answerInput">${esc(label)}</label><div class="answer-row"><input id="answerInput" autocomplete="off"><button type="button" class="btn" data-action="check">Kontrollieren</button></div></div>`}
 function options(item){const values=S.shuffle(item.options||[]),abc=values.length===3;return`<div class="choice-grid ${abc?'abc-list':''}">${values.map((v,i)=>`<button type="button" class="choice" data-answer="${esc(v)}">${abc?`<span class="abc-letter">${String.fromCharCode(65+i)}</span>`:''}<span>${esc(v)}</span></button>`).join('')}</div>`}
 function render(){stopMic();const t=R.t,item=current(),kind=t.kind||item.kind||'choice';document.title=`Aufgabe ${taskNumber(t)} · ${t.title}`;let body='';if(kind==='cards')body=card(item);else if(kind==='choice')body=options(item);else if(kind==='input')body=input('Schreibe die vollständige Antwort.');else if(kind==='order')body=`<div id="orderAnswer" class="order-answer">Klicke die Wörter in der richtigen Reihenfolge an.</div><div class="token-grid">${S.shuffle(item.tokens||[]).map(v=>`<button type="button" class="token" data-token="${esc(v)}">${esc(v)}</button>`).join('')}</div><div class="actions centered"><button class="btn" data-action="check-order">Kontrollieren</button><button class="btn secondary" data-action="undo">Zurück</button><button class="btn ghost" data-action="reset-order">Neu</button></div>`;else if(kind==='speak')body=`<div class="mode-actions"><button class="btn" data-action="mic">🎤 Sprechen</button><button class="btn secondary" data-action="write">✍️ Schreiben</button></div>${input('Schreibe die vollständige Antwort.',!writeOpen)}`;else if(kind==='free')body=`<div class="free-area"><label for="freeAnswer">Deine Antwort</label><textarea id="freeAnswer" rows="7" placeholder="${esc(item.example||'Schreibe vollständige Sätze.')}\"></textarea><p>Mindestens ${item.minWords||5} Wörter.</p><button class="btn" data-action="save-free">Speichern und weiter</button></div>`;else body=options(item);root.innerHTML=`<div class="container">${header(t.title,false,true)}${note()}<section class="card task-card">${top(t,item)}<div class="question-card">${item.context?`<div class="dialog-box">${esc(item.context).replace(/\n/g,'<br>')}</div>`:''}${kind!=='cards'?image(item.image,item.prompt||item.word):''}${kind!=='cards'?audio(item):''}${kind!=='cards'&&item.prompt?`<h2 class="question">${esc(item.prompt)}</h2>`:''}${body}<div id="feedback" class="feedback">${hint(item)}</div><div id="tech"></div></div></section><footer>© SprachPilot</footer></div>`;bind()}
 function card(item){const plural=item.plural?`<div><span>Plural</span><strong>${esc(item.plural)}</strong></div>`:'';return`<div class="flip-wrap"><div id="flipCard" class="flip-card ${revealed?'flipped':''}" tabindex="0"><div class="flip-face flip-front">${image(item.image,item.word)}<div class="card-translation-box"><span>Bedeutung</span><strong>${esc(item.meaning||'')}</strong></div><div class="flip-note">Karte umdrehen</div></div><div class="flip-face flip-back"><div class="flip-word">${esc(item.word)}</div><div class="card-details">${plural}<div><span>Beispiel</span><strong>${esc(item.example||'')}</strong></div></div><button type="button" class="btn secondary card-listen-btn" data-action="card-audio">🔊 Anhören</button></div></div></div><div class="actions card-actions"><button class="btn" data-action="card-mic">🎤 Sprechen</button><button class="btn secondary" data-action="card-write">✍️ Schreiben</button></div><div id="cardWrite" hidden>${input('Wort schreiben')}</div><div id="cardAfter" class="actions card-actions">${revealed?'<button class="btn" data-action="card-next">Weiter</button>':''}</div>`}
 function bind(){root.querySelectorAll('audio').forEach(a=>a.addEventListener('error',()=>{a.hidden=true;a.nextElementSibling.hidden=false},{once:true}));root.onclick=e=>{const b=e.target.closest('button');if(!b){if(e.target.closest('#flipCard'))revealCard();return}if(b.dataset.answer!==undefined)return check(b.dataset.answer);if(b.dataset.token!==undefined)return token(b);const a=b.dataset.action;if(a==='check')return check(document.getElementById('answerInput')?.value);if(a==='audio')return S.say(b.dataset.audio,()=>technical('Die Audiofunktion ist nicht verfügbar.'));if(a==='card-audio')return S.say(current().audio||current().word,()=>technical('Die Audiofunktion ist nicht verfügbar.'));if(a==='mic')return mic(false);if(a==='write'){writeOpen=true;return render()}if(a==='card-mic')return mic(true);if(a==='card-write'){document.getElementById('cardWrite').hidden=false;return document.getElementById('answerInput')?.focus()}if(a==='card-next'){S.right(THEME,R.t.id,R.t.items.length);return taskPage(R.t.id)}if(a==='check-order')return check(order.join(' '));if(a==='undo')return undo();if(a==='reset-order')return resetOrder();if(a==='save-free')return saveFree()};document.getElementById('answerInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')check(e.target.value)})}
 function correctValue(item,value){const compact=v=>norm(v).replace(/\s+/g,'');return accepted(item).some(a=>norm(a)===norm(value)||((R.t.kind||item.kind)==='order'&&compact(a)===compact(value)))}
 function check(value){const item=current();if(!String(value||'').trim())return;const ok=correctValue(item,value);S.attempt(THEME,R.t.id,R.t.items.length,R.index,ok);if(ok)return right();S.wrong(THEME,R.t.id,R.t.items.length);writeOpen=true;taskPage(R.t.id)}
 function right(){const st=S.load(THEME,R.t.id,R.t.items.length),repeat=st.hadWrong||st.tries>0;S.right(THEME,R.t.id,R.t.items.length);root.querySelectorAll('button,input,textarea,audio').forEach(x=>x.disabled=true);document.getElementById('feedback').innerHTML=`<div class="ok">Richtig.${repeat?' Die Aufgabe kommt am Ende noch einmal.':''}</div>`;setTimeout(()=>taskPage(R.t.id),650)}
 function revealCard(){if(revealed)return;revealed=true;const item=current();S.attempt(THEME,R.t.id,R.t.items.length,R.index,false);S.wrong(THEME,R.t.id,R.t.items.length);render()}
 function token(b){if(b.disabled)return;order.push(b.dataset.token);b.disabled=true;drawOrder()}
 function drawOrder(){const x=document.getElementById('orderAnswer');if(x)x.textContent=order.length?order.join(' '):'Klicke die Wörter in der richtigen Reihenfolge an.'}
 function undo(){if(!order.length)return;order.pop();render()}
 function resetOrder(){order=[];render()}
 function saveFree(){const item=current(),v=String(document.getElementById('freeAnswer')?.value||'').trim();if(v.split(/\s+/).filter(Boolean).length<(item.minWords||5))return technical(`Schreibe mindestens ${item.minWords||5} Wörter und vollständige Sätze.`);S.attempt(THEME,R.t.id,R.t.items.length,R.index,true);S.right(THEME,R.t.id,R.t.items.length,true);taskPage(R.t.id)}
 function mic(cardMode){const item=current();S.mic(item,answers=>{const exact=answers.find(v=>correctValue(item,v));check(exact||answers[0]||'')},technical)}
 function stopMic(){if(recognition)try{recognition.abort()}catch{}recognition=null}
 function technical(message){const x=document.getElementById('tech');if(x)x.innerHTML=`<div class="hint">${esc(message)}</div>`}
 function finish(t){const st=S.load(THEME,t.id,t.items.length),idx=T.tasks.indexOf(t),next=T.tasks[idx+1],score=t.exam?Math.round((st.firstCorrect||0)/Math.max(1,t.items.length)*100):100,stars=score>=100?3:score>=70?2:score>=50?1:0;root.innerHTML=`<div class="container">${header(t.title,false,true)}<section class="card finish-box"><div class="finish-icon">✓</div><h2>Geschafft!</h2>${t.exam?`<div class="stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>${score}% beim ersten Versuch</p>`:'<p>Du hast diese Aufgabe fehlerfrei abgeschlossen.</p>'}<div class="actions centered"><a class="btn" href="${next?taskFile(next):'index.html'}">Weiter →</a><a class="btn secondary" href="index.html">Zur Übersicht</a></div></section><footer>© SprachPilot</footer></div>`}
 const params=new URLSearchParams(location.search);document.body.dataset.page==='task'?taskPage(params.get('task')||T.tasks[0]?.id):overview();
}
})();