import {renderSpHeader,bindSpHeader} from '/js/sp-header.js?v=theme-standard4';

const D=window.L10T1||{cards:[],tasks:[]};
const cards=D.cards||[];
const qs=new URLSearchParams(location.search);
const taskId=String(qs.get('task')||'karteikarten');
const task=D.tasks.find(t=>t.id===taskId)||D.tasks[0];
const root=document.getElementById('app');
const total=cards.length;
const CARD_BY_ID=Object.fromEntries(cards.map(c=>[c.id,c]));
let memoryOpen=[];
let busy=false;

function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function normalize(v){return String(v??'').trim().toLowerCase().replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function wordOk(value,item){const n=normalize(value);return n===normalize(item.term)||n===normalize(item.full)}
function pluralOk(value,item){const n=normalize(value);return n===normalize(item.plural)||n===normalize(String(item.plural).replace(/^die\s+/i,''))}
function stateKey(id=taskId){return`SP_L10_T1_${id}`}
function baseState(id=taskId){return{id,order:shuffle(cards.map(c=>c.id)),done:[],firstCorrect:[],total,updatedAt:Date.now()}}
function loadState(){
 let s=null;try{s=JSON.parse(localStorage.getItem(stateKey())||'null')}catch(e){}
 if(!s||!Array.isArray(s.order)||s.order.length!==total)s=baseState();
 s.done=Array.isArray(s.done)?s.done:[];s.firstCorrect=Array.isArray(s.firstCorrect)?s.firstCorrect:[];s.total=total;
 if(taskId==='pruefung'&&s.finished&&s.percent<100){const last={percent:s.percent,at:s.updatedAt};s=baseState();s.last=last}
 if(taskId==='memory'&&!Array.isArray(s.pairOrder))s.pairOrder=shuffle(cards.flatMap(c=>[c.id+':img',c.id+':word']));
 if(taskId==='pruefung'&&!s.modes){const modes=shuffle(['image-word','word-image','article','plural','listen-image','definition-choice','definition-write']);s.modes={};s.order.forEach((id,i)=>s.modes[id]=modes[i%modes.length])}
 saveState(s);return s
}
let state=loadState();
function saveState(s=state){s.updatedAt=Date.now();try{localStorage.setItem(stateKey(),JSON.stringify(s))}catch(e){}}
function doneCount(){return state.done.length}
function nextItem(){const id=state.order.find(x=>!state.done.includes(x));return id?CARD_BY_ID[id]:null}
function image(item,cls='l10-image'){return`<img class="${cls}" src="${esc(item.image)}" alt="" draggable="false">`}
function taskProgress(){return`<div class="l10-progress"><span>${doneCount()} / ${total}</span><div><i style="width:${total?Math.round(doneCount()/total*100):0}%"></i></div></div>`}
function header(){return renderSpHeader({subtitle:`${task.title} · A1 Lektion 10 · Thema 1`,color:{main:'#F4A3A3',dark:'#A86464',soft:'#FDF1F1',line:'#F3C9C9'},navItems:[{label:'← Zurück',href:'./'},{label:'Übersicht',href:'uebersicht.html'}]})}
function shell(content,{progress=true}={}){root.innerHTML=`<div class="l10-task-page">${header()}<div class="l8-wrap"><section class="l8-task-head"><div class="l8-task-title-block"><h1>${esc(task.title)}</h1><p>${esc(task.icon||'📘')} ${esc(task.text||'')}</p></div>${progress?taskProgress():''}</section>${content}<footer>© SprachPilot</footer></div></div>`;bindSpHeader(root);setTimeout(()=>window.SPTaskAutoScroll?.schedule?.(0,'render'),40)}
function feedback(text,ok){const el=document.querySelector('.l10-feedback');if(!el)return;el.textContent=text;el.className='l10-feedback '+(ok?'ok':'bad')}
function markAndNext(id,delay=480){if(!state.done.includes(id))state.done.push(id);saveState();busy=true;setTimeout(()=>{busy=false;render()},delay)}
function finish(title='Geschafft!',text=`Du hast alle ${total} Wörter bearbeitet.`){shell(`<section class="l8-card l8-finish"><div class="l10-finish-icon">✅</div><h2>${esc(title)}</h2><p>${esc(text)}</p><div class="l10-finish-actions"><a class="l10-btn primary" href="./">Zur Themenübersicht</a><a class="l10-btn" href="uebersicht.html">Wortschatzübersicht</a></div></section>`,{progress:false})}
function optionsFor(item,count=4){const rest=shuffle(cards.filter(c=>c.id!==item.id)).slice(0,count-1);return shuffle([item,...rest])}
function speak(item){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(item.term);u.lang='de-DE';u.rate=.78;speechSynthesis.speak(u)}catch(e){}}
function listenButton(item){return`<button class="l10-listen" type="button" data-listen="${esc(item.id)}">🔊 Anhören</button>`}
function bindListen(){document.querySelectorAll('[data-listen]').forEach(b=>b.onclick=()=>speak(CARD_BY_ID[b.dataset.listen]))}
function choiceButtons(options,labelOf,onPick){document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{if(busy)return;onPick(b,b.dataset.choice)})}
function standardQuestion(prompt,main,optionsHtml,extra=''){return`<section class="l8-card l10-question"><div class="l10-question-label">${esc(prompt)}</div>${main}<div class="l10-options">${optionsHtml}</div>${extra}<div class="l10-feedback" aria-live="polite"></div></section>`}

function renderImageWord(){const item=nextItem();if(!item)return finish();const opts=optionsFor(item);shell(standardQuestion('Welches Wort passt zum Bild?',`<div class="l10-main-image">${image(item)}</div>`,opts.map(o=>`<button type="button" data-choice="${esc(o.id)}">${esc(o.full)}</button>`).join('')));choiceButtons(opts,null,(b,id)=>{if(id===item.id){b.classList.add('correct');feedback('Richtig!',true);markAndNext(item.id)}else{b.classList.add('wrong');feedback('Noch einmal.',false)}})}
function renderWordImage(){const item=nextItem();if(!item)return finish();const opts=optionsFor(item);shell(standardQuestion('Welches Bild passt zum Wort?',`<div class="l10-word-prompt">${esc(item.full)}</div>`,opts.map(o=>`<button class="l10-image-choice" type="button" data-choice="${esc(o.id)}">${image(o,'')}</button>`).join('')));choiceButtons(opts,null,(b,id)=>{if(id===item.id){b.classList.add('correct');feedback('Richtig!',true);markAndNext(item.id)}else{b.classList.add('wrong');feedback('Noch einmal.',false)}})}
function renderArticle(){const item=nextItem();if(!item)return finish();const opts=shuffle(['der','die','das']);shell(standardQuestion('Wähle den richtigen Artikel.',`<div class="l10-main-image">${image(item)}</div><div class="l10-word-hint">${esc(item.term)}</div>`,opts.map(o=>`<button type="button" data-choice="${o}">${o}</button>`).join('')));choiceButtons(opts,null,(b,val)=>{if(val===item.article){b.classList.add('correct');feedback('Richtig!',true);markAndNext(item.id)}else{b.classList.add('wrong');feedback('Noch einmal.',false)}})}
function renderPlural(){const item=nextItem();if(!item)return finish();shell(`<section class="l8-card l10-question"><div class="l10-question-label">Schreibe die Pluralform.</div><div class="l10-main-image">${image(item)}</div><div class="l10-word-hint">${esc(item.full)}</div><div class="l10-write-row"><input id="answerInput" autocomplete="off" placeholder="Pluralform"><button id="checkBtn" type="button">Prüfen</button></div><div class="l10-feedback" aria-live="polite"></div></section>`);const input=document.getElementById('answerInput'),check=document.getElementById('checkBtn');const run=()=>{if(busy)return;if(pluralOk(input.value,item)){feedback(`Richtig: ${item.plural}`,true);markAndNext(item.id)}else feedback('Noch einmal.',false)};check.onclick=run;input.onkeydown=e=>{if(e.key==='Enter')run()};input.focus()}
function renderListenImage(){const item=nextItem();if(!item)return finish();const opts=optionsFor(item);shell(standardQuestion('Höre das Wort. Welches Bild passt?',`<div class="l10-audio-stage">${listenButton(item)}</div>`,opts.map(o=>`<button class="l10-image-choice" type="button" data-choice="${esc(o.id)}">${image(o,'')}</button>`).join('')));bindListen();choiceButtons(opts,null,(b,id)=>{if(id===item.id){b.classList.add('correct');feedback('Richtig!',true);markAndNext(item.id)}else{b.classList.add('wrong');feedback('Noch einmal.',false)}})}
function renderListenWrite(){const item=nextItem();if(!item)return finish();shell(`<section class="l8-card l10-question"><div class="l10-question-label">Höre und schreibe das Wort.</div><div class="l10-audio-stage">${listenButton(item)}</div><div class="l10-write-row"><input id="answerInput" autocomplete="off" placeholder="Wort schreiben"><button id="checkBtn" type="button">Prüfen</button></div><div class="l10-feedback" aria-live="polite"></div></section>`);bindListen();const input=document.getElementById('answerInput');const run=()=>{if(busy)return;if(wordOk(input.value,item)){feedback(`Richtig: ${item.full}`,true);markAndNext(item.id)}else feedback('Noch einmal.',false)};document.getElementById('checkBtn').onclick=run;input.onkeydown=e=>{if(e.key==='Enter')run()};setTimeout(()=>speak(item),180);input.focus()}
function renderGap(){const item=nextItem();if(!item)return finish();const sentence=String(item.gap||'').replace('___','<span class="l10-gap">_____</span>');shell(`<section class="l8-card l10-question"><div class="l10-question-label">Ergänze das richtige Körperteil.</div><div class="l10-sentence">${sentence}</div><div class="l10-write-row"><input id="answerInput" autocomplete="off" placeholder="Körperteil"><button id="checkBtn" type="button">Prüfen</button></div><div class="l10-feedback" aria-live="polite"></div></section>`);const input=document.getElementById('answerInput');const run=()=>{if(wordOk(input.value,item)){feedback(`Richtig: ${item.term}`,true);markAndNext(item.id)}else feedback('Noch einmal.',false)};document.getElementById('checkBtn').onclick=run;input.onkeydown=e=>{if(e.key==='Enter')run()};input.focus()}
function renderDefinitionChoice(){const item=nextItem();if(!item)return finish();const opts=optionsFor(item);shell(standardQuestion('Welches Wort passt zur Bedeutung?',`<div class="l10-definition">${esc(item.meaning)}</div>`,opts.map(o=>`<button type="button" data-choice="${esc(o.id)}">${esc(o.full)}</button>`).join('')));choiceButtons(opts,null,(b,id)=>{if(id===item.id){b.classList.add('correct');feedback('Richtig!',true);markAndNext(item.id)}else{b.classList.add('wrong');feedback('Noch einmal.',false)}})}
function renderDefinitionWrite(){const item=nextItem();if(!item)return finish();shell(`<section class="l8-card l10-question"><div class="l10-question-label">Schreibe das passende Wort.</div><div class="l10-definition">${esc(item.meaning)}</div><div class="l10-write-row"><input id="answerInput" autocomplete="off" placeholder="Körperteil"><button id="checkBtn" type="button">Prüfen</button></div><div class="l10-feedback" aria-live="polite"></div></section>`);const input=document.getElementById('answerInput');const run=()=>{if(wordOk(input.value,item)){feedback(`Richtig: ${item.full}`,true);markAndNext(item.id)}else feedback('Noch einmal.',false)};document.getElementById('checkBtn').onclick=run;input.onkeydown=e=>{if(e.key==='Enter')run()};input.focus()}

function renderCards(){const item=nextItem();if(!item)return finish('Karteikarten geschafft!',`Du hast alle ${total} Karten angesehen.`);shell(`<section class="l8-card-stage"><div class="l8-flip-wrap"><div class="l8-flip-card" id="studyCard"><div class="l8-flip-front"><div class="l8-card-visual">${image(item)}</div><div class="l8-card-translation"><span>Muttersprache</span><strong>${esc(item.translation||'–')}</strong></div></div><div class="l8-flip-back"><div class="l8-flip-back-grid"><div class="l8-back-image">${image(item)}</div><div class="l8-back-info"><div class="l8-flip-word">${esc(item.full)}</div><div class="l8-card-translation"><span>Muttersprache</span><strong>${esc(item.translation||'–')}</strong></div><div class="l8-card-detail"><span>Plural</span><strong>${esc(item.plural)}</strong></div><button class="l8-card-listen" id="cardListen" type="button">🔊 Anhören</button></div></div></div></div></div><div class="l8-card-actions"><button class="btn" id="flipBtn" type="button">🔄 Umdrehen</button><button class="btn" id="cardMic" type="button">🎤 Sprechen</button><button class="btn secondary" id="cardWrite" type="button">✍️ Schreiben</button><button class="btn primary" id="nextCard" type="button">Weiter →</button></div><div class="l8-card-write l7-answer-box" id="cardWriteBox" hidden><div class="l8-answer-row"><input id="cardInput" autocomplete="off" placeholder="Wort schreiben"><button id="cardCheck" class="btn" type="button">Prüfen</button></div><div class="l10-feedback"></div></div>`);const card=document.getElementById('studyCard');document.getElementById('flipBtn').onclick=()=>card.classList.toggle('is-flipped');document.getElementById('cardListen').onclick=()=>speak(item);document.getElementById('nextCard').onclick=()=>markAndNext(item.id,100);document.getElementById('cardWrite').onclick=()=>{const box=document.getElementById('cardWriteBox');box.hidden=!box.hidden;if(!box.hidden)document.getElementById('cardInput').focus()};const check=()=>{const box=document.getElementById('cardWriteBox'),fb=box.querySelector('.l10-feedback');if(wordOk(document.getElementById('cardInput').value,item)){fb.textContent='Richtig!';fb.className='l10-feedback ok'}else{fb.textContent='Noch einmal.';fb.className='l10-feedback bad'}};document.getElementById('cardCheck').onclick=check;document.getElementById('cardInput').onkeydown=e=>{if(e.key==='Enter')check()};document.getElementById('cardMic').onclick=()=>startRecognition(item);setTimeout(()=>window.SPCardTaskStandard?.normalizeCard?.(),50)}
function startRecognition(item){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){const box=document.getElementById('cardWriteBox');box.hidden=false;box.querySelector('.l10-feedback').textContent='Sprechen wird von diesem Browser nicht unterstützt.';return}const r=new SR();r.lang='de-DE';r.interimResults=false;r.maxAlternatives=1;const mic=document.getElementById('cardMic');mic.textContent='🎤 …';r.onresult=e=>{const heard=e.results?.[0]?.[0]?.transcript||'';const box=document.getElementById('cardWriteBox');box.hidden=false;const fb=box.querySelector('.l10-feedback');fb.textContent=wordOk(heard,item)?`Richtig: ${heard}`:`Gehört: ${heard}`;fb.className='l10-feedback '+(wordOk(heard,item)?'ok':'bad')};r.onend=()=>mic.textContent='🎤 Sprechen';r.onerror=()=>mic.textContent='🎤 Sprechen';try{r.start()}catch(e){mic.textContent='🎤 Sprechen'}}

function renderMemory(){if(state.done.length>=total)return finish('Memory geschafft!',`Du hast alle ${total} Paare gefunden.`);const deck=state.pairOrder||[];shell(`<section class="l8-card l10-memory-wrap"><div class="l10-question-label">Finde Wort und Bild.</div><div class="l10-memory-grid">${deck.map(token=>{const [id,type]=token.split(':');const item=CARD_BY_ID[id],matched=state.done.includes(id),open=matched||memoryOpen.includes(token);let inside='?';if(open)inside=type==='img'?image(item,''):esc(item.full);return`<button type="button" class="l10-memory-card ${open?'open':''} ${matched?'matched':''}" data-memory="${esc(token)}" ${matched?'disabled':''}>${inside}</button>`}).join('')}</div><div class="l10-feedback"></div></section>`);document.querySelectorAll('[data-memory]').forEach(b=>b.onclick=()=>memoryPick(b.dataset.memory))}
function memoryPick(token){if(busy||memoryOpen.includes(token))return;memoryOpen.push(token);renderMemory();if(memoryOpen.length<2)return;const [a,b]=memoryOpen.map(t=>t.split(':'));if(a[0]===b[0]&&a[1]!==b[1]){busy=true;setTimeout(()=>{if(!state.done.includes(a[0]))state.done.push(a[0]);saveState();memoryOpen=[];busy=false;renderMemory()},450)}else{busy=true;setTimeout(()=>{memoryOpen=[];busy=false;renderMemory()},700)}}

function examAnswer(item,correct,correctText){if(busy)return;busy=true;if(correct&&!state.firstCorrect.includes(item.id))state.firstCorrect.push(item.id);if(!state.done.includes(item.id))state.done.push(item.id);saveState();feedback(correct?'Richtig.':`Richtig wäre: ${correctText}`,correct);setTimeout(()=>{busy=false;renderExam()},750)}
function renderExam(){if(state.done.length>=total)return finishExam();const item=nextItem();const mode=state.modes[item.id];if(mode==='image-word'){const opts=optionsFor(item);shell(standardQuestion('Prüfung: Welches Wort passt zum Bild?',`<div class="l10-main-image">${image(item)}</div>`,opts.map(o=>`<button type="button" data-choice="${o.id}">${esc(o.full)}</button>`).join('')));choiceButtons(opts,null,(b,id)=>examAnswer(item,id===item.id,item.full));return}
 if(mode==='word-image'){const opts=optionsFor(item);shell(standardQuestion(`Prüfung: Welches Bild zeigt „${item.full}“?`,'',opts.map(o=>`<button class="l10-image-choice" type="button" data-choice="${o.id}">${image(o,'')}</button>`).join('')));choiceButtons(opts,null,(b,id)=>examAnswer(item,id===item.id,item.full));return}
 if(mode==='article'){const opts=shuffle(['der','die','das']);shell(standardQuestion(`Prüfung: Artikel für „${item.term}“?`,`<div class="l10-main-image">${image(item)}</div>`,opts.map(o=>`<button type="button" data-choice="${o}">${o}</button>`).join('')));choiceButtons(opts,null,(b,val)=>examAnswer(item,val===item.article,item.article));return}
 if(mode==='plural'){return examWrite(item,'Prüfung: Schreibe die Pluralform.',item.full,v=>pluralOk(v,item),item.plural)}
 if(mode==='listen-image'){const opts=optionsFor(item);shell(standardQuestion('Prüfung: Höre und wähle das Bild.',`<div class="l10-audio-stage">${listenButton(item)}</div>`,opts.map(o=>`<button class="l10-image-choice" type="button" data-choice="${o.id}">${image(o,'')}</button>`).join('')));bindListen();choiceButtons(opts,null,(b,id)=>examAnswer(item,id===item.id,item.full));return}
 if(mode==='definition-choice'){const opts=optionsFor(item);shell(standardQuestion('Prüfung: Welches Wort passt?',`<div class="l10-definition">${esc(item.meaning)}</div>`,opts.map(o=>`<button type="button" data-choice="${o.id}">${esc(o.full)}</button>`).join('')));choiceButtons(opts,null,(b,id)=>examAnswer(item,id===item.id,item.full));return}
 return examWrite(item,'Prüfung: Schreibe das passende Wort.',item.meaning,v=>wordOk(v,item),item.full)}
function examWrite(item,label,prompt,check,answer){shell(`<section class="l8-card l10-question"><div class="l10-question-label">${esc(label)}</div><div class="l10-definition">${esc(prompt)}</div><div class="l10-write-row"><input id="answerInput" autocomplete="off" placeholder="Antwort"><button id="checkBtn" type="button">Antwort speichern</button></div><div class="l10-feedback"></div></section>`);const input=document.getElementById('answerInput');let used=false;const run=()=>{if(used)return;used=true;examAnswer(item,check(input.value),answer)};document.getElementById('checkBtn').onclick=run;input.onkeydown=e=>{if(e.key==='Enter')run()};input.focus()}
async function finishExam(){const correct=state.firstCorrect.length,percent=Math.round(correct/total*100);state.finished=true;state.percent=percent;saveState();if(!state.examSynced){state.examSynced=true;saveState();try{const mod=await import('/js/progress.js?v=20260831-central6');await mod.recordExamResult({module:'wortschatz',moduleTitle:'Wortschatz',level:'A1',lesson:10,theme:1,topicId:'wortschatz-a1-lektion-10-thema-1',title:'A1 Lektion 10 · Thema 1 · Körper und Körperteile',percent,stars:percent>=100?3:percent>=70?2:percent>=50?1:0})}catch(e){console.warn('L10T1 exam sync failed',e)}}const run=Number(window.SPProgress?.currentRun?.('wortschatz-a1-lektion-10-thema-1')||localStorage.getItem('SP_SCORE_RUN_wortschatz-a1-lektion-10-thema-1')||1),max=run===1?100:run===2?200:300,points=Math.round(max*percent/100);shell(`<section class="l8-card l8-finish" data-sp-points-shown="1"><div class="l10-finish-icon">⭐</div><h2>Prüfung beendet</h2><div class="l10-exam-score">${percent}%</div><p>${correct} von ${total} Wörtern richtig beim ersten Versuch.</p><div class="l8-score-total">${points} / ${max} Punkte</div><div class="l10-finish-actions"><a class="l10-btn primary" href="./">Zur Themenübersicht</a>${percent<100?`<button class="l10-btn" id="retryExam" type="button">Prüfung wiederholen</button>`:''}</div></section>`,{progress:false});const retry=document.getElementById('retryExam');if(retry)retry.onclick=()=>{localStorage.removeItem(stateKey());state=loadState();renderExam()}}

function render(){if(taskId==='karteikarten')return renderCards();if(taskId==='bild-wort')return renderImageWord();if(taskId==='wort-bild')return renderWordImage();if(taskId==='artikel')return renderArticle();if(taskId==='plural')return renderPlural();if(taskId==='hoeren-bild')return renderListenImage();if(taskId==='hoeren-schreiben')return renderListenWrite();if(taskId==='memory')return renderMemory();if(taskId==='lueckentext')return renderGap();if(taskId==='bedeutung-waehlen')return renderDefinitionChoice();if(taskId==='bedeutung-schreiben')return renderDefinitionWrite();if(taskId==='pruefung')return renderExam();return renderCards()}
render();
