const TOPIC='wortschatz-a1-lektion-9-thema-1',TASK_ID='behoerden-dialog';
const root=document.getElementById('app');let recognition=null;
const turns=[
{id:'d1',scene:'1 · Einen Antrag stellen',officer:'Guten Tag. Was kann ich für Sie tun?',instruction:'Sagen Sie, dass Sie einen Antrag stellen möchten, und fragen Sie, was Sie machen müssen.',answers:['Ich möchte einen Antrag stellen. Was muss ich machen?','Ich will einen Antrag stellen. Was muss ich machen?','Ich möchte einen Antrag stellen. Was muss ich zuerst machen?'],hint:'Benutzen Sie „einen Antrag stellen“ und „Was muss ich …?“.'},
{id:'d2',scene:'1 · Einen Antrag stellen',officer:'Zuerst müssen Sie den Antrag ausfüllen.',instruction:'Fragen Sie, ob Sie Ihren Ausweis mitbringen müssen.',answers:['Muss ich meinen Ausweis mitbringen?','Muss ich den Ausweis mitbringen?','Brauche ich meinen Ausweis?','Brauche ich den Ausweis?'],hint:'Beginnen Sie zum Beispiel mit „Muss ich …?“.'},
{id:'d3',scene:'1 · Einen Antrag stellen',officer:'Ja. Bitte bringen Sie Ihren Ausweis und Ihre Unterlagen mit.',instruction:'Fragen Sie, wo Sie unterschreiben müssen.',answers:['Wo muss ich unterschreiben?','Wo muss ich den Antrag unterschreiben?','Wo muss ich die Papiere unterschreiben?'],hint:'Fragewort „Wo“ + müssen + ich + … + unterschreiben.'},
{id:'d4',scene:'1 · Einen Antrag stellen',officer:'Unten auf Seite zwei.',instruction:'Fragen Sie, ob Sie auch die Papiere unterschreiben müssen.',answers:['Muss ich auch die Papiere unterschreiben?','Muss ich die Papiere auch unterschreiben?'],hint:'Muss ich + die Papiere + auch + unterschreiben?'},
{id:'d5',scene:'2 · Ausländischer Führerschein',officer:'Guten Tag. Wie kann ich Ihnen helfen?',instruction:'Sagen Sie, dass Sie einen ausländischen Führerschein haben, und fragen Sie, ob er hier gültig ist.',answers:['Ich habe einen ausländischen Führerschein. Ist er hier gültig?','Mein Führerschein ist ausländisch. Ist er hier gültig?','Ist mein ausländischer Führerschein hier gültig?'],hint:'Benutzen Sie „ausländischer Führerschein“ und „gültig“.'},
{id:'d6',scene:'2 · Ausländischer Führerschein',officer:'Ich muss den Führerschein prüfen.',instruction:'Fragen Sie, ob Sie einen Antrag stellen müssen.',answers:['Muss ich einen Antrag stellen?','Muss ich dafür einen Antrag stellen?','Muss ich einen Antrag ausfüllen?'],hint:'Muss ich + einen Antrag + …?'},
{id:'d7',scene:'2 · Ausländischer Führerschein',officer:'Ja. Bitte füllen Sie diesen Antrag aus.',instruction:'Fragen Sie, welche Unterlagen Sie mitbringen müssen.',answers:['Welche Unterlagen muss ich mitbringen?','Welche Dokumente muss ich mitbringen?','Welche Papiere muss ich mitbringen?','Was muss ich mitbringen?','Welche Unterlagen brauche ich?'],hint:'Beginnen Sie mit „Welche Unterlagen …?“ oder „Was …?“.'},
{id:'d8',scene:'2 · Ausländischer Führerschein',officer:'Bringen Sie bitte den Führerschein und den Ausweis mit.',instruction:'Fragen Sie, ob Sie den Antrag hier ausfüllen müssen.',answers:['Muss ich den Antrag hier ausfüllen?','Muss ich ihn hier ausfüllen?'],hint:'Muss ich + den Antrag + hier + ausfüllen?'},
{id:'d9',scene:'3 · Antrag auf Kindergeld',officer:'Guten Tag. Was möchten Sie?',instruction:'Sagen Sie, dass Sie einen Antrag auf Kindergeld stellen möchten, und fragen Sie nach dem ersten Schritt.',answers:['Ich möchte einen Antrag auf Kindergeld stellen. Was muss ich zuerst machen?','Ich will einen Antrag auf Kindergeld stellen. Was muss ich zuerst machen?','Was muss ich zuerst für den Antrag auf Kindergeld machen?'],hint:'Benutzen Sie „Antrag auf Kindergeld“, „zuerst“ und „müssen“.'},
{id:'d10',scene:'3 · Antrag auf Kindergeld',officer:'Zuerst müssen Sie den Antrag ausfüllen.',instruction:'Fragen Sie, welche Unterlagen Sie mitbringen müssen.',answers:['Welche Unterlagen muss ich mitbringen?','Welche Papiere muss ich mitbringen?','Welche Dokumente muss ich mitbringen?','Welche Unterlagen brauche ich?','Was muss ich mitbringen?'],hint:'Welche Unterlagen + muss ich + mitbringen?'},
{id:'d11',scene:'3 · Antrag auf Kindergeld',officer:'Bringen Sie bitte Ihren Ausweis und die Unterlagen für das Kind mit.',instruction:'Fragen Sie, ob Sie die Papiere auch unterschreiben müssen.',answers:['Muss ich die Papiere auch unterschreiben?','Muss ich auch die Papiere unterschreiben?'],hint:'Muss ich + die Papiere + auch + unterschreiben?'},
{id:'d12',scene:'3 · Antrag auf Kindergeld',officer:'Ja, bitte unterschreiben Sie die Papiere.',instruction:'Fragen Sie, ob Sie den Antrag hier ausfüllen können.',answers:['Kann ich den Antrag hier ausfüllen?','Kann ich den Antrag auch hier ausfüllen?','Kann ich ihn hier ausfüllen?'],hint:'Benutzen Sie das bekannte Modalverb „können“.'},
{id:'d13',scene:'4 · Ein Dokument abholen',officer:'Guten Tag. Ihr Dokument ist fertig.',instruction:'Fragen Sie, wann Sie das Dokument abholen können.',answers:['Wann kann ich das Dokument abholen?','Wann kann ich mein Dokument abholen?','Kann ich das Dokument heute abholen?'],hint:'Wann + kann ich + das Dokument + abholen?'},
{id:'d14',scene:'4 · Ein Dokument abholen',officer:'Sie können es morgen ab neun Uhr abholen.',instruction:'Fragen Sie, ob Sie Ihren Ausweis mitbringen müssen.',answers:['Muss ich meinen Ausweis mitbringen?','Muss ich den Ausweis mitbringen?'],hint:'Muss ich + meinen Ausweis + mitbringen?'},
{id:'d15',scene:'4 · Ein Dokument abholen',officer:'Ja, bitte bringen Sie den Ausweis mit.',instruction:'Fragen Sie, ob Sie bar bezahlen müssen.',answers:['Muss ich bar bezahlen?','Muss man hier bar bezahlen?'],hint:'Muss ich + bar + bezahlen?'},
{id:'d16',scene:'4 · Ein Dokument abholen',officer:'Nein, Sie müssen nichts bezahlen.',instruction:'Fragen Sie, ob Sie noch etwas unterschreiben müssen.',answers:['Muss ich noch etwas unterschreiben?','Muss ich noch Papiere unterschreiben?','Muss ich das Dokument unterschreiben?'],hint:'Muss ich + noch etwas + unterschreiben?'}
];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').trim().toLowerCase().replace(/[.,!?;:“”"'`´()]/g,'').replace(/\s+/g,' ');
function profile(){try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||localStorage.getItem('SP_STUDENT_PROFILE')||'{}')}catch(e){return{}}}
function pid(){const p=profile();return String(p.canonicalStudentId||p.studentId||p.uid||p.email||localStorage.getItem('SP_STUDENT_ID')||'student').toLowerCase().replace(/[^a-z0-9äöüß@._-]+/gi,'_')}
function preview(){return ['teacher','lehrer','admin','owner','superadmin'].includes(String(localStorage.getItem('SP_LOGIN_ROLE')||localStorage.getItem('SP_ACTIVE_ROLE')||'').toLowerCase())||localStorage.getItem('SP_TEACHER_PREVIEW')==='1'}
const key=()=>`SP_L9_${pid()}_T1_${TASK_ID}`;
function read(){let s={done:[],wrong:{},answers:{},firstSeen:[],firstCorrect:[]};try{s={...s,...JSON.parse(localStorage.getItem(key())||'{}')}}catch(e){}s.done=[...new Set((s.done||[]).filter(id=>turns.some(x=>x.id===id)))];s.wrong=s.wrong||{};s.answers=s.answers||{};s.firstSeen=s.firstSeen||[];s.firstCorrect=s.firstCorrect||[];return s}
function write(s){if(!preview())localStorage.setItem(key(),JSON.stringify(s))}
function pct(){return Math.round(read().done.length/turns.length*100)}
function current(){const s=read();return turns.find(x=>!s.done.includes(x.id))||null}
function markAttempt(id,ok){const s=read();if(!s.firstSeen.includes(id)){s.firstSeen.push(id);if(ok)s.firstCorrect.push(id)}write(s)}
function markWrong(id){const s=read();s.wrong[id]=(Number(s.wrong[id])||0)+1;write(s);return s.wrong[id]}
function markDone(id,value){const s=read();if(!s.done.includes(id))s.done.push(id);s.answers[id]=value;delete s.wrong[id];write(s);sync();return s}
function saveDraft(id,value){const s=read();s.draft=s.draft||{};s.draft[id]=value;write(s)}
function hint(item,n){if(!n)return'';if(n===1)return'<div class="dialog-no">Noch nicht richtig. Formulieren Sie die Frage noch einmal.</div>';if(n===2)return`<div class="dialog-hint"><strong>Hinweis:</strong> ${esc(item.hint)}</div>`;return`<div class="dialog-no"><strong>Mögliche Antwort:</strong> ${esc(item.answers[0])}<br><span>Auch andere richtige Formulierungen sind möglich. Sprechen oder schreiben Sie jetzt selbst eine richtige Antwort.</span></div>`}
function speak(text){if(!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='de-DE';u.rate=.86;speechSynthesis.speak(u)}catch(e){}}
function mic(item){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){tech('Das Mikrofon wird nicht unterstützt. Bitte schreiben Sie.');return}if(recognition)try{recognition.abort()}catch(e){}recognition=new R();recognition.lang='de-DE';recognition.interimResults=false;recognition.maxAlternatives=7;tech('Ich höre zu …');recognition.onresult=e=>{const vals=Array.from(e.results[0]||[]).map(x=>x.transcript),exact=vals.find(v=>item.answers.some(a=>norm(a)===norm(v))),value=exact||vals[0]||'';const input=document.getElementById('dialogAnswer');if(input)input.value=value;check(item,value)};recognition.onerror=()=>tech('Das Mikrofon hat nicht funktioniert. Bitte schreiben Sie.');recognition.onend=()=>{recognition=null};try{recognition.start()}catch(e){tech('Das Mikrofon konnte nicht gestartet werden. Bitte schreiben Sie.')}}
function tech(text){const e=document.getElementById('technical');if(e)e.innerHTML=`<div class="dialog-tech">${esc(text)}</div>`}
async function sync(){if(preview())return;try{const api=window.SPProgress||await import('/js/progress.js?v=20260831-central6');const s=read(),percent=pct();await (window.SPProgress||api)?.recordTaskProgress?.({module:'wortschatz',moduleTitle:'Wortschatz',level:'A1',lesson:9,theme:1,topicId:TOPIC,title:'A1 Lektion 9 · Thema 1',file:'dialog.html',taskKey:TASK_ID,taskTitle:'Dialog im Amt',percent,completed:percent>=100,total:turns.length,done:s.done.length})}catch(e){console.warn('L9T1 dialog sync',e)}}
async function hydrate(){if(preview())return;try{const api=window.SPProgress||await import('/js/progress.js?v=20260831-central6'),all=await (window.SPProgress||api)?.loadCurrentStudentProgress?.(),topic=all?.wortschatz?.[TOPIC],cloud=topic?.tasks?.['dialog.html']||topic?.tasks?.[TASK_ID];if(!cloud)return;const n=Math.min(turns.length,Math.max(Number(cloud.done)||0,Math.round(turns.length*Number(cloud.percent||0)/100))),s=read();for(const x of turns.slice(0,n))if(!s.done.includes(x.id))s.done.push(x.id);write(s)}catch(e){console.warn('L9T1 dialog restore',e)}}
function historyHtml(item){const s=read(),idx=turns.indexOf(item),prior=turns.slice(0,idx).filter(x=>s.done.includes(x.id));return prior.map(x=>`<div class="bubble officer"><small>Mitarbeiter/in</small>${esc(x.officer)}</div><div class="bubble student"><small>Sie</small>${esc(s.answers[x.id]||x.answers[0])}</div>`).join('')}
function header(){return `<header class="l9-top"><div class="l9-topline"><a class="l9-brand" href="/index.html"><img src="/assets/logo/sprachpilot-logo.png" alt="SprachPilot"><div><h1>SprachPilot</h1><p>Lektion 9 · Thema 1 · Dialog im Amt</p></div></a></div><nav class="l9-nav"><a href="../index.html">← Lektion 9</a><a href="index.html">Themenübersicht</a><a href="/student-dashboard/index.html">Dashboard</a></nav></header>`}
function render(){const item=current(),s=read(),p=pct();if(!item)return finish();const tries=Number(s.wrong[item.id]||0),draft=s.draft?.[item.id]||'';root.innerHTML=`<div class="l9-page">${header()}<div class="dialog-wrap"><section class="dialog-card"><div class="dialog-head"><div><h2>🗣️ Gespräch im Amt</h2><p>Antworten Sie selbst. Mehrere richtige Formulierungen sind möglich.</p></div><strong>${s.done.length} / ${turns.length}</strong></div><div class="dialog-progress"><span style="width:${p}%"></span></div><div class="dialog-scene">${esc(item.scene)}</div><div class="chat dialog-history">${historyHtml(item)}<div class="bubble officer"><small>Mitarbeiter/in</small>${esc(item.officer)}</div></div><div class="dialog-task"><h3>${esc(item.instruction)}</h3><div class="dialog-actions"><button class="dialog-secondary" id="listen">🔊 Mitarbeiter/in hören</button><button class="dialog-primary" id="mic">🎤 Sprechen</button></div><div class="dialog-input"><input id="dialogAnswer" value="${esc(draft)}" autocomplete="off" placeholder="Ihre Antwort"><button class="dialog-primary" id="check">Prüfen</button></div><div id="feedback" class="dialog-feedback">${hint(item,tries)}</div><div id="technical"></div></div></section></div></div>`;const input=document.getElementById('dialogAnswer');input.oninput=()=>saveDraft(item.id,input.value);input.onkeydown=e=>{if(e.key==='Enter')check(item,input.value)};document.getElementById('check').onclick=()=>check(item,input.value);document.getElementById('mic').onclick=()=>mic(item);document.getElementById('listen').onclick=()=>speak(item.officer)}
function check(item,value){if(!String(value||'').trim())return;const ok=item.answers.some(a=>norm(a)===norm(value));markAttempt(item.id,ok);if(ok){markDone(item.id,value);const f=document.getElementById('feedback');if(f)f.innerHTML='<div class="dialog-ok">Richtig. Das Gespräch geht weiter.</div>';setTimeout(render,520)}else{const n=markWrong(item.id),f=document.getElementById('feedback');if(f)f.innerHTML=hint(item,n);document.getElementById('dialogAnswer')?.focus()}}
function finish(){const s=read(),first=Math.round((s.firstCorrect?.length||0)/turns.length*100);root.innerHTML=`<div class="l9-page">${header()}<div class="dialog-wrap"><section class="dialog-card dialog-finish"><div class="big">✓</div><h2>Gut gemacht!</h2><p>Sie haben alle ${turns.length} Gesprächsschritte richtig gesprochen oder geschrieben.</p><p>Beim ersten Versuch richtig: ${first}%</p><div class="dialog-actions" style="justify-content:center"><a class="dialog-secondary" href="index.html">Zur Übersicht</a><a class="dialog-primary" href="task.html?task=pruefung">Zur Prüfung</a></div></section></div></div>`;sync()}
await hydrate();render();