(function(){
'use strict';
const D=window.L9T1,root=document.getElementById('app');if(!D||!root)return;
const TOPIC='wortschatz-a1-lektion-9-thema-1';let Progress=null,recognition=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').trim().toLowerCase().replace(/[.,!?;:“”"'`´()]/g,'').replace(/\s+/g,' ');
const profile=()=>{try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||localStorage.getItem('SP_STUDENT_PROFILE')||'{}')}catch(e){return{}}};
const pid=()=>String(profile().canonicalStudentId||profile().studentId||profile().uid||profile().email||localStorage.getItem('SP_STUDENT_ID')||'student').toLowerCase().replace(/[^a-z0-9äöüß@._-]+/gi,'_');
const isPreview=()=>['teacher','lehrer','admin','owner','superadmin'].includes(String(localStorage.getItem('SP_LOGIN_ROLE')||localStorage.getItem('SP_ACTIVE_ROLE')||'').toLowerCase())||localStorage.getItem('SP_TEACHER_PREVIEW')==='1';
const taskDef=id=>D.tasks.find(t=>t.id===id);
function idsFor(t){switch(t.kind){case'cards':return D.cards.map(x=>x.id);case'listen':return D.listen.map(x=>x.id);case'defs':return D.defs.map(x=>x.id);case'speak':return D.speak.map(x=>x.id);case'forms':return D.forms.map(x=>x.id);case'gaps':return D.gaps.map(x=>x.id);case'modals':return D.modals.map(x=>x.id);case'sequences':return D.sequences.map(x=>x.id);case'writing':return D.writing.flatMap(x=>x.steps.map(s=>s.id));case'cloze':return D.cloze.flatMap((x,i)=>x.answers.map((_,j)=>`c${i}-${j}`));case'exam':return D.exam.map(x=>x.id);default:return[]}}
const key=id=>`SP_L9_${pid()}_T1_${id}`;
function load(id){const t=taskDef(id),all=idsFor(t);let s={done:[],wrong:{},answers:{},firstSeen:[],firstCorrect:[]};try{s={...s,...JSON.parse(localStorage.getItem(key(id))||'{}')}}catch(e){}s.done=[...new Set((s.done||[]).filter(x=>all.includes(x)))];s.wrong=s.wrong||{};s.answers=s.answers||{};s.firstSeen=s.firstSeen||[];s.firstCorrect=s.firstCorrect||[];return s}
function save(id,s){if(!isPreview())localStorage.setItem(key(id),JSON.stringify(s));}
function pct(id){const t=taskDef(id),n=idsFor(t).length;return n?Math.round(load(id).done.length/n*100):0}
function completedPractice(){return D.tasks.filter(t=>!t.exam).every(t=>pct(t.id)>=100)}
function firstOpen(t){const s=load(t.id);return idsFor(t).find(id=>!s.done.includes(id))||null}
function markAttempt(taskId,itemId,ok){const s=load(taskId);if(!s.firstSeen.includes(itemId)){s.firstSeen.push(itemId);if(ok)s.firstCorrect.push(itemId)}save(taskId,s)}
function wrong(taskId,itemId){const s=load(taskId);s.wrong[itemId]=(Number(s.wrong[itemId])||0)+1;save(taskId,s);return s.wrong[itemId]}
function markDone(taskId,itemId){const s=load(taskId);if(!s.done.includes(itemId))s.done.push(itemId);delete s.wrong[itemId];delete s.answers[itemId];save(taskId,s);syncTask(taskId);return s}
function remember(taskId,itemId,value){const s=load(taskId);s.answers[itemId]=value;save(taskId,s)}
function header(title){const p=profile(),name=[p.vorname||p.firstName,p.nachname||p.lastName].filter(Boolean).join(' ')||(isPreview()?'Lehrer-Vorschau':'Schüler/in');return `<header class="l9-top"><div class="l9-topline"><a class="l9-brand" href="/index.html"><img src="/assets/logo/sprachpilot-logo.png" alt="SprachPilot"><div><h1>SprachPilot</h1><p>Lektion 9 · Thema 1 · ${esc(title)}</p></div></a><div class="score-box">${esc(name)}</div></div><nav class="l9-nav"><a href="../index.html">← Lektion 9</a><a href="index.html">Themenübersicht</a><a href="/student-dashboard/index.html">Dashboard</a></nav></header>`}
function progressHtml(id){const t=taskDef(id),s=load(id),n=idsFor(t).length,p=n?Math.round(s.done.length/n*100):0;return `<div class="progress-row"><span>${s.done.length} von ${n} richtig</span><strong>${p}%</strong></div><div class="progress"><span style="width:${p}%"></span></div>`}
function image(src,alt='Bild',cls='image-box'){return `<div class="${cls}"><img src="${esc(src)}" alt="${esc(alt)}" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="image-fallback" hidden>🖼️ Bild</div></div>`}
function helpText(solution,hint,n){if(n<=0)return'';if(n===1)return'<div class="no">Noch nicht richtig. Versuche es noch einmal.</div>';if(n===2)return`<div class="hint"><strong>Hinweis:</strong> ${esc(hint||'Lies die Aufgabe noch einmal genau.')}</div>`;return`<div class="no"><strong>Lösung:</strong> ${esc(solution)}<br>Gib oder wähle die richtige Antwort selbst. Erst dann ist die Aufgabe richtig.</div>`}
function playAudio(src,text){try{const a=new Audio(src);a.play().catch(()=>speakText(text));a.onerror=()=>speakText(text)}catch(e){speakText(text)}}
function speakText(text){if(!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='de-DE';u.rate=.84;speechSynthesis.speak(u)}catch(e){}}
function mic(answers,onText){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){tech('Das Mikrofon wird nicht unterstützt. Bitte schreibe.');return}if(recognition)try{recognition.abort()}catch(e){}recognition=new R();recognition.lang='de-DE';recognition.interimResults=false;recognition.maxAlternatives=5;tech('Ich höre zu …');recognition.onresult=e=>{const vals=Array.from(e.results[0]||[]).map(x=>x.transcript);const exact=vals.find(v=>answers.some(a=>norm(a)===norm(v)));onText(exact||vals[0]||'')};recognition.onerror=()=>tech('Das Mikrofon hat nicht funktioniert. Bitte schreibe.');recognition.onend=()=>{recognition=null};try{recognition.start()}catch(e){tech('Das Mikrofon konnte nicht gestartet werden. Bitte schreibe.')}}
function tech(x){const e=document.getElementById('technical');if(e)e.innerHTML=`<div class="technical">${esc(x)}</div>`}
async function ensureProgress(){if(Progress)return Progress;try{const mod=await import('/js/progress.js?v=20260831-central6');Progress=window.SPProgress||mod;return Progress}catch(e){console.warn('L9T1 Firebase progress',e);return null}}
async function syncTask(id){if(isPreview())return;const api=await ensureProgress();if(!api?.recordTaskProgress)return;const t=taskDef(id),total=idsFor(t).length,done=load(id).done.length,percent=total?Math.round(done/total*100):0;api.recordTaskProgress({module:'wortschatz',moduleTitle:'Wortschatz',level:'A1',lesson:9,theme:1,topicId:TOPIC,title:'A1 Lektion 9 · Thema 1',file:`task.html?task=${id}`,taskTitle:t.title,percent,completed:percent>=100,total,done}).catch?.(()=>{})}
async function hydrate(){if(isPreview())return;const api=await ensureProgress();if(!api?.loadCurrentStudentProgress)return;try{const all=await api.loadCurrentStudentProgress(),topic=all?.wortschatz?.[TOPIC];if(!topic)return;for(const t of D.tasks.filter(x=>!x.exam)){const cloud=topic.tasks?.[`task.html?task=${t.id}`]||topic.tasks?.[t.id];if(!cloud)continue;const n=Math.min(idsFor(t).length,Math.max(Number(cloud.done)||0,Math.round(idsFor(t).length*Number(cloud.percent||0)/100)));const s=load(t.id);for(const id of idsFor(t).slice(0,n))if(!s.done.includes(id))s.done.push(id);save(t.id,s)}}catch(e){console.warn('L9T1 restore',e)}}
function runInfo(){const api=Progress||window.SPProgress,run=api?.currentRun?.(TOPIC)||Number(localStorage.getItem(`SP_SCORE_RUN_${TOPIC}`)||1)||1,pts=api?.taskPointsForRun?.(run)||(run===1?5:run===2?10:15);return{run,pts}}
function overview(){const practice=D.tasks.filter(t=>!t.exam),avg=Math.round(practice.reduce((a,t)=>a+pct(t.id),0)/practice.length),done=practice.filter(t=>pct(t.id)>=100).length,{run,pts}=runInfo(),earned=done*pts,totalAccount=Number(localStorage.getItem('SP_POINTS_TOTAL')||0)||0;root.innerHTML=`<div class="l9-page">${header(D.title)}<section class="card hero"><div class="circle">${avg}%</div><div><h2>${esc(D.title)}</h2><p>${esc(D.goal)}</p><div class="progress"><span style="width:${avg}%"></span></div><p class="muted">${done} von ${practice.length} Lernaufgaben abgeschlossen · Versuch ${run} von 3 · ${earned} Aufgabenpunkte in diesem Durchlauf${totalAccount?` · Gesamt ${totalAccount} Punkte`:''}</p></div></section><section class="card"><h2>Aufgaben</h2><div class="task-grid">${D.tasks.map((t,i)=>{const p=pct(t.id),lock=t.exam&&!completedPractice();return `<a class="task-card ${p>=100?'done':''} ${lock?'locked':''}" href="${lock?'#':`task.html?task=${encodeURIComponent(t.id)}`}"><div class="task-top"><span class="task-num">${i+1}</span><strong>${p>=100?'✓':lock?'🔒':''}</strong></div><div class="task-icon">${t.icon}</div><h3>${esc(t.title)}</h3><p>${esc(t.description)}</p><div class="progress"><span style="width:${p}%"></span></div><div class="task-bottom"><span>${lock?'Erst alle Aufgaben 100%':p+'%'}</span><strong>${p>=100?'Fertig':'Starten'}</strong></div></a>`}).join('')}</div></section></div>`}
function finish(t){const next=D.tasks[D.tasks.indexOf(t)+1];root.innerHTML=`<div class="l9-page">${header(t.title)}<section class="card finish"><div class="check">✅</div><h2>Gut gemacht!</h2><p>${t.exam?'Prüfung abgeschlossen.':'Du hast diese Aufgabe zu 100% abgeschlossen.'}</p><div class="actions"><a class="btn" href="index.html">Zur Übersicht</a>${next?`<a class="btn primary" href="${next.exam&&!completedPractice()?'index.html':`task.html?task=${next.id}`}">Weiter</a>`:''}</div></section></div>`}
function renderTask(){const id=new URLSearchParams(location.search).get('task'),t=taskDef(id);if(!t){overview();return}if(t.exam&&!completedPractice()){root.innerHTML=`<div class="l9-page">${header(t.title)}<section class="card exam-lock"><div class="task-icon">🔒</div><h2>Prüfung gesperrt</h2><p>Schließe zuerst alle Lernaufgaben mit 100% ab.</p><a class="btn" href="index.html">Zur Übersicht</a></section></div>`;return}if(pct(id)>=100&&t.kind!=='exam'){finish(t);return}root.innerHTML=`<div class="l9-page">${header(t.title)}<section class="card">${progressHtml(id)}<div class="instruction">${esc(t.description)}</div><div id="taskArea"></div></section></div>`;draw(t)}
function draw(t){switch(t.kind){case'cards':return drawCards(t);case'listen':return drawListen(t);case'defs':return drawChoice(t,D.defs);case'speak':return drawSpeak(t);case'forms':return drawForms(t);case'gaps':return drawGaps(t);case'modals':return drawChoice(t,D.modals);case'sequences':return drawSequence(t);case'writing':return drawWriting(t);case'cloze':return drawCloze(t);case'exam':return drawExam(t)}}
function currentItem(t,items){const id=firstOpen(t);return items.find(x=>x.id===id)}
function accepted(item){return [item.answer,...(item.answers||[])].filter(Boolean)}
function checkSimple(t,item,value,after){if(!String(value||'').trim())return;const ok=accepted(item).some(a=>norm(a)===norm(value));markAttempt(t.id,item.id,ok);if(ok){markDone(t.id,item.id);feedback('<div class="ok">Richtig.</div>');setTimeout(()=>pct(t.id)>=100?finish(t):after(),450)}else{const n=wrong(t.id,item.id);feedback(helpText(item.answer,item.hint,n))}}
function feedback(html){const e=document.getElementById('feedback');if(e)e.innerHTML=html}
function drawCards(t){const item=currentItem(t,D.cards);if(!item)return finish(t);const ans=item.full||item.word,tries=load(t.id).wrong[item.id]||0;document.getElementById('taskArea').innerHTML=`<div class="question card-learning">${image(item.image,item.word)}<p class="muted">${esc(item.meaning||'')}</p><div class="actions"><button class="btn" id="listen">🔊 Anhören</button><button class="btn primary" id="mic">🎤 Sprechen</button><button class="btn" id="reveal">Lösung zeigen</button></div><div class="answer-row"><input id="answer" type="text" placeholder="Schreibe das deutsche Wort"><button class="btn primary" id="check">Prüfen</button></div><div id="back" class="card-back" hidden><div class="word-big">${esc(ans)}</div><div class="details">${item.plural?`<div class="detail"><span>Plural</span><strong>${esc(item.plural)}</strong></div>`:''}${item.perfect?`<div class="detail"><span>Perfekt</span><strong>${esc(item.perfect)}</strong></div>`:''}<div class="detail"><span>Beispiel</span><strong>${esc(item.example||'')}</strong></div></div></div><div id="feedback" class="feedback">${helpText(ans,item.meaning,tries)}</div><div id="technical"></div></div>`;const check=()=>checkSimple(t,{...item,answer:ans,hint:item.meaning},document.getElementById('answer').value,()=>drawCards(t));document.getElementById('check').onclick=check;document.getElementById('answer').onkeydown=e=>{if(e.key==='Enter')check()};document.getElementById('listen').onclick=()=>playAudio(item.audio,ans);document.getElementById('mic').onclick=()=>mic([ans],v=>{document.getElementById('answer').value=v;checkSimple(t,{...item,answer:ans,hint:item.meaning},v,()=>drawCards(t))});document.getElementById('reveal').onclick=()=>{document.getElementById('back').hidden=false;const s=load(t.id);s.wrong[item.id]=Math.max(3,Number(s.wrong[item.id])||0);save(t.id,s);feedback(helpText(ans,item.meaning,3))}}
function drawListen(t){const item=currentItem(t,D.listen);if(!item)return finish(t);const tries=load(t.id).wrong[item.id]||0,opts=[...item.options].sort(()=>Math.random()-.5);document.getElementById('taskArea').innerHTML=`<div class="question"><h2>${esc(item.prompt)}</h2><div class="audio-row"><button class="btn primary" id="listen">🔊 Anhören</button></div><div class="options">${opts.map(id=>`<button class="option image-option" data-id="${esc(id)}"><div class="mini-img"><img src="${esc((D.cards.find(x=>x.id===id)||{}).image||'')}" alt="Bild" onerror="this.hidden=true"></div></button>`).join('')}</div><div id="feedback" class="feedback">${helpText(item.answer,item.hint,tries)}</div></div>`;document.getElementById('listen').onclick=()=>playAudio(item.audio,item.spoken);document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const ok=b.dataset.id===item.answer;markAttempt(t.id,item.id,ok);if(ok){markDone(t.id,item.id);feedback('<div class="ok">Richtig.</div>');setTimeout(()=>pct(t.id)>=100?finish(t):drawListen(t),450)}else feedback(helpText(item.spoken,item.hint,wrong(t.id,item.id)))})}
function drawChoice(t,items){const item=currentItem(t,items);if(!item)return finish(t);const tries=load(t.id).wrong[item.id]||0,opts=[...item.options].sort(()=>Math.random()-.5);document.getElementById('taskArea').innerHTML=`<div class="question"><h2>${esc(item.prompt)}</h2><div class="options">${opts.map(x=>`<button class="option" data-value="${esc(x)}">${esc(x)}</button>`).join('')}</div><div id="feedback" class="feedback">${helpText(item.answer,item.hint,tries)}</div></div>`;document.querySelectorAll('[data-value]').forEach(b=>b.onclick=()=>checkSimple(t,item,b.dataset.value,()=>drawChoice(t,items)))}
function drawSpeak(t){const item=currentItem(t,D.speak);if(!item)return finish(t);const tries=load(t.id).wrong[item.id]||0;document.getElementById('taskArea').innerHTML=`<div class="question"><h2>${esc(item.prompt)}</h2>${image(item.image)}<div class="actions"><button class="btn primary" id="mic">🎤 Sprechen</button></div><div class="answer-row"><input id="answer" type="text" placeholder="Schreibe das Wort"><button class="btn primary" id="check">Prüfen</button></div><div id="feedback" class="feedback">${helpText(item.answer,item.hint,tries)}</div><div id="technical"></div></div>`;const check=v=>checkSimple(t,item,v,()=>drawSpeak(t));document.getElementById('check').onclick=()=>check(document.getElementById('answer').value);document.getElementById('answer').onkeydown=e=>{if(e.key==='Enter')check(e.target.value)};document.getElementById('mic').onclick=()=>mic(accepted(item),v=>{document.getElementById('answer').value=v;check(v)})}
function drawForms(t){const s=load(t.id);document.getElementById('taskArea').innerHTML=`<div class="question"><h2>müssen</h2><table class="forms-table"><thead><tr><th>Pronomen</th><th>Form von müssen</th></tr></thead><tbody>${D.forms.map(x=>`<tr><td><strong>${esc(x.pronoun)}</strong></td><td><input type="text" data-form="${x.id}" value="${esc(s.answers[x.id]||'')}" ${s.done.includes(x.id)?'disabled':''}><div class="row-feedback" id="fb-${x.id}">${s.done.includes(x.id)?'✓ richtig':''}</div></td></tr>`).join('')}</tbody></table><div class="actions"><button class="btn primary" id="checkAll">Tabelle prüfen</button></div></div>`;document.querySelectorAll('[data-form]').forEach(i=>i.oninput=()=>remember(t.id,i.dataset.form,i.value));document.getElementById('checkAll').onclick=()=>{for(const x of D.forms){if(load(t.id).done.includes(x.id))continue;const inp=document.querySelector(`[data-form="${x.id}"]`),v=inp.value,ok=norm(v)===norm(x.answer);markAttempt(t.id,x.id,ok);const f=document.getElementById(`fb-${x.id}`);if(ok){markDone(t.id,x.id);inp.disabled=true;f.innerHTML='<span class="ok">Richtig.</span>'}else{const n=wrong(t.id,x.id);f.innerHTML=helpText(x.answer,x.hint,n)}}document.querySelector('.card').insertAdjacentHTML('afterbegin','');if(pct(t.id)>=100)setTimeout(()=>finish(t),500);else document.querySelector('.progress-row').outerHTML=progressHtml(t.id).split('</div><div class="progress">')[0]+'</div>'}}
function drawGaps(t){const item=currentItem(t,D.gaps);if(!item)return finish(t);const tries=load(t.id).wrong[item.id]||0;document.getElementById('taskArea').innerHTML=`<div class="question">${image(item.image,'Verb','verb-image')}<h2>Ergänze beide Lücken.</h2><div class="sentence-builder">${esc(item.left)} <input id="modal" type="text"> ${esc(item.middle)} <input id="verb" type="text">.</div><div class="actions"><button class="btn primary" id="check">Prüfen</button></div><div id="feedback" class="feedback">${helpText(`${item.modal} / ${item.verb}`,item.hint,tries)}</div></div>`;document.getElementById('check').onclick=()=>{const ok=norm(document.getElementById('modal').value)===norm(item.modal)&&norm(document.getElementById('verb').value)===norm(item.verb);markAttempt(t.id,item.id,ok);if(ok){markDone(t.id,item.id);feedback('<div class="ok">Richtig.</div>');setTimeout(()=>pct(t.id)>=100?finish(t):drawGaps(t),450)}else feedback(helpText(`${item.modal} / ${item.verb}`,item.hint,wrong(t.id,item.id)))}}
function shuffled(a){return [...a].sort(()=>Math.random()-.5)}
function drawSequence(t){const item=currentItem(t,D.sequences);if(!item)return finish(t);const s=load(t.id),saved=s.answers[item.id];let imgs=saved?.imgs||shuffled(item.steps.map(x=>x.id)),texts=saved?.texts||shuffled(item.steps.map(x=>x.id));const tries=s.wrong[item.id]||0;const by=id=>item.steps.find(x=>x.id===id);document.getElementById('taskArea').innerHTML=`<div class="question"><h2 class="sequence-title">${esc(item.title)}</h2><div class="audio-row"><button class="btn primary" id="listen">🔊 Anleitung hören</button></div><div class="sequence-board"><div class="slot-labels"><span>1</span><span>2</span><span>3</span><span>4</span></div><div id="imgRow" class="order-row">${imgs.map((id,i)=>orderCard(id,i,'img',by(id),true)).join('')}</div><div id="textRow" class="order-row">${texts.map((id,i)=>orderCard(id,i,'txt',by(id),false)).join('')}</div></div><div class="actions"><button class="btn primary" id="check">Reihenfolge prüfen</button></div><div id="feedback" class="feedback">${helpText(item.steps.map(x=>x.text).join(' → '),'Hör auf die Wörter zuerst, danach, dann und zum Schluss.',tries)}</div></div>`;function store(){const st=load(t.id);st.answers[item.id]={imgs,texts};save(t.id,st)}document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const [row,dir,pos]=b.dataset.move.split(':'),arr=row==='img'?imgs:texts,i=Number(pos),j=i+(dir==='l'?-1:1);if(j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];store();drawSequence(t)});document.getElementById('listen').onclick=()=>playAudio(item.audio,item.spoken);document.getElementById('check').onclick=()=>{const expected=item.steps.map(x=>x.id),ok=expected.every((x,i)=>imgs[i]===x&&texts[i]===x);markAttempt(t.id,item.id,ok);if(ok){markDone(t.id,item.id);feedback('<div class="ok">Richtig.</div>');setTimeout(()=>pct(t.id)>=100?finish(t):drawSequence(t),500)}else feedback(helpText(item.steps.map(x=>x.text).join(' → '),'Bilder und Sätze müssen beide dieselbe Reihenfolge wie die gehörte Anleitung haben.',wrong(t.id,item.id)))}}
function orderCard(id,i,row,item,isImg){return `<div class="order-card">${isImg?`<img src="${esc(item.image)}" alt="Schritt" onerror="this.hidden=true">`:`<p>${esc(item.text)}</p>`}<div class="move"><button data-move="${row}:l:${i}">←</button><button data-move="${row}:r:${i}">→</button></div></div>`}
function drawWriting(t){const s=load(t.id);document.getElementById('taskArea').innerHTML=`<div class="question"><h2>Schreibe die Anleitungen.</h2><p>Benutze <strong>man</strong>, <strong>müssen</strong> und die Reihenfolge: zuerst – dann – danach – dann – danach – zum Schluss.</p>${D.writing.map(g=>`<div class="writing-group"><h3>${esc(g.title)}</h3>${g.steps.map(step=>`<div class="writing-step">${image(step.image,'Schritt','verb-image')}<div><input type="text" data-write="${step.id}" value="${esc(s.answers[step.id]||'')}" ${s.done.includes(step.id)?'disabled':''}><div id="fb-${step.id}" class="row-feedback">${s.done.includes(step.id)?'✓ richtig':''}</div></div></div>`).join('')}</div>`).join('')}<div class="actions"><button class="btn primary" id="checkAll">Texte prüfen</button></div></div>`;document.querySelectorAll('[data-write]').forEach(i=>i.oninput=()=>remember(t.id,i.dataset.write,i.value));document.getElementById('checkAll').onclick=()=>{for(const g of D.writing)for(const step of g.steps){if(load(t.id).done.includes(step.id))continue;const inp=document.querySelector(`[data-write="${step.id}"]`),ok=norm(inp.value)===norm(step.answer);markAttempt(t.id,step.id,ok);const f=document.getElementById(`fb-${step.id}`);if(ok){markDone(t.id,step.id);inp.disabled=true;f.innerHTML='<span class="ok">Richtig.</span>'}else f.innerHTML=helpText(step.answer,step.hint,wrong(t.id,step.id))}if(pct(t.id)>=100)setTimeout(()=>finish(t),500)}}
function drawCloze(t){const s=load(t.id);document.getElementById('taskArea').innerHTML=`<div class="question"><h2>Fülle die Lücken.</h2>${D.cloze.map((g,gi)=>{let html=esc(g.parts[0]);for(let j=0;j<g.answers.length;j++){const id=`c${gi}-${j}`;html+=` <input type="text" data-cloze="${id}" value="${esc(s.answers[id]||'')}" ${s.done.includes(id)?'disabled':''}> ${esc(g.parts[j+1])}`}return `<div class="writing-group"><h3>${esc(g.title)}</h3><div class="cloze-text">${html}</div><div id="group-${gi}" class="row-feedback"></div></div>`}).join('')}<div class="actions"><button class="btn primary" id="checkAll">Texte prüfen</button></div></div>`;document.querySelectorAll('[data-cloze]').forEach(i=>i.oninput=()=>remember(t.id,i.dataset.cloze,i.value));document.getElementById('checkAll').onclick=()=>{D.cloze.forEach((g,gi)=>{let messages=[];g.answers.forEach((ans,j)=>{const id=`c${gi}-${j}`;if(load(t.id).done.includes(id))return;const inp=document.querySelector(`[data-cloze="${id}"]`),ok=norm(inp.value)===norm(ans);markAttempt(t.id,id,ok);if(ok){markDone(t.id,id);inp.disabled=true}else messages.push(helpText(ans,'Lies den ganzen Satz und achte auf Grammatik und Wortschatz.',wrong(t.id,id)))});document.getElementById(`group-${gi}`).innerHTML=messages.join('')||'<span class="ok">Dieser Text ist richtig.</span>'});if(pct(t.id)>=100)setTimeout(()=>finish(t),500)}}
function drawExam(t){const s=load(t.id),id=firstOpen(t),item=D.exam.find(x=>x.id===id);if(!item){return finishExam(t)}const tries=s.wrong[item.id]||0;let body='';if(item.kind==='choice')body=`<div class="options">${shuffled(item.options).map(x=>`<button class="option" data-value="${esc(x)}">${esc(x)}</button>`).join('')}</div>`;else body=`<div class="answer-row"><input id="answer" type="text"><button class="btn primary" id="check">Prüfen</button></div>`;document.getElementById('taskArea').innerHTML=`<div class="question"><p class="muted">Prüfungsfrage ${s.done.length+1} von ${D.exam.length}</p><h2>${esc(item.prompt)}</h2>${body}<div id="feedback" class="feedback">${helpText(item.answer,item.hint,tries)}</div></div>`;const go=v=>{if(!String(v||'').trim())return;const ok=accepted(item).some(a=>norm(a)===norm(v));markAttempt(t.id,item.id,ok);if(ok){markDone(t.id,item.id);feedback('<div class="ok">Richtig.</div>');setTimeout(()=>drawExam(t),350)}else feedback(helpText(item.answer,item.hint,wrong(t.id,item.id)))};document.querySelectorAll('[data-value]').forEach(b=>b.onclick=()=>go(b.dataset.value));if(document.getElementById('check'))document.getElementById('check').onclick=()=>go(document.getElementById('answer').value)}
async function finishExam(t){const s=load(t.id),percent=Math.round((s.firstCorrect?.length||0)/D.exam.length*100),stars=percent>=100?3:percent>=70?2:percent>=50?1:0,{run}=runInfo();if(!isPreview()){const bestKey=`SP_L9T1_EXAM_BEST_${pid()}_${run}`,old=Number(localStorage.getItem(bestKey)||0);localStorage.setItem(bestKey,String(Math.max(old,percent)));const api=await ensureProgress();api?.recordExamResult?.({module:'wortschatz',moduleTitle:'Wortschatz',level:'A1',lesson:9,theme:1,topicId:TOPIC,title:'A1 Lektion 9 · Thema 1',percent,stars,run}).catch?.(()=>{})}root.innerHTML=`<div class="l9-page">${header(t.title)}<section class="card finish"><div class="check">⭐</div><h2>Prüfung abgeschlossen</h2><p><strong>${percent}%</strong> · ${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</p><p>Es wurden keine neuen Höraufgaben verwendet.</p><a class="btn primary" href="index.html">Zur Übersicht</a></section></div>`}
(async()=>{await hydrate();const page=document.body.dataset.page||'theme';if(page==='task')renderTask();else overview()})();
})();