const CFG=window.SP_L5_THEME||{id:'Thema-1',title:'Alltag und trennbare Verben',sub:'A1 Lektion 5 · Thema 1',key:'SP_L5_T1_V1'};
const DATA=window.SP_A1_LEKTION5_WORTSCHATZ||{parts:[]};
const THEME=(DATA.parts||[]).find(p=>p.id===CFG.id)||{words:[],title:CFG.title};
const WORDS=THEME.words||[];
const BAD_IMAGE_IDS=new Set(['einkaufen','spazieren_gehen']);
const STD_LANGS=[['en','EN'],['ru','RU'],['tr','TR'],['uk','UK'],['ar','AR'],['ja','JA'],['ro','RO']];
function hasGoodImage(w){return !!(w&&w.image&&!BAD_IMAGE_IDS.has(w.id))}
function simple(x){return String(x||'').toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[.,!?;:]/g,'').replace(/\s+/g,' ')}
function full(w){return w.full||((w.article?`${w.article} `:'')+(w.word||''))}
function profile(){try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||'null')}catch(e){return null}}
function langKey(){const m=String(profile()?.muttersprache||'').toLowerCase();if(m.includes('russ'))return'ru';if(m.includes('türk')||m.includes('turk'))return'tr';if(m.includes('ukrain'))return'uk';if(m.includes('arab'))return'ar';if(m.includes('japan'))return'ja';if(m.includes('rumän')||m.includes('ruman')||m.includes('roman'))return'ro';return'en'}
function tr(w){const t=w.tr||{};return t[langKey()]||t.en||t.ru||t.tr||''}
function stdTr(w){const t=w.tr||{};return `<div class="std-trans">${STD_LANGS.map(([k,l])=>`<div><b>${l}:</b> ${t[k]||'—'}</div>`).join('')}</div>`}
function typeLabel(t){return({noun:'Nomen',verb:'Verben',adjective:'Adjektive',adverb:'Adverbien',preposition:'Präpositionen',phrase:'Ausdrücke',question:'Fragewörter',conjunction:'Verbindungen',determiner:'Begleiter',time:'Zeitwörter'})[t]||'Andere Wörter'}
function byType(){const order=['noun','verb','adjective','adverb','preposition','phrase','question','conjunction','determiner','time'],g={};WORDS.forEach(w=>{(g[w.type||'other']||(g[w.type||'other']=[])).push(w)});return order.filter(k=>g[k]).map(k=>[typeLabel(k),g[k]]).concat(Object.keys(g).filter(k=>!order.includes(k)).map(k=>[typeLabel(k),g[k]]))}
function imgHtml(w){return hasGoodImage(w)?`<img src="${w.image}" onerror="fixImg(this)" alt="">`:`<div class="word-placeholder">kein Bild</div>`}
function bigImgHtml(w){return hasGoodImage(w)?`<img class="task-img" src="${w.image}" onerror="fixImg(this)" alt="">`:`<div class="placeholder-img">Bild fehlt<br>${full(w)}</div>`}
function fixImg(img){const ph=document.createElement('div');ph.className='word-placeholder';ph.textContent='kein Bild';img.replaceWith(ph)}
function isThemePage(){return /\/Thema-1\/?(index\.html)?$/.test(location.pathname)}
function header(title,showReset=false){const h=document.querySelector('.topbar');if(!h)return;const p=profile();const first=p?.vorname||p?.firstName||'';const last=p?.nachname||p?.lastName||'';const name=`${first} ${last}`.trim()||'Schüler/in';const course=p?.kurs||p?.kursnummer||p?.courseCode||'';const dashboard=localStorage.getItem('SP_LOGIN_ROLE')==='teacher'?'/teacher/index.html':'/student-dashboard/index.html';const backHref=isThemePage()?'../index.html':'index.html';h.innerHTML=`<div class="topbar-main sp-account-row"><a class="brand" href="/index.html"><div class="logo"><img src="/assets/logo/sprachpilot-logo.png" alt="SprachPilot"></div><div><h1>SprachPilot</h1><div class="subtitle">${title} · ${CFG.sub}</div></div></a><div class="account-tools"><span class="account-pill">${name}${course?' · '+course:''}</span><a class="account-link" href="${dashboard}">Dashboard</a><a class="account-link" href="/profile/index.html">Profil</a><button class="account-link account-btn" onclick="spLogout()">Abmelden</button></div></div><nav class="nav sp-page-nav"><a class="btn secondary" href="${backHref}">← Zurück</a><a class="btn secondary" href="uebersicht.html">Übersicht</a><a class="btn secondary" href="statistik.html">Statistik</a>${showReset?'<button class="btn danger-btn" onclick="resetThemeProgress()">Fortschritte löschen</button>':''}</nav>`}
function spLogout(){['SP_USER_PROFILE','SP_KEEP_LOGGED_IN','SP_LOGIN_ROLE','SP_TEACHER_PREVIEW','SP_PREVIEW_COURSE','SP_TEACHER_PREVIEW_COURSE'].forEach(k=>localStorage.removeItem(k));location.href='/index.html'}
function instruction(txt){return `<div class="task-instruction">${txt}</div>`}
function exampleBox(txt){return `<div class="example-box">${txt}</div>`}
function exactAnswer(value,solutions){const a=simple(value);return (Array.isArray(solutions)?solutions:[solutions]).some(s=>simple(s)===a)}
function taskKey(file){return CFG.key+'_'+file}
function loadTask(file,total){try{const st=JSON.parse(localStorage.getItem(taskKey(file))||'null');if(st&&st.total===total&&Array.isArray(st.done)&&Array.isArray(st.queue))return st}catch(e){}return{total,done:[],queue:[...Array(total).keys()].sort(()=>Math.random()-.5),current:null,tries:0,hadWrong:false}}
function saveTask(file,st){localStorage.setItem(taskKey(file),JSON.stringify(st))}
function markTaskDone(file,total){saveTask(file,{total,done:[...Array(total).keys()],queue:[],current:null,tries:0,hadWrong:false})}
function spNextIndex(file,total){let st=loadTask(file,total);if(st.current===null||st.current===undefined){if(!st.queue.length&&st.done.length<total)st.queue=[...Array(total).keys()].filter(i=>!st.done.includes(i)).sort(()=>Math.random()-.5);st.current=st.queue.shift();st.tries=0;st.hadWrong=false;saveTask(file,st)}return st.current}
function spMarkRight(file,total){let st=loadTask(file,total),c=st.current;if(c!==null&&c!==undefined){if(st.hadWrong||st.tries>0){if(!st.done.includes(c)&&!st.queue.includes(c))st.queue.push(c)}else if(!st.done.includes(c))st.done.push(c)}st.current=null;st.tries=0;st.hadWrong=false;saveTask(file,st)}
function spMarkWrong(file,total){let st=loadTask(file,total);st.tries=(st.tries||0)+1;st.hadWrong=true;saveTask(file,st);return st.tries}
function pctFor(file,total){if(!total)return 0;return Math.round((loadTask(file,total).done.length||0)/total*100)||0}
function spProgressHtml(file,total){const st=loadTask(file,total),d=st.done.length,p=pctFor(file,total);return`<div class="small">${d} richtig · ${total-d} übrig · ${p}%</div><div class="progress"><div class="bar" style="width:${p}%"></div></div>`}
function complete(area,file,next='index.html'){area.innerHTML=`<div class="finish-box"><div class="finish-icon">✓</div><div class="question">Geschafft!</div><div class="hint">Diese Aufgabe ist abgeschlossen.</div><div class="actions"><a class="btn" href="${next}">Weiter →</a><a class="btn secondary" href="index.html">Zum Menü</a></div></div>`}
function resetThemeProgress(){if(!confirm('Fortschritte in diesem Thema löschen?'))return;Object.keys(localStorage).filter(k=>k.startsWith(CFG.key)).forEach(k=>localStorage.removeItem(k));location.reload()}
function startMic(btn,callback){const SR=window.SpeechRecognition||window.webkitSpeechRecognition,status=document.getElementById('micStatus');if(!SR){if(status)status.textContent='Mikrofon wird hier nicht unterstützt. Bitte schreibe.';return}const rec=new SR();rec.lang='de-DE';rec.onresult=e=>callback(e.results[0][0].transcript);rec.onerror=()=>{if(status)status.textContent='Mikrofon hat nicht funktioniert. Bitte schreibe.'};rec.onend=()=>{if(btn)btn.classList.remove('active')};if(btn)btn.classList.add('active');if(status)status.textContent='Ich höre zu …';rec.start()}
function renderOverview(target){target.innerHTML=byType().map(([label,items])=>`<section class="type-block"><div class="type-title">${label}</div>${items.map(w=>`<div class="word-row">${imgHtml(w)}<div><b>${full(w)}</b><br><span class="small">${w.plural?`Plural: ${w.plural}`:'kein Plural'}</span>${stdTr(w)}<span class="tag">${w.section||''}</span>${hasGoodImage(w)?'':'<span class="tag">Bild fehlt</span>'}<div class="small">${w.sentence||''}</div></div></div>`).join('')}</section>`).join('')}
function renderStats(target){const st=loadTask('karteikarten.html',WORDS.length);target.innerHTML=byType().map(([label,items])=>`<section class="type-block"><div class="type-title">${label}</div>${items.map(w=>{const idx=WORDS.indexOf(w),ok=st.done.includes(idx);return`<div class="word-row">${imgHtml(w)}<div><b>${full(w)}</b>${stdTr(w)}<span class="small ${ok?'ok':'todo'}">${ok?'gelernt':'noch offen'}</span><br><span class="small">Karteikarten-Fortschritt wird gespeichert.</span></div></div>`}).join('')}</section>`).join('')}
function loadPointsHook(){if(window.__spL5PointsHookLoading)return;window.__spL5PointsHookLoading=true;const s=document.createElement('script');s.src='points-hook.js?v=3';document.head.appendChild(s)}
loadPointsHook();
