import { requireLogin, getActiveProfile, getActiveRole, dashboardHref, logout } from '/js/auth.js?v=login-main-4';
import { loadCourseRelease, moduleOpen } from '/js/course-releases.js?v=verb-stable3';

const app = document.querySelector('#app');
const topbar = document.querySelector('#topbar');

const TASKS = [
  ['cards', 'Aa', 'Karteikarten'],
  ['recognize', '?', 'Dativ erkennen'],
  ['article', 'der→dem', 'Artikel im Dativ'],
  ['noun-dativ', '→', 'Nomen → Dativ'],
  ['pronoun', 'ich→mir', 'Dativpronomen'],
  ['sentence', '✓', 'Richtigen Satz wählen'],
  ['listen', '🔊', 'Dativ hören'],
  ['write', '✎', 'Dativ schreiben'],
  ['speak', '🎙', 'Dativ sprechen'],
  ['verb', 'V', 'Dativverb erkennen'],
  ['exam', '★', 'Gruppenprüfung']
];
const LEARN = TASKS.slice(0, -1).map(x => x[0]);
const TITLE = Object.fromEntries(TASKS.map(x => [x[0], x[2]]));

// Die Verbliste und die Ausgangsbeispiele stammen aus der bereitgestellten Dativtabelle.
// Die Übungssätze sind bewusst neu formuliert, damit der Dativ in unterschiedlichen Strukturen trainiert wird.
const ENTRIES = [
  { level:'A1', verb:'antworten', source:'Ich antworte dir später.', nom:'der Lehrer', acc:'den Lehrer', dat:'dem Lehrer', pronoun:'ihm', sentence:'Ich antworte dem Lehrer später.' },
  { level:'A1', verb:'folgen', source:'Ich folge dem Mann unauffällig.', nom:'der Mann', acc:'den Mann', dat:'dem Mann', pronoun:'ihm', sentence:'Die Frau folgt dem Mann.' },
  { level:'A1', verb:'gefallen', source:'Gefällt dir deine neue Wohnung?', nom:'die Nachbarin', acc:'die Nachbarin', dat:'der Nachbarin', pronoun:'ihr', sentence:'Die neue Wohnung gefällt der Nachbarin.' },
  { level:'A1', verb:'gehören', source:'Das Auto gehört dem neuen Nachbarn.', nom:'der Nachbar', acc:'den Nachbarn', dat:'dem Nachbarn', pronoun:'ihm', sentence:'Das Auto gehört dem Nachbarn.' },
  { level:'A1', verb:'glauben', source:'Warum glaubst du mir nicht?', nom:'die Schwester', acc:'die Schwester', dat:'der Schwester', pronoun:'ihr', sentence:'Ich glaube der Schwester.' },
  { level:'A1', verb:'helfen', source:'Sie hilft dem alten Mann.', nom:'der alte Mann', acc:'den alten Mann', dat:'dem alten Mann', pronoun:'ihm', sentence:'Sie hilft dem alten Mann.' },
  { level:'A1', verb:'passieren', source:'Passiert dir das öfters?', nom:'der Freund', acc:'den Freund', dat:'dem Freund', pronoun:'ihm', sentence:'Das passiert dem Freund oft.' },
  { level:'A1', verb:'raten', source:'Der Arzt hat meinem Opa geraten, sich auszuruhen.', nom:'der Opa', acc:'den Opa', dat:'dem Opa', pronoun:'ihm', sentence:'Der Arzt rät dem Opa zu einer Pause.' },
  { level:'A1', verb:'schmecken', source:'Pizza schmeckt meinem Vater nicht.', nom:'der Vater', acc:'den Vater', dat:'dem Vater', pronoun:'ihm', sentence:'Die Pizza schmeckt dem Vater.' },
  { level:'A1', verb:'wehtun', source:'Ich werde dir wehtun.', nom:'das Kind', acc:'das Kind', dat:'dem Kind', pronoun:'ihm', sentence:'Der Zahn tut dem Kind weh.' },
  { level:'A1', verb:'zuhören', source:'Die Schüler hören dem Lehrer zu.', nom:'der Lehrer', acc:'den Lehrer', dat:'dem Lehrer', pronoun:'ihm', sentence:'Die Schüler hören dem Lehrer zu.' },

  { level:'A2', verb:'befehlen', source:'Der General befiehlt dem Soldaten zu schießen.', nom:'der Soldat', acc:'den Soldaten', dat:'dem Soldaten', pronoun:'ihm', sentence:'Der General befiehlt dem Soldaten zu warten.' },
  { level:'A2', verb:'danken', source:'Ich danke dir für deine Hilfe.', nom:'die Kollegin', acc:'die Kollegin', dat:'der Kollegin', pronoun:'ihr', sentence:'Ich danke der Kollegin für die Hilfe.' },
  { level:'A2', verb:'fehlen', source:'Du fehlst mir!', nom:'die Mutter', acc:'die Mutter', dat:'der Mutter', pronoun:'ihr', sentence:'Du fehlst der Mutter.' },
  { level:'A2', verb:'nachlaufen', source:'Ich laufe dem Ball nach.', nom:'der Ball', acc:'den Ball', dat:'dem Ball', pronoun:'ihm', sentence:'Das Kind läuft dem Ball nach.' },
  { level:'A2', verb:'nachrennen', source:'Ich renne dem Auto nach.', nom:'das Auto', acc:'das Auto', dat:'dem Auto', pronoun:'ihm', sentence:'Der Hund rennt dem Auto nach.' },
  { level:'A2', verb:'hinterherlaufen', source:'Ich laufe dem Ball hinterher.', nom:'der Ball', acc:'den Ball', dat:'dem Ball', pronoun:'ihm', sentence:'Das Kind läuft dem Ball hinterher.' },
  { level:'A2', verb:'hinterherrennen', source:'Ich renne dem Auto hinterher.', nom:'das Auto', acc:'das Auto', dat:'dem Auto', pronoun:'ihm', sentence:'Der Hund rennt dem Auto hinterher.' },
  { level:'A2', verb:'passen', source:'Die Hose passt mir nicht mehr. Ich bin zu dick.', nom:'der Mann', acc:'den Mann', dat:'dem Mann', pronoun:'ihm', sentence:'Die Hose passt dem Mann nicht.' },
  { level:'A2', verb:'vertrauen', source:'Ich vertraue meinem Bruder.', nom:'der Bruder', acc:'den Bruder', dat:'dem Bruder', pronoun:'ihm', sentence:'Ich vertraue dem Bruder.' },
  { level:'A2', verb:'vergeben', source:'Ich kann meinem Mann den Seitensprung nicht vergeben.', nom:'der Mann', acc:'den Mann', dat:'dem Mann', pronoun:'ihm', sentence:'Sie vergibt dem Mann den Fehler.' },
  { level:'A2', verb:'verzeihen', source:'Ich kann meinem Mann den Seitensprung nicht verzeihen.', nom:'der Mann', acc:'den Mann', dat:'dem Mann', pronoun:'ihm', sentence:'Sie verzeiht dem Mann den Fehler.' },
  { level:'A2', verb:'widersprechen', source:'Der Chef widerspricht seinem Mitarbeiter.', nom:'der Mitarbeiter', acc:'den Mitarbeiter', dat:'dem Mitarbeiter', pronoun:'ihm', sentence:'Der Chef widerspricht dem Mitarbeiter.' },
  { level:'A2', verb:'zusehen', source:'Kann ich dir bei deiner Arbeit zusehen?', nom:'die Kollegin', acc:'die Kollegin', dat:'der Kollegin', pronoun:'ihr', sentence:'Ich sehe der Kollegin bei der Arbeit zu.' },
  { level:'A2', verb:'fremdgehen', source:'Bist du mir fremdgegangen?', nom:'der Partner', acc:'den Partner', dat:'dem Partner', pronoun:'ihm', sentence:'Sie geht dem Partner fremd.' },
  { level:'A2', verb:'zustimmen', source:'Der Politiker stimmt dem neuen Gesetz zu.', nom:'das Gesetz', acc:'das Gesetz', dat:'dem Gesetz', pronoun:'ihm', sentence:'Der Politiker stimmt dem Gesetz zu.' },

  { level:'B1', verb:'ähneln', source:'Ich ähnele meinem Bruder.', nom:'der Bruder', acc:'den Bruder', dat:'dem Bruder', pronoun:'ihm', sentence:'Der Junge ähnelt dem Bruder.' },
  { level:'B1', verb:'begegnen', source:'Ich bin heute Morgen zufällig einem alten Freund begegnet.', nom:'der alte Freund', acc:'den alten Freund', dat:'dem alten Freund', pronoun:'ihm', sentence:'Ich begegne dem alten Freund zufällig.' },
  { level:'B1', verb:'beistehen', source:'Ich stehe dir in dieser schweren Zeit bei.', nom:'die Freundin', acc:'die Freundin', dat:'der Freundin', pronoun:'ihr', sentence:'Ich stehe der Freundin in dieser Zeit bei.' },
  { level:'B1', verb:'beitreten', source:'Ich bin gestern einem Fußballclub beigetreten.', nom:'der Fußballclub', acc:'den Fußballclub', dat:'dem Fußballclub', pronoun:'ihm', sentence:'Er tritt dem Fußballclub bei.' },
  { level:'B1', verb:'drohen', source:'Der Lehrer droht den Schülern mit extra Hausaufgaben, wenn sie nicht still sind.', nom:'die Schüler', acc:'die Schüler', dat:'den Schülern', pronoun:'ihnen', sentence:'Der Lehrer droht den Schülern mit Hausaufgaben.' },
  { level:'B1', verb:'entgegengehen', source:'Ich gehe dir schon mal entgegen.', nom:'die Schwester', acc:'die Schwester', dat:'der Schwester', pronoun:'ihr', sentence:'Ich gehe der Schwester entgegen.' },
  { level:'B1', verb:'entgegenfahren', source:'Er fährt dir schon entgegen.', nom:'die Mutter', acc:'die Mutter', dat:'der Mutter', pronoun:'ihr', sentence:'Er fährt der Mutter entgegen.' },
  { level:'B1', verb:'entgegenkommen', source:'Kommst du mir entgegen?', nom:'der Chef', acc:'den Chef', dat:'dem Chef', pronoun:'ihm', sentence:'Der Kollege kommt dem Chef entgegen.' },
  { level:'B1', verb:'gratulieren', source:'Ich gratuliere dir zum Geburtstag.', nom:'die Freundin', acc:'die Freundin', dat:'der Freundin', pronoun:'ihr', sentence:'Ich gratuliere der Freundin zum Geburtstag.' },
  { level:'B1', verb:'kündigen', source:'Der Chef hat mir gekündigt.', nom:'der Mitarbeiter', acc:'den Mitarbeiter', dat:'dem Mitarbeiter', pronoun:'ihm', sentence:'Die Firma kündigt dem Mitarbeiter.' },
  { level:'B1', verb:'sich nähern', source:'Der Löwe nähert sich seiner Beute.', nom:'die Beute', acc:'die Beute', dat:'der Beute', pronoun:'ihr', sentence:'Der Löwe nähert sich der Beute.' },
  { level:'B1', verb:'schaden', source:'Du schadest dir nur selbst mit deinem schlechten Verhalten.', nom:'der Körper', acc:'den Körper', dat:'dem Körper', pronoun:'ihm', sentence:'Zu wenig Schlaf schadet dem Körper.' },

  { level:'B2', verb:'einfallen', source:'Fällt dir noch etwas ein?', nom:'der Student', acc:'den Studenten', dat:'dem Studenten', pronoun:'ihm', sentence:'Dem Studenten fällt eine Idee ein.' },
  { level:'B2', verb:'gehorchen', source:'Der Soldat gehorcht dem General.', nom:'der General', acc:'den General', dat:'dem General', pronoun:'ihm', sentence:'Der Soldat gehorcht dem General.' },
  { level:'B2', verb:'genügen', source:'Das genügt mir.', nom:'der Schüler', acc:'den Schüler', dat:'dem Schüler', pronoun:'ihm', sentence:'Eine Erklärung genügt dem Schüler.' },
  { level:'B2', verb:'guttun', source:'Ein Urlaub würde dir guttun.', nom:'das Kind', acc:'das Kind', dat:'dem Kind', pronoun:'ihm', sentence:'Die Pause tut dem Kind gut.' },
  { level:'B2', verb:'nützen', source:'Der Sieg nützt dem Team nichts mehr.', nom:'das Team', acc:'das Team', dat:'dem Team', pronoun:'ihm', sentence:'Der Sieg nützt dem Team.' },
  { level:'B2', verb:'ausweichen', source:'Du konntest dem Hindernis zum Glück noch ausweichen.', nom:'das Fahrrad', acc:'das Fahrrad', dat:'dem Fahrrad', pronoun:'ihm', sentence:'Der Fahrer weicht dem Fahrrad aus.' },

  { level:'C1', verb:'dienen', source:'Wie kann ich Ihnen dienen?', nom:'die Kundin', acc:'die Kundin', dat:'der Kundin', pronoun:'ihr', sentence:'Wie kann ich der Kundin dienen?' },
  { level:'C1', verb:'gelingen', source:'Das Bild ist dir wirklich gut gelungen.', nom:'der Schüler', acc:'den Schüler', dat:'dem Schüler', pronoun:'ihm', sentence:'Die Aufgabe gelingt dem Schüler.' },
  { level:'C1', verb:'misslingen', source:'Der Test ist mir total misslungen.', nom:'das Team', acc:'das Team', dat:'dem Team', pronoun:'ihm', sentence:'Der Versuch misslingt dem Team.' }
];

const LEVEL_TITLES = { A1:'A1 · Grundlagen', A2:'A2 · Alltag', B1:'B1 · Erweiterung', B2:'B2 · Fortgeschritten', C1:'C1 · Sicher anwenden' };
const LEVELS = ['A1','A2','B1','B2','C1'];
const GROUPS = LEVELS.map((level,index)=>({id:index+1,level,title:LEVEL_TITLES[level],entries:ENTRIES.filter(e=>e.level===level),signature:`${level}|${ENTRIES.filter(e=>e.level===level).map(e=>e.verb).join('|')}`}));

let profile={}, preview=false, locked=false, state=null, currentQuestion=null, rec=null, cardRevealed=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[.,!?;:"'`´()]/g,'').replace(/\s+/g,' ');
const answerNorm=v=>norm(v).replace(/\s+/g,'');
const shuffle=a=>{a=[...(a||[])];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const uniq=a=>[...new Set(a.filter(Boolean))];
const entryKey=e=>`${e.level}:${e.verb}`;
const entryByKey=key=>ENTRIES.find(e=>entryKey(e)===key)||null;
const groupById=id=>GROUPS[id-1]||null;

function wrongCasePhrase(e){const rest=e.dat.split(/\s+/).slice(1).join(' '),article=e.dat.startsWith('dem ')?'der':e.dat.startsWith('der ')?'dem':'dem';return`${article} ${rest}`}
function caseOptions(e){return shuffle(uniq([e.dat,e.nom,e.acc,wrongCasePhrase(e)]))}
function articleOfDat(e){return e.dat.split(/\s+/)[0]}
function datRest(e){return e.dat.split(/\s+/).slice(1).join(' ')}
function sentenceWithPhrase(e,phrase){return e.sentence.replace(e.dat,phrase)}
function sentenceOptions(e){return shuffle(uniq([e.sentence,sentenceWithPhrase(e,e.nom),sentenceWithPhrase(e,e.acc),sentenceWithPhrase(e,wrongCasePhrase(e))]))}
function options(answer,pool,count=4){const seen=new Set([norm(answer)]),others=[];shuffle(pool).forEach(x=>{if(x!=null&&!seen.has(norm(x))){seen.add(norm(x));others.push(x)}});return shuffle([answer,...others.slice(0,count-1)])}

const userSlug=()=>[profile.email,profile.courseCode,profile.kurs,profile.kursnummer,profile.vorname,profile.nachname].filter(Boolean).join('_').toLowerCase().replace(/[^a-z0-9äöüß]+/gi,'_')||'student';
const storageKey=()=>`SP_DATIVVERBEN_${userSlug()}`;
const blankTask=total=>({total,done:[],queue:[],current:null,tries:0,hadWrong:false});
const blankRun=()=>({tasks:{},exam:{bestPercent:0,stars:0,session:null},awards:{tasks:{},examPoints:0},completed:false});
const blankGroup=sig=>({signature:sig,currentRun:1,runs:{'1':blankRun()}});
const blankState=()=>({version:1,selectedGroup:1,groups:{}});
function normalizeRun(run,g){run={...blankRun(),...(run||{})};run.tasks=run.tasks||{};const keys=g.entries.map(entryKey);for(const t of LEARN){const x=run.tasks[t]||blankTask(keys.length);x.total=keys.length;x.done=[...new Set((x.done||[]).filter(k=>keys.includes(k)))];x.queue=[...new Set((x.queue||[]).filter(k=>keys.includes(k)&&!x.done.includes(k)))];x.current=x.current&&keys.includes(x.current)&&!x.done.includes(x.current)?x.current:null;x.tries=Number(x.tries)||0;x.hadWrong=!!x.hadWrong;run.tasks[t]=x}run.exam={bestPercent:0,stars:0,session:null,...(run.exam||{})};run.awards={tasks:{},examPoints:0,...(run.awards||{})};run.awards.tasks=run.awards.tasks||{};return run}
function groupState(id){const g=groupById(id);if(!g)return null;let gs=state.groups[g.signature];if(!gs)gs=state.groups[g.signature]=blankGroup(g.signature);gs.currentRun=Math.max(1,Math.min(3,Number(gs.currentRun)||1));gs.runs=gs.runs||{};for(let r=1;r<=gs.currentRun;r++)gs.runs[String(r)]=normalizeRun(gs.runs[String(r)],g);return gs}
const currentRun=id=>{const gs=groupState(id);return gs?.runs?.[String(gs.currentRun)]||null};
function load(){try{state=JSON.parse(localStorage.getItem(storageKey())||'null')||blankState()}catch{state=blankState()}state.groups=state.groups||{};GROUPS.forEach(g=>groupState(g.id))}
function save(){if(preview)return;try{localStorage.setItem(storageKey(),JSON.stringify(state))}catch{}}
const taskState=(id,t)=>currentRun(id)?.tasks?.[t],taskPercent=(id,t)=>{const x=taskState(id,t);return x?.total?Math.round(x.done.length/x.total*100):0},taskDone=(id,t)=>taskPercent(id,t)>=100,learnDone=id=>LEARN.every(t=>taskDone(id,t));
function taskPoints(id){return(groupState(id)?.currentRun||1)*5}
function groupPoints(id){const gs=groupState(id);if(!gs)return 0;return Object.values(gs.runs||{}).reduce((sum,r)=>sum+Object.values(r.awards?.tasks||{}).reduce((s,n)=>s+(Number(n)||0),0)+(Number(r.awards?.examPoints)||0),0)}
const totalPoints=()=>GROUPS.reduce((s,g)=>s+groupPoints(g.id),0);
function nextEntry(id,t){const x=taskState(id,t),g=groupById(id);if(!x||!g)return null;if(x.current&&!x.done.includes(x.current))return entryByKey(x.current);if(!x.queue.length)x.queue=shuffle(g.entries.map(entryKey).filter(k=>!x.done.includes(k)));x.current=x.queue.shift()||null;x.tries=0;x.hadWrong=false;save();return entryByKey(x.current)}
function markWrong(id,t){const x=taskState(id,t);if(!x)return 0;x.tries++;x.hadWrong=true;save();return x.tries}
function markRight(id,t){const x=taskState(id,t),k=x?.current;if(!x||!k)return;if(x.hadWrong||x.tries>0){if(!x.done.includes(k)&&!x.queue.includes(k))x.queue.push(k)}else if(!x.done.includes(k))x.done.push(k);x.current=null;x.tries=0;x.hadWrong=false;if(taskDone(id,t)&&!currentRun(id).awards.tasks[t])currentRun(id).awards.tasks[t]=taskPoints(id);save()}
function resetGroup(id){const g=groupById(id),gs=groupState(id);if(!g||!gs)return;const awards={};for(const[r,run]of Object.entries(gs.runs||{}))awards[r]=run.awards;state.groups[g.signature]=blankGroup(g.signature);for(const[r,a]of Object.entries(awards)){state.groups[g.signature].runs[r]=normalizeRun(blankRun(),g);state.groups[g.signature].runs[r].awards=a}save()}
function canRepeat(id){const gs=groupState(id),run=currentRun(id);return!!gs&&gs.currentRun<3&&learnDone(id)&&Number(run.exam.bestPercent||0)>=100}
function nextRun(id){const gs=groupState(id),g=groupById(id);if(!canRepeat(id))return false;gs.currentRun++;gs.runs[String(gs.currentRun)]=normalizeRun(blankRun(),g);save();return true}

function question(id,t,e){const g=groupById(id);if(t==='recognize')return{kind:'mc',prompt:`Welcher Teil steht im Dativ? ${e.sentence}`,answer:e.dat,options:caseOptions(e),hintType:'case'};if(t==='article')return{kind:'mc',prompt:`Ergänze den Artikel: ${e.sentence.replace(e.dat,`___ ${datRest(e)}`)}`,answer:articleOfDat(e),options:shuffle(uniq([articleOfDat(e),'dem','der','den','die']).slice(0,4)),hintType:'article'};if(t==='noun-dativ')return{kind:'input',prompt:`Setze in den Dativ: ${e.nom}`,answer:e.dat,placeholder:'Dativform schreiben',hintType:'case'};if(t==='pronoun')return{kind:'mc',prompt:`Ersetze „${e.dat}“ durch ein Pronomen.`,subprompt:e.sentence,answer:e.pronoun,options:options(e.pronoun,['mir','dir','ihm','ihr','uns','euch','ihnen']),hintType:'pronoun'};if(t==='sentence')return{kind:'mc',prompt:'Welcher Satz ist richtig?',answer:e.sentence,options:sentenceOptions(e),hintType:'case'};if(t==='listen')return{kind:'mc',prompt:'Welche Dativform hörst du?',answer:e.dat,options:caseOptions(e),audio:e.sentence,hintType:'case'};if(t==='write')return{kind:'input',prompt:`Ergänze den Satz: ${e.sentence.replace(e.dat,'_____')} (${e.nom})`,answer:e.dat,placeholder:'Dativform schreiben',hintType:'case'};if(t==='speak')return{kind:'speech',prompt:`Sprich die Dativform: ${e.nom}`,answer:e.dat,writeAnswer:e.dat,hintType:'case'};if(t==='verb')return{kind:'mc',prompt:'Welches Dativverb gehört zu diesem Beispiel?',subprompt:e.source,answer:e.verb,options:options(e.verb,g.entries.map(x=>x.verb)),hintType:'verb'};return{kind:'input',prompt:e.verb,answer:e.dat,hintType:'case'}}
function examItems(id){const g=groupById(id),kinds=LEARN.filter(t=>t!=='cards'),items=[],entries=shuffle(g.entries);for(let i=0;i<20;i++)items.push({key:entryKey(entries[i%entries.length]),task:kinds[i%kinds.length]});return items}
const route=()=>{const q=new URLSearchParams(location.search),group=Math.max(0,Math.min(GROUPS.length,Number(q.get('group'))||0)),task=q.get('task')||'',view=q.get('view')||'';return{group,task:TASKS.some(x=>x[0]===task)?task:'',view:view==='overview'?'overview':''}};
const href=(group=0,task='',view='')=>{const q=new URLSearchParams();if(group)q.set('group',group);if(task)q.set('task',task);if(view)q.set('view',view);return'/dativverben/'+(q.toString()?'?'+q.toString():'')};
const go=o=>{history.pushState(null,'',href(o.group,o.task,o.view));render()};

function stopMic(){if(rec)try{rec.abort()}catch{}rec=null}
function header(r){const name=[profile.vorname||profile.firstName,profile.nachname||profile.lastName].filter(Boolean).join(' ')||(preview?'Lehrer-Vorschau':'Schüler');topbar.innerHTML=`<div class="topbar-main"><a class="brand" href="/verben-bereich/"><img src="/assets/logo/sprachpilot-logo.png" alt="SprachPilot"><div><h1>Dativverben</h1><p>${ENTRIES.length} Verben · A1 bis C1</p></div></a><div class="account-actions"><span class="account-pill">${esc(name)}</span><a class="btn secondary" href="${esc(dashboardHref())}">Dashboard</a><button class="btn secondary" data-action="logout">Abmelden</button></div></div><nav class="topnav"><a class="btn secondary" href="/verben-bereich/">← Verben</a><button class="btn secondary ${r.view==='overview'?'active-nav':''}" data-action="overview">Übersicht</button>${r.group?`<button class="btn secondary" data-action="group" data-group="${r.group}">Aufgaben</button><button class="btn danger-btn" data-action="reset-group" data-group="${r.group}">Fortschritt löschen</button>`:''}</nav>`}
const previewNote=()=>preview?'<div class="preview-note">Lehrer-Vorschau · nichts wird gespeichert</div>':'';
function grammarBox(){return`<section class="card dativ-rule"><h2>Dativverben</h2><p>Diese Verben stehen mit einem Dativ. Frage: <strong>Wem?</strong></p><div class="case-grid"><span><b>der</b> → dem</span><span><b>die</b> → der</span><span><b>das</b> → dem</span><span><b>Plural</b> → den + -n</span></div><p class="small">Pronomen: mir · dir · ihm · ihr · uns · euch · ihnen · Ihnen. Der Dativ kann vor oder nach dem Verb stehen.</p></section>`}
function scoreCard(id=0){if(preview)return'';if(!id)return`<section class="card score-card compact-score"><h2>${totalPoints()} Punkte</h2><span>gesamt</span></section>`;const gs=groupState(id),run=currentRun(id);return`<section class="card score-card"><div><p class="eyebrow">${esc(groupById(id).level)}</p><h2>Runde ${gs.currentRun} von 3</h2><p>${Object.values(run.awards.tasks||{}).reduce((s,n)=>s+(Number(n)||0),0)} Aufgabenpunkte · ${Number(run.awards.examPoints)||0} Prüfungspunkte</p>${canRepeat(id)?`<button class="btn" data-action="next-run" data-group="${id}">Runde ${gs.currentRun+1} starten</button>`:''}</div><div class="score-total">${groupPoints(id)}<span>Punkte</span></div></section>`}
function taskCards(id){const run=currentRun(id);return TASKS.map((t,i)=>{const exam=t[0]==='exam',open=!exam||learnDone(id),p=exam?Number(run.exam.bestPercent)||0:taskPercent(id,t[0]);return`<button class="task-card ${p>=100?'done-card':''} ${!open?'locked-task':''}" data-action="task" data-group="${id}" data-task="${t[0]}" ${open?'':'disabled'}><span class="task-number">${i+1}</span><span class="task-icon">${open?t[1]:'🔒'}</span><span class="task-title">${t[2]}</span><div class="task-mini-progress"><span style="width:${p}%"></span></div><span class="task-status">${open?(p>=100?'Fertig':p?`${p}%`:'Starten'):'Gesperrt'}</span></button>`}).join('')}
function renderHome(selected=0){const panels=GROUPS.map(g=>{const gs=groupState(g.id),done=LEARN.filter(t=>taskDone(g.id,t)).length,exam=Number(currentRun(g.id).exam.bestPercent)||0;return`<details class="group-panel" ${selected===g.id?'open':''}><summary data-action="group" data-group="${g.id}"><span class="group-number">${g.level}</span><span>${esc(g.title)}</span><span>${g.entries.length} Verben</span><span>Runde ${gs.currentRun}/3 · ${done}/${LEARN.length} · Prüfung ${exam}%</span></summary><div class="group-body"><div class="task-grid">${taskCards(g.id)}</div></div></details>`}).join('');app.innerHTML=`${previewNote()}${grammarBox()}${scoreCard(selected)}<section class="card"><div class="section-head"><h2>Niveaustufen</h2><span class="overview-total">${ENTRIES.length} Verben</span></div><div class="groups-accordion">${panels}</div></section>`}
function renderOverview(){const sections=GROUPS.map(g=>`<section class="overview-level"><div class="section-head"><h2>${esc(g.title)}</h2><span class="overview-total">${g.entries.length} Verben</span></div><div class="dativ-overview-grid">${g.entries.map(e=>`<article class="dativ-verb-card"><div class="level-chip">${e.level}</div><h3>${esc(e.verb)}</h3><p class="source-example">${esc(e.source)}</p><div class="dativ-answer"><span>Wem?</span><strong>${esc(e.dat)}</strong></div><button class="audio-mini" data-action="audio" data-text="${esc(e.source)}">🔊</button></article>`).join('')}</div></section>`).join('');app.innerHTML=`${previewNote()}${grammarBox()}<section class="card"><div class="section-head"><h2>Übersicht</h2><span class="overview-total">${ENTRIES.length} Verben</span></div>${sections}</section>`}
function progress(id,t){const x=taskState(id,t),p=taskPercent(id,t);return`<div class="task-progress-row"><span>${x.done.length} richtig · ${x.total-x.done.length} übrig</span><strong>${p}%</strong></div><div class="mini-progress"><div style="width:${p}%"></div></div>`}
function feedback(text,ok=false){const el=document.querySelector('#feedback');if(el){el.className='feedback '+(ok?'ok':'no');el.innerHTML=text}}
function hint(tries,q){if(tries>=3)return`Lösung: <strong>${esc(q.answer)}</strong>`;if(tries===2){if(q.hintType==='article')return'Tipp: Im Dativ heißen die bestimmten Artikel <strong>dem, der, dem, den</strong>.';if(q.hintType==='pronoun')return'Tipp: Dativpronomen sind z. B. <strong>mir, dir, ihm, ihr, uns, euch, ihnen</strong>.';if(q.hintType==='verb')return`Tipp: Das gesuchte Verb beginnt mit <strong>${esc(String(q.answer).slice(0,2))}…</strong>`;return`Tipp: Die Dativform beginnt mit <strong>${esc(String(q.answer).split(/\s+/)[0])}</strong>.`}if(q.hintType==='verb')return'Achte auf das Verb im Beispielsatz.';return'Noch nicht richtig. Frage: Wem?'}
function body(q){const media=q.audio?`<div class="listen-box"><button class="btn" data-action="audio" data-text="${esc(q.audio)}">🔊 Hören</button><button class="btn secondary" data-action="audio-slow" data-text="${esc(q.audio)}">Langsam</button></div>`:'',sub=q.subprompt?`<div class="question-sub">${esc(q.subprompt)}</div>`:'';let answer='';if(q.kind==='mc')answer=`<div class="option-grid">${q.options.map(o=>`<button class="option" data-action="answer" data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div>`;if(q.kind==='input')answer=`<div class="answer-form"><div class="answer-row"><input id="answerInput" autocomplete="off" placeholder="${esc(q.placeholder||'Antwort schreiben')}"><button class="btn" data-action="check-input">Kontrollieren</button></div></div>`;if(q.kind==='speech')answer=`<div class="speech-box"><div class="actions"><button class="btn" data-action="mic">🎤 Sprechen</button><button class="btn secondary" data-action="write-fallback">✍️ Schreiben</button></div><div id="micStatus" class="small"></div><div id="writeFallback" class="answer-form hidden"><div class="answer-row"><input id="answerInput" autocomplete="off" placeholder="Dativform"><button class="btn" data-action="check-input">Kontrollieren</button></div></div></div>`;return`${media}<div class="question">${esc(q.prompt)}</div>${sub}${answer}<div id="feedback"></div>`}

function renderCards(id){const e=nextEntry(id,'cards');if(!e)return finishTask(id,'cards');currentQuestion={answer:e.dat,hintType:'case'};cardRevealed=false;app.innerHTML=`<section class="card task-page"><div class="task-page-head"><div><p class="eyebrow">${esc(groupById(id).level)}</p><h2>Karteikarten</h2></div><button class="btn secondary" data-action="group" data-group="${id}">Aufgaben</button></div>${progress(id,'cards')}<div class="flip-wrap"><div id="verbFlipCard" class="flip-card" role="button" tabindex="0"><div class="flip-face flip-front"><div class="dativ-card-front"><span class="level-chip">${e.level}</span><div class="flip-word">${esc(e.verb)}</div><p>Welcher Dativ gehört zum Satz?</p><strong>${esc(sentenceWithPhrase(e,'_____'))}</strong></div></div><div class="flip-face flip-back"><div class="dativ-card-back"><div class="flip-word">${esc(e.dat)}</div><p>${esc(e.sentence)}</p><p class="source-example">Tabelle: ${esc(e.source)}</p><button type="button" class="btn secondary" id="cardListenBtn">🔊 Anhören</button></div></div></div></div><div id="cardAfter" class="actions card-selfcheck" hidden><button class="btn" id="cardKnow">Gewusst</button><button class="btn secondary" id="cardAgain">Nochmal</button></div><div class="hint">Klicke auf die Karte und kontrolliere dich selbst.</div></section>`;const flip=document.querySelector('#verbFlipCard'),reveal=()=>{if(cardRevealed)return;cardRevealed=true;flip.classList.add('flipped');document.querySelector('#cardAfter').hidden=false};flip.addEventListener('click',reveal);flip.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();reveal()}});document.querySelector('#cardListenBtn').addEventListener('click',ev=>{ev.stopPropagation();speak(e.sentence)});document.querySelector('#cardKnow').onclick=()=>{markRight(id,'cards');renderCards(id)};document.querySelector('#cardAgain').onclick=()=>{markWrong(id,'cards');markRight(id,'cards');renderCards(id)}}
function renderTask(id,t){if(t==='exam')return renderExam(id);if(taskDone(id,t))return finishTask(id,t);if(t==='cards')return renderCards(id);const e=nextEntry(id,t);if(!e)return finishTask(id,t);currentQuestion=question(id,t,e);app.innerHTML=`<section class="card task-page"><div class="task-page-head"><div><p class="eyebrow">${esc(groupById(id).level)}</p><h2>${esc(TITLE[t])}</h2></div><button class="btn secondary" data-action="group" data-group="${id}">Aufgaben</button></div>${progress(id,t)}<div class="question-card">${body(currentQuestion)}</div></section>`;setTimeout(()=>document.querySelector('#answerInput')?.focus(),50)}
function finishTask(id,t){const gs=groupState(id),pts=Number(currentRun(id).awards.tasks[t])||0,next=LEARN[LEARN.indexOf(t)+1]||'exam';app.innerHTML=`<section class="card"><div class="finish-box"><div class="finish-icon">✓</div><h2>Gut gemacht!</h2><p>${pts} Punkte · Runde ${gs.currentRun}</p><div class="actions"><button class="btn" data-action="task" data-group="${id}" data-task="${next}">Weiter</button><button class="btn secondary" data-action="group" data-group="${id}">Aufgaben</button></div></div></section>`}
function isCorrect(value,q){return answerNorm(value)===answerNorm(q.answer)}
function checkTask(value){const r=route(),q=currentQuestion;if(!r.group||!r.task||!q)return;if(isCorrect(value,q)){feedback('Richtig.',true);markRight(r.group,r.task);setTimeout(()=>renderTask(r.group,r.task),450)}else{const tries=markWrong(r.group,r.task);feedback(hint(tries,q))}}
function openWriteFallback(msg='Bitte schreibe die Antwort.'){document.querySelector('#writeFallback')?.classList.remove('hidden');const s=document.querySelector('#micStatus');if(s)s.textContent=msg;setTimeout(()=>document.querySelector('#answerInput')?.focus(),20)}
function startMic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){openWriteFallback();return}try{stopMic();rec=new SR();rec.lang='de-DE';rec.interimResults=false;rec.continuous=false;const s=document.querySelector('#micStatus');if(s)s.textContent='Ich höre zu …';rec.onresult=e=>{const text=e.results?.[0]?.[0]?.transcript||'';if(!text){openWriteFallback();return}route().task==='exam'?checkExam(text):checkTask(text)};rec.onerror=()=>openWriteFallback('Mikrofon hat nicht funktioniert. Bitte schreiben.');rec.onnomatch=()=>openWriteFallback();rec.onend=()=>{rec=null};rec.start()}catch{openWriteFallback('Mikrofon konnte nicht gestartet werden.')}}
function speak(text,slow=false){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text||''));u.lang='de-DE';u.rate=slow?.58:.92;speechSynthesis.speak(u)}
function renderExam(id){if(!learnDone(id)){app.innerHTML=`<section class="card locked-card"><h2>Prüfung gesperrt</h2><p>Bearbeite zuerst alle zehn Lernaufgaben zu 100 %.</p><button class="btn" data-action="group" data-group="${id}">Aufgaben</button></section>`;return}const run=currentRun(id),ex=run.exam;if(!ex.session){app.innerHTML=`<section class="card"><div class="finish-box"><div class="finish-icon">★</div><h2>Gruppenprüfung</h2><p>Bester Stand: ${ex.bestPercent||0}%</p><button class="btn" data-action="start-exam" data-group="${id}">Starten</button><button class="btn secondary" data-action="group" data-group="${id}">Aufgaben</button></div></section>`;return}if(ex.session.index>=ex.session.items.length)return finishExam(id);const item=ex.session.items[ex.session.index],e=entryByKey(item.key);currentQuestion=question(id,item.task,e);const p=Math.round(ex.session.index/ex.session.items.length*100);app.innerHTML=`<section class="card task-page"><div class="task-page-head"><div><p class="eyebrow">${esc(groupById(id).level)}</p><h2>Gruppenprüfung</h2></div><button class="btn secondary" data-action="group" data-group="${id}">Abbrechen</button></div><div class="task-progress-row"><span>${ex.session.index+1}/${ex.session.items.length}</span><strong>${p}%</strong></div><div class="mini-progress"><div style="width:${p}%"></div></div><div class="question-card">${body(currentQuestion)}</div></section>`}
function startExam(id){currentRun(id).exam.session={items:examItems(id),index:0,correct:0};save();renderExam(id)}
function checkExam(value){const r=route(),ex=currentRun(r.group).exam,q=currentQuestion;if(!ex.session||!q)return;const good=isCorrect(value,q);if(good)ex.session.correct++;feedback(good?'Richtig.':`Lösung: <strong>${esc(q.answer)}</strong>`,good);ex.session.index++;save();setTimeout(()=>renderExam(r.group),500)}
function finishExam(id){const run=currentRun(id),session=run.exam.session,total=session?.items?.length||1,correct=session?.correct||0,p=Math.round(correct/total*100),stars=p>=100?3:p>=70?2:p>=50?1:0;run.exam.session=null;run.exam.bestPercent=Math.max(Number(run.exam.bestPercent)||0,p);run.exam.stars=Math.max(Number(run.exam.stars)||0,stars);const max=groupState(id).currentRun*100,earned=Math.round(max*p/100);run.awards.examPoints=Math.max(Number(run.awards.examPoints)||0,earned);run.completed=learnDone(id)&&run.exam.bestPercent>=100;save();app.innerHTML=`<section class="card"><div class="finish-box"><div class="finish-icon">✓</div><h2>${p}%</h2><div class="stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>${correct}/${total} richtig</p><div class="actions"><button class="btn" data-action="start-exam" data-group="${id}">Noch einmal</button><button class="btn secondary" data-action="group" data-group="${id}">Aufgaben</button>${canRepeat(id)?`<button class="btn" data-action="next-run" data-group="${id}">Runde ${groupState(id).currentRun+1}</button>`:''}</div></div></section>`}
function answerFromInput(){const value=document.querySelector('#answerInput')?.value||'';route().task==='exam'?checkExam(value):checkTask(value)}
function render(){stopMic();const r=route();header(r);if(locked){app.innerHTML='<section class="card locked-card"><h2>Dativverben sind gesperrt</h2><a class="btn" href="/verben-bereich/">Zurück zu Verben</a></section>';return}if(r.view==='overview')return renderOverview();if(r.group&&r.task)return renderTask(r.group,r.task);renderHome(r.group)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,g=Number(b.dataset.group)||0,t=b.dataset.task||'';if(a==='logout')return logout();if(a==='overview')return go({view:'overview'});if(a==='group')return go({group:g});if(a==='task')return go({group:g,task:t});if(a==='reset-group'){if(!preview&&confirm(`Fortschritt von ${groupById(g)?.level||'dieser Gruppe'} löschen? Bereits verdiente Punkte bleiben erhalten.`)){resetGroup(g);render()}return}if(a==='next-run'){if(confirm(`Runde ${groupState(g).currentRun+1} starten?`)&&nextRun(g))go({group:g});return}if(a==='audio')return speak(b.dataset.text||'');if(a==='audio-slow')return speak(b.dataset.text||'',true);if(a==='answer')return route().task==='exam'?checkExam(b.dataset.answer||''):checkTask(b.dataset.answer||'');if(a==='check-input')return answerFromInput();if(a==='mic')return startMic();if(a==='write-fallback')return openWriteFallback();if(a==='start-exam'){go({group:g,task:'exam'});return startExam(g)}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target?.id==='answerInput'){e.preventDefault();answerFromInput()}});window.addEventListener('popstate',render);
async function init(){const user=requireLogin();if(!user)return;profile=getActiveProfile()||{};const role=String(getActiveRole()||'').toLowerCase();preview=role==='teacher';try{const raw=sessionStorage.getItem('SP_TEACHER_PREVIEW');if(raw==='1'||JSON.parse(raw||'null')?.teacherPreview===true)preview=true}catch{}try{const assignments=await loadCourseRelease(profile);locked=!preview&&!moduleOpen(assignments,'Verben')}catch{locked=!preview}load();render()}
init().catch(error=>{console.error(error);app.innerHTML='<section class="card"><h2>Dativverben konnten nicht geladen werden</h2><p>Bitte lade die Seite neu.</p><button class="btn" onclick="location.reload()">Neu laden</button></section>'});
