const CFG={lesson:'A1 Lektion 6',theme:'Thema 1',title:'Wetter',sub:'A1 Lektion 6 · Thema 1',key:'SP_L6_T1_V1'};
const BASE_WORDS=[
{id:'wetter',group:'Im Buch',type:'noun',article:'das',word:'Wetter',full:'das Wetter',sentence:'Wie ist das Wetter?',symbol:'🌡️',tr:{en:'weather',ru:'погода',tr:'hava durumu',uk:'погода',ar:'الطقس',ja:'天気',ro:'vremea',pl:'pogoda',ku:'hewa'}},
{id:'sonne',group:'Im Buch',type:'noun',article:'die',word:'Sonne',full:'die Sonne',sentence:'Die Sonne scheint.',altSentences:['Es ist sonnig.'],symbol:'☀️',tr:{en:'sun',ru:'солнце',tr:'güneş',uk:'сонце',ar:'الشمس',ja:'太陽',ro:'soare',pl:'słońce',ku:'roj'}},
{id:'regen',group:'Im Buch',type:'noun',article:'der',word:'Regen',full:'der Regen',sentence:'Es regnet.',symbol:'🌧️',sound:'/assets/audio/a1-l6-t1-sound-01-regen.mp3',tr:{en:'rain',ru:'дождь',tr:'yağmur',uk:'дощ',ar:'المطر',ja:'雨',ro:'ploaie',pl:'deszcz',ku:'baran'}},
{id:'wind',group:'Im Buch',type:'noun',article:'der',word:'Wind',full:'der Wind',sentence:'Es ist windig.',symbol:'💨',sound:'/assets/audio/a1-l6-t1-sound-04-wind.mp3',tr:{en:'wind',ru:'ветер',tr:'rüzgar',uk:'вітер',ar:'الرياح',ja:'風',ro:'vânt',pl:'wiatr',ku:'ba'}},
{id:'wolke',group:'Im Buch',type:'noun',article:'die',word:'Wolke',full:'die Wolke',sentence:'Es ist bewölkt.',symbol:'☁️',tr:{en:'cloud',ru:'облако',tr:'bulut',uk:'хмара',ar:'سحابة',ja:'雲',ro:'nor',pl:'chmura',ku:'ewr'}},
{id:'schnee',group:'Im Buch',type:'noun',article:'der',word:'Schnee',full:'der Schnee',sentence:'Es schneit.',symbol:'❄️',sound:'/assets/audio/a1-l6-t1-sound-06-schnee.mp3',tr:{en:'snow',ru:'снег',tr:'kar',uk:'сніг',ar:'الثلج',ja:'雪',ro:'zăpadă',pl:'śnieg',ku:'berf'}},
{id:'warm',group:'Im Buch',type:'adjective',article:'',word:'warm',full:'warm',sentence:'Es ist warm.',symbol:'🌤️',tr:{en:'warm',ru:'тёплый',tr:'sıcak',uk:'тепло',ar:'دافئ',ja:'暖かい',ro:'cald',pl:'ciepło',ku:'germ'}},
{id:'kalt',group:'Im Buch',type:'adjective',article:'',word:'kalt',full:'kalt',sentence:'Es ist kalt.',symbol:'🥶',tr:{en:'cold',ru:'холодный',tr:'soğuk',uk:'холодно',ar:'بارد',ja:'寒い',ro:'rece',pl:'zimno',ku:'sar'}},
{id:'heiss',group:'Im Buch',type:'adjective',article:'',word:'heiß',full:'heiß',sentence:'Es ist heiß.',symbol:'🔥',tr:{en:'hot',ru:'жарко',tr:'çok sıcak',uk:'спекотно',ar:'حار',ja:'暑い',ro:'foarte cald',pl:'gorąco',ku:'pir germ'}},
{id:'grad',group:'Im Buch',type:'noun',article:'der',word:'Grad',full:'der Grad',sentence:'Es sind 20 Grad.',symbol:'🌡️',tr:{en:'degree',ru:'градус',tr:'derece',uk:'градус',ar:'درجة',ja:'度',ro:'grad',pl:'stopień',ku:'pile'}}
];
const EXTRA_WORDS=[
{id:'gewitter',group:'Nicht im Buch',type:'noun',article:'das',word:'Gewitter',full:'das Gewitter',sentence:'Es gewittert.',symbol:'⛈️',sound:'/assets/audio/a1-l6-t1-sound-07-gewitter.mp3',tr:{en:'thunderstorm',ru:'гроза',tr:'fırtına/gök gürültülü sağanak',uk:'гроза',ar:'عاصفة رعدية',ja:'雷雨',ro:'furtună',pl:'burza',ku:'bahoz'}},
{id:'blitz',group:'Nicht im Buch',type:'noun',article:'der',word:'Blitz',full:'der Blitz',sentence:'Es blitzt.',symbol:'⚡',sound:'/assets/audio/a1-l6-t1-sound-02-blitz.mp3',tr:{en:'lightning',ru:'молния',tr:'şimşek',uk:'блискавка',ar:'برق',ja:'稲妻',ro:'fulger',pl:'błyskawica',ku:'birûsk'}},
{id:'eis',group:'Nicht im Buch',type:'noun',article:'das',word:'Eis',full:'das Eis',sentence:'Es ist eisig.',symbol:'🧊',sound:'/assets/audio/a1-l6-t1-sound-05-eis.mp3',tr:{en:'ice',ru:'лёд',tr:'buz',uk:'лід',ar:'جليد',ja:'氷',ro:'gheață',pl:'lód',ku:'qeşayî'}},
{id:'donner',group:'Nicht im Buch',type:'noun',article:'der',word:'Donner',full:'der Donner',sentence:'Es donnert.',symbol:'🔊',sound:'/assets/audio/a1-l6-t1-sound-08-donner.mp3',tr:{en:'thunder',ru:'гром',tr:'gök gürültüsü',uk:'грім',ar:'رعد',ja:'雷鳴',ro:'tunet',pl:'grzmot',ku:'gurîn'}},
{id:'hagel',group:'Nicht im Buch',type:'noun',article:'der',word:'Hagel',full:'der Hagel',sentence:'Es hagelt.',symbol:'🌨️',sound:'/assets/audio/a1-l6-t1-sound-03-hagel.mp3',tr:{en:'hail',ru:'град',tr:'dolu',uk:'град',ar:'بَرَد',ja:'雹',ro:'grindină',pl:'grad',ku:'tîrşok'}},
{id:'nebel',group:'Nicht im Buch',type:'noun',article:'der',word:'Nebel',full:'der Nebel',sentence:'Es ist neblig.',symbol:'🌫️',tr:{en:'fog',ru:'туман',tr:'sis',uk:'туман',ar:'ضباب',ja:'霧',ro:'ceață',pl:'mgła',ku:'mij'}},
{id:'sturm',group:'Nicht im Buch',type:'noun',article:'der',word:'Sturm',full:'der Sturm',sentence:'Es ist stürmisch.',symbol:'🌪️',tr:{en:'storm',ru:'буря',tr:'fırtına',uk:'буря',ar:'عاصفة',ja:'嵐',ro:'furtună',pl:'sztorm/burza',ku:'tûfan'}}
];
const DAYS=[['Mo.','Montag'],['Di.','Dienstag'],['Mi.','Mittwoch'],['Do.','Donnerstag'],['Fr.','Freitag'],['Sa.','Samstag'],['So.','Sonntag']];
const LANGS={en:'Englisch',ru:'Russisch',tr:'Türkisch',uk:'Ukrainisch',ar:'Arabisch',ja:'Japanisch',ro:'Rumänisch',pl:'Polnisch',ku:'Kurdisch'};
function isTeacher(){return localStorage.getItem('SP_LOGIN_ROLE')==='teacher'||localStorage.getItem('SP_TEACHER_PREVIEW')==='1'}
function extraOn(){return localStorage.getItem('SP_L6_T1_EXTRA_WEATHER')==='1'}
function setExtraWeather(v){localStorage.setItem('SP_L6_T1_EXTRA_WEATHER',v?'1':'0');Object.keys(localStorage).filter(k=>k.startsWith(CFG.key)).forEach(k=>localStorage.removeItem(k));location.reload()}
function words(){return extraOn()?BASE_WORDS.concat(EXTRA_WORDS):BASE_WORDS}
function nouns(){return words().filter(w=>w.type==='noun')}
function soundWords(){return words().filter(w=>w.sound)}
function simple(x){return String(x||'').toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[.,!?;:]/g,'').replace(/\s+/g,' ')}
function exact(value,solutions){const a=simple(value);return (Array.isArray(solutions)?solutions:[solutions]).some(s=>simple(s)===a)}
function full(w){return w.full||((w.article?`${w.article} `:'')+w.word)}
function profile(){try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||'null')}catch(e){return null}}
function langKey(){const m=String(profile()?.muttersprache||profile()?.motherLanguage||'').toLowerCase();if(['uk','ua'].includes(m)||m.includes('ukrain'))return'uk';if(m.includes('russ'))return'ru';if(m.includes('türk')||m.includes('turk'))return'tr';if(m.includes('arab'))return'ar';if(m.includes('japan'))return'ja';if(m.includes('rumän')||m.includes('ruman')||m.includes('roman'))return'ro';if(m.includes('pol'))return'pl';if(m.includes('kurd'))return'ku';return'en'}
function tr(w){const k=langKey(),t=w.tr||{};return t[k]||t.en||'—'}
function visual(w,small=false){return `<div class="weather-card ${small?'small-card':''}" aria-label="${w.word}">${w.symbol||'•'}</div>`}
function taskKey(file){return CFG.key+'_'+(extraOn()?'EXTRA_':'BOOK_')+file}
function loadTask(file,total){try{const st=JSON.parse(localStorage.getItem(taskKey(file))||'null');if(st&&st.total===total&&Array.isArray(st.done)&&Array.isArray(st.queue))return st}catch(e){}return{total,done:[],queue:[...Array(total).keys()].sort(()=>Math.random()-.5),current:null,tries:0,hadWrong:false}}
function saveTask(file,st){localStorage.setItem(taskKey(file),JSON.stringify(st))}
function markTaskDone(file,total){saveTask(file,{total,done:[...Array(total).keys()],queue:[],current:null,tries:0,hadWrong:false})}
function spNextIndex(file,total){let st=loadTask(file,total);if(st.current===null||st.current===undefined){if(!st.queue.length&&st.done.length<total)st.queue=[...Array(total).keys()].filter(i=>!st.done.includes(i)).sort(()=>Math.random()-.5);st.current=st.queue.shift();st.tries=0;st.hadWrong=false;saveTask(file,st)}return st.current}
function spMarkRight(file,total){let st=loadTask(file,total),c=st.current;if(c!==null&&c!==undefined){if(st.hadWrong||st.tries>0){if(!st.done.includes(c)&&!st.queue.includes(c))st.queue.push(c)}else if(!st.done.includes(c))st.done.push(c)}st.current=null;st.tries=0;st.hadWrong=false;saveTask(file,st)}
function spMarkWrong(file,total){let st=loadTask(file,total);st.tries=(st.tries||0)+1;st.hadWrong=true;saveTask(file,st);return st.tries}
function pctFor(file,total){return total?Math.round((loadTask(file,total).done.length||0)/total*100)||0:0}
function progress(file,total){const d=loadTask(file,total).done.length,p=pctFor(file,total);return `<div class="small">${d} richtig · ${total-d} übrig · ${p}%</div><div class="progress"><div class="bar" style="width:${p}%"></div></div>`}
function help3(t,a,b,sol){if(t===1)return `<div class="no">${a}</div>`;if(t===2)return `<div class="hint">${b}</div>`;return `<div class="no">Lösung: ${sol}</div>`}
function instruction(txt){return `<div class="task-instruction">${txt}</div>`}
function complete(area,file,next='index.html'){area.innerHTML=`<div class="finish-box"><div class="finish-icon">✓</div><div class="question">Geschafft!</div><div class="hint">Diese Aufgabe ist abgeschlossen.</div><div class="actions"><a class="btn" href="${next}">Weiter →</a><a class="btn secondary" href="index.html">Zum Menü</a></div></div>`}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function say(t){if(!('speechSynthesis'in window))return; speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='de-DE';u.rate=.86;speechSynthesis.speak(u)}
function header(title,showReset=false){const h=document.querySelector('.topbar');if(!h)return;const p=profile();const name=`${p?.vorname||p?.firstName||''} ${p?.nachname||p?.lastName||''}`.trim()||'Schüler/in';const dashboard=localStorage.getItem('SP_LOGIN_ROLE')==='teacher'?'/teacher/index.html':'/student-dashboard/index.html';h.innerHTML=`<div class="topbar-main"><a class="brand" href="/index.html"><div class="logo"><img src="/assets/logo/sprachpilot-logo.png" alt="SprachPilot"></div><div><h1>SprachPilot</h1><div class="subtitle">${title} · ${CFG.sub}</div></div></a><div class="account-tools"><span class="account-pill">${name}</span><a class="account-link" href="${dashboard}">Dashboard</a><a class="account-link" href="/profile/index.html">Profil</a></div></div><nav class="nav"><a class="btn secondary" href="index.html">← Zurück</a><a class="btn secondary" href="uebersicht.html">Übersicht</a><a class="btn secondary" href="statistik.html">Statistik</a>${showReset?'<button class="btn danger-btn" onclick="resetThemeProgress()">Fortschritte löschen</button>':''}</nav>`}
function resetThemeProgress(){if(!confirm('Fortschritte in Thema 1 löschen?'))return;Object.keys(localStorage).filter(k=>k.startsWith(CFG.key)).forEach(k=>localStorage.removeItem(k));location.reload()}
function renderOverview(target){target.innerHTML=['Im Buch','Nicht im Buch'].map(g=>{const list=(g==='Im Buch'?BASE_WORDS:EXTRA_WORDS).filter(w=>g==='Im Buch'||extraOn());return list.length?`<section class="type-block"><div class="type-title">${g}</div>${list.map(w=>`<div class="word-row"><div class="word-placeholder">${w.symbol}</div><div><b>${full(w)}</b><br><span class="small">${w.sentence}${w.altSentences?' / '+w.altSentences.join(' / '):''}</span><div class="small">Übersetzung (${LANGS[langKey()]||'EN'}): ${tr(w)}</div><span class="tag">${w.type}</span></div></div>`).join('')}</section>`:''}).join('')}
function renderStats(target){const total=cardItems().length,st=loadTask('karteikarten.html',total);target.innerHTML=`<div class="card"><b>Karteikarten:</b> ${st.done.length} / ${total}</div>`+renderTaskList(false)}
function cardItems(){return words().flatMap(w=>[{mode:'noun',w},{mode:'sentence',w}])}
function sentenceSolutions(w){return [w.sentence].concat(w.altSentences||[])}
function weatherSentence(w){return w.sentence}
function sentenceItems(){const base=words().filter(w=>w.sentence);return base.map(w=>({w,sol:sentenceSolutions(w)}))}
function writingItems(){const book=[['Mo.','Montag','8:00','acht Uhr','regen'],['Di.','Dienstag','10:00','zehn Uhr','sonne'],['Mi.','Mittwoch','7:00','sieben Uhr','schnee'],['Do.','Donnerstag','15:00','fünfzehn Uhr','wind'],['Fr.','Freitag','18:00','achtzehn Uhr','wolke'],['Sa.','Samstag','9:00','neun Uhr','regen'],['So.','Sonntag','12:00','zwölf Uhr','sonne'],['Mo.','Montag','20:00','zwanzig Uhr','schnee'],['Di.','Dienstag','14:00','vierzehn Uhr','wind'],['Mi.','Mittwoch','16:00','sechzehn Uhr','wolke'],['Do.','Donnerstag','11:00','elf Uhr','regen'],['Fr.','Freitag','13:00','dreizehn Uhr','sonne'],['Sa.','Samstag','17:00','siebzehn Uhr','schnee'],['So.','Sonntag','19:00','neunzehn Uhr','wind'],['Mo.','Montag','6:00','sechs Uhr','wolke']];const extra=[['Di.','Dienstag','21:00','einundzwanzig Uhr','gewitter'],['Mi.','Mittwoch','8:00','acht Uhr','donner'],['Do.','Donnerstag','10:00','zehn Uhr','blitz'],['Fr.','Freitag','15:00','fünfzehn Uhr','hagel'],['Sa.','Samstag','18:00','achtzehn Uhr','nebel']];const fill=[['Di.','Dienstag','21:00','einundzwanzig Uhr','regen'],['Mi.','Mittwoch','8:00','acht Uhr','sonne'],['Do.','Donnerstag','10:00','zehn Uhr','wind'],['Fr.','Freitag','15:00','fünfzehn Uhr','schnee'],['Sa.','Samstag','18:00','achtzehn Uhr','wolke']];return book.concat(extraOn()?extra:fill).map(x=>{const w=words().find(a=>a.id===x[4])||BASE_WORDS.find(a=>a.id===x[4]);let sol=`Am ${x[1]} um ${x[3]} ${w.sentence.charAt(0).toLowerCase()+w.sentence.slice(1)}`;return{short:x[0],day:x[1],time:x[2],timeText:x[3],w,sol:sol.replace('die sonne scheint','scheint die Sonne')}})}
function listenItems(){return[
{audio:'/assets/audio/a1-l6-t1-hoeren-01.mp3',q:'Wie ist das Wetter am Montagvormittag in Berlin?',a:'sonnig',opts:['sonnig','windig','verschneit']},
{audio:'/assets/audio/a1-l6-t1-hoeren-02.mp3',q:'Wann regnet es in Hamburg?',a:'am Dienstag um 8 Uhr',opts:['am Montag um 8 Uhr','am Dienstag um 8 Uhr','am Dienstag um 18 Uhr']},
{audio:'/assets/audio/a1-l6-t1-hoeren-03.mp3',q:'Wo schneit es?',a:'in München',opts:['in München','in Berlin','in Köln']},
{audio:'/assets/audio/a1-l6-t1-hoeren-04.mp3',q:'Wie ist das Wetter am Wochenende?',a:'kalt und bewölkt',opts:['warm und sonnig','kalt und bewölkt','windig und heiß']},
{audio:'/assets/audio/a1-l6-t1-hoeren-05.mp3',q:'Wie viel Grad sind es?',a:'sieben Grad',opts:['fünf Grad','sieben Grad','zwanzig Grad']},
{audio:'/assets/audio/a1-l6-t1-hoeren-06.mp3',q:'Was passiert am Freitag?',a:'Es schneit.',opts:['Es schneit.','Es regnet.','Die Sonne scheint.']},
{audio:'/assets/audio/a1-l6-t1-hoeren-07.mp3',q:'Wann ist es windig?',a:'am Abend',opts:['am Morgen','am Mittag','am Abend']},
{audio:'/assets/audio/a1-l6-t1-hoeren-08.mp3',q:'Wie ist das Wetter morgen?',a:'nicht so schön',opts:['sehr schön','nicht so schön','heiß']},
{audio:'/assets/audio/a1-l6-t1-hoeren-09.mp3',q:'Was hört man?',a:'der Regen',opts:['der Regen','der Wind','der Schnee']},
{audio:'/assets/audio/a1-l6-t1-hoeren-10.mp3',q:'Was ist richtig?',a:'Am Sonntag scheint die Sonne.',opts:['Am Sonntag regnet es.','Am Sonntag scheint die Sonne.','Am Sonntag schneit es.']}
]}
function taskTotals(){return[['karteikarten.html',cardItems().length,'Karteikarten'],['artikel.html',nouns().length,'Artikel'],['hoeren-schreiben.html',cardItems().length,'Hören/Schreiben'],['hoeren-bild.html',words().length,'Hören/Karte'],['nomen-satz-a.html',sentenceItems().length,'Nomen → Satz A'],['nomen-satz-b.html',sentenceItems().length,'Nomen → Satz B'],['geraeusche.html',soundWords().length,'Geräusche'],['geraeusche-satz.html',soundWords().length,'Geräusch → Satz'],['wetter-saetze.html',20,'20 Sätze'],['hoeren.html',listenItems().length,'Hören'],['pruefung.html',12,'Prüfung']]}
function renderTaskList(includeExam=true){const ts=taskTotals().filter(t=>includeExam||t[0]!=='pruefung.html');return `<div class="grid">${ts.map((t,i)=>`<a class="module" href="${t[0]}"><div class="num">${i+1}. ${t[2]}</div><div class="progress"><div class="bar" style="width:${pctFor(t[0],t[1])}%"></div></div><div class="small">${pctFor(t[0],t[1])}%</div><div class="start">${pctFor(t[0],t[1])>=100?'Fertig':'Starten'}</div></a>`).join('')}</div>`}
function renderMenu(){const box=document.getElementById('teacherBox');if(box){box.innerHTML=isTeacher()?`<section class="card teacher-box"><div class="toggle-row"><div><b>Lehreroption</b><br><span class="small">Wetter „Nicht im Buch“ aktivieren: Gewitter, Blitz, Eis, Donner, Hagel, Nebel, Sturm.</span></div><label class="switch"><input type="checkbox" ${extraOn()?'checked':''} onchange="setExtraWeather(this.checked)"> Nicht im Buch</label></div></section>`:''}document.getElementById('taskGrid').innerHTML=renderTaskList(true);const ts=taskTotals(),avg=Math.round(ts.reduce((s,t)=>s+pctFor(t[0],t[1]),0)/ts.length)||0,done=ts.filter(t=>pctFor(t[0],t[1])>=100).length;totalCircle.textContent=avg+'%';totalBar.style.width=avg+'%';totalText.textContent=done+' / '+ts.length+' Aufgaben abgeschlossen'}
