const L6T1_CDN='https://sprachpilot.b-cdn.net/';
const L6T1_MEDIA={
  wetter:{image:'a1-l6-t1-wetter.webp'},sonne:{image:'a1-l6-t1-sonne.webp'},regen:{image:'a1-l6-t1-regen.webp',sound:'a1-l6-t1-sound-regen.mp3'},wind:{image:'a1-l6-t1-wind.webp',sound:'a1-l6-t1-sound-wind.mp3'},wolke:{image:'a1-l6-t1-wolke.webp'},schnee:{image:'a1-l6-t1-schnee.webp',sound:'a1-l6-t1-sound-schnee.mp3'},warm:{image:'a1-l6-t1-warm.webp'},kalt:{image:'a1-l6-t1-kalt.webp'},heiss:{image:'a1-l6-t1-heiss.webp'},grad:{image:'a1-l6-t1-grad.webp'},unter_null:{image:'a1-l6-t1-unter-null.webp'},
  gewitter:{image:'a1-l6-t1-gewitter.webp',sound:'a1-l6-t1-sound-gewitter.mp3'},blitz:{image:'a1-l6-t1-blitz.webp',sound:'a1-l6-t1-sound-blitz.mp3'},eis:{image:'a1-l6-t1-eis.webp',sound:'a1-l6-t1-sound-eis.mp3'},donner:{image:'a1-l6-t1-donner.webp',sound:'a1-l6-t1-sound-donner.mp3'},hagel:{image:'a1-l6-t1-hagel.webp',sound:'a1-l6-t1-sound-hagel.mp3'},nebel:{image:'a1-l6-t1-nebel.webp'},sturm:{image:'a1-l6-t1-sturm.webp'}
};
const L6T1_LISTENING=[
  {file:'a1-l6-t1-hoeren-01.mp3',q:'Wie ist das Wetter am Montagvormittag in Berlin?',a:'sonnig',opts:['sonnig','windig','verschneit'],transcript:'Guten Morgen. Hier ist der Wetterbericht für Berlin. Am Montagvormittag scheint die Sonne. Es ist warm.'},
  {file:'a1-l6-t1-hoeren-02.mp3',q:'Wann regnet es in Hamburg?',a:'am Dienstag um 8 Uhr',opts:['am Montag um 8 Uhr','am Dienstag um 8 Uhr','am Dienstag um 18 Uhr'],transcript:'In Hamburg regnet es am Dienstag um 8 Uhr. Am Abend ist es trocken.'},
  {file:'a1-l6-t1-hoeren-03.mp3',q:'Wo schneit es?',a:'in München',opts:['in München','in Berlin','in Köln'],transcript:'In München schneit es heute. In Berlin ist es kalt, aber trocken.'},
  {file:'a1-l6-t1-hoeren-04.mp3',q:'Wie ist das Wetter am Wochenende?',a:'kalt und bewölkt',opts:['warm und sonnig','kalt und bewölkt','windig und heiß'],transcript:'Am Wochenende ist es kalt und bewölkt. Die Sonne scheint nicht.'},
  {file:'a1-l6-t1-hoeren-05.mp3',q:'Wie viel Grad sind es?',a:'sieben Grad',opts:['fünf Grad','sieben Grad','zwanzig Grad'],transcript:'Heute ist es kalt. Es sind sieben Grad.'},
  {file:'a1-l6-t1-hoeren-06.mp3',q:'Was passiert am Freitag?',a:'Es schneit.',opts:['Es schneit.','Es regnet.','Die Sonne scheint.'],transcript:'Am Freitag schneit es. Bitte fahren Sie vorsichtig.'},
  {file:'a1-l6-t1-hoeren-07.mp3',q:'Wann ist es windig?',a:'am Abend',opts:['am Morgen','am Mittag','am Abend'],transcript:'Am Morgen ist es ruhig. Am Mittag ist es warm. Am Abend ist es windig.'},
  {file:'a1-l6-t1-hoeren-08.mp3',q:'Wie ist das Wetter morgen?',a:'nicht so schön',opts:['sehr schön','nicht so schön','heiß'],transcript:'Das Wetter morgen ist nicht so schön. Es regnet und es ist kalt.'},
  {file:'a1-l6-t1-hoeren-09.mp3',q:'Was hört man?',a:'der Regen',opts:['der Regen','der Wind','der Schnee'],transcript:'Hören Sie genau. Man hört den Regen.'},
  {file:'a1-l6-t1-hoeren-10.mp3',q:'Was ist richtig?',a:'Am Sonntag scheint die Sonne.',opts:['Am Sonntag regnet es.','Am Sonntag scheint die Sonne.','Am Sonntag schneit es.'],transcript:'Am Sonntag scheint die Sonne. Es ist warm und schön.'}
];
function l6Cdn(file){return /^https?:\/\//i.test(String(file||''))?file:L6T1_CDN+file}
function l6ApplyMedia(){try{BASE_WORDS.concat(EXTRA_WORDS).forEach(w=>{const m=L6T1_MEDIA[w.id]||{};if(m.image)w.image=l6Cdn(m.image);if(m.sound)w.sound=l6Cdn(m.sound)})}catch(e){}}
l6ApplyMedia();
function l6ReleaseData(){try{return (window.SprachPilotRelease&&SprachPilotRelease.localData&&SprachPilotRelease.localData())||JSON.parse(localStorage.getItem('SP_COURSE_RELEASES')||'{}')||((profile()||{}).assignments)||{}}catch(e){return {}}}
function l6Val(obj,path){let cur=obj;for(const p of path){if(!cur||typeof cur!=='object'||!(p in cur))return undefined;cur=cur[p]}return cur}
function l6Any(paths,fallback){const data=l6ReleaseData();for(const p of paths){const v=l6Val(data,p);if(v!==undefined)return v===true}return fallback}
function l6SetPaths(key){const aliases={book:['book','buch','basis','im-buch','im_buch','im buch','Im Buch'],extra:['extra','plus','nicht-im-buch','nicht_im_buch','nicht im buch','Nicht im Buch','nicht-aus-dem-buch','nicht_aus_dem_buch','nicht aus dem buch','Nicht aus dem Buch','not-in-book','not_in_book','extra-weather','extra_weather','weather-extra','weather_extra']}[key]||[key];const out=[];aliases.forEach(k=>{out.push(['enabledSets','A1-Lektion-6/Thema-1/'+k],['enabledSets','wortschatz/A1-Lektion-6/Thema-1/'+k],['enabledSets','Wortschatz/A1-Lektion-6/Thema-1/'+k],['enabledSets','Thema-1/'+k],['enabledSets',k],['releases','wortschatz','lessons','A1-Lektion-6','themes','Thema-1','sets',k],['releases','Wortschatz','lessons','A1-Lektion-6','themes','Thema-1','sets',k])});return out}
function l6HasExplicitSetData(){const data=l6ReleaseData();return l6SetPaths('book').concat(l6SetPaths('extra')).some(p=>l6Val(data,p)!==undefined)}
function bookOn(){return l6Any(l6SetPaths('book'),true)}
function extraOn(){return l6Any(l6SetPaths('extra'),localStorage.getItem('SP_L6_T1_EXTRA_WEATHER')==='1')}
function setExtraWeather(v){localStorage.setItem('SP_L6_T1_EXTRA_WEATHER',v?'1':'0');Object.keys(localStorage).filter(k=>k.startsWith(CFG.key)).forEach(k=>localStorage.removeItem(k));location.reload()}
function words(){return (bookOn()?BASE_WORDS:[]).concat(extraOn()?EXTRA_WORDS:[])}
function wordItems(){return words()}
function soundWords(){return words().filter(w=>w.sound)}
function listenItems(){return L6T1_LISTENING.map(x=>({audio:l6Cdn(x.file),audioName:x.file,transcript:x.transcript,q:x.q,a:x.a,opts:x.opts}))}
function visual(w,small=false){const img=w.image||'';const alt=(w.full||w.word||'Wetterbild').replace(/"/g,'&quot;');const fallback=w.symbol||'•';return `<div class="weather-card ${small?'small-card':''}" aria-label="${alt}">${img?`<img class="weather-img" src="${img}" alt="${alt}" loading="lazy" onerror="this.remove();this.parentElement.textContent='${fallback}'">`:fallback}</div>`}
function l6CourseCodes(){const p=profile()||{};const raw=[p.courseDocId,p.kurs,p.kursnummer,p.courseCode,p.courseId,p.courseName,p.code,p.id,localStorage.getItem('SP_COURSE_CODE')].filter(Boolean);const out=[];raw.forEach(v=>{v=String(v).trim();[v,v.toUpperCase(),v.toLowerCase(),v.replace(/\s+/g,''),v.toLowerCase().replace(/\s+/g,'')].forEach(x=>{if(x&&!out.includes(x))out.push(x)})});return out}
function l6HasReleaseData(d){return !!(d&&typeof d==='object'&&(d.enabledModules||d.enabledLessons||d.enabledThemes||d.enabledTasks||d.enabledSets||d.releases||d.releaseMode||d.defaultLocked!==undefined))}
function l6RememberRelease(data){try{if(!l6HasReleaseData(data))return data;localStorage.setItem('SP_COURSE_RELEASES',JSON.stringify(data));localStorage.setItem('SP_RELEASE_SYNC_AT',String(Date.now()));const p=profile()||{};p.assignments=data;if(data.id||data.courseDocId)p.courseDocId=data.courseDocId||data.id;if(data.courseCode||data.kurs||data.kursnummer){p.courseCode=data.courseCode||data.kurs||data.kursnummer;p.kurs=p.kurs||p.courseCode;p.kursnummer=p.kursnummer||p.courseCode}localStorage.setItem('SP_USER_PROFILE',JSON.stringify(p));localStorage.setItem('SP_STUDENT_PROFILE',JSON.stringify(p))}catch(e){}return data}
async function l6ReadCourseReleaseFresh(){try{const mod=await import('/js/firebase.js?v=6');if(mod.authReady)await Promise.race([mod.authReady,new Promise(r=>setTimeout(r,3000))]);const codes=l6CourseCodes();for(const c of codes){try{const snap=await mod.getDoc(mod.doc(mod.db,'courses',String(c)));if(snap.exists()){const d={id:snap.id,...(snap.data()||{})};if(l6HasReleaseData(d))return d}}catch(e){}}for(const field of ['courseCode','kurs','kursnummer','courseDocId','courseId','id','name','courseName','code']){for(const c of codes){try{const q=mod.query(mod.collection(mod.db,'courses'),mod.where(field,'==',String(c)),mod.limit(1));const s=await mod.getDocs(q);if(s&&!s.empty){const doc=s.docs[0];const d={id:doc.id,...(doc.data()||{})};if(l6HasReleaseData(d))return d}}catch(e){}}}}catch(e){console.warn('L6T1 Freigabe konnte nicht frisch geladen werden',e)}return null}
async function l6ForceReleaseRefresh(){const data=await l6ReadCourseReleaseFresh();if(l6HasReleaseData(data)){l6RememberRelease(data);l6ApplyMedia();try{renderMenu()}catch(e){}try{const wordList=document.getElementById('wordList');if(wordList&&typeof renderOverview==='function')renderOverview(wordList)}catch(e){}try{const stats=document.getElementById('stats');if(stats&&typeof renderStats==='function')renderStats(stats)}catch(e){}}return data}
const L6_T1_TASK_ICONS={'karteikarten.html':'🃏','artikel.html':'🔤','hoeren-schreiben.html':'🎧','hoeren-bild.html':'🖼️','nomen-satz-a.html':'💬','nomen-satz-b.html':'🔁','geraeusche.html':'🔊','geraeusche-satz.html':'🌦️','wetter-saetze.html':'✍️','hoeren.html':'🎧','pruefung.html':'★'};
function l6t1Logout(){try{if(typeof logout==='function'){logout();return}}catch(e){}try{localStorage.removeItem('SP_USER_PROFILE');localStorage.removeItem('SP_STUDENT_PROFILE');localStorage.removeItem('SP_KEEP_LOGGED_IN');localStorage.removeItem('SP_LOGIN_ROLE');localStorage.removeItem('SP_ACTIVE_ROLE')}catch(e){}location.href='/index.html'}
function l6StatusBox(){if(!isTeacher())return '';const b=bookOn(),e=extraOn(),explicit=l6HasExplicitSetData();return `<section class="card release-status-card"><h2>Wortschatz-Freigabe</h2><div class="release-pill-row"><span class="release-pill ${b?'is-on':'is-off'}">Im Buch: ${b?'freigegeben':'gesperrt'}</span><span class="release-pill ${e?'is-on':'is-off'}">Nicht im Buch: ${e?'freigegeben':'gesperrt'}</span></div><p class="small">${explicit?'Diese Einstellung kommt aus der Kursfreigabe im Lehrer-Dashboard.':'Noch keine explizite Kursfreigabe gefunden: Basiswortschatz bleibt sichtbar, Zusatzwörter bleiben gesperrt.'}</p><p class="small"><a href="/teacher/index.html">Im Lehrer-Dashboard ändern</a></p></section>`}
function renderOverview(target){target.innerHTML=['Im Buch','Nicht im Buch'].map(g=>{const visible=g==='Im Buch'?bookOn():extraOn();const list=(g==='Im Buch'?BASE_WORDS:EXTRA_WORDS);if(!visible&&!isTeacher())return '';if(!visible)return `<section class="type-block locked-set"><div class="type-title">${g} 🔒</div><p class="small">Diese Wortschatzliste ist für deinen Kurs noch nicht freigegeben.</p></section>`;return `<section class="type-block"><div class="type-title">${g}</div>${list.map(w=>`<div class="word-row"><div class="word-placeholder">${visual(w,true)}</div><div><b>${full(w)}</b><br><span class="small">${w.sentence}${w.altSentences?' / '+w.altSentences.join(' / '):''}</span><div class="small">Übersetzung (${LANGS[langKey()]||'EN'}): ${tr(w)}</div><span class="tag">${w.type}</span></div></div>`).join('')}</section>`}).join('')}
function renderTaskList(includeExam=true){const ts=taskTotals().filter(t=>includeExam||t[0]!=='pruefung.html');return `<div class="grid task-grid">${ts.map((t,i)=>{const p=pctFor(t[0],t[1]);const icon=L6_T1_TASK_ICONS[t[0]]||'▶';return `<a class="module task-card" href="${t[0]}"><div class="num">${i+1}. ${t[2]}</div><div class="icon big-icon">${icon}</div><p>${t[0]==='pruefung.html'?'Teste dein Wissen.':'Wetter und Sätze üben.'}</p><div class="progress"><div class="bar" style="width:${p}%"></div></div><div class="small">${p}%</div><div class="start">${p>=100?'Fertig':'Starten'}</div></a>`}).join('')}</div>`}
function renderMenu(){const box=document.getElementById('teacherBox');if(box){box.innerHTML=isTeacher()?l6StatusBox():''}const usable=words().length>0;taskGrid.innerHTML=usable?renderTaskList(true):'<section class="card"><h2>Keine Wörter freigegeben</h2><p class="small">Für dieses Thema ist noch keine Wortschatzliste freigeschaltet.</p></section>';const ts=usable?taskTotals():[],avg=ts.length?Math.round(ts.reduce((s,t)=>s+pctFor(t[0],t[1]),0)/ts.length)||0:0,done=ts.filter(t=>pctFor(t[0],t[1])>=100).length;totalCircle.textContent=avg+'%';totalBar.style.width=avg+'%';totalText.textContent=done+' / '+ts.length+' Aufgaben abgeschlossen'}
(function(){const css=document.createElement('style');css.textContent='.topbar-main.sp-account-row{align-items:center}.sp-page-nav{margin-top:14px}.task-grid .module{text-align:center}.task-grid .icon.big-icon{font-size:46px;line-height:1;margin:14px auto;color:var(--lesson-main-dark)}.task-grid .module p{min-height:44px}.account-btn{cursor:pointer}.release-status-card{margin:16px 0}.release-pill-row{display:flex;gap:10px;flex-wrap:wrap;margin:10px 0}.release-pill{display:inline-flex;border-radius:999px;padding:9px 14px;font-weight:900;border:2px solid var(--lesson-line);background:#fff}.release-pill.is-on{background:#dcfce7;border-color:#22c55e;color:#166534}.release-pill.is-off{background:#fee2e2;border-color:#ef4444;color:#991b1b}.locked-set{opacity:.72;border-style:dashed}.weather-img{width:100%;height:100%;object-fit:cover;display:block;border-radius:16px}.word-placeholder .weather-card{width:86px;height:70px;margin:0;font-size:26px}.choice .weather-img{pointer-events:none}';document.head.appendChild(css)})();
try{setTimeout(()=>{l6ForceReleaseRefresh()},300);setTimeout(()=>{l6ForceReleaseRefresh()},1600)}catch(e){}