const L6T1_CDN='https://sprachpilot.b-cdn.net/';
window.L6_BUNNY_IMAGES={wetter:'wetter.webp',sonne:'sonne.webp',regen:'regen.webp',wind:'wind.webp',wolke:'wolke.webp',schnee:'schnee.webp',warm:'warm.webp',kalt:'kalt.webp',heiss:'heiss.webp',grad:'grad.webp',gewitter:'gewitter.webp',blitz:'blitz.webp',eis:'das_eis.webp',donner:'donner.webp',hagel:'hagel.webp',nebel:'nebel.webp',sturm:'sturm.webp'};
const L6T1_MEDIA={
  wetter:{image:'wetter.webp'},sonne:{image:'sonne.webp'},regen:{image:'regen.webp',sound:'a1-l6-t1-sound-regen.mp3'},wind:{image:'wind.webp',sound:'a1-l6-t1-sound-wind.mp3'},wolke:{image:'wolke.webp'},schnee:{image:'schnee.webp',sound:'a1-l6-t1-sound-schnee.mp3'},warm:{image:'warm.webp'},kalt:{image:'kalt.webp'},heiss:{image:'heiss.webp'},grad:{image:'grad.webp'},
  gewitter:{image:'gewitter.webp',sound:'a1-l6-t1-sound-gewitter.mp3'},blitz:{image:'blitz.webp',sound:'a1-l6-t1-sound-blitz.mp3'},eis:{image:'das_eis.webp',sound:'a1-l6-t1-sound-eis.mp3'},donner:{image:'donner.webp',sound:'a1-l6-t1-sound-donner.mp3'},hagel:{image:'hagel.webp',sound:'a1-l6-t1-sound-hagel.mp3'},nebel:{image:'nebel.webp'},sturm:{image:'sturm.webp'}
};
const L6T1_LISTENING=[
  {file:'a1-l6-t1-hoeren-01.mp3',q:'Wie ist das Wetter am Montagvormittag in Berlin?',a:'sonnig',opts:['sonnig','windig','verschneit']},
  {file:'a1-l6-t1-hoeren-02.mp3',q:'Wann regnet es in Hamburg?',a:'am Dienstag um 8 Uhr',opts:['am Montag um 8 Uhr','am Dienstag um 8 Uhr','am Dienstag um 18 Uhr']},
  {file:'a1-l6-t1-hoeren-03.mp3',q:'Wo schneit es?',a:'in München',opts:['in München','in Berlin','in Köln']},
  {file:'a1-l6-t1-hoeren-04.mp3',q:'Wie ist das Wetter am Wochenende?',a:'kalt und bewölkt',opts:['warm und sonnig','kalt und bewölkt','windig und heiß']},
  {file:'a1-l6-t1-hoeren-05.mp3',q:'Wie viel Grad sind es?',a:'sieben Grad',opts:['fünf Grad','sieben Grad','zwanzig Grad']},
  {file:'a1-l6-t1-hoeren-06.mp3',q:'Was passiert am Freitag?',a:'Es schneit.',opts:['Es schneit.','Es regnet.','Die Sonne scheint.']},
  {file:'a1-l6-t1-hoeren-07.mp3',q:'Wann ist es windig?',a:'am Abend',opts:['am Morgen','am Mittag','am Abend']},
  {file:'a1-l6-t1-hoeren-08.mp3',q:'Wie ist das Wetter morgen?',a:'nicht so schön',opts:['sehr schön','nicht so schön','heiß']},
  {file:'a1-l6-t1-hoeren-09.mp3',q:'Was hört man?',a:'der Regen',opts:['der Regen','der Wind','der Schnee']},
  {file:'a1-l6-t1-hoeren-10.mp3',q:'Was ist richtig?',a:'Am Sonntag scheint die Sonne.',opts:['Am Sonntag regnet es.','Am Sonntag scheint die Sonne.','Am Sonntag schneit es.']}
];
function header(){return true}
function l6Cdn(file){return /^https?:\/\//i.test(String(file||''))?file:L6T1_CDN+file}
function l6CleanWordLists(){try{[window.BASE_WORDS,window.EXTRA_WORDS].filter(Array.isArray).forEach(list=>{for(let i=list.length-1;i>=0;i--){if(list[i]&&list[i].id==='unter_null')list.splice(i,1)}})}catch(e){}}
function l6ApplyMedia(){try{l6CleanWordLists();BASE_WORDS.concat(EXTRA_WORDS).forEach(w=>{const m=L6T1_MEDIA[w.id]||{};if(m.image)w.image=l6Cdn(m.image);if(m.sound)w.sound=l6Cdn(m.sound)})}catch(e){}}
l6ApplyMedia();
const L6_TIME_WORDS={ein:'1',eins:'1',eine:'1',zwei:'2',drei:'3',vier:'4',fuenf:'5',fünf:'5',sechs:'6',sieben:'7',acht:'8',neun:'9',zehn:'10',elf:'11',zwoelf:'12',zwölf:'12',dreizehn:'13',vierzehn:'14',fuenfzehn:'15',fünfzehn:'15',sechzehn:'16',siebzehn:'17',achtzehn:'18',neunzehn:'19',zwanzig:'20'};
function l6NormTimeText(s){let x=String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[.,!?;:]/g,' ').replace(/\s+/g,' ').trim();x=x.replace(/um\s+(\d{1,2})(?:\s*[:.]\s*00)?\s*uhr/g,'um $1 uhr');Object.entries(L6_TIME_WORDS).forEach(([w,n])=>{const ww=w.normalize('NFD').replace(/[\u0300-\u036f]/g,'');x=x.replace(new RegExp('um '+ww+' uhr','g'),'um '+n+' uhr')});return x}
function exact(value,solutions){const list=Array.isArray(solutions)?solutions:[solutions];const a=simple(value),at=l6NormTimeText(value);return list.some(s=>simple(s)===a||l6NormTimeText(s)===at)}
function l6ReleaseData(){try{return (window.SprachPilotRelease&&SprachPilotRelease.localData&&SprachPilotRelease.localData())||JSON.parse(localStorage.getItem('SP_COURSE_RELEASES')||'{}')||((profile()||{}).assignments)||{}}catch(e){return {}}}
function l6Val(obj,path){let cur=obj;for(const p of path){if(!cur||typeof cur!=='object'||!(p in cur))return undefined;cur=cur[p]}return cur}
function l6Any(paths,fallback){const data=l6ReleaseData();for(const p of paths){const v=l6Val(data,p);if(v!==undefined)return v===true}return fallback}
function l6SetPaths(key){const aliases={book:['book','buch','basis','im-buch','im_buch','im buch','Im Buch'],extra:['extra','plus','nicht-im-buch','nicht_im_buch','nicht im buch','Nicht im Buch','nicht-aus-dem-buch','nicht_aus_dem_buch','nicht aus dem buch','Nicht aus dem Buch','not-in-book','not_in_book','extra-weather','extra_weather','weather-extra','weather_extra']}[key]||[key];const out=[];aliases.forEach(k=>{out.push(['enabledSets','A1-Lektion-6/Thema-1/'+k],['enabledSets','wortschatz/A1-Lektion-6/Thema-1/'+k],['enabledSets','Wortschatz/A1-Lektion-6/Thema-1/'+k],['enabledSets','Thema-1/'+k],['enabledSets',k],['releases','wortschatz','lessons','A1-Lektion-6','themes','Thema-1','sets',k],['releases','Wortschatz','lessons','A1-Lektion-6','themes','Thema-1','sets',k])});return out}
function l6HasExplicitSetData(){const data=l6ReleaseData();return l6SetPaths('book').concat(l6SetPaths('extra')).some(p=>l6Val(data,p)!==undefined)}
function bookOn(){return l6Any(l6SetPaths('book'),true)}
function extraOn(){return l6Any(l6SetPaths('extra'),localStorage.getItem('SP_L6_T1_EXTRA_WEATHER')==='1')}
function setExtraWeather(v){localStorage.setItem('SP_L6_T1_EXTRA_WEATHER',v?'1':'0');Object.keys(localStorage).filter(k=>k.startsWith(CFG.key)).forEach(k=>localStorage.removeItem(k));location.reload()}
function words(){l6ApplyMedia();return (bookOn()?BASE_WORDS:[]).concat(extraOn()?EXTRA_WORDS:[])}
function wordItems(){return words()}
function soundWords(){return words().filter(w=>w.sound)}
function listenItems(){return L6T1_LISTENING.map(x=>({audio:l6Cdn(x.file),audioName:x.file,q:x.q,a:x.a,opts:x.opts}))}
function visual(w,small=false){const img=w.image||'';const alt=(w.full||w.word||'Wetterbild').replace(/"/g,'&quot;');const fallback=w.symbol||'•';return `<div class="weather-card ${small?'small-card':''}" aria-label="${alt}">${img?`<img class="weather-img" src="${img}" alt="${alt}" loading="lazy" onerror="this.remove();this.parentElement.textContent='${fallback}'">`:fallback}</div>`}
function l6CourseCodes(){const p=profile()||{};const raw=[p.courseDocId,p.kurs,p.kursnummer,p.courseCode,p.courseId,p.courseName,p.code,p.id,localStorage.getItem('SP_COURSE_CODE')].filter(Boolean);const out=[];raw.forEach(v=>{v=String(v).trim();[v,v.toUpperCase(),v.toLowerCase(),v.replace(/\s+/g,''),v.toLowerCase().replace(/\s+/g,'')].forEach(x=>{if(x&&!out.includes(x))out.push(x)})});return out}
function l6HasReleaseData(d){return !!(d&&typeof d==='object'&&(d.enabledModules||d.enabledLessons||d.enabledThemes||d.enabledTasks||d.enabledSets||d.releases||d.releaseMode||d.defaultLocked!==undefined))}
function l6RememberRelease(data){try{if(!l6HasReleaseData(data))return data;localStorage.setItem('SP_COURSE_RELEASES',JSON.stringify(data));localStorage.setItem('SP_RELEASE_SYNC_AT',String(Date.now()));const p=profile()||{};p.assignments=data;if(data.id||data.courseDocId)p.courseDocId=data.courseDocId||data.id;if(data.courseCode||data.kurs||data.kursnummer){p.courseCode=data.courseCode||data.kurs||data.kursnummer;p.kurs=p.kurs||p.courseCode;p.kursnummer=p.kursnummer||p.courseCode}localStorage.setItem('SP_USER_PROFILE',JSON.stringify(p));localStorage.setItem('SP_STUDENT_PROFILE',JSON.stringify(p))}catch(e){}return data}
async function l6ReadCourseReleaseFresh(){try{const mod=await import('/js/firebase.js?v=6');if(mod.authReady)await Promise.race([mod.authReady,new Promise(r=>setTimeout(r,3000))]);const codes=l6CourseCodes();for(const c of codes){try{const snap=await mod.getDoc(mod.doc(mod.db,'courses',String(c)));if(snap.exists()){const d={id:snap.id,...(snap.data()||{})};if(l6HasReleaseData(d))return d}}catch(e){}}for(const field of ['courseCode','kurs','kursnummer','courseDocId','courseId','id','name','courseName','code']){for(const c of codes){try{const q=mod.query(mod.collection(mod.db,'courses'),mod.where(field,'==',String(c)),mod.limit(1));const s=await mod.getDocs(q);if(s&&!s.empty){const doc=s.docs[0];const d={id:doc.id,...(doc.data()||{})};if(l6HasReleaseData(d))return d}}catch(e){}}}}catch(e){console.warn('L6T1 Freigabe konnte nicht frisch geladen werden',e)}return null}
async function l6ForceReleaseRefresh(){const data=await l6ReadCourseReleaseFresh();if(l6HasReleaseData(data)){l6RememberRelease(data);l6ApplyMedia();try{renderMenu()}catch(e){}try{const wordList=document.getElementById('wordList');if(wordList&&typeof renderOverview==='function')renderOverview(wordList)}catch(e){}}return data}
const L6_T1_TASK_ICONS={'karteikarten.html':'🃏','artikel.html':'🔤','hoeren-schreiben.html':'🎧','hoeren-bild.html':'🖼️','nomen-satz-a.html':'💬','nomen-satz-b.html':'🔁','geraeusche.html':'🔊','geraeusche-satz.html':'🌦️','wetter-saetze.html':'✍️','hoeren.html':'🎧','pruefung.html':'★'};
function l6StatusBox(){if(!isTeacher())return '';const b=bookOn(),e=extraOn(),explicit=l6HasExplicitSetData();return `<section class="card release-status-card"><h2>Wortschatz-Freigabe</h2><div class="release-pill-row"><span class="release-pill ${b?'is-on':'is-off'}">Im Buch: ${b?'freigegeben':'gesperrt'}</span><span class="release-pill ${e?'is-on':'is-off'}">Nicht im Buch: ${e?'freigegeben':'gesperrt'}</span></div><p class="small">${explicit?'Diese Einstellung kommt aus der Kursfreigabe im Lehrer-Dashboard.':'Noch keine explizite Kursfreigabe gefunden: Basiswortschatz bleibt sichtbar, Zusatzwörter bleiben gesperrt.'}</p><p class="small"><a href="/teacher/index.html">Im Lehrer-Dashboard ändern</a></p></section>`}
function renderOverview(target){target.innerHTML=['Im Buch','Nicht im Buch'].map(g=>{const visible=g==='Im Buch'?bookOn():extraOn();const list=(g==='Im Buch'?BASE_WORDS:EXTRA_WORDS);if(!visible&&!isTeacher())return '';if(!visible)return `<section class="type-block locked-set"><div class="type-title">${g} 🔒</div><p class="small">Diese Wortschatzliste ist für deinen Kurs noch nicht freigegeben.</p></section>`;return `<section class="type-block"><div class="type-title">${g}</div>${list.map(w=>`<div class="word-row"><div class="word-placeholder">${visual(w,true)}</div><div><b>${full(w)}</b><br><span class="small">${w.sentence}${w.altSentences?' / '+w.altSentences.join(' / '):''}</span><div class="small">Übersetzung (${LANGS[langKey()]||'EN'}): ${tr(w)}</div><span class="tag">${w.type}</span></div></div>`).join('')}</section>`}).join('')}
function renderTaskList(includeExam=true){const ts=taskTotals().filter(t=>includeExam||t[0]!=='pruefung.html');return `<div class="grid task-grid">${ts.map((t,i)=>{const p=pctFor(t[0],t[1]);const icon=L6_T1_TASK_ICONS[t[0]]||'▶';return `<a class="module task-card" href="${t[0]}"><div class="num">${i+1}. ${t[2]}</div><div class="icon big-icon">${icon}</div><p>${t[0]==='pruefung.html'?'Teste dein Wissen.':'Wetter und Sätze üben.'}</p><div class="progress"><div class="bar" style="width:${p}%"></div></div><div class="small">${p}%</div><div class="start">${p>=100?'Fertig':'Starten'}</div></a>`}).join('')}</div>`}
function renderMenu(){const box=document.getElementById('teacherBox');if(box){box.innerHTML=isTeacher()?l6StatusBox():''}const usable=words().length>0;taskGrid.innerHTML=usable?renderTaskList(true):'<section class="card"><h2>Keine Wörter freigegeben</h2><p class="small">Für dieses Thema ist noch keine Wortschatzliste freigeschaltet.</p></section>';const ts=usable?taskTotals():[],avg=ts.length?Math.round(ts.reduce((s,t)=>s+pctFor(t[0],t[1]),0)/ts.length)||0:0,done=ts.filter(t=>pctFor(t[0],t[1])>=100).length;totalCircle.textContent=avg+'%';totalBar.style.width=avg+'%';totalText.textContent=done+' / '+ts.length+' Aufgaben abgeschlossen'}
(function(){const css=document.createElement('style');css.textContent='.topbar,.hero:empty,#spHeader:empty{display:none!important;height:0!important;min-height:0!important;margin:0!important;padding:0!important;overflow:hidden!important}.task-grid .module{text-align:center}.task-grid .icon.big-icon{font-size:46px;line-height:1;margin:14px auto;color:var(--lesson-main-dark)}.task-grid .module p{min-height:44px}.release-status-card{margin:16px 0}.release-pill-row{display:flex;gap:10px;flex-wrap:wrap;margin:10px 0}.release-pill{display:inline-flex;border-radius:999px;padding:9px 14px;font-weight:900;border:2px solid var(--lesson-line);background:#fff}.release-pill.is-on{background:#dcfce7;border-color:#22c55e;color:#166534}.release-pill.is-off{background:#fee2e2;border-color:#ef4444;color:#991b1b}.locked-set{opacity:.72;border-style:dashed}.weather-card{overflow:hidden!important;padding:8px!important;background:#fff!important}.weather-img{width:100%!important;height:100%!important;object-fit:contain!important;display:block!important;border-radius:14px!important;background:#fff}.word-placeholder .weather-card{width:92px!important;height:72px!important;max-width:92px!important;margin:0!important;padding:5px!important}.choice .weather-img{pointer-events:none}.flip-wrap{perspective:1000px;max-width:360px;margin:16px auto}.flip-card{position:relative;width:100%;min-height:300px;transform-style:preserve-3d;transition:transform .55s ease;cursor:pointer}.flip-card.flipped{transform:rotateY(180deg)}.flip-face{position:absolute;inset:0;backface-visibility:hidden;border:2px solid var(--lesson-line);border-radius:24px;background:#fff;padding:18px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px}.flip-back{transform:rotateY(180deg);background:var(--lesson-soft)}.flip-word{font-size:30px;font-weight:900;color:var(--lesson-main-dark);text-align:center}.flip-plural{font-size:18px;text-align:center}';document.head.appendChild(css)})();
try{setTimeout(()=>{l6ForceReleaseRefresh()},300);setTimeout(()=>{l6ForceReleaseRefresh()},1600)}catch(e){}