(function(){
'use strict';
const E=window.VerbGroupsEngine,app=document.querySelector('#app'),topbar=document.querySelector('#topbar');
let dashboard='/student-dashboard/index.html',logoutFn=()=>{},locked=false,currentQuestion=null,rec=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const route=()=>{const q=new URLSearchParams(location.search),group=Math.max(0,Math.min(E.GROUPS.length,Number(q.get('group'))||0)),task=q.get('task')||'';return{group,task:E.TASKS.some(x=>x[0]===task)?task:''}};
const href=(group=0,task='')=>{const q=new URLSearchParams();if(group)q.set('group',group);if(task)q.set('task',task);return'/verben/'+(q.toString()?'?'+q.toString():'')};
const go=({group=0,task=''})=>{history.pushState(null,'',href(group,task));render()};
function image(v,compact=false){return`<div class="verb-image ${compact?'compact':''}"><img src="${E.imageUrl(v)}" alt="Bild zu ${esc(v)}" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="image-fallback" hidden><strong>${esc(v)}</strong><span>Bild nicht verfügbar</span></div></div>`}
function speak(text,slow=false){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='de-DE';u.rate=slow?.55:.92;speechSynthesis.speak(u)}
function stopMic(){if(rec)try{rec.abort()}catch{}rec=null}
function header(r){const p=window.VerbGroupsProfile||{},name=[p.vorname||p.firstName,p.nachname||p.lastName].filter(Boolean).join(' ')||(E.isPreview()?'Lehrer-Vorschau':'Schüler');topbar.innerHTML=`<div class="topbar-main"><a class="brand" href="/index.html"><img src="/assets/logo/sprachpilot-logo.png" alt="SprachPilot"><div><h1>Verben</h1><p>${E.VERBS.length} Verben · ${E.GROUPS.length} frei wählbare Gruppen</p></div></a><div class="account-actions"><span class="account-pill">${esc(name)}</span><a class="btn secondary" href="${esc(dashboard)}">Dashboard</a><button class="btn secondary" data-action="logout">Abmelden</button></div></div><nav class="topnav"><a class="btn secondary" href="/index.html">← Startseite</a><button class="btn secondary" data-action="groups">Gruppen</button>${r.group?`<button class="btn secondary" data-action="group" data-group="${r.group}">Gruppe ${r.group}</button><button class="btn danger-btn" data-action="reset-group" data-group="${r.group}">Fortschritt der Gruppe löschen</button>`:''}</nav>`}
const previewNote=()=>E.isPreview()?'<div class="preview-note">Lehrer-Vorschau: Alle Gruppen sind offen. Fortschritt und Punkte werden nicht gespeichert.</div>':'';
function scoreCard(groupId=0){
 if(E.isPreview())return'<section class="card score-card"><h2>Punkte</h2><p>Lehrer-Vorschau: Es werden keine Schülerpunkte gespeichert.</p></section>';
 if(!groupId)return`<section class="card score-card"><div><p class="eyebrow">Punktesystem</p><h2>Alle Gruppen</h2><p>Jede Gruppe besitzt drei eigene Wiederholungsrunden.</p></div><div class="score-total">${E.totalPoints()}<span>Punkte gesamt</span></div></section>`;
 const gs=E.groupState(groupId),run=E.currentRun(groupId),taskSum=Object.values(run.awards.tasks||{}).reduce((s,n)=>s+(Number(n)||0),0);
 return`<section class="card score-card"><div><p class="eyebrow">Gruppe ${groupId}</p><h2>Punkterunde ${gs.currentRun} von 3</h2><p>Aufgaben: ${taskSum} Punkte · Prüfung: ${Number(run.awards.examPoints)||0} Punkte</p><div class="score-rules"><span>Aufgabe: ${E.taskPoints(gs.currentRun)} P.</span><span>Prüfung: bis ${E.examMax(gs.currentRun)} P.</span></div>${E.canRepeat(groupId)?`<button class="btn" data-action="next-run" data-group="${groupId}">Runde ${gs.currentRun+1} starten</button>`:''}</div><div class="score-total">${E.groupPoints(groupId)}<span>Punkte der Gruppe</span></div></section>`}
function renderHome(){
 const cards=E.GROUPS.map(g=>{const gs=E.groupState(g.id),run=E.currentRun(g.id),done=E.LEARN.filter(t=>E.taskDone(g.id,t)).length,exam=Number(run.exam.bestPercent)||0,progress=Math.round((done+(exam>=100?1:0))/(E.LEARN.length+1)*100);return`<button class="group-card" data-action="group" data-group="${g.id}"><div class="group-head"><span>Gruppe ${g.id}</span><span>Runde ${gs.currentRun}/3</span></div><p>${g.verbs.join(', ')}</p><div class="progress"><div class="bar" style="width:${progress}%"></div></div><div class="group-foot"><span>${done}/${E.LEARN.length} Aufgaben · Prüfung ${exam}%</span><strong>${E.groupPoints(g.id)} P.</strong></div></button>`}).join('');
 app.innerHTML=`${previewNote()}${scoreCard()}<section class="card progress-card"><div class="circle">${E.GROUPS.length}</div><div><h2>Gruppe auswählen</h2><p>Jede Gruppe ist sofort verfügbar. Die Gruppen 1 bis 12 enthalten je 20 Verben. Gruppe 13 enthält ${E.GROUPS.at(-1)?.verbs.length||0} Verben.</p><p>Falsche Antworten kommen am Ende erneut. Nach 100% in allen Aufgaben und der Prüfung kannst du dieselbe Gruppe in Runde 2 und Runde 3 wiederholen.</p></div></section><section class="groups-grid">${cards}</section>`}
function taskCards(groupId){
 const run=E.currentRun(groupId);
 return E.TASKS.map((t,i)=>{const exam=t[0]==='exam',open=!exam||E.learnDone(groupId),p=exam?Number(run.exam.bestPercent)||0:E.taskPercent(groupId,t[0]);return`<button class="task-card ${p>=100?'done-card':''} ${!open?'locked-task':''}" data-action="task" data-group="${groupId}" data-task="${t[0]}" ${open?'':'disabled'}><span class="task-number">${i+1}</span><span class="task-icon">${open?t[1]:'🔒'}</span><span class="task-title">${t[2]}</span><span class="task-desc">${exam?'Prüfung mit 20 gemischten Fragen.':'Alle Verben dieser Gruppe.'}</span><div class="task-mini-progress"><span style="width:${p}%"></span></div><span class="task-status">${open?(p>=100?'100% abgeschlossen':p?`${p}% gespeichert`:'Noch offen'):'Erst alle Lernaufgaben abschließen'}</span></button>`}).join('')}
function renderGroup(groupId){
 const group=E.GROUPS[groupId-1],run=E.currentRun(groupId),done=E.LEARN.filter(t=>E.taskDone(groupId,t)).length,p=Math.round((done+(run.exam.bestPercent>=100?1:0))/(E.LEARN.length+1)*100);E.setRunKey(groupId);
 app.innerHTML=`${previewNote()}${scoreCard(groupId)}<section class="card progress-card"><div class="circle">${p}%</div><div><h2>Gruppe ${groupId}</h2><p><strong>${group.verbs.length} Verben:</strong> ${group.verbs.join(', ')}</p><div class="progress"><div class="bar" style="width:${p}%"></div></div><p>${done}/${E.LEARN.length} Lernaufgaben · Prüfung: ${run.exam.bestPercent||0}%</p></div></section><section class="card"><h2>Aufgaben</h2><div class="task-grid">${taskCards(groupId)}</div></section>`}
function taskProgressHtml(groupId,task){const st=E.taskState(groupId,task),p=E.taskPercent(groupId,task);return`<div class="task-progress-row"><span>${st.done.length} richtig · ${st.total-st.done.length} übrig</span><strong>${p}%</strong></div><div class="mini-progress"><div style="width:${p}%"></div></div>`}
function feedback(text,ok=false){const el=document.querySelector('#feedback');if(el){el.className='feedback '+(ok?'ok':'no');el.innerHTML=text}}
function questionBody(q){
 const media=q.image?image(q.image):q.audio?`<div class="listen-box"><button class="btn" data-action="audio" data-text="${esc(q.audio)}">🔊 Hören</button><button class="btn secondary" data-action="audio-slow" data-text="${esc(q.audio)}">🐢 Langsam</button></div>`:'';
 let answer='';
 if(q.kind==='mc')answer=`<div class="option-grid">${q.options.map(o=>`<button class="option" data-action="answer" data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div>`;
 if(q.kind==='images')answer=`<div class="image-choice-grid">${q.options.map(o=>`<button class="image-option" data-action="answer" data-answer="${esc(o)}">${image(o,true)}<span>${esc(o)}</span></button>`).join('')}</div>`;
 if(q.kind==='input')answer=`<div class="answer-form"><div class="answer-row"><input id="answerInput" autocomplete="off" placeholder="${esc(q.placeholder||'Antwort schreiben')}"><button class="btn" data-action="check-input">Kontrollieren</button></div></div>`;
 if(q.kind==='speech')answer=`<div class="speech-box"><div class="actions"><button class="btn" data-action="mic">🎤 Sprechen</button><button class="btn secondary" data-action="write-fallback">✍️ Stattdessen schreiben</button></div><div id="micStatus" class="small"></div><div id="writeFallback" class="answer-form hidden"><div class="answer-row"><input id="answerInput" autocomplete="off" placeholder="Verbform schreiben"><button class="btn" data-action="check-input">Kontrollieren</button></div></div></div>`;
 return`${media}<div class="question">${esc(q.prompt)}</div>${q.support?`<div class="question-support">${esc(q.support)}</div>`:''}${answer}<div id="feedback"></div>`}
function renderCards(groupId){
 const task='cards',v=E.nextVerb(groupId,task);if(!v)return finishTask(groupId,task);currentQuestion={kind:'card',answer:v};
 app.innerHTML=`<section class="card task-page"><div class="task-page-head"><div><p class="eyebrow">Gruppe ${groupId}</p><h2>Karteikarten</h2></div><button class="btn secondary" data-action="group" data-group="${groupId}">Zur Aufgabenübersicht</button></div>${taskProgressHtml(groupId,task)}<div class="flashcard">${image(v)}<div class="flash-verb">${esc(v)}</div><div class="change-badge">${esc(E.typeOf(v))}</div><div class="forms-grid">${E.PERSONS.map((person,i)=>`<div><span>${person.label}</span><strong>${esc(E.displayForm(v,i))}</strong></div>`).join('')}</div><div class="actions"><button class="btn secondary" data-action="audio" data-text="${esc(v)}">🔊 Verb hören</button><button class="btn" data-action="card-next">Gelernt · weiter</button></div></div></section>`}
function renderTask(groupId,task){
 if(task==='exam')return renderExam(groupId);
 if(E.taskDone(groupId,task))return finishTask(groupId,task);
 if(task==='cards')return renderCards(groupId);
 const v=E.nextVerb(groupId,task);if(!v)return finishTask(groupId,task);currentQuestion=E.question(groupId,task,v);
 app.innerHTML=`<section class="card task-page"><div class="task-page-head"><div><p class="eyebrow">Gruppe ${groupId}</p><h2>${esc(E.TASK_TITLE[task])}</h2></div><button class="btn secondary" data-action="group" data-group="${groupId}">Zur Aufgabenübersicht</button></div>${taskProgressHtml(groupId,task)}<div class="question-card">${questionBody(currentQuestion)}</div></section>`;setTimeout(()=>document.querySelector('#answerInput')?.focus(),60)}
function finishTask(groupId,task){const gs=E.groupState(groupId),points=Number(E.currentRun(groupId).awards.tasks[task])||0,next=E.LEARN[E.LEARN.indexOf(task)+1]||'exam';app.innerHTML=`<section class="card"><div class="finish-box"><div class="finish-icon">✓</div><h2>${esc(E.TASK_TITLE[task])} geschafft</h2><p>100% erreicht · Punkterunde ${gs.currentRun}: ${points} Punkte.</p><div class="actions"><button class="btn secondary" data-action="reset-task" data-group="${groupId}" data-task="${task}">Nochmal üben</button><button class="btn" data-action="task" data-group="${groupId}" data-task="${next}">Weiter</button><button class="btn secondary" data-action="group" data-group="${groupId}">Zur Gruppe</button></div></div></section>`}
function checkTaskAnswer(value){const r=route(),q=currentQuestion;if(!r.group||!r.task||!q)return;if(E.isCorrect(value,q)){feedback('Richtig.',true);E.markRight(r.group,r.task);setTimeout(()=>renderTask(r.group,r.task),550);return}const tries=E.markWrong(r.group,r.task);feedback(tries>=3?`Lösung: <strong>${esc(q.writeAnswer||q.answer)}</strong>`:tries===2?'Noch nicht richtig. Prüfe die Verbform.':'Noch nicht richtig.')}
function openWriteFallback(message='Bitte schreibe die Antwort.'){const box=document.querySelector('#writeFallback'),status=document.querySelector('#micStatus');if(box)box.classList.remove('hidden');if(status)status.textContent=message;setTimeout(()=>document.querySelector('#answerInput')?.focus(),30)}
function startMic(){
 const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){openWriteFallback('Mikrofon wird hier nicht unterstützt. Bitte schreibe.');return}
 try{stopMic();rec=new SR();rec.lang='de-DE';rec.interimResults=false;rec.continuous=false;const status=document.querySelector('#micStatus');if(status)status.textContent='Ich höre zu …';rec.onresult=e=>{const text=e.results?.[0]?.[0]?.transcript||'';if(!text){openWriteFallback('Nichts erkannt. Bitte schreibe.');return}if(status)status.textContent='Gehört: '+text;checkTaskAnswer(text)};rec.onerror=()=>openWriteFallback('Mikrofon hat nicht funktioniert. Bitte schreibe.');rec.onnomatch=()=>openWriteFallback('Nichts erkannt. Bitte schreibe.');rec.onend=()=>{rec=null};rec.start()}catch{openWriteFallback('Mikrofon konnte nicht gestartet werden. Bitte schreibe.')}}
function renderExam(groupId){
 if(!E.learnDone(groupId)){app.innerHTML=`<section class="card locked-card"><h2>Prüfung gesperrt</h2><p>Schließe zuerst alle zwölf Lernaufgaben der Gruppe mit 100% ab.</p><button class="btn" data-action="group" data-group="${groupId}">Zur Gruppe</button></section>`;return}
 const run=E.currentRun(groupId),ex=run.exam;
 if(!ex.session){app.innerHTML=`<section class="card"><div class="finish-box"><div class="finish-icon">★</div><h2>Gruppenprüfung</h2><p>20 gemischte Fragen aus Gruppe ${groupId}. Bester Stand: ${ex.bestPercent||0}%.</p><button class="btn" data-action="start-exam" data-group="${groupId}">Prüfung starten</button><button class="btn secondary" data-action="group" data-group="${groupId}">Zur Gruppe</button></div></section>`;return}
 if(ex.session.index>=ex.session.items.length)return finishExam(groupId);
 const item=ex.session.items[ex.session.index];currentQuestion=E.question(groupId,item.task,item.v,item.person);const p=Math.round(ex.session.index/ex.session.items.length*100);
 app.innerHTML=`<section class="card task-page"><div class="task-page-head"><div><p class="eyebrow">Gruppe ${groupId}</p><h2>Gruppenprüfung</h2></div><button class="btn secondary" data-action="group" data-group="${groupId}">Abbrechen</button></div><div class="task-progress-row"><span>Aufgabe ${ex.session.index+1}/${ex.session.items.length}</span><strong>${p}%</strong></div><div class="mini-progress"><div style="width:${p}%"></div></div><div class="question-card">${questionBody(currentQuestion)}</div></section>`;setTimeout(()=>document.querySelector('#answerInput')?.focus(),60)}
function startExam(groupId){E.currentRun(groupId).exam.session={items:E.examItems(groupId),index:0,correct:0};E.save();renderExam(groupId)}
function checkExamAnswer(value){const r=route(),ex=E.currentRun(r.group).exam,q=currentQuestion;if(!ex.session||!q)return;const good=E.isCorrect(value,q);if(good)ex.session.correct++;feedback(good?'Richtig.':`Richtige Lösung: <strong>${esc(q.writeAnswer||q.answer)}</strong>`,good);ex.session.index++;E.save();setTimeout(()=>renderExam(r.group),650)}
function finishExam(groupId){const run=E.currentRun(groupId),session=run.exam.session,total=session?.items?.length||1,correct=session?.correct||0,percent=Math.round(correct/total*100),stars=percent>=100?3:percent>=70?2:percent>=50?1:0;run.exam.session=null;E.awardExam(groupId,percent);app.innerHTML=`<section class="card"><div class="finish-box"><div class="finish-icon">✓</div><h2>Prüfung fertig</h2><div class="exam-percent">${percent}%</div><div class="stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>${correct}/${total} richtig · Bester Stand: ${E.currentRun(groupId).exam.bestPercent}%</p><p>Prüfungspunkte dieser Runde: ${E.currentRun(groupId).awards.examPoints}/${E.examMax(E.groupState(groupId).currentRun)}</p><div class="actions"><button class="btn" data-action="start-exam" data-group="${groupId}">Neue Prüfung</button><button class="btn secondary" data-action="group" data-group="${groupId}">Zur Gruppe</button>${E.canRepeat(groupId)?`<button class="btn" data-action="next-run" data-group="${groupId}">Runde ${E.groupState(groupId).currentRun+1} starten</button>`:''}</div></div></section>`}
function answerFromInput(){const value=document.querySelector('#answerInput')?.value||'',r=route();r.task==='exam'?checkExamAnswer(value):checkTaskAnswer(value)}
function render(){stopMic();const r=route();header(r);if(locked){app.innerHTML='<section class="card locked-card"><h2>Verben sind noch nicht freigeschaltet</h2><p>Die Lehrkraft muss das Modul für deinen Kurs freigeben.</p><a class="btn" href="/index.html">Zur Startseite</a></section>';return}if(r.group&&r.task)return renderTask(r.group,r.task);if(r.group)return renderGroup(r.group);renderHome()}
function install(options={}){dashboard=options.dashboard||dashboard;logoutFn=options.logout||logoutFn;locked=!!options.locked;E.load();render()}
document.addEventListener('click',ev=>{const b=ev.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,g=Number(b.dataset.group)||0,t=b.dataset.task||'';if(a==='logout')return logoutFn();if(a==='groups')return go({});if(a==='group')return go({group:g});if(a==='task')return go({group:g,task:t});if(a==='reset-group'){if(E.isPreview())return alert('In der Lehrer-Vorschau wird nichts gespeichert.');if(confirm(`Sichtbaren Fortschritt von Gruppe ${g} löschen? Bereits verdiente Punkte bleiben erhalten.`)){E.resetGroup(g);render()}return}if(a==='next-run'){const next=E.groupState(g).currentRun+1;if(confirm(`Runde ${next} für Gruppe ${g} starten? Es gibt ${next===2?'doppelte':'dreifache'} Punkte.`)&&E.startNextRun(g))go({group:g});return}if(a==='reset-task'){E.resetTask(g,t);render();return}if(a==='audio')return speak(b.dataset.text||'');if(a==='audio-slow')return speak(b.dataset.text||'',true);if(a==='card-next'){const r=route();E.markRight(r.group,'cards');return renderCards(r.group)}if(a==='answer'){const r=route();return r.task==='exam'?checkExamAnswer(b.dataset.answer||''):checkTaskAnswer(b.dataset.answer||'')}if(a==='check-input')return answerFromInput();if(a==='mic')return startMic();if(a==='write-fallback')return openWriteFallback();if(a==='start-exam'){go({group:g,task:'exam'});return startExam(g)}});
document.addEventListener('keydown',ev=>{if(ev.key==='Enter'&&ev.target?.id==='answerInput'){ev.preventDefault();answerFromInput()}});
window.addEventListener('popstate',render);
window.VerbGroupsUI={install,render};
})();