(function(){
'use strict';
if(window.__SP_L4T5_UI_V1)return;window.__SP_L4T5_UI_V1=true;
const D=()=>window.L4T5_DATA||{tasks:[],topicId:'wortschatz-a1-lektion-4-thema-5'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').normalize('NFC').trim().toLowerCase().replace(/[.,!?;:“”"'`´()]/g,'').replace(/\s+/g,' ');
const same=(a,b)=>(Array.isArray(b)?b:[b]).some(x=>norm(x)===norm(a));
function profile(){try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||localStorage.getItem('SP_STUDENT_PROFILE')||'{}')}catch(e){return{}}}
function preview(){const role=String(localStorage.getItem('SP_LOGIN_ROLE')||localStorage.getItem('SP_ACTIVE_ROLE')||'').toLowerCase();return ['teacher','lehrer','admin','owner'].includes(role)||!!sessionStorage.getItem('SP_TEACHER_PREVIEW')}
function pid(){const p=profile();return String(p.canonicalStudentId||p.docId||p.studentId||p.authUid||p.uid||p.email||'student').toLowerCase().replace(/[^a-z0-9]+/g,'-')}
function key(task){return `${preview()?'SP_L4T5_PREVIEW':'SP_L4T5'}_${pid()}_${task.id}`}
function blank(task){return{done:[],tries:{},answers:{},firstSeen:[],firstCorrect:0,updatedAt:new Date().toISOString()}}
function load(task){try{const x=JSON.parse((preview()?sessionStorage:localStorage).getItem(key(task))||'null')||blank(task);x.done=[...new Set((x.done||[]).map(Number))].filter(i=>i>=0&&i<task.items.length);x.tries=x.tries||{};x.answers=x.answers||{};x.firstSeen=x.firstSeen||[];return x}catch(e){return blank(task)}}
function save(task,state){state.updatedAt=new Date().toISOString();(preview()?sessionStorage:localStorage).setItem(key(task),JSON.stringify(state));return state}
function pct(task){return task.items.length?Math.min(100,Math.round(load(task).done.length/task.items.length*100)):0}
function taskById(id){return D().tasks.find(t=>t.id===id)}
function practice(){return D().tasks.filter(t=>!t.exam)}
function allDone(){return preview()||practice().every(t=>pct(t)>=100)}
function api(){return window.SPProgress}
function queueProgress(method,payload){if(preview())return;const A=api();if(A?.[method]){A[method](payload).catch?.(()=>{});return}(window.SP_PROGRESS_QUEUE||(window.SP_PROGRESS_QUEUE=[])).push({method,payload})}
function taskPayload(task,state){const p=task.items.length?Math.round(state.done.length/task.items.length*100):0;return{module:'wortschatz',moduleTitle:'Wortschatz',level:'A1',lesson:4,theme:5,topicId:D().topicId,title:'A1 Lektion 4 · Thema 5 · Am Telefon',file:task.id,taskKey:task.id,taskTitle:task.title,percent:p,completed:p>=100,total:task.items.length,done:state.done.length}}
function syncTask(task,state){if(task.exam)return;queueProgress('recordTaskProgress',taskPayload(task,state))}
async function hydrate(){if(preview())return;let n=0;while(!api()?.loadCurrentStudentProgress&&n++<80)await new Promise(r=>setTimeout(r,50));try{const p=await api()?.loadCurrentStudentProgress?.(),topic=p?.wortschatz?.[D().topicId];if(!topic)return;for(const task of practice()){const cloud=topic.tasks?.[task.id];if(!cloud)continue;const s=load(task),done=Math.min(task.items.length,Number(cloud.done)||Math.round((Number(cloud.percent)||0)/100*task.items.length));if(cloud.completed||Number(cloud.percent)>=100){s.done=[...Array(task.items.length).keys()]}else for(let i=0;i<done;i++)if(!s.done.includes(i))s.done.push(i);save(task,s)}window.L4T5Run=Number(topic.currentRun||topic.current?.run||1)||1}catch(e){}}
function mark(task,state,index,correct,answer){if(!state.firstSeen.includes(index)){state.firstSeen.push(index);if(correct)state.firstCorrect++}state.answers[index]=answer;if(correct){if(!state.done.includes(index))state.done.push(index);delete state.tries[index]}else state.tries[index]=Number(state.tries[index]||0)+1;save(task,state);syncTask(task,state);return Number(state.tries[index]||0)}
function feedback(type,text){const b=document.getElementById('feedback');if(b)b.innerHTML=`<div class="l4t5-feedback ${type}">${esc(text)}</div>`}
function tts(text){if(!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text||''));u.lang='de-DE';u.rate=.84;speechSynthesis.speak(u)}catch(e){}}
function speech(target){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){feedback('warn','Das Mikrofon wird auf diesem Gerät nicht unterstützt. Bitte schreibe.');target?.focus();return}const r=new R();r.lang='de-DE';r.interimResults=false;r.onresult=e=>{const v=e.results?.[0]?.[0]?.transcript||'';if(target){target.value=v;target.dispatchEvent(new Event('input',{bubbles:true}))}};r.onerror=()=>feedback('warn','Das Mikrofon hat nicht funktioniert. Bitte schreibe.');try{r.start()}catch(e){}}
function nextIndex(task,state){for(let i=0;i<task.items.length;i++)if(!state.done.includes(i))return i;return null}
function head(task,state){const p=task.items.length?Math.round(state.done.length/task.items.length*100):0;return `<section class="l4t5-card l4t5-head"><span>Aufgabe</span><h1>${task.icon||'✅'} ${esc(task.title)}</h1><p>${esc(task.instruction||'')}</p><div class="l4t5-progress"><i style="width:${p}%"></i></div><small>${state.done.length} von ${task.items.length} fertig · ${p}%</small></section>`}
function finish(task,root){if(task.exam){const s=load(task),percent=Math.round((s.firstCorrect||0)/Math.max(1,task.items.length)*100);queueProgress('recordExamResult',{module:'wortschatz',moduleTitle:'Wortschatz',level:'A1',lesson:4,theme:5,topicId:D().topicId,title:'A1 Lektion 4 · Thema 5 · Am Telefon',percent});root.innerHTML=`<div class="l4t5-wrap"><section class="l4t5-card l4t5-finish"><div class="big">⭐ ${percent}%</div><h2>Prüfung abgeschlossen</h2><p>Dein Ergebnis des ersten Lösungsversuchs wurde gespeichert.</p><a class="l4t5-btn primary" href="index.html">Zur Themenübersicht</a></section></div>`;return}root.innerHTML=`<div class="l4t5-wrap"><section class="l4t5-card l4t5-finish"><div class="big">✓</div><h2>Aufgabe abgeschlossen</h2><p>Du hast diese Aufgabe zu 100 % bearbeitet.</p><a class="l4t5-btn primary" href="index.html">Zur Themenübersicht</a></section></div>`}
function renderCards(task,root,state,index){const x=task.items[index];root.innerHTML=`<div class="l4t5-wrap">${head(task,state)}<section class="l4t5-card"><div class="l4t5-flash" id="flash"><div class="front"><span>🃏 Karte ${index+1}</span><strong>${esc(x.term)}</strong><button class="l4t5-btn" id="hear" type="button">🔊 Anhören</button></div><div class="back" hidden><strong>${esc(x.term)}</strong><p>${esc(x.detail||'')}</p>${x.plural?`<p><b>Plural:</b> ${esc(x.plural)}</p>`:''}${x.example?`<p><b>Beispiel:</b> ${esc(x.example)}</p>`:''}<button class="l4t5-btn primary" id="know" type="button">Karte gelernt</button></div></div><div id="feedback"></div></section></div>`;document.getElementById('hear').onclick=e=>{e.stopPropagation();tts(x.term)};document.getElementById('flash').onclick=()=>{document.querySelector('.front').hidden=true;document.querySelector('.back').hidden=false};document.getElementById('know').onclick=e=>{e.stopPropagation();mark(task,state,index,true,x.term);setTimeout(()=>renderTask(task,root),150)}}
function renderChoice(task,root,state,index,item){const options=[...(item.options||[])].sort(()=>Math.random()-.5);root.innerHTML=`<div class="l4t5-wrap">${head(task,state)}<section class="l4t5-card">${item.context?`<div class="l4t5-context">${esc(item.context).replace(/\n/g,'<br>')}</div>`:''}${item.audio?`<button class="l4t5-btn listen" id="listen">🔊 Hör zu</button>`:''}<h2>${esc(item.prompt)}</h2><div class="l4t5-options">${options.map(o=>`<button type="button" data-a="${esc(o)}">${esc(o)}</button>`).join('')}</div><div id="feedback"></div></section></div>`;if(item.audio)document.getElementById('listen').onclick=()=>tts(item.audio);root.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{const value=b.dataset.a,ok=same(value,item.answer);if(ok){mark(task,state,index,true,value);feedback('good','Richtig!');setTimeout(()=>renderTask(task,root),450)}else{const n=mark(task,state,index,false,value);feedback(n===1?'bad':'warn',n===1?'Noch nicht richtig. Lies oder höre noch einmal.':n===2?(item.hint||'Achte genau auf die Situation.'):`Richtig ist: ${Array.isArray(item.answer)?item.answer[0]:item.answer}. Wähle die richtige Antwort jetzt selbst.`)}})}
function renderInput(task,root,state,index,item){root.innerHTML=`<div class="l4t5-wrap">${head(task,state)}<section class="l4t5-card">${item.context?`<div class="l4t5-context">${esc(item.context)}</div>`:''}<h2>${esc(item.prompt)}</h2><div class="l4t5-answer"><input id="answer" autocomplete="off"><button class="l4t5-btn primary" id="check">Prüfen</button></div><div id="feedback"></div></section></div>`;const run=()=>{const v=document.getElementById('answer').value.trim();if(!v)return;if(same(v,item.answer)){mark(task,state,index,true,v);feedback('good','Richtig!');setTimeout(()=>renderTask(task,root),450)}else{const n=mark(task,state,index,false,v);feedback(n===1?'bad':'warn',n===1?'Noch nicht richtig. Versuch es noch einmal.':n===2?(item.hint||'Achte auf das passende Wort.'):`Lösung: ${(Array.isArray(item.answer)?item.answer:[item.answer])[0]}. Gib sie jetzt selbst ein.`)}};document.getElementById('check').onclick=run;document.getElementById('answer').onkeydown=e=>{if(e.key==='Enter')run()}}
function renderOrder(task,root,state,index,item){const tokens=[...(item.tokens||[])].sort(()=>Math.random()-.5);let built=[];root.innerHTML=`<div class="l4t5-wrap">${head(task,state)}<section class="l4t5-card">${item.context?`<div class="l4t5-context">${esc(item.context)}</div>`:''}<h2>${esc(item.prompt)}</h2><div class="l4t5-built" id="built"></div><div class="l4t5-tokens">${tokens.map((t,i)=>`<button type="button" data-i="${i}" data-t="${esc(t)}">${esc(t)}</button>`).join('')}</div><div class="l4t5-actions"><button class="l4t5-btn primary" id="check">Prüfen</button><button class="l4t5-btn" id="undo">Zurück</button><button class="l4t5-btn" id="clear">Neu</button></div><div id="feedback"></div></section></div>`;root.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{if(b.disabled)return;b.disabled=true;built.push(b);document.getElementById('built').textContent=built.map(x=>x.dataset.t).join(' ')});document.getElementById('undo').onclick=()=>{const b=built.pop();if(b)b.disabled=false;document.getElementById('built').textContent=built.map(x=>x.dataset.t).join(' ')};document.getElementById('clear').onclick=()=>renderOrder(task,root,state,index,item);document.getElementById('check').onclick=()=>{const v=built.map(x=>x.dataset.t).join(' ');if(same(v,item.answer)){mark(task,state,index,true,v);feedback('good','Richtig!');setTimeout(()=>renderTask(task,root),450)}else{const n=mark(task,state,index,false,v);feedback(n===1?'bad':'warn',n===1?'Die Reihenfolge stimmt noch nicht.':'Achte auf Verbposition und Frageform.')}}}
function renderFree(task,root,state,index,item){const old=state.answers[index]||item.starter||'';root.innerHTML=`<div class="l4t5-wrap">${head(task,state)}<section class="l4t5-card">${item.context?`<div class="l4t5-context">${esc(item.context)}</div>`:''}<h2>${esc(item.prompt)}</h2><textarea id="free" rows="7">${esc(old)}</textarea><p class="small">Mindestens ${item.min||3} vollständige Sätze oder Fragen. Du kannst sprechen oder schreiben.</p><div class="l4t5-actions"><button class="l4t5-btn" id="mic">🎤 Sprechen</button><button class="l4t5-btn primary" id="save">Speichern und fertig</button></div><div id="feedback"></div></section></div>`;const box=document.getElementById('free');box.oninput=()=>{state.answers[index]=box.value;save(task,state)};document.getElementById('mic').onclick=()=>speech(box);document.getElementById('save').onclick=()=>{const v=box.value.trim(),sent=v.split(/[.!?]+/).map(x=>x.trim()).filter(Boolean);if(sent.length<(item.min||3)){feedback('bad',`Bitte mindestens ${item.min||3} vollständige Sätze oder Fragen.`);return}mark(task,state,index,true,v);renderTask(task,root)}}
function renderTask(task,root=document.getElementById('app')){let state=load(task),index=nextIndex(task,state);if(index==null)return finish(task,root);const item=task.items[index];if(task.kind==='cards')return renderCards(task,root,state,index);if(item.type==='input')return renderInput(task,root,state,index,item);if(item.type==='order')return renderOrder(task,root,state,index,item);if(item.type==='free')return renderFree(task,root,state,index,item);return renderChoice(task,root,state,index,item)}
function card(task,n){const p=pct(task),locked=task.exam&&!allDone();if(locked)return `<div class="l4t5-task locked"><b>${n}. ${esc(task.title)}</b><div class="icon">⭐</div><p>Erst alle Aufgaben auf 100 % bearbeiten.</p><small>gesperrt</small></div>`;return `<a class="l4t5-task" href="task.html?task=${encodeURIComponent(task.id)}"><b>${n}. ${esc(task.title)}</b><div class="icon">${task.icon||'✅'}</div><p>${esc(task.instruction||'')}</p><div class="l4t5-progress"><i style="width:${p}%"></i></div><small>${p>=100?'100% · Fertig':p+'% · Starten'}</small></a>`}
async function renderTheme(){await hydrate();renderSprachPilotHeader?.({title:'Am Telefon',subtitle:'A1 Lektion 4 · Thema 5',backHref:'../index.html',overviewHref:'uebersicht.html'});const root=document.getElementById('app');if(!root)return;const ps=practice(),avg=Math.round(ps.reduce((s,t)=>s+pct(t),0)/Math.max(1,ps.length)),run=window.L4T5Run||1;root.innerHTML=`<div class="l4t5-wrap">${preview()?'<div class="l4t5-note">Lehrer-Vorschau: Es werden keine Teilnehmerfortschritte oder Punkte gespeichert.</div>':''}<section class="l4t5-card l4t5-progress-card"><div class="circle">${avg}%</div><div><h2>Dein Fortschritt</h2><p>${ps.filter(t=>pct(t)>=100).length} / ${ps.length} Aufgaben abgeschlossen · ${run===1?'Versuch 1':`Wiederholung ${run}`} von 3</p><div class="l4t5-progress"><i style="width:${avg}%"></i></div><button class="l4t5-btn danger" id="resetTheme" type="button">Thema wiederholen</button></div></section><section class="l4t5-grid">${D().tasks.map((t,i)=>card(t,i+1)).join('')}</section></div>`;document.getElementById('resetTheme').onclick=async()=>{if(preview()){alert('In der Lehrer-Vorschau wird nichts gespeichert.');return}if(!confirm('Thema wirklich für den nächsten Durchlauf zurücksetzen? Bereits verdiente Punkte bleiben erhalten.'))return;for(const t of D().tasks)localStorage.removeItem(key(t));await api()?.recordThemeReset?.({module:'wortschatz',level:'A1',lesson:4,theme:5,topicId:D().topicId,title:'A1 Lektion 4 · Thema 5 · Am Telefon'});location.reload()}}
async function taskPage(){await hydrate();const id=new URLSearchParams(location.search).get('task'),task=taskById(id);if(!task){location.href='index.html';return}if(task.exam&&!allDone()){location.href='index.html';return}renderSprachPilotHeader?.({title:task.title,subtitle:'A1 Lektion 4 · Thema 5',backHref:'index.html',overviewHref:'uebersicht.html'});renderTask(task)}
function overview(){renderSprachPilotHeader?.({title:'Wortschatzübersicht',subtitle:'A1 Lektion 4 · Thema 5',backHref:'index.html'});const root=document.getElementById('app');root.innerHTML=`<div class="l4t5-wrap"><section class="l4t5-card"><h1>Wörter und Redemittel</h1><p>Höre die Wörter und lies die Beispielsätze.</p><div class="l4t5-vocab">${D().vocab.map((x,i)=>`<article><div><b>${esc(x.term)}</b>${x.plural?`<span>${esc(x.plural)}</span>`:''}<p>${esc(x.detail)}</p><small>${esc(x.example)}</small></div><button class="l4t5-btn" data-v="${i}">🔊</button></article>`).join('')}</div></section></div>`;root.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>tts(D().vocab[Number(b.dataset.v)]?.term))}
const style=document.createElement('style');style.textContent=`body{margin:0;background:#fffdf5;font-family:Arial,sans-serif;color:#2f2b20}.l4t5-wrap{max-width:1100px;margin:0 auto;padding:20px}.l4t5-card{background:#fff;border:2px solid #eadf9f;border-radius:20px;padding:20px;margin:14px 0;box-shadow:0 8px 24px #0000000a}.l4t5-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(235px,1fr));gap:14px}.l4t5-task{display:block;text-decoration:none;color:inherit;background:#fff;border:2px solid #eadf9f;border-radius:18px;padding:16px}.l4t5-task .icon{font-size:38px;margin:12px 0}.l4t5-task.locked{opacity:.55}.l4t5-progress{height:10px;background:#f4edd0;border-radius:999px;overflow:hidden}.l4t5-progress i{display:block;height:100%;background:#d0ad24}.l4t5-progress-card{display:grid;grid-template-columns:90px 1fr;gap:18px;align-items:center}.circle{width:78px;height:78px;border-radius:50%;display:grid;place-items:center;background:#fff4be;border:6px solid #d0ad24;font-weight:900}.l4t5-btn{border:0;border-radius:12px;padding:11px 15px;font-weight:800;cursor:pointer;background:#f5e9aa;color:#514000}.l4t5-btn.primary{background:#d0ad24;color:#fff}.l4t5-btn.danger{margin-top:12px;background:#fff0e8;color:#8a3c20}.l4t5-options{display:grid;gap:10px;margin:18px 0}.l4t5-options button,.l4t5-tokens button{border:2px solid #eadf9f;background:#fff;border-radius:12px;padding:12px;text-align:left;cursor:pointer}.l4t5-context{background:#fff9dc;border-radius:14px;padding:14px;line-height:1.55;margin:10px 0 18px}.l4t5-answer{display:flex;gap:8px}.l4t5-answer input,textarea{width:100%;box-sizing:border-box;border:2px solid #eadf9f;border-radius:12px;padding:12px;font:inherit}.l4t5-built{min-height:48px;padding:12px;border:2px dashed #d0ad24;border-radius:12px;margin-bottom:12px}.l4t5-tokens,.l4t5-actions{display:flex;flex-wrap:wrap;gap:8px;margin:10px 0}.l4t5-feedback{padding:12px;border-radius:12px;margin-top:12px;font-weight:800}.l4t5-feedback.good{background:#eaffee;color:#176b39}.l4t5-feedback.bad{background:#fff0f0;color:#992e2e}.l4t5-feedback.warn{background:#fff8d9;color:#755d00}.l4t5-flash{text-align:center;min-height:300px;display:grid;place-items:center}.l4t5-flash strong{display:block;font-size:30px;margin:18px}.l4t5-finish{text-align:center}.l4t5-finish .big{font-size:54px;font-weight:900}.l4t5-vocab{display:grid;gap:10px}.l4t5-vocab article{display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid #eadf9f;padding:12px}.l4t5-vocab span{display:block;font-size:13px;color:#705d12}.l4t5-note{background:#fff4be;padding:12px;border-radius:12px}@media(max-width:600px){.l4t5-wrap{padding:12px}.l4t5-progress-card{grid-template-columns:1fr}.l4t5-answer{display:grid}.l4t5-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
window.L4T5UI={renderTheme,taskPage,overview,pct,allDone,hydrate};
})();