import{requireLogin,getActiveProfile,getActiveRole,dashboardHref,logout}from'/js/auth.js?v=login-main-4';
import{loadCourseRelease,moduleOpen}from'/js/course-releases.js?v=irregular-verbs-1';
const D=window.IRREGULAR_VERB_DAYS||[],A=D.flatMap(x=>x.verbs||[]),app=document.querySelector('#app'),head=document.querySelector('#topbar'),cdn='https://sprachpilot.b-cdn.net/';
const P=[['ich','ich','ich'],['du','du','du'],['er','er','er'],['er','sie (Singular)','sie'],['er','es','es'],['wir','wir','wir'],['ihr','ihr','ihr'],['sie','sie (Plural)','sie'],['sie','Sie','Sie']].map(([key,label,spoken])=>({key,label,spoken}));
const TP=[['ich','ich'],['du','du'],['er','er/sie/es'],['wir','wir'],['ihr','ihr'],['sie','sie/Sie']].map(([key,label])=>({key,label}));
const T=[['cards','Aa','Karteikarten'],['meaning-to-verb','B→V','Bedeutung → Verb'],['verb-to-meaning','V→B','Verb → Bedeutung'],['listen','🔊','Hören → Verb'],['image-to-verb','▣','Bild → Verb'],['verb-to-image','V→▣','Verb → Bild'],['read-sentence','📖','Lesen → Verb'],['change','e→i','Vokalwechsel'],['choose-form','du','Form auswählen'],['write-form','✎','Form schreiben'],['speak','🎙','Form sprechen'],['sentence','…','Satz ergänzen'],['exam','★','Tagesprüfung']];
const ids=T.map(x=>x[0]),learn=ids.slice(0,-1),special=new Set(['haben','sein','werden','wissen']);let S,R,rec=null;
const e=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=x=>String(x??'').trim().toLowerCase().replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss').replace(/[.,!?;:"'`´()]/g,'').replace(/\s+/g,' ');
const prof=()=>getActiveProfile()||{},role=()=>String(getActiveRole()||'').toLowerCase(),day=x=>D.find(y=>y.day===+x)||D[0],fresh=x=>day(x).verbs||[],all=x=>D.filter(y=>y.day<=+x).flatMap(y=>y.verbs||[]),pct=(a,b)=>b?Math.round(a/b*100):0;
const preview=()=>role()==='teacher'||(()=>{try{return JSON.parse(sessionStorage.getItem('SP_TEACHER_PREVIEW')||'null')?.teacherPreview===true}catch{return false}})();
const key=()=>`SP_IRREGULAR_VERBS_PROGRESS_${[prof().email,prof().courseCode,prof().kurs,prof().kursnummer,prof().vorname,prof().nachname].filter(Boolean).join('_').toLowerCase().replace(/[^a-z0-9äöüß]+/gi,'_')||'student'}`;
function load(){try{const x=JSON.parse(localStorage.getItem(key())||'null')||{};return{version:5,selectedDay:1,completed:{},runs:{},...x,completed:x.completed||{},runs:x.runs||{}}}catch{return{version:5,selectedDay:1,completed:{},runs:{}}}}
function save(){if(!preview())try{localStorage.setItem(key(),JSON.stringify(S))}catch{}}
const done=(d,t)=>!!S.completed?.[d]?.[t]?.done,practiceDone=d=>learn.every(t=>done(d,t)),dayDone=d=>practiceDone(d)&&done(d,'exam'),examOpen=d=>preview()||practiceDone(d),openDay=d=>preview()||d===1||dayDone(d-1);
function mark(d,t,perfect,score){if(preview())return;S.completed[d]??={};const o=S.completed[d][t]||{};S.completed[d][t]={done:true,perfect:o.perfect||perfect,bestScore:100,firstScore:Math.max(o.firstScore||0,score)};if(S.runs[d])delete S.runs[d][t];save()}
function runSave(){if(preview()||!R)return;S.runs[R.d]??={};S.runs[R.d][R.t]={seq:R.seq,pos:R.pos,err:R.err,seen:[...R.seen],first:R.first,wrong:R.wrong,ok:R.ok,show:R.show,write:R.write,base:R.base,kind:R.kind};save()}
function part(d,t){if(done(d,t))return 100;const x=S.runs?.[d]?.[t];if(!x)return 0;return Math.min(99,pct(x.pos??x.index??0,x.base||x.seq?.length||x.order?.length||1))}
function stop(){if(rec)try{rec.abort()}catch{}rec=null}
function url(t,push=false){const u=new URL(location.href);u.searchParams.set('day',S.selectedDay);t?u.searchParams.set('task',t):u.searchParams.delete('task');history[push?'pushState':'replaceState']({},'',u)}
const scroll=(q,b='center')=>requestAnimationFrame(()=>setTimeout(()=>document.querySelector(q)?.scrollIntoView({behavior:'smooth',block:b}),80));
const imgName=v=>v.toLowerCase().replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,'_')+'.webp';
function image(v,small=false){return`<div class="verb-image ${small?'compact':''}"><img src="${cdn+imgName(v.v)}" alt="Bild zu ${e(v.v)}" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="image-fallback" hidden><strong>Kein Bild verfügbar</strong><span>${e(v.meaning)}</span></div></div>`}
function lang(){const x=String(prof().muttersprache||prof().motherLanguage||'Englisch').toLowerCase(),m=[[/russ/,'Russisch'],[/ukrain|ukrainisch|україн/,'Ukrainisch'],[/türk|turk/,'Türkisch'],[/arab/,'Arabisch'],[/japan/,'Japanisch'],[/rumän|ruman|roman/,'Rumänisch'],[/pol/,'Polnisch'],[/kurd/,'Kurdisch'],[/engl|english/,'Englisch']];return m.find(([r])=>r.test(x))?.[1]||'Englisch'}
const tr=v=>(window.SP_VERB_TRANSLATIONS||{})?.[lang()]?.[v.v]||(window.SP_VERB_TRANSLATIONS||{})?.Englisch?.[v.v]||v.meaning;
const sentence=v=>`${v.sentence.subject} ${v.forms[v.sentence.person]} ${v.sentence.rest}`;
function group(v){if(special.has(v.v))return'Sonderform';if(v.change==='e → i')return'e → i';if(v.change==='e → ie')return'e → ie';return'a → ä'}
function options(ans,pool,off=0){const seen=new Set(),a=pool.filter(x=>{const z=n(x);if(!z||seen.has(z)||z===n(ans))return false;seen.add(z);return true}),r=[ans,...a.slice(off).concat(a.slice(0,off)).slice(0,3)];return r.slice((off+1)%r.length).concat(r.slice(0,(off+1)%r.length))}
function forms(v,ans,off=0){return options(ans,Object.values(v.forms),off)}
const person=(i,d,o=0)=>P[(i+d+o)%P.length];
function header(){const p=prof(),nm=[p.vorname||p.firstName,p.nachname||p.lastName].filter(Boolean).join(' ')||(preview()?'Lehrer-Vorschau':'Schüler');head.innerHTML=`<div class="topbar-main"><a class="brand" href="/index.html"><img src="/assets/logo/sprachpilot-logo.png"><div><h1>Irreguläre Verben</h1><p>${A.length} Verben · ${D.length} Lerntage</p></div></a><div class="account-actions"><span class="account-pill">${e(nm)}</span><a class="btn secondary" href="${e(dashboardHref())}">Dashboard</a><button class="btn secondary" id="logout">Abmelden</button></div></div><nav class="topnav"><a class="btn secondary" href="/index.html">← Startseite</a><button class="btn danger-btn" id="reset">Fortschritte löschen</button></nav>`;head.querySelector('#logout').onclick=logout;head.querySelector('#reset').onclick=()=>{if(preview())return alert('In der Lehrer-Vorschau wird nichts gespeichert.');if(confirm('Fortschritte bei „Irreguläre Verben“ löschen?')){localStorage.removeItem(key());S=load();home(false,'',true)}}}
const note=()=>preview()?'<div class="preview-note">Lehrer-Vorschau: Alle Tage sind offen. Es wird nichts gespeichert.</div>':'';
function overview(){const gs=[['a → ä','Bei du und er/sie/es wird a zu ä. Bei laufen und saufen wird au zu äu.'],['e → i','Bei du und er/sie/es wird e zu i.'],['e → ie','Bei du und er/sie/es wird e zu ie.'],['Sonderform','haben, sein, werden und wissen haben eigene Formen.']];return`<section class="card overview-card"><h2>Verben und Formen</h2><p class="overview-intro">Öffne eine Gruppe. Achte auf du und er/sie/es.</p><div class="verb-groups">${gs.map(([g,txt])=>{const vs=A.filter(v=>group(v)===g);return`<details class="verb-group"><summary><span>${g}</span><span>${vs.length} Verben</span></summary><p class="group-note">${txt}</p><div class="table-scroll"><table class="conjugation-table"><thead><tr><th>Verb</th>${TP.map(p=>`<th>${p.label}</th>`).join('')}</tr></thead><tbody>${vs.map(v=>`<tr><th>${e(v.v)}</th>${TP.map(p=>`<td class="${p.key==='du'||p.key==='er'?'changed':''}">${e(v.forms[p.key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details>`}).join('')}</div></section>`}
function taskCards(d){return T.map((t,i)=>{const lock=t[0]==='exam'&&!examOpen(d),p=part(d,t[0]);return`<button class="task-card ${done(d,t[0])?'done-card':''} ${lock?'locked-task':''}" data-task="${t[0]}" data-task-card="${t[0]}" ${lock?'disabled':''}><span class="task-number">${i+1}</span><span class="task-icon">${lock?'🔒':t[1]}</span><span class="task-title">${t[2]}</span><span class="task-desc">${t[0]==='cards'?'Nur die drei neuen Verben.':'Alle bisher gelernten Verben.'}</span><div class="task-mini-progress"><span style="width:${done(d,t[0])?100:p}%"></span></div><span class="task-status">${lock?'Erst alle Lernaufgaben zu 100% abschließen':done(d,t[0])?'100% abgeschlossen':p?`${p}% gespeichert`:'Noch offen'}</span></button>`}).join('')}
function days(){return D.map(x=>{const o=openDay(x.day),sel=o&&x.day===+S.selectedDay;return`<details class="day-panel ${o?'':'locked'}" data-day-panel="${x.day}" ${sel?'open':''}><summary data-day="${x.day}"><span class="day-number">${o?'':'🔒 '}Tag ${x.day}</span><span class="day-verbs"><strong>Neu:</strong> ${x.verbs.map(v=>e(v.v)).join(', ')}</span><span class="day-cumulative">${all(x.day).length} Verben insgesamt</span><span class="day-progress">${o?`${learn.filter(t=>done(x.day,t)).length}/${learn.length} Lernaufgaben`:`Tag ${x.day-1} zuerst fertig machen`}</span></summary>${o?`<div class="day-body" id="day-${x.day}"><div class="cumulative-note">Nur Karteikarten: 3 neue Verben. Alle anderen Aufgaben: alle ${all(x.day).length} Verben aus Tag 1 bis Tag ${x.day}.</div><div class="task-grid">${taskCards(x.day)}</div></div>`:''}</details>`}).join('')}
function home(push=false,task='',toDay=false){stop();R=null;if(!openDay(+S.selectedDay))S.selectedDay=1;url('',push);const c=D.reduce((s,d)=>s+learn.filter(t=>done(d.day,t)).length,0),tot=D.length*learn.length;app.innerHTML=`${note()}${overview()}<section class="card progress-card"><div class="circle">${pct(c,tot)}%</div><div><h2>Dein Fortschritt</h2><p>Falsche Fragen bleiben stehen und kommen am Ende noch einmal.</p><div class="progress"><div class="bar" style="width:${pct(c,tot)}%"></div></div></div></section><section class="card"><h2>Tage öffnen</h2><div class="days-accordion">${days()}</div></section>`;if(task)scroll(`[data-day-panel="${S.selectedDay}"] [data-task-card="${task}"]`);else if(toDay)scroll(`#day-${S.selectedDay}`,'start')}
function q(task,v,i,d,prefix=task){const av=all(d),names=av.map(x=>x.v),mean=av.map(x=>x.meaning);if(task==='cards')return{id:`${prefix}-${v.v}`,type:'word',v,p:'Wie heißt das Verb auf Deutsch?',a:v.v,input:true,img:true};if(task==='meaning-to-verb')return{id:`${prefix}-${v.v}`,type:'word',v,p:v.meaning,a:v.v,o:options(v.v,names,i),img:true};if(task==='verb-to-meaning')return{id:`${prefix}-${v.v}`,type:'meaning',v,p:`Was bedeutet „${v.v}“?`,a:v.meaning,o:options(v.meaning,mean,i),small:true};if(task==='listen')return{id:`${prefix}-${v.v}`,type:'word',v,p:'Höre das Verb.',a:v.v,o:options(v.v,names,i),audio:v.v};if(task==='image-to-verb')return{id:`${prefix}-${v.v}`,type:'word',v,p:'Welches Verb zeigt das Bild?',a:v.v,o:options(v.v,names,i),img:true};if(task==='verb-to-image')return{id:`${prefix}-${v.v}`,type:'word',v,p:`Welches Bild passt zu „${v.v}“?`,a:v.v,imgs:options(v.v,names,i).map(z=>av.find(x=>x.v===z))};if(task==='read-sentence')return{id:`${prefix}-${v.v}`,type:'word',v,p:sentence(v),a:v.v,o:options(v.v,names,i),small:true};if(task==='change')return{id:`${prefix}-${v.v}`,type:'change',v,p:`Zu welcher Gruppe gehört „${v.v}“?`,a:group(v),o:['a → ä','e → i','e → ie','Sonderform']};let pe;if(task==='choose-form'){pe=person(i,d);const a=v.forms[pe.key];return{id:`${prefix}-${v.v}-${pe.label}`,type:'form',v,pe,p:`${pe.label}: ${v.v}`,a,o:forms(v,a,i),small:true}}if(task==='write-form'){pe=person(i,d,3);return{id:`${prefix}-${v.v}-${pe.label}`,type:'form',v,pe,p:`${pe.label}: ${v.v}`,a:v.forms[pe.key],input:true,small:true}}if(task==='speak'){pe=person(i,d,6);const a=`${pe.spoken} ${v.forms[pe.key]}`;return{id:`${prefix}-${v.v}-${pe.label}`,type:'form',v,pe,p:`Sprich: ${pe.label} – ${v.v}`,a,answers:[a,v.forms[pe.key]],speech:true,small:true}}pe=person(i,d,8);const a=v.forms[pe.key];return{id:`${prefix}-${v.v}-${pe.label}`,type:'form',v,pe,p:`${pe.label} ___ heute.`,a,o:forms(v,a,i+2),small:true}}
function questions(t,d){const av=all(d);if(t!=='exam')return av.map((v,i)=>q(t,v,i,d));const nv=fresh(d),ordered=[...nv,...av.filter(v=>!nv.some(x=>x.v===v.v))],r=learn.map((s,i)=>q(s,ordered[i%ordered.length],i,d,`exam-${s}`)),used=new Set(r.map(x=>x.v.v));ordered.filter(v=>!used.has(v.v)).forEach((v,i)=>r.push(q(learn[i%learn.length],v,i+learn.length,d,`exam-extra-${i}`)));return r}
function openTask(t,push=true){if(!openDay(+S.selectedDay)||t==='exam'&&!examOpen(+S.selectedDay))return home(push,t);stop();sessionStorage.setItem('SP_IRREGULAR_RETURN_TASK',t);url(t,push);const d=+S.selectedDay,s=S.runs?.[d]?.[t];if(t==='cards'){const base=fresh(d).map(v=>v.v),seq=Array.isArray(s?.seq)?s.seq.filter(x=>base.includes(x)):base;R={kind:'cards',t,d,seq:seq.length?seq:base,pos:s?.pos??s?.index??0,err:s?.err??s?.tries??0,seen:new Set(s?.seen||[]),first:s?.first||0,wrong:!!s?.wrong,ok:!!s?.ok||!!s?.cardSolved,show:!!s?.show||!!s?.revealed,write:!!s?.write,base:base.length}}else{const qs=questions(t,d),map=new Map(qs.map(x=>[x.id,x])),base=qs.map(x=>x.id),seq=Array.isArray(s?.seq||s?.order)?(s.seq||s.order).filter(x=>map.has(x)):base;R={kind:'quiz',t,d,map,seq:seq.length?seq:base,pos:s?.pos??s?.index??0,err:s?.err??0,seen:new Set(s?.seen||s?.firstSeen||[]),first:s?.first??s?.firstCorrect??0,wrong:!!s?.wrong||!!s?.hadWrong,ok:!!s?.ok||!!s?.correct,show:false,write:!!s?.write,base:base.length}}runSave();render()}
const current=()=>R.kind==='cards'?A.find(v=>v.v===R.seq[R.pos]):R.map.get(R.seq[R.pos]);
function hint(x){if(R.err===1)return'<div class="feedback no">Noch nicht richtig. Versuche es noch einmal.</div>';if(R.err===2){const a=String(x.a);return`<div class="feedback no">Hinweis: ${x.type==='change'?`Bei du heißt es „${e(x.v.forms.du)}“.`:x.type==='form'?`Gesucht ist ${e(x.pe?.label||'diese Person')}. Die Antwort beginnt mit „${e(a[0])}“.`:`Das Wort beginnt mit „${e(a[0])}“ und hat ${a.length} Buchstaben.`}</div>`}if(R.err>=3)return`<div class="feedback no">Lösung: <strong>${e(x.a)}</strong>. Gib die richtige Antwort jetzt selbst ein.</div>`;return''}
function shell(body){return`${note()}<section class="card task-page"><div class="task-page-head"><button class="btn secondary" data-act="back">← Zurück</button><div><p class="eyebrow">Tag ${R.d}</p><h2>${T.find(x=>x[0]===R.t)[2]}</h2></div><span class="package-label">3 neu · ${all(R.d).length} insgesamt</span></div>${body}</section>`}
const input=(disabled=false,label='Schreibe deine Antwort')=>`<form id="answerForm" class="answer-form"><label>${label}</label><div class="answer-row"><input name="answer" ${disabled?'disabled':''}><button class="btn" ${disabled?'disabled':''}>Prüfen</button></div></form>`;
function render(){if(R.pos>=R.seq.length)return finish();const x=current();if(R.kind==='cards')return cards(x);let ans=x.imgs?`<div class="image-choice-grid">${x.imgs.map(v=>`<button class="image-option" data-answer="${e(v.v)}" ${R.ok?'disabled':''}>${image(v,true)}</button>`).join('')}</div>`:x.speech?`<div class="speech-box"><button class="btn" data-act="mic" ${R.ok?'disabled':''}>Form sprechen</button><button class="btn secondary" data-act="write">Stattdessen schreiben</button>${R.write?input(R.ok,'Schreibe Pronomen und Verbform'):''}</div>`:x.o?`<div class="option-grid">${x.o.map(o=>`<button class="option" data-answer="${e(o)}" ${R.ok?'disabled':''}>${e(o)}</button>`).join('')}</div>`:input(R.ok);app.innerHTML=shell(`<div class="task-progress-row"><span>${R.pos} von ${R.seq.length} gelöst</span><span>Fehler: ${R.err}</span></div><div class="mini-progress"><div style="width:${pct(R.pos,R.seq.length)}%"></div></div><div class="question-card">${x.img?image(x.v):x.small?image(x.v,true):''}${x.audio?`<button class="btn" data-act="play">🔊 Anhören</button>`:''}<div class="question">${e(x.p)}</div>${ans}${R.ok?'<div class="feedback ok">Richtig.</div><button class="btn" data-act="next">Weiter</button>':hint(x)}</div>`);if(!R.ok&&!x.o&&!x.imgs&&(!x.speech||R.write))requestAnimationFrame(()=>app.querySelector('input')?.focus())}
function cards(v){const x={id:`card-${v.v}`,type:'word',v,a:v.v},back=R.show||R.err>=3||R.ok;app.innerHTML=shell(`<div class="task-progress-row"><span>${R.pos} von ${R.seq.length} gelöst</span><span>Fehler: ${R.err}</span></div><div class="flip-wrap"><div class="flip-card ${back?'flipped':''}" data-act="reveal"><div class="flip-face flip-front">${image(v)}<div class="translation-box"><strong>${lang()}:</strong> ${e(tr(v))}</div></div><div class="flip-face flip-back"><div class="flash-verb">${e(v.v)}</div><p>${e(v.meaning)}</p><div class="forms-grid">${TP.map(p=>`<div><span>${p.label}</span><strong>${e(v.forms[p.key])}</strong></div>`).join('')}</div><p>${e(sentence(v))}</p></div></div></div>${R.ok?'<div class="feedback ok">Richtig.</div><button class="btn" data-act="next">Weiter</button>':`<div class="actions"><button class="btn" data-act="cardmic">Sprechen</button><button class="btn secondary" data-act="write">Schreiben</button></div>${R.write?input(false,'Schreibe den Infinitiv'):''}${hint(x)}`}`);if(R.write&&!R.ok)requestAnimationFrame(()=>app.querySelector('input')?.focus())}
function answer(raw){const x=R.kind==='cards'?{id:`card-${current().v}`,a:current().v,answers:[current().v]}:current();if(!x||R.ok||!String(raw||'').trim())return;const ok=(x.answers||[x.a]).some(a=>n(a)===n(raw));if(!R.seen.has(x.id)){R.seen.add(x.id);if(ok)R.first++}if(ok){if(R.err>0)R.seq.push(R.seq[R.pos]);R.ok=true;R.show=true}else{R.err++;R.wrong=true;if(R.err>=3)R.show=true}runSave();render()}
function next(){if(!R.ok)return;R.pos++;R.err=0;R.ok=false;R.show=false;R.write=false;if(R.pos>=R.seq.length)return finish();runSave();render()}
function finish(){mark(R.d,R.t,!R.wrong,pct(R.first,R.base));const ni=ids.indexOf(R.t),nx=ids.slice(ni+1).find(x=>x!=='exam'||examOpen(R.d)),nd=R.d<D.length?R.d+1:null;app.innerHTML=shell(`<div class="finish-box"><h3>Aufgabe fertig</h3><p>Falsche Fragen wurden am Ende wiederholt.</p><button class="btn" data-act="${nx?'continue':R.t==='exam'&&nd?'nextday':'back'}">Weiter</button></div>`)}
function mic(card=false){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){R.write=true;runSave();return render()}stop();const x=card?{answers:[current().v]}:current();try{rec=new SR();rec.lang='de-DE';rec.maxAlternatives=5;rec.onresult=ev=>{const a=Array.from(ev.results[0]).map(z=>z.transcript),ok=a.find(z=>(x.answers||[x.a]).some(y=>n(y)===n(z)));answer(ok||a[0]||'')};rec.onerror=()=>{R.write=true;runSave();render()};rec.onend=()=>{rec=null};rec.start()}catch{R.write=true;runSave();render()}}
app.onclick=ev=>{const s=ev.target.closest('summary[data-day]');if(s){const d=+s.dataset.day;if(!openDay(d)){ev.preventDefault();return}if(d!==+S.selectedDay){ev.preventDefault();S.selectedDay=d;save();return home(false,'',true)}setTimeout(()=>scroll(`#day-${d}`,'start'),50);return}const b=ev.target.closest('button');if(!b){if(ev.target.closest('[data-act="reveal"]')&&!R.ok){R.err=Math.max(3,R.err);R.wrong=true;R.show=true;runSave();cards(current())}return}if(b.dataset.task)return openTask(b.dataset.task);if(b.dataset.answer)return answer(b.dataset.answer);const a=b.dataset.act;if(a==='back')return home(true,R?.t||sessionStorage.getItem('SP_IRREGULAR_RETURN_TASK')||'');if(a==='write'){R.write=true;runSave();return render()}if(a==='mic')return mic();if(a==='cardmic')return mic(true);if(a==='play'){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current().audio);u.lang='de-DE';speechSynthesis.speak(u);return}if(a==='next')return next();if(a==='continue'){const ni=ids.indexOf(R.t),nx=ids.slice(ni+1).find(x=>x!=='exam'||examOpen(R.d));return nx?openTask(nx,true):home(true,R.t)}if(a==='nextday'){S.selectedDay=R.d+1;save();return home(false,'',true)}};
app.onsubmit=ev=>{if(ev.target.id==='answerForm'){ev.preventDefault();answer(new FormData(ev.target).get('answer'))}};
window.onpopstate=()=>{const p=new URLSearchParams(location.search),d=+p.get('day');S.selectedDay=D.some(x=>x.day===d)&&openDay(d)?d:1;const t=p.get('task');t&&ids.includes(t)&&(t!=='exam'||examOpen(S.selectedDay))?openTask(t,false):home(false,sessionStorage.getItem('SP_IRREGULAR_RETURN_TASK')||'')};
async function init(){if(!requireLogin())return;S=load();header();if(role()!=='teacher')try{if(!moduleOpen(await loadCourseRelease(prof()),'Irreguläre Verben'))return app.innerHTML='<section class="card"><h2>Noch gesperrt</h2></section>'}catch{return app.innerHTML='<section class="card"><h2>Noch gesperrt</h2></section>'}const p=new URLSearchParams(location.search),d=+p.get('day');S.selectedDay=D.some(x=>x.day===d)&&openDay(d)?d:Math.min(+S.selectedDay||1,D.length);if(!openDay(S.selectedDay))S.selectedDay=1;const t=p.get('task');t&&ids.includes(t)&&(t!=='exam'||examOpen(S.selectedDay))?openTask(t,false):home(false,'')}
init().catch(err=>{console.error(err);app.innerHTML='<section class="card"><h2>Die Seite lädt nicht.</h2></section>'});