import{requireLogin,getActiveProfile,getActiveRole,dashboardHref,logout}from'/js/auth.js?v=login-main-4';
import{loadCourseRelease,moduleOpen}from'/js/course-releases.js?v=irregular-verbs-1';
const NAME='Irreguläre Verben',D=window.IRREGULAR_VERB_DAYS||[],V=D.flatMap(x=>x.verbs||[]),A=document.querySelector('#app'),H=document.querySelector('#topbar');
const T=[['cards','Aa','Karteikarten','Bedeutung, Vokalwechsel und alle Präsensformen lernen.'],['change','e→i','Vokalwechsel','Erkenne den Stammvokal bei du und er/sie/es.'],['du','du','du-Form auswählen','Wähle die richtige Verbform.'],['er','er','er/sie/es schreiben','Schreibe die richtige Verbform.'],['speak','🎙','Form sprechen','Sprich die du-Form oder schreibe sie.'],['sentence','…','Satz ergänzen','Setze die passende Form in einen A1-Satz ein.'],['exam','★','Prüfung','Prüfe die du- und er/sie/es-Formen.']];
const CH=['e → i','e → ie','a → ä','au → äu','Sonderform'];
let S,Q=null,R=null;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=x=>String(x??'').trim().toLowerCase().replace(/ß/g,'ss').replace(/[.,!?;:"'`´]/g,'').replace(/\s+/g,' ');
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const uniq=a=>{let s=new Set;return a.filter(x=>{let k=norm(x);if(!k||s.has(k))return false;s.add(k);return true})};
const role=()=>String(getActiveRole()||'').toLowerCase(),profile=()=>getActiveProfile()||{};
function preview(){if(role()==='teacher')return true;try{return JSON.parse(sessionStorage.getItem('SP_TEACHER_PREVIEW')||'null')?.teacherPreview===true}catch(e){return false}}
function key(){let p=profile(),id=[p.email,p.courseCode,p.kurs,p.kursnummer,p.vorname,p.nachname].filter(Boolean).join('_')||'student';return'SP_IRREGULAR_VERBS_PROGRESS_'+id.toLowerCase().replace(/[^a-z0-9äöüß]+/gi,'_')}
function load(){try{let x=JSON.parse(localStorage.getItem(key())||'null');if(x)return{selectedDay:1,completed:{},...x}}catch(e){}return{selectedDay:1,completed:{}}}
function save(){if(!preview())try{localStorage.setItem(key(),JSON.stringify(S))}catch(e){}}
const day=()=>D.find(x=>x.day===+S.selectedDay)||D[0],rec=(d,t)=>S.completed?.[d]?.[t];
function done(d,t,perfect,score=100){if(preview())return;S.completed[d]??={};let old=S.completed[d][t]||{};S.completed[d][t]={done:true,perfect:!!(old.perfect||perfect),bestScore:Math.max(old.bestScore||0,score)};save()}
const count=d=>T.filter(t=>rec(String(d),t[0])?.done).length,pc=(a,b)=>b?Math.round(a/b*100):0;
function stop(){if(R)try{R.abort()}catch(e){}R=null}
function url(task,push=false){let u=new URL(location.href);u.searchParams.set('day',S.selectedDay);task?u.searchParams.set('task',task):u.searchParams.delete('task');history[push?'pushState':'replaceState']({},'',u)}
function header(){let p=profile(),n=[p.vorname||p.firstName,p.nachname||p.lastName].filter(Boolean).join(' ')||(role()==='teacher'?'Lehrer-Vorschau':'Schüler');H.innerHTML=`<div class="topbar-main"><a class="brand" href="/index.html"><img src="/assets/logo/sprachpilot-logo.png" alt="SprachPilot Logo"><div><h1>${NAME}</h1><p>40 Verben im Präsens · 13 Tagespakete</p></div></a><div class="account-actions"><span class="account-pill">${esc(n)}</span><a class="btn secondary" href="${esc(dashboardHref())}">Dashboard</a><button class="btn secondary" id="out">Abmelden</button></div></div><nav class="topnav"><a class="btn secondary" href="/index.html">← Startseite</a><button class="btn secondary" id="home">Tagesübersicht</button></nav>`;H.querySelector('#out').onclick=logout;H.querySelector('#home').onclick=()=>home(true)}
const note=()=>preview()?'<div class="preview-note">Lehrer-Vorschau: Es werden keine Teilnehmerpunkte und kein Teilnehmerfortschritt gespeichert.</div>':'';
function locked(){A.innerHTML='<section class="card locked-card"><h2>Noch nicht freigeschaltet</h2><p>Das Modul „Irreguläre Verben“ ist für deinen Kurs gesperrt.</p><a class="btn" href="/index.html">Zur Startseite</a></section>'}
function home(push=false){stop();Q=null;if(push)url(null,true);let d=day(),all=D.reduce((n,x)=>n+count(x.day),0),total=D.length*T.length,p=pc(all,total);A.innerHTML=`${note()}<section class="card progress-card"><div class="circle">${p}%</div><div><p class="eyebrow">Dein Lernplan</p><h2>Irreguläre Verben im Präsens</h2><p>${all} von ${total} Tagesaufgaben abgeschlossen.</p><div class="progress"><div class="bar" style="width:${p}%"></div></div><p class="small">Falsche Aufgaben kommen am Ende erneut. Nach drei Fehlern erscheint die Lösung.</p></div></section><section class="card"><div class="section-head"><div><p class="eyebrow">13 Tage</p><h2>Wähle ein Tagespaket</h2></div><div class="day-status">Tag ${d.day}: ${count(d.day)}/${T.length}</div></div><div class="day-grid">${D.map(x=>`<button class="day-card ${x.day===d.day?'active':''}" data-day="${x.day}"><span class="day-number">Tag ${x.day}</span><span class="day-verbs">${esc(x.verbs.map(v=>v.v).join(', '))}</span><span class="day-progress">${count(x.day)}/${T.length} abgeschlossen</span></button>`).join('')}</div></section><section class="card"><div class="section-head"><div><p class="eyebrow">Tag ${d.day}</p><h2>${esc(d.verbs.map(v=>v.v).join(' · '))}</h2></div><div class="change-legend">${esc(uniq(d.verbs.map(v=>v.change)).join(' · '))}</div></div><div class="task-grid">${T.map((t,i)=>{let r=rec(String(d.day),t[0]);return`<button class="task-card ${r?.done?'done-card':''}" data-task="${t[0]}"><span class="task-number">${i+1}</span><span class="task-icon">${t[1]}</span><span class="task-title">${t[2]}</span><span class="task-desc">${t[3]}</span><span class="task-status">${r?.done?(r.perfect?'Fehlerfrei abgeschlossen':'Abgeschlossen'):'Noch offen'}</span></button>`}).join('')}</div></section>`}
function shell(body){let t=T.find(x=>x[0]===Q.task),d=Q.day;return`${note()}<section class="card task-page"><div class="task-page-head"><button class="btn secondary" data-act="back">← Zur Übersicht</button><div><p class="eyebrow">Tag ${d.day}</p><h2>${t[2]}</h2></div><span class="package-label">${esc(d.verbs.map(v=>v.v).join(' · '))}</span></div>${body}</section>`}
function regDu(v){let s=v.replace(/en$/,'').replace(/n$/,'');return/[td]$/.test(s)?s+'est':s+'st'}
function opts(ans,pool,n=4){let a=uniq([ans,...shuffle(pool)]).filter((x,i)=>i===0||norm(x)!==norm(ans));return shuffle([ans,...a.filter(x=>norm(x)!==norm(ans)).slice(0,n-1)])}
const pool=p=>V.map(v=>v.forms[p]);
function questions(id,d){if(id==='change')return d.verbs.map(v=>({id:id+v.v,v,p:`Welchen Vokalwechsel hat „${v.v}“?`,a:v.change,o:CH}));if(id==='du')return d.verbs.map(v=>({id:id+v.v,v,p:`du – ${v.v}`,a:v.forms.du,o:opts(v.forms.du,[v.forms.er,v.forms.ihr,regDu(v.v),...pool('du')])}));if(id==='er')return d.verbs.map(v=>({id:id+v.v,v,p:`er/sie/es – ${v.v}`,a:v.forms.er,input:1}));if(id==='speak')return d.verbs.map(v=>({id:id+v.v,v,p:`Sprich: du ${v.v}`,a:`du ${v.forms.du}`,speech:1}));if(id==='sentence')return d.verbs.map(v=>{let p=v.sentence.person,a=v.forms[p];return{id:id+v.v,v,p:`${v.sentence.subject} ___ ${v.sentence.rest}`,a,o:opts(a,[v.forms.du,v.forms.er,v.forms.ihr,...pool(p)])}});if(id==='exam')return d.verbs.flatMap(v=>[{id:id+'du'+v.v,v,p:`du – ${v.v}`,a:v.forms.du,input:1},{id:id+'er'+v.v,v,p:`er/sie/es – ${v.v}`,a:v.forms.er,input:1}]);return[]}
function open(id,push=true){if(!T.some(t=>t[0]===id))return home(push);stop();url(id,push);let d=day();Q=id==='cards'?{task:id,day:d,i:0,reveal:false,finish:false}:{task:id,day:d,all:questions(id,d),queue:[],cur:null,tries:{},first:new Set,firstOK:0,res:new Set,wrong:false,fb:null,finish:false,write:false,listening:false,tech:''};if(id!=='cards'){Q.queue=[...Q.all];next()}render()}
function render(){if(Q.task==='cards')return cards();if(Q.finish)return finish();quiz()}
function cards(){if(Q.finish)return finish();let v=Q.day.verbs[Q.i];A.innerHTML=shell(`<div class="task-progress-row"><span>Karte ${Q.i+1} von ${Q.day.verbs.length}</span></div><div class="flashcard"><p class="eyebrow">Infinitiv</p><div class="flash-verb">${v.v}</div><p class="flash-meaning">${esc(v.meaning)}</p>${Q.reveal?`<div class="change-badge">Vokalwechsel: ${v.change}</div><div class="forms-grid">${[['ich','ich'],['du','du'],['er','er/sie/es'],['wir','wir'],['ihr','ihr'],['sie','sie/Sie']].map(x=>`<div><span>${x[1]}</span><strong>${v.forms[x[0]]}</strong></div>`).join('')}</div><div class="example-sentence"><strong>Beispiel:</strong> ${esc(v.sentence.subject)} ${v.forms[v.sentence.person]} ${esc(v.sentence.rest)}</div>${v.note?`<div class="word-note">${esc(v.note)}</div>`:''}`:'<p class="hint">Denke zuerst an du und er/sie/es.</p>'}</div><div class="actions"><button class="btn" data-act="${Q.reveal?'next-card':'reveal'}">${Q.reveal?(Q.i===Q.day.verbs.length-1?'Abschließen':'Nächste Karte'):'Formen zeigen'}</button></div>`)}
function next(){Q.fb=null;Q.tech='';Q.write=false;Q.listening=false;Q.cur=Q.queue.shift()||null;if(!Q.cur){Q.finish=true;let score=pc(Q.firstOK,Q.all.length);done(String(Q.day.day),Q.task,!Q.wrong,score)}}
function input(disabled=false,label='Schreibe nur die Verbform'){return`<form id="answer"><label>${label}</label><div class="answer-row"><input name="answer" autocomplete="off" autocapitalize="none" spellcheck="false" ${disabled?'disabled':''}><button class="btn" ${disabled?'disabled':''}>Prüfen</button></div></form>`}
function quiz(){if(!Q.cur){Q.finish=true;return finish()}let q=Q.cur,fb=Q.fb,area='';if(q.o)area=`<div class="option-grid ${q.o.length===5?'five-options':''}">${q.o.map(x=>`<button class="option" data-answer="${esc(x)}" ${fb?'disabled':''}>${esc(x)}</button>`).join('')}</div>`;else if(q.speech){let support=window.SpeechRecognition||window.webkitSpeechRecognition;if(!support)Q.write=true;area=`<div class="speech-box"><p>Sprich genau: <strong>${esc(q.a)}</strong></p><div class="actions"><button class="btn" data-act="mic" ${fb||Q.listening?'disabled':''}>${Q.listening?'Ich höre zu …':'Rolle sprechen'}</button><button class="btn secondary" data-act="write" ${fb?'disabled':''}>Stattdessen schreiben</button></div>${Q.tech?`<div class="tech-note">${esc(Q.tech)}</div>`:''}${Q.write?input(!!fb,'Schreibe: du + Verbform'):''}</div>`}else area=input(!!fb);let f=fb?`<div class="feedback ${fb.ok?'ok':'no'}">${fb.ok?'Richtig.':esc(fb.msg)}${fb.sol?`<div class="solution">Lösung: <strong>${esc(q.a)}</strong></div>`:''}</div><div class="actions"><button class="btn" data-act="next">Weiter</button></div>`:'';A.innerHTML=shell(`<div class="task-progress-row"><span>${Q.res.size} von ${Q.all.length} gelöst</span><span>Fehler: ${Q.tries[q.id]||0}/3</span></div><div class="mini-progress"><div style="width:${pc(Q.res.size,Q.all.length)}%"></div></div><div class="question-card"><p class="eyebrow">${q.v.v} · ${q.v.change}</p><div class="question">${esc(q.p)}</div>${q.speech?'':`<p class="meaning-line">${esc(q.v.meaning)}</p>`}${q.v.note?`<div class="word-note">${esc(q.v.note)}</div>`:''}${area}${f}</div>`);if(!fb&&!q.o&&(!q.speech||Q.write))requestAnimationFrame(()=>A.querySelector('input')?.focus())}
function answer(raw){let q=Q?.cur;if(!q||Q.fb||!String(raw||'').trim())return;let ok=norm(raw)===norm(q.a);if(!Q.first.has(q.id)){Q.first.add(q.id);if(ok)Q.firstOK++}if(ok){Q.res.add(q.id);Q.fb={ok:1}}else{Q.wrong=true;let n=(Q.tries[q.id]||0)+1;Q.tries[q.id]=n;if(n>=3){Q.res.add(q.id);Q.fb={ok:0,msg:'Das war der dritte Fehler. Jetzt siehst du die Lösung.',sol:1}}else{Q.queue.push(q);Q.fb={ok:0,msg:'Noch nicht richtig. Diese Aufgabe kommt am Ende erneut.'}}}quiz()}
function mic(){let q=Q.cur,C=window.SpeechRecognition||window.webkitSpeechRecognition;if(!C){Q.write=true;Q.tech='Das Mikrofon ist nicht verfügbar. Bitte schreibe die Antwort.';return quiz()}stop();let got=false,s=Q;try{R=new C;R.lang='de-DE';R.interimResults=false;R.maxAlternatives=3;Q.listening=true;quiz();R.onresult=e=>{if(Q!==s)return;got=true;Q.listening=false;let a=Array.from(e.results[0]).map(x=>x.transcript),hit=a.find(x=>norm(x)===norm(q.a));answer(hit||a[0]||'')};R.onerror=e=>{if(Q!==s)return;Q.listening=false;Q.write=true;Q.tech=e.error==='not-allowed'?'Der Mikrofonzugriff ist blockiert. Bitte schreibe die Antwort.':'Das Mikrofon konnte nichts erkennen. Bitte schreibe die Antwort.';R=null;quiz()};R.onend=()=>{R=null;if(Q!==s||got||Q.fb)return;Q.listening=false;Q.write=true;Q.tech='Es wurde keine Antwort erkannt. Bitte schreibe die Antwort.';quiz()};R.start()}catch(e){R=null;Q.listening=false;Q.write=true;Q.tech='Das Mikrofon konnte nicht gestartet werden. Bitte schreibe die Antwort.';quiz()}}
function finish(){let score=Q.task==='cards'?100:pc(Q.firstOK,Q.all.length),perfect=Q.task==='cards'||!Q.wrong;A.innerHTML=shell(`<div class="finish-box"><div class="finish-icon">${perfect?'★':'✓'}</div><h3>${perfect?'Fehlerfrei abgeschlossen':'Aufgabe abgeschlossen'}</h3><p>${Q.task==='cards'?'Du hast alle Formen angesehen.':`Beim ersten Versuch waren ${score}% richtig.`}</p>${perfect?'':'<p class="small">Falsche Aufgaben wurden wiederholt. Nach drei Fehlern wurde die Lösung gezeigt.</p>'}<div class="actions"><button class="btn" data-act="repeat">Wiederholen</button><button class="btn secondary" data-act="back">Zur Übersicht</button></div></div>`)}
A.onclick=e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.day){S.selectedDay=+b.dataset.day;save();url(null);return home()}if(b.dataset.task)return open(b.dataset.task);if(b.dataset.answer)return answer(b.dataset.answer);let x=b.dataset.act;if(x==='back')return home(true);if(x==='reveal'){Q.reveal=true;return cards()}if(x==='next-card'){if(Q.i===Q.day.verbs.length-1){Q.finish=true;done(String(Q.day.day),'cards',true)}else{Q.i++;Q.reveal=false}return render()}if(x==='next'){stop();next();return render()}if(x==='write'){Q.write=true;Q.tech='';return quiz()}if(x==='mic')return mic();if(x==='repeat')return open(Q.task,false)};
A.onsubmit=e=>{if(e.target.id!=='answer')return;e.preventDefault();answer(new FormData(e.target).get('answer'))};
window.onpopstate=()=>{stop();let p=new URLSearchParams(location.search),d=+p.get('day');if(D.some(x=>x.day===d))S.selectedDay=d;let t=p.get('task');T.some(x=>x[0]===t)?open(t,false):home()};
async function init(){if(!requireLogin())return;window.logout=logout;S=load();let p=new URLSearchParams(location.search),d=+p.get('day');if(D.some(x=>x.day===d))S.selectedDay=d;save();header();if(role()!=='teacher'){try{if(!moduleOpen(await loadCourseRelease(profile()),NAME))return locked()}catch(e){return locked()}}let t=p.get('task');T.some(x=>x[0]===t)?open(t,false):(url(null),home())}
init().catch(e=>{console.error(e);A.innerHTML='<section class="card locked-card"><h2>Das Modul konnte nicht geladen werden.</h2><button class="btn" onclick="location.reload()">Neu laden</button></section>'});
