(function(){
  'use strict';
  var VERSION='20260715-lite-1';
  var PACKAGE_SIZE=20;
  var TASK_POINTS=[5,10,15];
  var EXAM_POINTS=[100,200,300];
  var BUNNY='https://sprachpilot.b-cdn.net/verben-A1/bilder/';
  var TASKS=[
    ['karteikarten','Karteikarten'],['memory','Memory'],['bild-verb','Bild -> Verb'],['verb-bild','Verb -> Bild'],['schreiben','Schreiben'],['hoeren-schreiben','Hoeren -> Schreiben'],['hoeren-sprechen','Hoeren -> Sprechen'],['bild-sprechen','Bild -> Sprechen'],['satz-puzzle','Satz-Puzzle'],['konjugieren','Konjugieren']
  ];
  var TASK_IDS=TASKS.map(function(t){return t[0];});
  var FALLBACK='lieben,kaufen,verstehen,brauchen,hoeren,lernen,wohnen,bringen,sein,schreiben,fotografieren,telefonieren,kochen,leben,kommen,buchstabieren,gehen,schwimmen,suchen,bestellen,weinen,reparieren,gewinnen,spielen,springen,verlieren,fragen,verkaufen,unterschreiben,reservieren,buchen,machen,malen,trinken,schicken,denken,winken,hassen,beissen,giessen,heissen,essen,lesen,sehen,sprechen,nehmen,geben,helfen,treffen,fahren,laufen,schlafen,aufstehen,anfangen,anrufen,einkaufen,fernsehen,sich vorstellen,sich kaemmen,sich rasieren,sich schminken,koennen,muessen,duerfen,wollen,sollen,moegen'.split(',');
  var MODALS=['koennen','können','muessen','müssen','duerfen','dürfen','wollen','sollen','moegen','mögen'];
  var IRREGULAR=['sein','haben','werden','wissen','tun','geben','nehmen','essen','sprechen','lesen','sehen','fahren','laufen','schlafen','helfen','treffen','tragen','waschen','fallen','fangen','halten','lassen','bringen','denken','kennen','nennen'];
  var SPECIAL_IMAGES={'sich vorstellen':'sich_vorstellen.webp','sich kaemmen':'sich_kaemmen.webp','sich kämmen':'sich_kaemmen.webp','sich rasieren':'sich_rasieren.webp','sich schminken':'sich_schminken.webp','koennen':'koennen.webp','können':'koennen.webp'};
  var SPECIAL_ICH={sein:'bin',haben:'habe',werden:'werde',wissen:'weiss',koennen:'kann','können':'kann',muessen:'muss','müssen':'muss',duerfen:'darf','dürfen':'darf',wollen:'will',sollen:'soll',moegen:'mag','mögen':'mag',sehen:'sehe',lesen:'lese',sprechen:'spreche',essen:'esse',nehmen:'nehme',geben:'gebe',helfen:'helfe',treffen:'treffe',fahren:'fahre',laufen:'laufe',schlafen:'schlafe','aufstehen':'stehe auf','anfangen':'fange an','anrufen':'rufe an','einkaufen':'kaufe ein','fernsehen':'sehe fern','sich vorstellen':'stelle mich vor','sich kaemmen':'kaemme mich','sich kämmen':'kämme mich','sich rasieren':'rasiere mich','sich schminken':'schminke mich'};
  var app=document.getElementById('app'),topbar=document.getElementById('topbar');
  var catalog=[],byVerb={},state=null,view='home',params={},query='',filter='all';
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function norm(v){return String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[.,!?;:"'`´]/g,'').replace(/\s+/g,' ');}
  function slug(v){return norm(v).replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');}
  function uniq(a){var s={},o=[];(a||[]).forEach(function(v){v=String(v||'').trim();if(v&&!s[v]){s[v]=1;o.push(v);}});return o;}
  function read(k,f){try{return JSON.parse(localStorage.getItem(k)||'')||f;}catch(e){return f;}}
  function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));}catch(e){}}
  function profile(){return read('SP_USER_PROFILE',null)||read('SP_STUDENT_PROFILE',null)||{vorname:'Test',nachname:'Schueler',kurs:'test',muttersprache:'Englisch',email:'test@sprachpilot.local'};}
  function key(){var p=profile();return 'SP_VERBEN_TEST_LITE_'+slug((p.email||p.vorname||'test')+'_'+(p.kurs||p.courseCode||'test'));}
  function trans(v){var p=profile(),lang=p.muttersprache||'Englisch',d=(typeof VERB_TRANSLATIONS!=='undefined'?VERB_TRANSLATIONS:{});return d[lang]&&d[lang][v]||d.Englisch&&d.Englisch[v]||'';}
  function sentence(v){var d=(typeof VERB_SENTENCES!=='undefined'?VERB_SENTENCES:{});return d[v]||('Ich '+ich(v)+'.');}
  function ich(v){if(SPECIAL_ICH[v])return SPECIAL_ICH[v];if(/eln$/.test(v))return v.slice(0,-3)+'le';if(/ern$/.test(v))return v.slice(0,-3)+'ere';if(/en$/.test(v))return v.slice(0,-2)+'e';return v;}
  function img(v){return BUNNY+encodeURIComponent(SPECIAL_IMAGES[v]||SPECIAL_IMAGES[norm(v)]||(slug(v)+'.webp'));}
  function answerEq(a,b){return norm(a).replace(/\beuro\b/g,'eur').replace(/\bgramm\b/g,'g').replace(/\bliter\b/g,'l').replace(/\bkilo\b/g,'kg')===norm(b).replace(/\beuro\b/g,'eur').replace(/\bgramm\b/g,'g').replace(/\bliter\b/g,'l').replace(/\bkilo\b/g,'kg');}
  function shuffle(a){a=(a||[]).slice();for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=a[i];a[i]=a[j];a[j]=t;}return a;}
  function buildCatalog(){var raw=(typeof ALL_VERBS!=='undefined'&&Array.isArray(ALL_VERBS))?ALL_VERBS:[];var names=raw.map(function(x){return x&&x.v||x&&x.verb||x;});if(!names.length)names=FALLBACK;catalog=uniq(names).map(function(v){var item={verb:v,translation:trans(v),sentence:sentence(v),ich:ich(v)};byVerb[v]=item;return item;});}
  function defaultState(){return {version:VERSION,learned:[],learnList:[],package:null};}
  function loadState(){state=read(key(),null)||defaultState();if(!state||state.version!==VERSION)state=defaultState();state.learned=uniq(state.learned);state.learnList=uniq(state.learnList);save();}
  function save(){write(key(),state);}
  function header(){var p=profile();var name=[p.vorname||p.firstName||p.name,p.nachname||p.lastName].filter(Boolean).join(' ')||p.email||'Teilnehmer';var kurs=p.kurs||p.kursnummer||p.courseCode||'test';topbar.innerHTML='<div class="topbar-main"><a class="brand" href="/index.html"><img src="/assets/logo/sprachpilot-logo.png" alt=""><div><h1>SprachPilot</h1><div class="subtitle">Verben Test</div></div></a><div class="account"><span class="pill">'+esc(name)+' · '+esc(kurs)+'</span><a class="btn secondary" href="/student-dashboard/index.html">Dashboard</a><a class="btn secondary" href="/profile/index.html">Profil</a></div></div><nav class="nav"><button class="secondary" data-go="home">← Zurueck</button><button class="secondary" data-go="home">Uebersicht</button><button class="danger" data-action="reset">Fortschritte loeschen</button></nav>';}
  function learnedMap(){var m={};state.learned.forEach(function(v){m[v]=1;});return m;}
  function activeMap(){var m={};if(state.package)state.package.verbs.forEach(function(v){m[v]=1;});return m;}
  function openVerbs(){var l=learnedMap(),a=activeMap();return catalog.map(function(x){return x.verb;}).filter(function(v){return !l[v]&&!a[v];});}
  function emptyDone(){var o={};TASK_IDS.forEach(function(id){o[id]=[];});return o;}
  function emptyRepeat(){var o={};TASK_IDS.forEach(function(id){o[id]=[];});return o;}
  function taskPointValue(){return TASK_POINTS[Math.min(2,(state.package.round||1)-1)];}
  function examPointValue(){return EXAM_POINTS[Math.min(2,(state.package.round||1)-1)];}
  function taskPercent(id){var p=state.package;if(!p)return 0;return Math.round(uniq(p.done[id]||[]).length*100/p.verbs.length);}
  function allTasksDone(){return !!state.package&&TASK_IDS.every(function(id){return taskPercent(id)>=100;});}
  function packageComplete(){return allTasksDone()&&state.package.examBest>=100;}
  function totalPoints(){var p=state.package;if(!p)return 0;var n=p.pointsBank||0;Object.keys(p.taskPoints||{}).forEach(function(k){n+=Number(p.taskPoints[k]||0);});return n+Number(p.examPoints||0);}
  function go(v,p){view=v||'home';params=p||{};render();}
  function render(){header();if(view==='choose')return renderChoose();if(view==='overview')return renderOverview();if(view==='task')return renderTask(params.id);if(view==='exam')return renderExam();if(view==='assess')return renderAssess();renderHome();}
  function renderHome(){var p=state.package;app.innerHTML='<section class="card hero"><h2>Was moechtest du machen?</h2><div class="actions"><button '+(p?'':'disabled')+' data-go="overview">Ueben</button><button data-go="assess">Verben einschaetzen</button><button data-go="choose">Verben waehlen</button></div><p class="notice">'+(p?'Aktuelles Paket: '+p.verbs.length+' Verben · Runde '+p.round:'Bitte zuerst Verben waehlen oder einschaetzen.')+'</p></section><section class="card"><div class="stats"><div class="stat"><b>'+catalog.length+'</b>moegliche Verben</div><div class="stat"><b>'+state.learned.length+'</b>gelernt</div><div class="stat"><b>'+(p?p.verbs.length:0)+'</b>im Paket</div><div class="stat"><b>'+openVerbs().length+'</b>offen</div></div></section>';}
  function tags(v){var low=norm(v),t=[];if(low.indexOf('sich ')==0)t.push('reflexive');if(MODALS.map(norm).indexOf(low)>=0)t.push('modal');if(IRREGULAR.map(norm).indexOf(low)>=0||t.indexOf('modal')>=0)t.push('irregular');if(['ab','an','auf','aus','ein','mit','nach','vor','weg','zu','zurueck','fern'].some(function(p){return low.indexOf(p)===0&&low.length>p.length+3;}))t.push('separable');if(!t.length)t.push('regular');return t;}
  function renderChoose(){var verbs=state.learnList.concat(openVerbs().filter(function(v){return state.learnList.indexOf(v)<0;}));verbs=uniq(verbs).filter(function(v){var text=norm(v+' '+(byVerb[v]&&byVerb[v].translation||''));var okQuery=!query||text.indexOf(norm(query))>=0;var tg=tags(v);return okQuery&&(filter==='all'||tg.indexOf(filter)>=0);});var shown=verbs.slice(0,60);var rows=shown.map(function(v){var b=byVerb[v]||{};return '<label class="verb-row" data-tags="'+tags(v).join(' ')+'"><input type="checkbox" data-verb="'+esc(v)+'" '+(state.learnList.indexOf(v)>=0?'checked':'')+'><span><b>'+esc(v)+'</b><span class="translation">'+esc(b.translation||'')+'</span></span></label>';}).join('');app.innerHTML='<section class="card"><h2>Verben waehlen</h2><input class="search" data-search value="'+esc(query)+'" placeholder="Verb suchen"><div class="verb-filter-bar"><div class="filter-buttons">'+['all','regular','irregular','modal','separable','reflexive'].map(function(f){var label={all:'Alle',regular:'Regulaer',irregular:'Irregulaer',modal:'Modal',separable:'Trennbar',reflexive:'Reflexiv'}[f];return '<button class="filter-chip '+(filter===f?'active':'')+'" data-filter="'+f+'">'+label+'</button>';}).join('')+'</div><div class="choice-count">'+verbs.length+' gefunden · maximal 60 sichtbar</div></div><div class="actions"><button class="secondary" data-action="select-visible">Erste 20 auswaehlen</button><button class="secondary" data-action="clear-choice">Auswahl loeschen</button><button data-action="start-choice">Auswahl starten</button></div><div class="verb-list">'+(rows||'<p class="small">Keine Verben gefunden.</p>')+'</div></section>';}
  function renderAssess(){var taken={};state.learned.concat(state.learnList,state.package?state.package.verbs:[]).forEach(function(v){taken[v]=1;});var v=catalog.map(function(x){return x.verb;}).find(function(x){return !taken[x];});if(!v){go('choose');return;}var b=byVerb[v]||{};app.innerHTML='<section class="card assessment"><div class="image-box"><img src="'+esc(img(v))+'" alt="'+esc(v)+'"></div><div><h2>Verben einschaetzen</h2><div class="question">'+esc(v)+'</div><p>'+esc(b.translation||'')+'</p><div class="actions"><button data-assess="learn" data-verb="'+esc(v)+'">Lernen</button><button class="secondary" data-assess="known" data-verb="'+esc(v)+'">Kann ich schon</button><button class="secondary" data-go="home">Spaeter</button></div></div></section>';}
  function startPackage(list){list=uniq(list).filter(function(v){return byVerb[v]&&!learnedMap()[v];}).slice(0,PACKAGE_SIZE);if(!list.length){alert('Bitte mindestens ein Verb auswaehlen.');return;}state.package={verbs:list,round:1,done:emptyDone(),repeat:emptyRepeat(),taskPoints:{},pointsBank:0,current:null,examBest:0,examPoints:0,examRun:null};state.learnList=state.learnList.filter(function(v){return list.indexOf(v)<0;});save();go('overview');}
  function renderOverview(){var p=state.package;if(!p){go('choose');return;}app.innerHTML='<section class="card"><div class="task-head"><div><h2>Aufgabenuebersicht</h2><p>'+p.verbs.length+' Verben · Runde '+p.round+' · '+totalPoints()+' Punkte</p></div>'+(packageComplete()?'<button data-action="'+(p.round<3?'repeat':'finish')+'">'+(p.round<3?'Wiederholen':'Neue Verben waehlen')+'</button>':'')+'</div>'+(packageComplete()?'<p class="notice">'+(p.round<3?'Wiederhole alle Aufgaben und bekomme mehr Punkte.':'Du bist fertig.')+'</p>':'')+'</section><section class="grid">'+TASKS.map(function(t,i){var pr=taskPercent(t[0]);return '<button class="module" data-task="'+t[0]+'"><div class="icon">'+(i+1)+'</div><h3>'+(i+1)+'. '+esc(t[1])+'</h3><div class="progress"><div class="bar" style="width:'+pr+'%"></div></div><b>'+pr+'%</b></button>';}).join('')+'<button class="module '+(allTasksDone()?'':'locked')+'" data-go="exam"><div class="icon">*</div><h3>Pruefung</h3><b>'+(allTasksDone()?(p.examBest||0)+'%':'gesperrt')+'</b></button></section>';}
  function nextVerb(task){var p=state.package,d=uniq(p.done[task]||[]),r=uniq(p.repeat[task]||[]),dm={};d.forEach(function(v){dm[v]=1;});return p.verbs.find(function(v){return !dm[v]&&r.indexOf(v)<0;})||r.find(function(v){return !dm[v];})||null;}
  function renderTask(task){var p=state.package;if(!p){go('choose');return;}var v=nextVerb(task);if(!v){app.innerHTML='<section class="card finish"><h2>Gut gemacht</h2><p>Diese Aufgabe ist fertig.</p><button data-go="overview">Weiter</button></section>';return;}p.current={task:task,verb:v,wrong:false,tries:0};save();drawTask('');}
  function drawTask(feedback){var p=state.package,c=p.current,v=c.verb,b=byVerb[v]||{},task=c.task,answer=task==='konjugieren'?b.ich:(task==='satz-puzzle'?b.sentence:v);var body;if(task==='karteikarten'){body=flashcardHtml(v,b);}else if(task==='bild-verb'||task==='memory'){body=imgHtml(v)+choiceHtml(v,false);}else if(task==='verb-bild'){body='<div class="question">'+esc(v)+'</div>'+choiceHtml(v,true);}else{body=(task.indexOf('bild')>=0?imgHtml(v):'')+'<div class="question">'+esc(task.indexOf('hoeren')>=0?'Deutsch':(task==='konjugieren'?'ich + '+v:'Satz schreiben'))+'</div>'+(task.indexOf('hoeren')>=0?'<div class="actions"><button class="secondary" data-speak="'+esc(v)+'">Deutsch anhoeren</button></div>':'')+'<input class="answer-input" data-input placeholder="Antwort schreiben"><div class="actions"><button data-check="'+esc(answer)+'">Kontrollieren</button>'+(task.indexOf('sprechen')>=0?'<button class="secondary" data-mic="'+esc(v)+'">Mikrofon</button>':'')+'</div>';}
    app.innerHTML='<section class="card"><div class="task-head"><div><h2>'+esc(TASKS.find(function(t){return t[0]===task;})[1])+'</h2><p>'+taskPercent(task)+'% fertig</p></div><button class="secondary" data-go="overview">Aufgabenuebersicht</button></div>'+body+'<div class="feedback">'+feedback+'</div></section>';}
  function flashcardHtml(v,b){return '<div class="flip-wrap"><div class="flip-card" role="button" tabindex="0" aria-label="Karte umdrehen" data-flip-card><div class="flip-face flip-front">'+imgHtml(v)+'<div class="small">Klicken: Karte umdrehen</div></div><div class="flip-face flip-back"><div class="flip-word">'+esc(v)+'</div>'+(b.translation?'<div class="flip-note">'+esc(b.translation)+'</div>':'')+'<button type="button" class="btn secondary card-listen-btn" data-speak="'+esc(v)+'">Hören</button></div></div></div><div class="actions card-actions"><button data-correct>Kann ich</button><button class="secondary" data-wrong>Noch einmal</button></div>';}
  function imgHtml(v){return '<div class="image-box"><img src="'+esc(img(v))+'" alt="'+esc(v)+'" onerror="this.parentNode.innerHTML=\'Bild fehlt\'"></div>';}
  function choiceHtml(answer,asImage){var list=shuffle([answer].concat(shuffle(state.package.verbs.filter(function(v){return v!==answer;})).slice(0,3))).slice(0,4);return '<div class="choices">'+list.map(function(v){return '<button class="choice" data-answer="'+esc(v)+'">'+(asImage?'<img src="'+esc(img(v))+'" alt="'+esc(v)+'">':esc(v))+'</button>';}).join('')+'</div>';}
  function wrong(){var p=state.package,c=p.current,b=byVerb[c.verb]||{};c.wrong=true;c.tries++;save();var hint=c.tries===1?'Bedeutung: '+(b.translation||''):(c.tries===2?'Satz: '+b.sentence:'Antwort: '+(c.task==='konjugieren'?b.ich:c.verb));drawTask('<div class="no">Noch nicht richtig. Versuch es noch einmal.</div><div class="hint">'+esc(hint)+'</div>');}
  function correct(){var p=state.package,c=p.current,task=c.task,v=c.verb;if(c.wrong){p.repeat[task]=uniq((p.repeat[task]||[]).concat([v]));p.current=null;save();setTimeout(function(){renderTask(task);},500);return;}p.done[task]=uniq((p.done[task]||[]).concat([v]));p.repeat[task]=uniq(p.repeat[task]||[]).filter(function(x){return x!==v;});if(taskPercent(task)>=100&&!p.taskPoints[task])p.taskPoints[task]=taskPointValue();p.current=null;save();setTimeout(function(){renderTask(task);},400);}
  function renderExam(){var p=state.package;if(!p||!allTasksDone()){app.innerHTML='<section class="card"><h2>Pruefung ist gesperrt</h2><button data-go="overview">Zurueck</button></section>';return;}if(!p.examRun)p.examRun={index:0,answers:[],verbs:shuffle(p.verbs)};var v=p.examRun.verbs[p.examRun.index];if(!v)return finishExam();app.innerHTML='<section class="card"><h2>* Pruefung</h2><p>Frage '+(p.examRun.index+1)+' von '+p.examRun.verbs.length+'</p>'+imgHtml(v)+'<input class="answer-input" data-input placeholder="Verb schreiben"><button data-exam-check="'+esc(v)+'">Kontrollieren</button></section>';save();}
  function finishExam(){var p=state.package,a=p.examRun.answers,right=a.filter(function(x){return x.right;}).length,score=Math.round(right*100/p.verbs.length);p.examBest=Math.max(p.examBest||0,score);if(score>=100&&!p.examPoints)p.examPoints=examPointValue();p.examRun=null;save();app.innerHTML='<section class="card finish"><h2>Pruefung beendet</h2><p>'+score+'% richtig.</p><button data-go="overview">Weiter</button></section>';}
  function repeatPackage(){var p=state.package;if(!packageComplete()||p.round>=3)return;p.pointsBank=totalPoints();p.round++;p.done=emptyDone();p.repeat=emptyRepeat();p.taskPoints={};p.examBest=0;p.examPoints=0;p.examRun=null;p.current=null;save();go('overview');}
  function finishPackage(){if(!packageComplete())return;state.learned=uniq(state.learned.concat(state.package.verbs));state.package=null;save();go('choose');}
  function startMic(answer){var SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){var f=document.querySelector('.feedback');if(f)f.innerHTML='<div class="no">Mikrofon wird nicht unterstuetzt. Bitte schreibe die Antwort.</div>';return;}var rec=new SR();rec.lang='de-DE';rec.onresult=function(e){var text=e.results[0][0].transcript,input=document.querySelector('[data-input]');if(input)input.value=text;answerEq(text,answer)?correct():wrong();};rec.onerror=function(){var f=document.querySelector('.feedback');if(f)f.innerHTML='<div class="no">Mikrofon konnte nicht geprueft werden. Bitte schreibe.</div>';};rec.start();}
  document.addEventListener('input',function(e){if(e.target&&e.target.matches('[data-search]')){query=e.target.value;clearTimeout(window.__vtSearchTimer);window.__vtSearchTimer=setTimeout(renderChoose,120);}});
  document.addEventListener('click',function(e){var flip=e.target.closest('[data-flip-card]');if(flip&&!e.target.closest('button')){flip.classList.add('flipped');return;}var t=e.target.closest('[data-go],[data-action],[data-task],[data-filter],[data-assess],[data-answer],[data-correct],[data-wrong],[data-check],[data-speak],[data-mic],[data-exam-check]');if(!t)return;if(t.dataset.go){go(t.dataset.go);return;}if(t.dataset.filter){filter=t.dataset.filter;renderChoose();return;}if(t.dataset.task){go('task',{id:t.dataset.task});return;}if(t.dataset.assess){var av=t.dataset.verb;if(t.dataset.assess==='known')state.learned=uniq(state.learned.concat([av]));else state.learnList=uniq(state.learnList.concat([av]));save();renderAssess();return;}if(t.dataset.action){if(t.dataset.action==='reset'){if(confirm('Fortschritte loeschen?')){state=defaultState();save();go('home');}}if(t.dataset.action==='select-visible'){var n=0;[].slice.call(document.querySelectorAll('.verb-row')).forEach(function(r){var i=r.querySelector('input');if(n<PACKAGE_SIZE){i.checked=true;n++;}});}if(t.dataset.action==='clear-choice'){state.learnList=[];[].slice.call(document.querySelectorAll('input[data-verb]')).forEach(function(i){i.checked=false;});}if(t.dataset.action==='start-choice'){startPackage([].slice.call(document.querySelectorAll('input[data-verb]:checked')).map(function(i){return i.dataset.verb;}));}if(t.dataset.action==='repeat')repeatPackage();if(t.dataset.action==='finish')finishPackage();return;}if(t.dataset.correct!==undefined){correct();return;}if(t.dataset.wrong!==undefined){wrong();return;}if(t.dataset.answer){answerEq(t.dataset.answer,state.package.current.verb)?correct():wrong();return;}if(t.dataset.check){var val=(document.querySelector('[data-input]')||{}).value||'';answerEq(val,t.dataset.check)?correct():wrong();return;}if(t.dataset.speak){try{speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(t.dataset.speak);u.lang='de-DE';u.rate=.86;speechSynthesis.speak(u);}catch(x){}return;}if(t.dataset.mic){startMic(t.dataset.mic);return;}if(t.dataset.examCheck){var given=(document.querySelector('[data-input]')||{}).value||'',r=answerEq(given,t.dataset.examCheck);state.package.examRun.answers.push({verb:t.dataset.examCheck,given:given,right:r});state.package.examRun.index++;save();renderExam();return;}});
  document.addEventListener('keydown',function(e){var card=e.target.closest&&e.target.closest('[data-flip-card]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();card.classList.add('flipped');}});
  buildCatalog();loadState();render();
})();
