(function(){
  'use strict';

  var VERSION='20260715-clean-1';
  var PACKAGE_SIZE=20;
  var TASK_POINTS=[5,10,15];
  var EXAM_POINTS=[100,200,300];
  var BUNNY='https://sprachpilot.b-cdn.net/verben-A1/bilder/';
  var TASKS=[
    {id:'karteikarten',title:'Karteikarten',icon:'Karten',desc:'Bild, Verb und Bedeutung lernen.'},
    {id:'memory',title:'Memory',icon:'Memory',desc:'Verb und Bild verbinden.'},
    {id:'bild-verb',title:'Bild -> Verb',icon:'Bild',desc:'Zum Bild das richtige Verb waehlen.'},
    {id:'verb-bild',title:'Verb -> Bild',icon:'Bild',desc:'Zum Verb das richtige Bild waehlen.'},
    {id:'schreiben',title:'Schreiben',icon:'Text',desc:'Das Verb richtig schreiben.'},
    {id:'hoeren-schreiben',title:'Hoeren -> Schreiben',icon:'Audio',desc:'Deutsch hoeren und schreiben.'},
    {id:'hoeren-sprechen',title:'Hoeren -> Sprechen',icon:'Mikro',desc:'Deutsch hoeren und sprechen oder schreiben.'},
    {id:'bild-sprechen',title:'Bild -> Sprechen',icon:'Mikro',desc:'Zum Bild sprechen oder schreiben.'},
    {id:'satz-puzzle',title:'Satz-Puzzle',icon:'Satz',desc:'Den Beispielsatz richtig schreiben.'},
    {id:'konjugieren',title:'Konjugieren',icon:'Ich',desc:'Die Ich-Form schreiben.'}
  ];
  var TASK_IDS=TASKS.map(function(t){return t.id;});
  var MODALS=['koennen','können','muessen','müssen','duerfen','dürfen','wollen','sollen','moegen','mögen'];
  var IRREGULAR=['sein','haben','werden','wissen','tun','geben','nehmen','essen','sprechen','lesen','sehen','fahren','laufen','schlafen','helfen','treffen','tragen','waschen','fallen','fangen','halten','lassen','gefallen','bringen','denken','kennen','nennen'];
  var PREFIXES=['ab','an','auf','aus','ein','mit','nach','vor','weg','zu','zurueck','zurück','fern','los'];
  var SPECIAL_IMAGES={
    'sich vorstellen':'sich_vorstellen.webp','sich kaemmen':'sich_kaemmen.webp','sich kämmen':'sich_kaemmen.webp','sich rasieren':'sich_rasieren.webp','sich schminken':'sich_schminken.webp','sich bewegen':'sich_bewegen.webp','sich veraendern':'sich_veraendern.webp','sich verändern':'sich_veraendern.webp','koennen':'koennen.webp','können':'koennen.webp','oeffnen':'oeffnen.webp','öffnen':'oeffnen.webp','schliessen':'schliessen.webp','schließen':'schliessen.webp','reissen':'reissen.webp','reißen':'reissen.webp'
  };
  var SPECIAL_ICH={sein:'bin',haben:'habe',werden:'werde',wissen:'weiss',tun:'tue','können':'kann',koennen:'kann','müssen':'muss',muessen:'muss','dürfen':'darf',duerfen:'darf',wollen:'will',sollen:'soll','mögen':'mag',moegen:'mag',sehen:'sehe',lesen:'lese',sprechen:'spreche',essen:'esse',nehmen:'nehme',geben:'gebe',helfen:'helfe',treffen:'treffe',fahren:'fahre',laufen:'laufe',schlafen:'schlafe','aufstehen':'stehe auf','anfangen':'fange an','anrufen':'rufe an','einkaufen':'kaufe ein','fernsehen':'sehe fern','sich vorstellen':'stelle mich vor','sich kämmen':'kämme mich','sich rasieren':'rasiere mich','sich schminken':'schminke mich'};

  var app=document.getElementById('app');
  var topbar=document.getElementById('topbar');
  var catalog=[];
  var byVerb={};
  var state=null;
  var currentView='home';
  var currentParams={};

  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch];});}
  function norm(v){return String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[.,!?;:"'`´]/g,'').replace(/\s+/g,' ');}
  function slug(v){return norm(v).replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');}
  function uniq(list){var seen={},out=[];(list||[]).forEach(function(v){v=String(v||'').trim();if(v&&!seen[v]){seen[v]=1;out.push(v);}});return out;}
  function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'')||fallback;}catch(e){return fallback;}}
  function writeJson(key,value){localStorage.setItem(key,JSON.stringify(value));}
  function profile(){return readJson('SP_USER_PROFILE',null)||readJson('SP_STUDENT_PROFILE',null)||{vorname:'Test',nachname:'Schueler',kurs:'test',muttersprache:'Englisch',email:'test@sprachpilot.local'};}
  function profileName(){var p=profile();return [p.vorname||p.firstName||p.name,p.nachname||p.lastName].filter(Boolean).join(' ')||p.email||'Teilnehmer';}
  function courseCode(){var p=profile();return p.kurs||p.kursnummer||p.courseCode||'test';}
  function storageKey(){var p=profile();return 'SP_VERBEN_TEST_V2_'+slug([p.email||profileName(),courseCode()].join('_'));}
  function language(){var p=profile();return p.muttersprache||p.motherLanguage||'Englisch';}
  function translation(verb){var data=window.VERB_TRANSLATIONS||{};var lang=language();return (data[lang]&&data[lang][verb])||(data.Englisch&&data.Englisch[verb])||(data.Russisch&&data.Russisch[verb])||'';}
  function sentence(verb){var data=window.VERB_SENTENCES||{};return data[verb]||('Ich '+ichForm(verb)+'.');}
  function ichForm(verb){if(SPECIAL_ICH[verb])return SPECIAL_ICH[verb];if(/eln$/.test(verb))return verb.slice(0,-3)+'le';if(/ern$/.test(verb))return verb.slice(0,-3)+'ere';if(/en$/.test(verb))return verb.slice(0,-2)+'e';return verb;}
  function imageFile(verb,item){var explicit=item&&(item.img||item.image||item.bild);if(explicit)return String(explicit).replace(/^.*\//,'');return SPECIAL_IMAGES[verb]||SPECIAL_IMAGES[norm(verb)]||(slug(verb)+'.webp');}
  function imgUrl(verb){var item=byVerb[verb]||{};return BUNNY+encodeURIComponent(imageFile(verb,item)).replace(/%2F/g,'/');}
  function speak(text){try{window.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(text);u.lang='de-DE';u.rate=.9;window.speechSynthesis.speak(u);}catch(e){}}
  function shuffle(list){var out=(list||[]).slice();for(var i=out.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var t=out[i];out[i]=out[j];out[j]=t;}return out;}
  function sameAnswer(a,b){return norm(a).replace(/\beuro\b/g,'eur').replace(/\bgramm\b/g,'g').replace(/\bliter\b/g,'l').replace(/\bkilo\b/g,'kg')===norm(b).replace(/\beuro\b/g,'eur').replace(/\bgramm\b/g,'g').replace(/\bliter\b/g,'l').replace(/\bkilo\b/g,'kg');}

  function buildCatalog(){
    var raw=Array.isArray(window.ALL_VERBS)?window.ALL_VERBS:[];
    var names=[];
    raw.forEach(function(item){names.push(item&&item.v||item&&item.verb||item&&item.infinitive||item);});
    Object.keys(window.VERB_TRANSLATIONS||{}).forEach(function(lang){Object.keys(window.VERB_TRANSLATIONS[lang]||{}).forEach(function(v){names.push(v);});});
    catalog=uniq(names).map(function(v){var rawItem=raw.find(function(item){return (item&&item.v)===v||(item&&item.verb)===v;})||{};var item={verb:v,translation:translation(v),sentence:sentence(v),ich:ichForm(v),raw:rawItem};byVerb[v]=item;return item;});
  }
  function defaultState(){return {version:VERSION,learned:[],assessmentKnown:[],assessmentLearn:[],package:null};}
  function loadState(){state=readJson(storageKey(),null)||defaultState();if(!state||state.version!==VERSION)state=defaultState();state.learned=uniq(state.learned);state.assessmentKnown=uniq(state.assessmentKnown);state.assessmentLearn=uniq(state.assessmentLearn);save();}
  function save(){writeJson(storageKey(),state);}
  function emptyDone(){var o={};TASK_IDS.forEach(function(id){o[id]=[];});return o;}
  function emptyRepeat(){var o={};TASK_IDS.forEach(function(id){o[id]=[];});return o;}
  function pkg(){return state.package;}
  function taskValue(){return TASK_POINTS[Math.min(2,Math.max(0,(pkg().round||1)-1))];}
  function examValue(){return EXAM_POINTS[Math.min(2,Math.max(0,(pkg().round||1)-1))];}
  function learnedSet(){var s={};state.learned.forEach(function(v){s[v]=1;});return s;}
  function activeSet(){var s={};if(pkg())pkg().verbs.forEach(function(v){s[v]=1;});return s;}
  function openVerbs(){var l=learnedSet(),a=activeSet();return catalog.map(function(x){return x.verb;}).filter(function(v){return !l[v]&&!a[v];});}
  function plannedVerbs(){var open={};openVerbs().forEach(function(v){open[v]=1;});return state.assessmentLearn.filter(function(v){return open[v];});}
  function typeTags(verb){var low=norm(verb),tags=[];if(low.indexOf('sich ')==0)tags.push('reflexive');if(MODALS.map(norm).indexOf(low)>=0)tags.push('modal');if(IRREGULAR.map(norm).indexOf(low)>=0||tags.indexOf('modal')>=0)tags.push('irregular');if(PREFIXES.some(function(p){return low.indexOf(p)===0&&low.length>p.length+3&&low.indexOf('sich ')!==0;}))tags.push('separable');if(!tags.length)tags.push('regular');return tags;}
  function choices(answer){var pool=(pkg()?pkg().verbs:catalog.map(function(x){return x.verb;})).filter(function(v){return v!==answer;});return shuffle([answer].concat(shuffle(pool).slice(0,3))).slice(0,4);}
  function taskDoneCount(task){return pkg()?uniq(pkg().taskDone[task]||[]).length:0;}
  function taskPercent(task){return pkg()?Math.round(taskDoneCount(task)*100/pkg().verbs.length):0;}
  function allTasksDone(){return !!pkg()&&TASK_IDS.every(function(id){return taskPercent(id)>=100;});}
  function packageComplete(){return allTasksDone()&&pkg()&&pkg().examBest>=100;}
  function totalPoints(){var p=pkg();if(!p)return 0;var n=p.pointsBank||0;Object.keys(p.taskPoints||{}).forEach(function(k){n+=Number(p.taskPoints[k]||0);});n+=Number(p.examPoints||0);return n;}
  function go(view,params){currentView=view||'home';currentParams=params||{};render();}

  function header(){topbar.innerHTML='<div class="topbar-main"><a class="brand" href="/index.html"><img src="/assets/logo/sprachpilot-logo.png" alt=""><div><h1>SprachPilot</h1><div class="subtitle">Verben Test</div></div></a><div class="account"><span class="pill">'+esc(profileName())+' · '+esc(courseCode())+'</span><a class="btn secondary" href="/student-dashboard/index.html">Dashboard</a><a class="btn secondary" href="/profile/index.html">Profil</a></div></div><nav class="nav"><button class="secondary" data-go="home">← Zurueck</button><button class="secondary" data-go="home">Uebersicht</button><button class="danger" data-action="reset">Fortschritte loeschen</button></nav>';}
  function card(title,body){return '<section class="card"><h2>'+esc(title)+'</h2>'+body+'</section>';}
  function render(){header();if(currentView==='choose')return renderChoose();if(currentView==='assess')return renderAssess();if(currentView==='overview')return renderOverview();if(currentView==='task')return renderTask(currentParams.id);if(currentView==='exam')return renderExam();renderHome();}
  function renderHome(){var has=!!pkg();var learned=state.learned.length;var open=openVerbs().length;app.innerHTML='<section class="card hero"><h2>Was moechtest du machen?</h2><div class="actions"><button '+(has?'':'disabled')+' data-go="overview">Ueben</button><button data-go="assess">Verben einschaetzen</button><button data-go="choose">Verben waehlen</button></div>'+(has?'<p class="notice">Aktuelles Paket: '+pkg().verbs.length+' Verben · Runde '+pkg().round+' · '+totalPoints()+' Punkte</p>':'<p class="notice">Bitte zuerst Verben waehlen oder einschaetzen.</p>')+'</section><section class="card"><div class="stats"><div class="stat"><b>'+catalog.length+'</b>moegliche Verben</div><div class="stat"><b>'+learned+'</b>gelernt</div><div class="stat"><b>'+(has?pkg().verbs.length:0)+'</b>im Paket</div><div class="stat"><b>'+open+'</b>offen</div></div></section>'+(has?packageSummary():'');}
  function packageSummary(){return '<section class="card"><h2>Aktuelles Paket</h2><div class="package-list">'+pkg().verbs.map(function(v){return '<span class="pill">'+esc(v)+'</span>';}).join('')+'</div>'+(packageComplete()?'<p class="notice">Wiederhole alle Aufgaben und bekomme mehr Punkte.</p><div class="actions">'+(pkg().round<3?'<button data-action="repeat">Wiederholen</button>':'<button data-action="finish">Neue Verben waehlen</button>')+'</div>':'')+'</section>';}
  function renderChoose(){var selectedFromPlan=plannedVerbs();var verbs=uniq(selectedFromPlan.concat(openVerbs().filter(function(v){return selectedFromPlan.indexOf(v)<0;})));var rows=verbs.map(function(v){var item=byVerb[v];var tags=typeTags(v);return '<label class="verb-row" data-tags="'+tags.join(' ')+'"><input type="checkbox" data-verb="'+esc(v)+'" '+(selectedFromPlan.indexOf(v)>=0?'checked':'')+'><span><b>'+esc(v)+'</b><span class="translation">'+esc(item.translation||'')+'</span></span></label>';}).join('');app.innerHTML='<section class="card"><h2>Verben waehlen</h2><input class="search" data-search placeholder="Verb suchen"><div class="verb-filter-bar"><div class="filter-buttons">'+['all','regular','irregular','modal','separable','reflexive'].map(function(f){return '<button class="filter-chip '+(f==='all'?'active':'')+'" data-filter="'+f+'">'+({all:'Alle',regular:'Regulaer',irregular:'Irregulaer',modal:'Modal',separable:'Trennbar',reflexive:'Reflexiv'}[f])+'</button>';}).join('')+'</div><div class="choice-count" data-count></div></div><div class="actions"><button class="secondary" data-action="select-visible">Erste 20 auswaehlen</button><button class="secondary" data-action="clear-choice">Auswahl loeschen</button></div><div class="verb-list">'+(rows||'<p class="small">Keine offenen Verben.</p>')+'</div><div class="actions"><button data-action="start-choice">Auswahl starten</button></div></section>';updateChooseFilter();}
  function renderAssess(){var decided={};state.learned.concat(pkg()?pkg().verbs:[],state.assessmentKnown,state.assessmentLearn).forEach(function(v){decided[v]=1;});var next=catalog.map(function(x){return x.verb;}).find(function(v){return !decided[v];});if(!next){app.innerHTML=card('Einschaetzen fertig','<p>Du kannst jetzt Verben waehlen.</p><div class="actions"><button data-go="choose">Verben waehlen</button></div>');return;}var item=byVerb[next];app.innerHTML='<section class="card assessment"><div class="image-box"><img src="'+esc(imgUrl(next))+'" alt="'+esc(next)+'" onerror="this.parentNode.innerHTML=\'Bild fehlt\'"></div><div><h2>Verben einschaetzen</h2><div class="question">'+esc(next)+'</div><p>'+esc(item.translation||'')+'</p><div class="actions"><button data-assess="learn" data-verb="'+esc(next)+'">Lernen</button><button class="secondary" data-assess="known" data-verb="'+esc(next)+'">Kann ich schon</button><button class="secondary" data-go="home">Spaeter</button></div></div></section>';}
  function startPackage(verbs){verbs=uniq(verbs).filter(function(v){return byVerb[v]&&!learnedSet()[v];}).slice(0,PACKAGE_SIZE);if(!verbs.length){alert('Bitte mindestens ein Verb auswaehlen.');return;}state.package={id:String(Date.now()),verbs:verbs,round:1,taskDone:emptyDone(),taskRepeat:emptyRepeat(),taskPoints:{},pointsBank:0,current:null,examBest:0,examPoints:0,examRun:null};state.assessmentLearn=state.assessmentLearn.filter(function(v){return verbs.indexOf(v)<0;});save();go('overview');}
  function renderOverview(){if(!pkg()){go('choose');return;}var examReady=allTasksDone();app.innerHTML='<section class="card"><div class="task-head"><div><h2>Aufgabenuebersicht</h2><p>'+pkg().verbs.length+' Verben · Runde '+pkg().round+' · '+totalPoints()+' Punkte</p></div>'+(packageComplete()?'<button data-action="'+(pkg().round<3?'repeat':'finish')+'">'+(pkg().round<3?'Wiederholen':'Neue Verben waehlen')+'</button>':'')+'</div>'+(packageComplete()?'<p class="notice">'+(pkg().round<3?'Wiederhole alle Aufgaben und bekomme mehr Punkte.':'Du bist fertig.')+'</p>':'')+'</section><section class="grid">'+TASKS.map(function(t,i){var p=taskPercent(t.id);return '<button class="module" data-task="'+t.id+'"><div class="icon">'+esc(t.icon)+'</div><h3>'+(i+1)+'. '+esc(t.title)+'</h3><p>'+esc(t.desc)+'</p><div class="progress"><div class="bar" style="width:'+p+'%"></div></div><b>'+p+'%</b></button>';}).join('')+'<button class="module '+(examReady?'':'locked')+'" data-go="exam"><div class="icon">Stern</div><h3>Pruefung</h3><p>'+(examReady?'Pruefung machen.':'Erst alle Aufgaben auf 100%.')+'</p><div class="progress"><div class="bar" style="width:'+(pkg().examBest||0)+'%"></div></div><b>'+(examReady?(pkg().examBest||0)+'%':'gesperrt')+'</b></button></section>';}
  function nextVerb(task){var p=pkg(),done=uniq(p.taskDone[task]||[]),repeat=uniq(p.taskRepeat[task]||[]);var doneMap={};done.forEach(function(v){doneMap[v]=1;});var normal=p.verbs.find(function(v){return !doneMap[v]&&repeat.indexOf(v)<0;});return normal||repeat.find(function(v){return !doneMap[v];})||null;}
  function renderTask(task){if(!pkg()){go('choose');return;}if(TASK_IDS.indexOf(task)<0){go('overview');return;}var verb=nextVerb(task);if(!verb){app.innerHTML=card('Gut gemacht','<p>Diese Aufgabe ist fertig.</p><div class="actions"><button data-go="overview">Weiter</button></div>');return;}pkg().current={task:task,verb:verb,hadWrong:false};save();drawTask(task,verb,'');}
  function taskTitle(task){var t=TASKS.find(function(x){return x.id===task;});return t?t.title:task;}
  function drawTask(task,verb,feedback){var item=byVerb[verb],body='',answer=task==='konjugieren'?item.ich:(task==='satz-puzzle'?item.sentence:verb);if(task==='karteikarten'){body=imageHtml(verb)+'<div class="question">'+esc(verb)+'</div><p class="small">'+esc(item.translation||'')+'</p><div class="actions"><button data-correct="1">Kann ich</button><button class="secondary" data-wrong="1">Noch einmal</button></div>';}else if(task==='bild-verb'||task==='memory'){body=imageHtml(verb)+'<div class="choices">'+choices(verb).map(function(v){return '<button class="choice" data-answer="'+esc(v)+'">'+esc(v)+'</button>';}).join('')+'</div>';}else if(task==='verb-bild'){body='<div class="question">'+esc(verb)+'</div><div class="choices">'+choices(verb).map(function(v){return '<button class="choice" data-answer="'+esc(v)+'"><img src="'+esc(imgUrl(v))+'" alt="'+esc(v)+'"></button>';}).join('')+'</div>';}else{var prompt=task==='konjugieren'?'ich + '+verb:(task==='satz-puzzle'?item.sentence.replace(/[.!?]/g,''):'Deutsch');body=(task.indexOf('bild')>=0?imageHtml(verb):'')+'<div class="question">'+esc(prompt)+'</div>'+(task.indexOf('hoeren')>=0?'<div class="actions"><button class="secondary" data-speak="'+esc(verb)+'">Deutsch anhoeren</button></div>':'')+'<input class="answer-input" data-input placeholder="Antwort schreiben"><div class="actions"><button data-check="'+esc(answer)+'">Kontrollieren</button>'+(task.indexOf('sprechen')>=0?'<button class="secondary" data-mic="'+esc(verb)+'">Mikrofon</button>':'')+'</div>';}
    app.innerHTML='<section class="card"><div class="task-head"><div><h2>'+(TASK_IDS.indexOf(task)+1)+'. '+esc(taskTitle(task))+'</h2><p>'+taskPercent(task)+'% fertig</p></div><button class="secondary" data-go="overview">Aufgabenuebersicht</button></div>'+body+'<div class="feedback">'+feedback+'</div></section>';}
  function imageHtml(verb){return '<div class="image-box"><img src="'+esc(imgUrl(verb))+'" alt="'+esc(verb)+'" onerror="this.parentNode.innerHTML=\'Bild fehlt\'"></div>';}
  function wrongFeedback(task,verb){var cur=pkg().current;cur.hadWrong=true;save();var item=byVerb[verb],tries=(cur.tries||0)+1;cur.tries=tries;var hint=tries===1?'Hilfe 1: Bedeutung: '+(item.translation||''):(tries===2?'Hilfe 2: Beispielsatz: '+item.sentence:'Hilfe 3: richtige Antwort: '+(task==='konjugieren'?item.ich:verb));drawTask(task,verb,'<div class="no">Noch nicht richtig. Versuch es noch einmal.</div><div class="hint">'+esc(hint)+'</div>');}
  function markCorrect(task,verb){var p=pkg(),cur=p.current||{};if(cur.hadWrong){p.taskRepeat[task]=uniq((p.taskRepeat[task]||[]).concat([verb]));p.current=null;save();app.querySelector('.feedback').innerHTML='<div class="ok">Richtig. Dieses Verb kommt am Ende noch einmal.</div>';setTimeout(function(){renderTask(task);},650);return;}p.taskDone[task]=uniq((p.taskDone[task]||[]).concat([verb]));p.taskRepeat[task]=uniq(p.taskRepeat[task]||[]).filter(function(v){return v!==verb;});if(taskPercent(task)>=100&&!p.taskPoints[task])p.taskPoints[task]=taskValue();p.current=null;save();app.querySelector('.feedback').innerHTML='<div class="ok">Richtig.</div>';setTimeout(function(){if(taskPercent(task)>=100)app.innerHTML=card('Gut gemacht','<p>Diese Aufgabe ist fertig.</p><div class="actions"><button data-go="overview">Weiter</button></div>');else renderTask(task);},500);}
  function renderExam(){if(!pkg()){go('choose');return;}if(!allTasksDone()){app.innerHTML=card('Pruefung ist gesperrt','<p>Erst alle Aufgaben auf 100% bringen.</p><div class="actions"><button data-go="overview">Zur Aufgabenuebersicht</button></div>');return;}var p=pkg();if(!p.examRun)p.examRun={index:0,answers:[],verbs:shuffle(p.verbs)};var verb=p.examRun.verbs[p.examRun.index];if(!verb)return finishExam();app.innerHTML='<section class="card"><div class="task-head"><div><h2>Stern Pruefung</h2><p>Frage '+(p.examRun.index+1)+' von '+p.examRun.verbs.length+'</p></div><button class="secondary" data-go="overview">Aufgabenuebersicht</button></div>'+imageHtml(verb)+'<input class="answer-input" data-input placeholder="Verb schreiben"><div class="actions"><button data-exam-check="'+esc(verb)+'">Kontrollieren</button></div><div class="feedback"></div></section>';save();}
  function finishExam(){var p=pkg(),answers=p.examRun.answers,right=answers.filter(function(a){return a.right;}).length,score=Math.round(right*100/p.verbs.length);p.examBest=Math.max(p.examBest||0,score);if(score>=100&&!p.examPoints)p.examPoints=examValue();p.examRun=null;save();app.innerHTML='<section class="card finish"><div class="stars">Stern</div><h2>'+(score>=100?'Pruefung bestanden':'Pruefung beendet')+'</h2><p>'+score+'% richtig. Bester Wert: '+p.examBest+'%.</p><div class="actions"><button data-go="overview">Weiter</button>'+(score<100?'<button data-go="exam">Pruefung wiederholen</button>':'')+'</div>'+(answers.some(function(a){return !a.right;})?'<div class="exam-review">'+answers.filter(function(a){return !a.right;}).map(function(a){return '<div class="review-row"><b>'+esc(a.verb)+'</b><div class="wrong">Deine Antwort: '+esc(a.given)+'</div><div class="right">Richtig: '+esc(a.verb)+'</div></div>';}).join('')+'</div>':'')+'</section>';}
  function repeatPackage(){var p=pkg();if(!packageComplete()||p.round>=3)return;p.pointsBank=totalPoints();p.round+=1;p.taskDone=emptyDone();p.taskRepeat=emptyRepeat();p.taskPoints={};p.current=null;p.examBest=0;p.examPoints=0;p.examRun=null;save();go('overview');}
  function finishPackage(){var p=pkg();if(!packageComplete())return;state.learned=uniq(state.learned.concat(p.verbs));state.package=null;save();go('choose');}
  function resetAll(){if(!confirm('Verben-Test-Fortschritte wirklich loeschen?'))return;state=defaultState();save();go('home');}
  function updateChooseFilter(){var card=app.querySelector('.card'),search=app.querySelector('[data-search]'),active='all';function apply(){var q=norm(search.value),rows=[].slice.call(app.querySelectorAll('.verb-row')),shown=0,checked=0;rows.forEach(function(row){var text=norm(row.textContent),tags=(row.getAttribute('data-tags')||'').split(' '),ok=(!q||text.indexOf(q)>=0)&&(active==='all'||tags.indexOf(active)>=0);row.style.display=ok?'flex':'none';if(ok)shown++;if(row.querySelector('input').checked)checked++;});var c=app.querySelector('[data-count]');if(c)c.textContent=shown+' sichtbar · '+checked+' gewaehlt';}card.addEventListener('click',function(e){var b=e.target.closest('[data-filter]');if(!b)return;active=b.getAttribute('data-filter');[].slice.call(app.querySelectorAll('[data-filter]')).forEach(function(x){x.classList.toggle('active',x===b);});apply();});card.addEventListener('change',apply);search.addEventListener('input',apply);apply();}
  document.addEventListener('click',function(e){var t=e.target.closest('[data-go],[data-task],[data-action],[data-assess],[data-answer],[data-correct],[data-wrong],[data-check],[data-speak],[data-mic],[data-exam-check]');if(!t)return;if(t.hasAttribute('data-go')){go(t.getAttribute('data-go'));return;}if(t.hasAttribute('data-task')){go('task',{id:t.getAttribute('data-task')});return;}if(t.hasAttribute('data-action')){var a=t.getAttribute('data-action');if(a==='reset')resetAll();if(a==='repeat')repeatPackage();if(a==='finish')finishPackage();if(a==='select-visible'){var n=0;[].slice.call(app.querySelectorAll('.verb-row')).forEach(function(row){var input=row.querySelector('input');if(row.style.display!=='none'&&n<PACKAGE_SIZE){input.checked=true;n++;}});updateChooseFilter();}if(a==='clear-choice'){[].slice.call(app.querySelectorAll('input[data-verb]')).forEach(function(i){i.checked=false;});updateChooseFilter();}if(a==='start-choice'){startPackage([].slice.call(app.querySelectorAll('input[data-verb]:checked')).map(function(i){return i.getAttribute('data-verb');}));}return;}if(t.hasAttribute('data-assess')){var v=t.getAttribute('data-verb');if(t.getAttribute('data-assess')==='known')state.learned=uniq(state.learned.concat([v]));else state.assessmentLearn=uniq(state.assessmentLearn.concat([v]));save();renderAssess();return;}var p=pkg(),cur=p&&p.current,task=cur&&cur.task,verb=cur&&cur.verb;if(t.hasAttribute('data-correct')){markCorrect(task,verb);return;}if(t.hasAttribute('data-wrong')){wrongFeedback(task,verb);return;}if(t.hasAttribute('data-answer')){sameAnswer(t.getAttribute('data-answer'),verb)?markCorrect(task,verb):wrongFeedback(task,verb);return;}if(t.hasAttribute('data-check')){var value=(app.querySelector('[data-input]')||{}).value||'';sameAnswer(value,t.getAttribute('data-check'))?markCorrect(task,verb):wrongFeedback(task,verb);return;}if(t.hasAttribute('data-speak')){speak(t.getAttribute('data-speak'));return;}if(t.hasAttribute('data-mic')){startMic(t.getAttribute('data-mic'));return;}if(t.hasAttribute('data-exam-check')){var given=(app.querySelector('[data-input]')||{}).value||'',right=t.getAttribute('data-exam-check');p.examRun.answers.push({verb:right,given:given,right:sameAnswer(given,right)});p.examRun.index+=1;save();renderExam();return;}});
  function startMic(answer){var SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){var input=app.querySelector('[data-input]');if(input)input.focus();app.querySelector('.feedback').innerHTML='<div class="no">Mikrofon wird nicht unterstuetzt. Bitte schreibe die Antwort.</div>';return;}var rec=new SR();rec.lang='de-DE';rec.interimResults=false;rec.maxAlternatives=3;rec.onresult=function(e){var texts=[].slice.call(e.results[0]).map(function(r){return r.transcript;});var input=app.querySelector('[data-input]');if(input)input.value=texts[0]||'';texts.some(function(x){return sameAnswer(x,answer);})?markCorrect(pkg().current.task,pkg().current.verb):wrongFeedback(pkg().current.task,pkg().current.verb);};rec.onerror=function(){app.querySelector('.feedback').innerHTML='<div class="no">Mikrofon konnte nicht geprueft werden. Bitte schreibe die Antwort.</div>';};rec.start();}
  function start(){buildCatalog();loadState();render();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
