const CFG=window.SP_L5_THEME||{id:'Thema-4',title:'Öffnungszeiten und Freizeit',sub:'A1 Lektion 5 · Thema 4',key:'SP_L5_T4_V1'};
const DATA=window.SP_A1_LEKTION5_WORTSCHATZ||{parts:[]};
const THEME=(DATA.parts||[]).find(p=>p.id===CFG.id)||{words:[],title:CFG.title};
const BASE_WORDS=THEME.words||[];
const EXTRA_IMAGES={geschaeft:'/wortschatz/A1-Lektion-3/bilder/geschaeft.png',kino:'/assets/img/kino.png',kita:'/assets/img/kita.png',bibliothek:'/assets/img/bibliothek.png',oeffnen:'/verben-A1/bilder/oeffnen.png',schliessen:'/verben-A1/bilder/schliessen.png'};
const EXTRA_WORDS=[
{id:'ist_geoeffnet',section:'Öffnungszeiten',word:'ist geöffnet',article:'',full:'ist geöffnet',plural:'',pluralGroup:'',type:'phrase',image:EXTRA_IMAGES.oeffnen,sentence:'Das Geschäft ist geöffnet.',tr:{en:'is open',ru:'открыто',tr:'açık',uk:'відчинено',ar:'مفتوح',ja:'開いています',ro:'este deschis',pl:'jest otwarte',ku:'vekirî ye'}},
{id:'ist_geschlossen',section:'Öffnungszeiten',word:'ist geschlossen',article:'',full:'ist geschlossen',plural:'',pluralGroup:'',type:'phrase',image:EXTRA_IMAGES.schliessen,sentence:'Die Bibliothek ist geschlossen.',tr:{en:'is closed',ru:'закрыто',tr:'kapalı',uk:'зачинено',ar:'مغلق',ja:'閉まっています',ro:'este închis',pl:'jest zamknięte',ku:'girtî ye'}},
{id:'vereinbaren',section:'Termine',word:'vereinbaren',article:'',full:'vereinbaren',plural:'',pluralGroup:'',type:'verb',image:null,sentence:'Ich vereinbare einen Termin.',tr:{en:'to make / arrange',ru:'договариваться / назначать',tr:'kararlaştırmak / almak',uk:'домовлятися / призначати',ar:'يتفق / يحدد موعدًا',ja:'予約する / 決める',ro:'a stabili / a programa',pl:'umawiać',ku:'li hev kirin'}},
{id:'ausleihen',section:'Bibliothek',word:'ausleihen',article:'',full:'ausleihen',plural:'',pluralGroup:'',type:'verb',image:null,sentence:'Ich leihe ein Buch aus.',tr:{en:'to borrow',ru:'брать напрокат / одалживать',tr:'ödünç almak',uk:'позичати',ar:'يستعير',ja:'借りる',ro:'a împrumuta',pl:'wypożyczać',ku:'deyn kirin'}},
{id:'jugend',section:'Freizeit',word:'Jugend',article:'die',full:'die Jugend',plural:'',pluralGroup:'Sg.',type:'noun',image:null,sentence:'Die Jugend trifft sich im Kino.',tr:{en:'youth',ru:'молодёжь',tr:'gençlik',uk:'молодь',ar:'الشباب',ja:'若者 / 青少年',ro:'tineret',pl:'młodzież',ku:'ciwanî'}},
{id:'jugendliche',section:'Freizeit',word:'Jugendlichen',article:'die',full:'die Jugendlichen',plural:'die Jugendlichen',pluralGroup:'Pl.',type:'noun',image:null,sentence:'Die Jugendlichen gehen in die Bibliothek.',tr:{en:'young people / teenagers',ru:'подростки / молодые люди',tr:'gençler',uk:'підлітки / молоді люди',ar:'الشباب / المراهقون',ja:'若者 / 青少年',ro:'tinerii / adolescenții',pl:'młodzi ludzie',ku:'ciwan'}},
{id:'feiertag',section:'Öffnungszeiten',word:'Feiertag',article:'der',full:'der Feiertag',plural:'die Feiertage',pluralGroup:'-e',type:'noun',image:null,sentence:'Am Feiertag ist das Geschäft geschlossen.',tr:{en:'public holiday',ru:'праздник',tr:'resmî tatil',uk:'свято / вихідний день',ar:'عطلة رسمية',ja:'祝日',ro:'sărbătoare legală',pl:'święto',ku:'roja betlaneyê'}},
{id:'oeffnungszeiten',section:'Öffnungszeiten',word:'Öffnungszeiten',article:'die',full:'die Öffnungszeiten',plural:'die Öffnungszeiten',pluralGroup:'Pl.',type:'noun',image:null,sentence:'Die Öffnungszeiten stehen am Schild.',tr:{en:'opening hours',ru:'часы работы',tr:'açılış saatleri',uk:'години роботи',ar:'ساعات العمل',ja:'営業時間',ro:'program de lucru',pl:'godziny otwarcia',ku:'demên vekirinê'}},
{id:'schild',section:'Öffnungszeiten',word:'Schild',article:'das',full:'das Schild',plural:'die Schilder',pluralGroup:'-er',type:'noun',image:null,sentence:'Das Schild ist an der Tür.',tr:{en:'sign',ru:'табличка / знак',tr:'tabela',uk:'табличка / знак',ar:'لافتة',ja:'看板 / 標識',ro:'semn / afiș',pl:'szyld / znak',ku:'nîşan / tablo'}},
{id:'ganzen_tag',section:'Zeit',word:'den ganzen Tag',article:'',full:'den ganzen Tag',plural:'',pluralGroup:'',type:'phrase',image:null,sentence:'Die Kita ist den ganzen Tag geöffnet.',tr:{en:'all day',ru:'весь день',tr:'bütün gün',uk:'цілий день',ar:'طوال اليوم',ja:'一日中',ro:'toată ziua',pl:'cały dzień',ku:'tevahiya rojê'}}
];
const byId=Object.fromEntries(BASE_WORDS.map(w=>[w.id,w]));
EXTRA_WORDS.forEach(w=>byId[w.id]=w);
const FOCUS_IDS=['ist_geoeffnet','ist_geschlossen','oeffnen','schliessen','anfangen','enden','vereinbaren','ausleihen','geschaeft','bibliothek','kita','kindergarten','praxis','kino','termin','feiertag','oeffnungszeiten','schild','ganzen_tag','zum_beispiel','wieder','total','jugend','jugendliche'];
const WORDS=FOCUS_IDS.map(id=>byId[id]).filter(Boolean);
const BAD_IMAGE_IDS=new Set([]);
const STD_LANGS=[['en','EN'],['ru','RU'],['tr','TR'],['uk','UK'],['ar','AR'],['ja','JA'],['ro','RO'],['pl','PL'],['ku','KU']];
const LANG_NAMES={en:'Englisch',ru:'Russisch',tr:'Türkisch',uk:'Ukrainisch',ar:'Arabisch',ja:'Japanisch',ro:'Rumänisch',pl:'Polnisch',ku:'Kurdisch'};
function displayImage(w){return EXTRA_IMAGES[w?.id]||w?.image||''}
function hasGoodImage(w){return !!(w&&!BAD_IMAGE_IDS.has(w.id)&&displayImage(w))}
function simple(x){return String(x||'').toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[.,!?;:]/g,'').replace(/\s+/g,' ')}
function full(w){return w.full||((w.article?`${w.article} `:'')+(w.word||''))}
function profile(){try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||'null')}catch(e){return null}}
function langKey(){const m=String(profile()?.muttersprache||profile()?.motherLanguage||'').toLowerCase();if(['uk','ua'].includes(m)||m.includes('ukrain'))return'uk';if(m.includes('russ'))return'ru';if(m.includes('türk')||m.includes('turk'))return'tr';if(m.includes('arab'))return'ar';if(m.includes('japan'))return'ja';if(m.includes('rumän')||m.includes('ruman')||m.includes('roman'))return'ro';if(m.includes('pol')||m.includes('poln'))return'pl';if(m.includes('kurd'))return'ku';return'en'}
function tr(w){const t=w.tr||{};return t[langKey()]||t.en||t.ru||t.tr||''}
function nativeTrHtml(w){const k=langKey(),t=w.tr||{};return `<div class="native-trans"><b>Übersetzung (${LANG_NAMES[k]||k.toUpperCase()}):</b> ${t[k]||t.en||'—'}</div>`}
function cardPrompt(w){return w?.type==='noun'?'Sage das deutsche Wort mit Artikel.':'Sage das deutsche Wort.'}
function cardTip(w){return w?.type==='noun'?'Artikel und Wort':'Wort'}
function typeLabel(t){return({noun:'Nomen',verb:'Verben',adjective:'Adjektive',adverb:'Adverbien',preposition:'Präpositionen',phrase:'Ausdrücke',question:'Fragewörter',conjunction:'Verbindungen',determiner:'Begleiter',time:'Zeitwörter'})[t]||'Andere Wörter'}
function byType(){const order=['noun','verb','phrase','adjective','adverb','preposition','question','conjunction','determiner','time'],g={};WORDS.forEach(w=>{(g[w.type||'other']||(g[w.type||'other']=[])).push(w)});return order.filter(k=>g[k]).map(k=>[typeLabel(k),g[k]]).concat(Object.keys(g).filter(k=>!order.includes(k)).map(k=>[typeLabel(k),g[k]]))}
function imgHtml(w){return hasGoodImage(w)?`<img src="${displayImage(w)}" onerror="fixImg(this)" alt="">`:`<div class="word-placeholder">${String(w?.word||'').slice(0,2).toUpperCase()}</div>`}
function bigImgHtml(w){return hasGoodImage(w)?`<img class="task-img" src="${displayImage(w)}" onerror="fixBigImg(this)" alt="">`:`<div class="placeholder-img">${full(w)}</div>`}
function fixImg(img){const ph=document.createElement('div');ph.className='word-placeholder';ph.textContent='Wort';img.replaceWith(ph)}
function fixBigImg(img){const ph=document.createElement('div');ph.className='placeholder-img';ph.textContent='Wort';img.replaceWith(ph)}
function isThemePage(){return /\/Thema-4\/?(index\.html)?$/.test(location.pathname)}
function header(title,showReset=false){const h=document.querySelector('.topbar');if(!h)return;const p=profile();const first=p?.vorname||p?.firstName||'';const last=p?.nachname||p?.lastName||'';const name=`${first} ${last}`.trim()||'Schüler/in';const course=p?.kurs||p?.kursnummer||p?.courseCode||'';const dashboard=localStorage.getItem('SP_LOGIN_ROLE')==='teacher'?'/teacher/index.html':'/student-dashboard/index.html';const backHref=isThemePage()?'../index.html':'index.html';h.innerHTML=`<div class="topbar-main sp-account-row"><a class="brand" href="/index.html"><div class="logo"><img src="/assets/logo/sprachpilot-logo.png" alt="SprachPilot"></div><div><h1>SprachPilot</h1><div class="subtitle">${title} · ${CFG.sub}</div></div></a><div class="account-tools"><span class="account-pill">${name}${course?' · '+course:''}</span><a class="account-link" href="${dashboard}">Dashboard</a><a class="account-link" href="/profile/index.html">Profil</a><button class="account-link account-btn" onclick="spLogout()">Abmelden</button></div></div><nav class="nav sp-page-nav"><a class="btn secondary" href="${backHref}">← Zurück</a><a class="btn secondary" href="uebersicht.html">Übersicht</a><a class="btn secondary" href="statistik.html">Statistik</a>${showReset?'<button class="btn danger-btn" onclick="resetThemeProgress()">Fortschritte löschen</button>':''}</nav>`}
function spLogout(){['SP_USER_PROFILE','SP_KEEP_LOGGED_IN','SP_LOGIN_ROLE','SP_TEACHER_PREVIEW','SP_PREVIEW_COURSE','SP_TEACHER_PREVIEW_COURSE'].forEach(k=>localStorage.removeItem(k));location.href='/index.html'}
function instruction(txt){return `<div class="task-instruction">${txt}</div>`}
function exampleBox(txt){return `<div class="example-box">${txt}</div>`}
function exactAnswer(value,solutions){const a=simple(value);return (Array.isArray(solutions)?solutions:[solutions]).some(s=>simple(s)===a)}
function help3(tries,step1,step2,solution){if(tries===1)return `<div class="no">${step1}</div>`;if(tries===2)return `<div class="hint">${step2}</div>`;return `<div class="no">Lösung: ${solution}</div>`}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function taskKey(file){return CFG.key+'_'+file}
function loadTask(file,total){try{const st=JSON.parse(localStorage.getItem(taskKey(file))||'null');if(st&&st.total===total&&Array.isArray(st.done)&&Array.isArray(st.queue))return st}catch(e){}return{total,done:[],queue:[...Array(total).keys()].sort(()=>Math.random()-.5),current:null,tries:0,hadWrong:false}}
function saveTask(file,st){localStorage.setItem(taskKey(file),JSON.stringify(st))}
function markTaskDone(file,total){saveTask(file,{total,done:[...Array(total).keys()],queue:[],current:null,tries:0,hadWrong:false})}
function spNextIndex(file,total){let st=loadTask(file,total);if(st.current===null||st.current===undefined){if(!st.queue.length&&st.done.length<total)st.queue=[...Array(total).keys()].filter(i=>!st.done.includes(i)).sort(()=>Math.random()-.5);st.current=st.queue.shift();st.tries=0;st.hadWrong=false;saveTask(file,st)}return st.current}
function spNextSequentialIndex(file,total){let st=loadTask(file,total);if(st.current===null||st.current===undefined){const next=[...Array(total).keys()].find(i=>!st.done.includes(i));st.current=next===undefined?0:next;st.tries=0;st.hadWrong=false;saveTask(file,st)}return st.current}
function spMarkRight(file,total){let st=loadTask(file,total),c=st.current;if(c!==null&&c!==undefined){if(st.hadWrong||st.tries>0){if(!st.done.includes(c)&&!st.queue.includes(c))st.queue.push(c)}else if(!st.done.includes(c))st.done.push(c)}st.current=null;st.tries=0;st.hadWrong=false;saveTask(file,st)}
function spMarkWrong(file,total){let st=loadTask(file,total);st.tries=(st.tries||0)+1;st.hadWrong=true;saveTask(file,st);return st.tries}
function pctFor(file,total){if(!total)return 0;return Math.round((loadTask(file,total).done.length||0)/total*100)||0}
function spProgressHtml(file,total){const st=loadTask(file,total),d=st.done.length,p=pctFor(file,total);return`<div class="small">${d} richtig · ${total-d} übrig · ${p}%</div><div class="progress"><div class="bar" style="width:${p}%"></div></div>`}
function complete(area,file,next='index.html'){area.innerHTML=`<div class="finish-box"><div class="finish-icon">✓</div><div class="question">Geschafft!</div><div class="hint">Diese Aufgabe ist abgeschlossen.</div><div class="actions"><a class="btn" href="${next}">Weiter →</a><a class="btn secondary" href="index.html">Zum Menü</a></div></div>`}
function resetThemeProgress(){if(!confirm('Fortschritte in diesem Thema löschen?'))return;Object.keys(localStorage).filter(k=>k.startsWith(CFG.key)).forEach(k=>localStorage.removeItem(k));location.reload()}
function startMic(btn,callback){const SR=window.SpeechRecognition||window.webkitSpeechRecognition,status=document.getElementById('micStatus');if(!SR){if(status)status.textContent='Mikrofon wird hier nicht unterstützt. Bitte schreibe.';return}const rec=new SR();rec.lang='de-DE';rec.onresult=e=>callback(e.results[0][0].transcript);rec.onerror=()=>{if(status)status.textContent='Mikrofon hat nicht funktioniert. Bitte schreibe.'};rec.onend=()=>{if(btn)btn.classList.remove('active')};if(btn)btn.classList.add('active');if(status)status.textContent='Ich höre zu …';rec.start()}
function renderOverview(target){target.innerHTML=byType().map(([label,items])=>`<section class="type-block"><div class="type-title">${label}</div>${items.map(w=>`<div class="word-row">${imgHtml(w)}<div><b>${full(w)}</b><br><span class="small">${w.plural?`Plural: ${w.plural}`:'kein Plural'}</span>${nativeTrHtml(w)}<span class="tag">${w.section||''}</span><div class="small">${w.sentence||''}</div></div></div>`).join('')}</section>`).join('')}
function renderStats(target){const st=loadTask('karteikarten.html',WORDS.length);target.innerHTML=byType().map(([label,items])=>`<section class="type-block"><div class="type-title">${label}</div>${items.map(w=>{const idx=WORDS.indexOf(w),ok=st.done.includes(idx);return`<div class="word-row">${imgHtml(w)}<div><b>${full(w)}</b>${nativeTrHtml(w)}<span class="small ${ok?'ok':'todo'}">${ok?'gelernt':'noch offen'}</span><br><span class="small">Karteikarten-Fortschritt wird gespeichert.</span></div></div>`}).join('')}</section>`).join('')}
