header('Hören');
const FILE='hoeren.html';
const ITEMS=[
{q:'Wann können Eltern ihr Kind am Montag bringen?',audio:'/assets/audio/a1-l5-t4-hoeren-01-kita.mp3',a:'ab 7:30 Uhr',opts:['ab 7:00 Uhr','ab 7:30 Uhr','ab 8:30 Uhr'],text:'Guten Morgen. Hier ist die Kita Regenbogen. Unsere Kita ist von Montag bis Freitag geöffnet. Am Montag können Eltern die Kinder ab halb acht bringen. Bitte bringen Sie die Kinder nicht früher, denn vor halb acht ist die Kita noch geschlossen. Abholen können Sie die Kinder bis siebzehn Uhr. Am Samstag und am Sonntag ist die Kita geschlossen.'},
{q:'Wann ist die Krippe am Freitag geschlossen?',audio:'/assets/audio/a1-l5-t4-hoeren-02-krippe.mp3',a:'ab 13:00 Uhr',opts:['ab 12:00 Uhr','ab 13:00 Uhr','ab 16:00 Uhr'],text:'Sie hören die Krippe Sonnenblume. Von Montag bis Donnerstag ist die Krippe von sieben Uhr bis sechzehn Uhr geöffnet. Am Freitag gibt es eine Teamsitzung. Deshalb schließen wir schon um dreizehn Uhr. Ab dreizehn Uhr ist die Krippe geschlossen. Bitte holen Sie Ihr Kind pünktlich ab.'},
{q:'Wann kann man telefonisch einen Termin vereinbaren?',audio:'/assets/audio/a1-l5-t4-hoeren-03-praxis.mp3',a:'von 8:00 bis 12:00 Uhr',opts:['von 8:00 bis 12:00 Uhr','von 12:00 bis 14:00 Uhr','von 14:00 bis 16:30 Uhr'],text:'Praxis Dr. Weber, guten Tag. Unsere Praxis ist heute von acht bis zwölf Uhr und von vierzehn bis sechzehn Uhr dreißig geöffnet. Zwischen zwölf und vierzehn Uhr ist Mittagspause. Einen Termin können Sie telefonisch nur am Vormittag von acht bis zwölf Uhr vereinbaren. Am Nachmittag behandeln wir nur Patienten mit Termin.'},
{q:'Wann schließt Elektro Müller am Samstag?',audio:'/assets/audio/a1-l5-t4-hoeren-04-geschaeft.mp3',a:'um 13:00 Uhr',opts:['um 12:30 Uhr','um 13:00 Uhr','um 18:30 Uhr'],text:'Willkommen bei Elektro Müller. Unser Geschäft ist am Montag, Dienstag, Donnerstag und Freitag von neun Uhr bis achtzehn Uhr dreißig geöffnet. Am Mittwoch schließen wir wegen Inventur um dreizehn Uhr. Auch am Samstag ist das Geschäft nur kurz geöffnet, von neun Uhr dreißig bis dreizehn Uhr. Am Sonntag ist geschlossen.'},
{q:'Wann kann man in der Bibliothek Bücher ausleihen?',audio:'/assets/audio/a1-l5-t4-hoeren-05-bibliothek.mp3',a:'am Samstag von 10:00 bis 16:00 Uhr',opts:['am Samstag von 10:00 bis 16:00 Uhr','am Sonntag von 10:00 bis 16:00 Uhr','am Feiertag von 13:00 bis 19:00 Uhr'],text:'Stadtbibliothek, guten Tag. Bücher können Sie von Montag bis Freitag von dreizehn bis neunzehn Uhr ausleihen. Am Samstag ist die Bibliothek zusätzlich von zehn bis sechzehn Uhr geöffnet. Am Sonntag ist die Bibliothek immer geschlossen. An Feiertagen ist sie auch geschlossen.'},
{q:'Wann beginnt der Film „Schönes Leben“?',audio:'/assets/audio/a1-l5-t4-hoeren-06-kino.mp3',a:'um 18:30 Uhr',opts:['um 17:30 Uhr','um 18:30 Uhr','um 20:15 Uhr'],text:'Sie hören das Kinoprogramm für heute Abend. Um siebzehn Uhr dreißig läuft der Kinderfilm „Pia und der Hund“. Danach, um achtzehn Uhr dreißig, beginnt der Film „Schönes Leben“. Der Film dauert zwei Stunden. Um zwanzig Uhr fünfzehn beginnt im großen Saal der Actionfilm. Die Kasse ist ab siebzehn Uhr geöffnet.'},
{q:'Wann bringt Nora Emil in die Kita?',audio:'/assets/audio/a1-l5-t4-hoeren-07-nora.mp3',a:'um 7:30 Uhr',opts:['um 6:15 Uhr','um 7:30 Uhr','um 9:00 Uhr'],text:'Nora wohnt in Mainz und hat einen Sohn. Er heißt Emil und ist drei Jahre alt. Nora steht jeden Morgen um sechs Uhr fünfzehn auf. Um sieben Uhr frühstückt sie mit Emil. Um halb acht bringt sie Emil in die Kita. Die Kita ist bis siebzehn Uhr geöffnet. Danach fährt Nora mit dem Bus zur Arbeit.'},
{q:'Warum holt Nora Emil am Mittwoch schon um 15:00 Uhr ab?',audio:'/assets/audio/a1-l5-t4-hoeren-08-nora-abholen.mp3',a:'weil das Geschäft am Mittwoch früher schließt',opts:['weil das Geschäft am Mittwoch früher schließt','weil die Kita geschlossen ist','weil die Bibliothek nicht geöffnet ist'],text:'Nora arbeitet in einem Geschäft in der Stadt. Normalerweise arbeitet sie bis achtzehn Uhr dreißig. Am Mittwoch ist das Geschäft aber nur bis dreizehn Uhr geöffnet. Nach der Arbeit geht Nora kurz in die Bibliothek und leiht ein Buch aus. Um fünfzehn Uhr holt sie Emil von der Kita ab.'},
{q:'Was möchte Nora am Abend machen?',audio:'/assets/audio/a1-l5-t4-hoeren-09-nora-abend.mp3',a:'lesen und schlafen',opts:['ins Kino gehen','lesen und schlafen','einen Termin vereinbaren'],text:'Am Abend ruft eine Freundin an. Sie fragt: Nora, hast du heute Zeit? Wir können ins Kino gehen. Nora antwortet: Heute nicht. Ich bin sehr müde. Ich habe gearbeitet, Emil abgeholt und eingekauft. Ich möchte nur noch lesen und schlafen. Vielleicht habe ich am Freitag wieder Zeit.'},
{q:'Wann ist der Jugendtreff geschlossen?',audio:'/assets/audio/a1-l5-t4-hoeren-10-jugend.mp3',a:'am Samstag und am Sonntag',opts:['am Freitag von 16:00 bis 20:00 Uhr','am Samstag und am Sonntag','den ganzen Freitag'],text:'Der Jugendtreff Nord ist diese Woche nur am Freitag geöffnet. Jugendliche können von sechzehn bis zwanzig Uhr kommen. Es gibt Musik, Getränke und einen Filmabend. Am Samstag ist ein Feiertag, deshalb ist der Jugendtreff geschlossen. Am Sonntag ist er auch geschlossen.'},
{q:'Wann ist der Termin?',audio:'/assets/audio/a1-l5-t4-hoeren-11-termin.mp3',a:'am Donnerstag um 15 Uhr',opts:['am Dienstag um 15 Uhr','am Donnerstag um 15 Uhr','am Donnerstag um 16 Uhr'],text:'Eigene Audiodatei: Der Termin ist am Donnerstag um 15 Uhr.'},
{q:'Wann soll Herr Ali zurückrufen?',audio:'/assets/audio/a1-l5-t4-hoeren-12-rueckruf-herr-ali.mp3',a:'heute Vormittag',opts:['heute Vormittag','heute Nachmittag','morgen Nachmittag'],text:'Eigene Audiodatei: Herr Ali soll heute Vormittag zurückrufen.'},
{q:'Welche Telefonnummer hört man?',audio:'/assets/audio/a1-l5-t4-hoeren-13-telefonnummer.mp3',a:'06841 73 19 28',opts:['06841 73 19 28','06841 37 19 28','06841 73 91 28'],text:'Eigene Audiodatei: 06841 73 19 28.'}
];
let i=0;
function show(){if(loadTask(FILE,ITEMS.length).done.length>=ITEMS.length){complete(area,FILE,'schilder.html');return}i=spNextIndex(FILE,ITEMS.length);const it=ITEMS[i];const opts=shuffle(it.opts);area.innerHTML=`${spProgressHtml(FILE,ITEMS.length)}${instruction('Hören Sie die Ansage. Es gibt mehrere Informationen. Wählen Sie die passende Antwort.')}<div class="audio-box"><audio controls preload="metadata"><source src="${it.audio}" type="audio/mpeg"></audio></div><div class="question">${it.q}</div><div class="choice-grid">${opts.map(o=>`<button class="choice" onclick="check(this,'${encodeURIComponent(o)}')">${o}</button>`).join('')}</div><div id="fb" class="feedback"></div>`}
function check(btn,raw){const val=decodeURIComponent(raw),it=ITEMS[i];if(val===it.a){btn.classList.add('ok');fb.textContent='Richtig!';spMarkRight(FILE,ITEMS.length);setTimeout(show,800)}else{btn.classList.add('no');const t=spMarkWrong(FILE,ITEMS.length);fb.innerHTML=help3(t,'Noch nicht richtig.','Tipp: Hören Sie noch einmal und achten Sie genau auf die Frage.',it.a)}}
show();
