const t4ImgCount=WORDS.filter(w=>w&&w.image).length;
const t4ImgCueCount=WORDS.filter(w=>w&&(w.image||w.cue)).length;
const t4extra=[['karteikarten.html',WORDS.length,'Karteikarten','🃏'],['artikel.html',12,'Artikel','📝'],['hoeren-schreiben.html',13,'Hören/Schreiben','✍️'],['hoeren-bild.html',t4ImgCount,'Hören/Bild','🎧'],['bild-wort.html',t4ImgCueCount,'Bild/Wort','🖼️'],['hoeren.html',13,'Hören','🎧'],['schilder.html',10,'Schilder','🪧'],['lesen.html',6,'Lesen: Noras Tag','🔎'],['tv-programm.html',6,'TV-Programm','📺'],['zuordnen-v5.html',10,'Zuordnen','🔗'],['saetze-bauen.html',8,'Sätze bauen','✍️'],['mini-dialoge.html',8,'Mini-Dialoge','💬'],['jede-zeit.html',16,'jeden / jede / jedes','🧩']];
function t4pct(file,total){if(file==='zuordnen-v5.html'){try{const state=JSON.parse(localStorage.getItem(taskKey(file))||'null');if(state&&state.rev==='20260825-task10-v5'&&Number(state.total)===total&&Array.isArray(state.done))return Math.round([...new Set(state.done.map(Number).filter(n=>Number.isInteger(n)&&n>=0&&n<total))].length/total*100)}catch(e){}return 0}return pctFor(file,total)}
function t4href(file){return file==='zuordnen-v5.html'?'zuordnen-v5.html?v=20260825-task10-v5':file}
function t4card(t,n){const p=t4pct(t[0],t[1]);return '<a class="module" href="'+t4href(t[0])+'"><div class="num">'+n+'. '+t[2]+'</div><div class="icon">'+t[3]+'</div><p>Üben</p><div class="progress"><div class="bar" style="width:'+p+'%"></div></div><div class="small">'+p+'%</div><div class="start">'+(p>=100?'Fertig':'Starten')+'</div></a>'}
let t4n=1;taskGrid.innerHTML=t4extra.map(t=>t4card(t,t4n++)).join('');
const t4open=t4extra.every(t=>t4pct(t[0],t[1])>=100),ep=pctFor('pruefung.html',12);
taskGrid.innerHTML+=t4open?'<a class="module" href="pruefung.html"><div class="num">'+t4n+'. Prüfung</div><div class="icon exam-icon">⭐</div><p>Prüfung</p><div class="small">'+(ep?ep+'%':'offen')+'</div><div class="start">Starten</div></a>':'<div class="module locked exam-locked"><div class="num">'+t4n+'. Prüfung</div><div class="icon exam-icon">⭐</div><p>Prüfung gesperrt.</p><div class="small">gesperrt</div></div>';
const t4all=[...t4extra,['pruefung.html',12]],t4avg=Math.round(t4all.reduce((s,t)=>s+(t[0]==='pruefung.html'?pctFor(t[0],t[1]):t4pct(t[0],t[1])),0)/t4all.length)||0,t4done=t4all.filter(t=>(t[0]==='pruefung.html'?pctFor(t[0],t[1]):t4pct(t[0],t[1]))>=100).length;totalCircle.textContent=t4avg+'%';totalBar.style.width=t4avg+'%';totalText.textContent=t4done+' / '+t4all.length+' Aufgaben abgeschlossen';
