header('Schilder lesen');
const FILE='schilder.html';
const ITEMS=[
{title:'Kita Regenbogen',lines:['Mo–Fr: 07:30–17:00 Uhr','Sa/So: geschlossen'],q:'Wann ist die Kita geöffnet?',must:[['kita','kindergarten'],['montag'],['freitag'],['7'],['17'],['geoffnet']],tip:'Die Kita ist von Montag bis Freitag von 7:30 bis 17:00 Uhr geöffnet.'},
{title:'Kita Regenbogen',lines:['Mo–Fr: 07:30–17:00 Uhr','Sa/So: geschlossen'],q:'Wann ist die Kita geschlossen?',must:[['kita','kindergarten'],['samstag'],['sonntag'],['geschlossen']],tip:'Die Kita ist am Samstag und am Sonntag geschlossen.'},
{title:'Krippe Sonnenblume',lines:['Mo–Do: 07:00–16:00 Uhr','Fr: 07:00–13:00 Uhr'],q:'Wann ist die Krippe am Freitag geöffnet?',must:[['krippe'],['freitag'],['7'],['13'],['geoffnet']],tip:'Die Krippe ist am Freitag von 7:00 bis 13:00 Uhr geöffnet.'},
{title:'Stadtbibliothek',lines:['Mo–Fr: 13:00–19:00 Uhr','Sa: 10:00–16:00 Uhr','Feiertag: geschlossen'],q:'Wann ist die Bibliothek geschlossen?',must:[['bibliothek'],['feiertag'],['geschlossen']],tip:'Die Bibliothek ist am Feiertag geschlossen.'},
{title:'Elektro Müller',lines:['Mo, Di, Do, Fr: 09:00–18:30 Uhr','Mi, Sa: 09:00–13:00 Uhr'],q:'Wann ist das Geschäft am Mittwoch geöffnet?',must:[['geschaft'],['mittwoch'],['9'],['13'],['geoffnet']],tip:'Das Geschäft ist am Mittwoch von 9:00 bis 13:00 Uhr geöffnet.'},
{title:'Praxis Dr. Weber',lines:['Mo–Do: 08:00–12:00 Uhr und 14:00–16:30 Uhr','Fr: 08:00–12:00 Uhr'],q:'Wann ist die Praxis am Freitag geöffnet?',must:[['praxis'],['freitag'],['8'],['12'],['geoffnet']],tip:'Die Praxis ist am Freitag von 8:00 bis 12:00 Uhr geöffnet.'},
{title:'Jugendtreff Nord',lines:['Fr: 16:00–20:00 Uhr','Sa/So und Feiertag: geschlossen'],q:'Wann ist der Jugendtreff geschlossen?',must:[['jugendtreff','jugend','jugendliche'],['samstag'],['sonntag'],['feiertag'],['geschlossen']],tip:'Der Jugendtreff ist am Samstag, am Sonntag und am Feiertag geschlossen.'},
{title:'Kino Palast',lines:['Kinderfilm: 17:30 Uhr','Schönes Leben: 18:30 Uhr','Actionfilm: 20:15 Uhr'],q:'Wann fängt der Film „Schönes Leben“ an?',must:[['film'],['schones leben'],['18'],['30'],['fangt']],tip:'Der Film „Schönes Leben“ fängt um 18:30 Uhr an.'},
{title:'Bücherbus',lines:['Dienstag: 15:00–17:00 Uhr','Donnerstag: 10:00–12:00 Uhr'],q:'Wann kann man am Dienstag Bücher ausleihen?',must:[['dienstag'],['15'],['17'],['bucher'],['ausleihen']],tip:'Man kann am Dienstag von 15:00 bis 17:00 Uhr Bücher ausleihen.'},
{title:'Bücherbus',lines:['Dienstag: 15:00–17:00 Uhr','Donnerstag: 10:00–12:00 Uhr','Montag: geschlossen'],q:'Wann ist der Bücherbus geschlossen?',must:[['bucherbus'],['montag'],['geschlossen']],tip:'Der Bücherbus ist am Montag geschlossen.'}
];
let i=0;
function norm(x){return simple(x).replace(/ä/g,'a').replace(/ö/g,'o').replace(/ü/g,'u')}
function hasAll(a,groups){return groups.every(g=>(Array.isArray(g)?g:[g]).some(m=>a.includes(norm(m))))}
function show(){if(loadTask(FILE,ITEMS.length).done.length>=ITEMS.length){complete(area,FILE,'lesen.html');return}i=spNextIndex(FILE,ITEMS.length);const it=ITEMS[i];area.innerHTML=`${spProgressHtml(FILE,ITEMS.length)}${instruction('Lesen Sie das Schild. Antworten Sie mit einem ganzen Satz. Sie können sprechen oder schreiben.')}<div class="open-text"><h2>${it.title}</h2>${it.lines.map(l=>`<p><b>${l}</b></p>`).join('')}</div><div class="question">${it.q}</div><textarea id="ans" rows="3" placeholder="Schreiben Sie einen ganzen Satz."></textarea><div class="actions"><button id="micBtn" class="btn secondary" onclick="say()">Sprechen</button><button class="btn" onclick="check()">Kontrollieren</button></div><div id="micStatus" class="mic-status"></div><div id="fb" class="feedback"></div>`}
function say(){startMic(micBtn,txt=>{ans.value=txt;check()})}
function check(){const it=ITEMS[i],a=norm(ans.value);if(!a){fb.innerHTML='<div class="no">Bitte sprechen oder schreiben Sie einen ganzen Satz.</div>';return}const ok=hasAll(a,it.must);if(ok){ans.classList.add('is-ok');fb.innerHTML='<div class="ok">Richtig!</div>';spMarkRight(FILE,ITEMS.length);setTimeout(show,900)}else{ans.classList.add('is-no');const t=spMarkWrong(FILE,ITEMS.length);fb.innerHTML=help3(t,'Der Satz passt noch nicht.','Tipp: Achten Sie auf Ort, Tag, Uhrzeit und geöffnet/geschlossen.',it.tip)}}
show();
