function renderHeader(){const h=$("spHeader");if(!h)return;h.innerHTML=`<div class="topbar"><a class="brand" href="/index.html"><span class="logo">SP</span><span><strong>SprachPilot</strong><small>Verben A1</small></span></a><button class="secondary" onclick="renderStudentDashboard()">📊 Statistik</button></div>`}
function renderSideMenu(){if(typeof renderMenu==="function")return renderMenu();const m=$("spMenu");if(!m)return;m.innerHTML=`<button onclick="renderHome()">Übersicht</button><button onclick="startAssessment()">Verben einschätzen</button>`}
function statusBox(){return `<div class="stats"><div class="stat"><div>Fortschritt</div><div class="num">${overall()}%</div></div><div class="stat"><div>Sterne</div><div class="num">${totalStars()}</div></div><div class="stat"><div>Aktiv</div><div class="num">${state.active.length}</div></div><div class="stat"><div>Üben</div><div class="num">${(state.practicePool||[]).length}</div></div></div>`}
function taskCard(skill,icon,fn){const done=taskDone(skill);return `<button class="task-card ${done?"done-card":""}" onclick="${fn}()"><span class="big-icon">${icon}</span><strong>${VERB_SKILL_LABELS[skill]}</strong><span class="task-status">${done?"Erledigt ✓":queuedProgress(skill).pct+"%"}</span></button>`}
function renderHome(){state.phase="home";migrateState();if(!state.active.length){$("app").innerHTML=`<h2>Start</h2><p>Schätze zuerst neue Verben ein. Wörter, die du nicht kannst, kommen im Üben öfter vor.</p><button class="success" onclick="startAssessment()">Neue Verben einschätzen</button>`;return}$("app").innerHTML=`<h2>Aufgabenübersicht</h2>${statusBox()}<div class="ok"><strong>Neues System:</strong> Unsichere Verben kommen 1× in den Übungsblock, unbekannte Verben 2×.</div><div class="task-grid">${taskCard("karteikarte","🃏","flashcards")}${taskCard("memory","🧠","memory")}${taskCard("bild_verb","🖼️","quiz")}${taskCard("verb_bild","🔁","verbToImage")}${taskCard("schreiben","✍️","writeVerb")}${taskCard("hoeren_schreiben","👂","hearWrite")}${taskCard("hoeren_sprechen","🎤","hearSpeak")}${taskCard("bild_sprechen","🗣️","imageSpeak")}${taskCard("satz_puzzle","🧩","sentencePuzzle")}</div><button class="secondary" onclick="startAssessment()">Weitere Verben einschätzen</button><button class="warning" onclick="buildPracticePool();renderHome()">Übungsblock neu mischen</button><button class="danger" onclick="resetCurrentPackage()">Aktuelles Paket zurücksetzen</button>`}
function resetCurrentPackage(){if(!confirm("Nur das aktuelle Verben-Paket zurücksetzen? Dein Profil bleibt erhalten."))return;state.active=[];state.practicePool=[];state.taskQueues={};state.taskDoneSets={};saveState();renderHome()}
function openNextTask(){const order=["karteikarte","memory","bild_verb","verb_bild","schreiben","hoeren_schreiben","hoeren_sprechen","bild_sprechen","satz_puzzle"];for(const s of order){if(!taskDone(s)){({karteikarte:flashcards,memory, bild_verb:quiz, verb_bild:verbToImage, schreiben:writeVerb, hoeren_schreiben:hearWrite, hoeren_sprechen:hearSpeak, bild_sprechen:imageSpeak, satz_puzzle:sentencePuzzle})[s]();return}}renderHome()}
async function boot(){renderHeader();if(!loadProfile())return;await loadState();if(!state.active.length&&unusedVerbs().length)startAssessment();else renderHome();renderSideMenu();renderAndHydrate()}
document.addEventListener("DOMContentLoaded",boot);
