(function(){
if(!document.currentScript)return;
var rel=null,loaded=false;
function j(k){try{return JSON.parse(localStorage.getItem(k)||'null')||{}}catch(e){return {}}}
function dbx(){try{if(typeof db!='undefined'&&db)return db}catch(e){}return window.db||null}
function st(){try{return typeof state!='undefined'&&state}catch(e){return null}}
function p(){try{if(typeof profile!='undefined'&&profile)return profile}catch(e){}return window.profile||j('SP_USER_PROFILE')||j('SP_STUDENT_PROFILE')||{}}
function teacher(){var r=String(localStorage.getItem('SP_LOGIN_ROLE')||localStorage.getItem('SP_ACTIVE_ROLE')||'').toLowerCase(),x=p();return r==='teacher'||r==='lehrer'||x.role==='teacher'||x.teacherPreview===true||x.isTeacher===true||localStorage.getItem('SP_TEACHER_PREVIEW')==='1'}
function has(d){return !!(d&&(d.enabledWords||d.releases||d.enabledModules||d.settings||d.defaultLocked!==undefined||d.releaseMode||d.verbenA1AssessmentEnabled!==undefined))}
function local(){var x=p();if(has(x.assignments))return x.assignments;var r=j('SP_COURSE_RELEASES');return has(r)?r:{}}
function saveRel(d){try{localStorage.setItem('SP_COURSE_RELEASES',JSON.stringify(d||{}));var x=p();x.assignments=d||{};x.courseCode=x.courseCode||d.courseCode||d.code||d.kurs||d.kursnummer||'';x.courseDocId=x.courseDocId||d.id||d.__docId||'';localStorage.setItem('SP_USER_PROFILE',JSON.stringify(x));localStorage.setItem('SP_STUDENT_PROFILE',JSON.stringify(x))}catch(e){}}
function get(o,a){var c=o;for(var i=0;i<a.length;i++){if(!c||typeof c!=='object'||!(a[i] in c))return undefined;c=c[a[i]]}return c}
function all(){return (window.ALL_VERBS||[]).map(function(x){return x&&x.v}).filter(Boolean)}
function uniq(a){return Array.from(new Set((a||[]).filter(Boolean)))}
function addCodesFrom(obj,out){if(!obj)return;['kurs','kursnummer','courseCode','courseDocId','courseId','courseName','name','code','id','__docId'].forEach(function(k){var v=String(obj[k]||'').trim();if(v)out.push(v,v.toUpperCase(),v.toLowerCase(),v.replace(/\s+/g,''),v.toLowerCase().replace(/\s+/g,''))})}
async function codes(){var x=p(),out=[];addCodesFrom(x,out);addCodesFrom(x.assignments,out);out.push(localStorage.getItem('SP_COURSE_CODE')||'');var dbs=dbx(),sid=x.studentId||x.userId||x.docId||localStorage.getItem('SP_STUDENT_ID')||'';if(dbs&&sid){try{var s=await dbs.collection('students').doc(String(sid)).get();if(s.exists)addCodesFrom(s.data()||{},out)}catch(e){}}return uniq(out.map(function(v){return String(v||'').trim()}).filter(Boolean))}
async function doc(db,id){try{var s=await db.collection('courses').doc(String(id)).get();return s.exists?Object.assign({id:s.id,__docId:s.id},s.data()||{}):null}catch(e){return null}}
async function qry(db,f,v){try{var s=await db.collection('courses').where(f,'==',String(v)).limit(1).get();return s&&!s.empty?Object.assign({id:s.docs[0].id,__docId:s.docs[0].id},s.docs[0].data()||{}):null}catch(e){return null}}
async function load(){if(teacher()){rel={releaseMode:'all',defaultLocked:false};loaded=true;return rel}var dbase=dbx(),fallback=local();if(!dbase){rel=fallback;loaded=true;return rel}var c=await codes();for(var i=0;i<c.length;i++){var d=await doc(dbase,c[i]);if(has(d)){rel=d;loaded=true;saveRel(d);return d}}var f=['courseCode','code','kurs','kursnummer','courseDocId','courseId','id','name','courseName'];for(var a=0;a<f.length;a++)for(var b=0;b<c.length;b++){var q=await qry(dbase,f[a],c[b]);if(has(q)){rel=q;loaded=true;saveRel(q);return q}}rel=fallback;loaded=true;return rel}
function data(){return teacher()?{releaseMode:'all',defaultLocked:false}:(has(rel)?rel:local())}
function val(d,v){var ew=d.enabledWords;if(Array.isArray(ew)&&(ew.includes(v)||ew.includes('verben-A1/'+v)||ew.includes('Verben A1/'+v)))return true;var pth=[['enabledWords',v],['enabledWords','verben-A1/'+v],['enabledWords','Verben A1/'+v],['releases','verben-A1','words',v],['releases','Verben A1','words',v]];for(var i=0;i<pth.length;i++){var x=get(d,pth[i]);if(x!==undefined)return x===true}return undefined}
function controls(d){var ew=d.enabledWords||{},n=all();if(Array.isArray(ew)&&ew.length)return true;if(Object.keys(ew).some(function(k){return k.indexOf('verben-A1/')>=0||k.indexOf('Verben A1/')>=0||n.indexOf(k)>=0}))return true;return !!(get(d,['releases','verben-A1','words'])||get(d,['releases','Verben A1','words']))}
function modOpen(d){var v=[get(d,['enabledModules','Verben A1']),get(d,['enabledModules','verben-A1']),get(d,['releases','Verben A1','enabled']),get(d,['releases','verben-A1','enabled'])];if(v.some(function(x){return x===false}))return false;return true}
function released(){var n=all(),d=data();if(teacher())return n;if(!has(d)||!modOpen(d))return [];var c=controls(d);if(c)return n.filter(function(v){return val(d,v)===true});if(d.releaseMode==='all'||d.releaseMode==='open'||d.defaultLocked===false)return n.filter(function(v){return val(d,v)!==false});return []}
function assess(){var d=data(),v=[get(d,['settings','verben-A1','assessmentEnabled']),get(d,['settings','Verben A1','assessmentEnabled']),d.verbenA1AssessmentEnabled,get(d,['releases','verben-A1','assessmentEnabled']),get(d,['releases','Verben A1','assessmentEnabled'])];for(var i=0;i<v.length;i++)if(v[i]!==undefined)return v[i]!==false;return true}
function target(){return Math.min(20,released().length)}
function filt(a){var s=new Set(released());return (a||[]).filter(function(v){return s.has(v)})}
function resetQueues(S){S.practicePool=[];S.taskQueues={};S.taskDoneSets={};S.currentTask=null;S.memoryCards=[];S.memoryDone=[];S.openCards=[];S.first=null;S.lock=false;S.exam={passed:false,score:0,stars:0,answers:[],current:0,items:[],awaiting:false,currentTry:0}}
function seedOff(S){if(assess())return;var l=released().slice(0,20);if(!l.length)return;S.currentPackageVerbs=l.slice();S.assessmentBatch=l.slice();S.assessed=l.slice();S.known=filt(S.known||[]);S.learned=filt(S.learned||[]);S.unsure=l.filter(function(v){return !(S.known||[]).includes(v)&&!(S.learned||[]).includes(v)});S.unknown=[];S.active=S.unsure.length?S.unsure.slice():l.slice();S.currentVerb=''}
function sync(){var S=st();if(!S||teacher()||(!loaded&&!has(rel)))return false;var A=new Set(released()),fp=JSON.stringify({v:Array.from(A),a:assess(),course:(rel&&rel.id)||''}),old=S._releaseFingerprint||'',before='';try{before=JSON.stringify(S)}catch(e){};['known','unsure','unknown','active','learned','practicePool','assessmentBatch','assessed','currentPackageVerbs'].forEach(function(k){if(Array.isArray(S[k]))S[k]=S[k].filter(function(v){return A.has(v)})});Object.keys(S.taskQueues||{}).forEach(function(k){S.taskQueues[k]=(S.taskQueues[k]||[]).filter(function(x){return x&&A.has(x.v)})});Object.keys(S.taskDoneSets||{}).forEach(function(k){S.taskDoneSets[k]=(S.taskDoneSets[k]||[]).filter(function(x){return A.has(String(x).split(':')[0])})});['skillDone','skillAttempts','skillSuccess','weak'].forEach(function(k){Object.keys(S[k]||{}).forEach(function(v){if(!A.has(v))delete S[k][v]})});if(S.currentVerb&&!A.has(S.currentVerb))S.currentVerb='';if(S.currentTask&&S.currentTask.v&&!A.has(S.currentTask.v))S.currentTask=null;if(S.exam&&Array.isArray(S.exam.items))S.exam.items=S.exam.items.filter(function(x){return x&&(!x.v||A.has(x.v))});if(old&&old!==fp)resetQueues(S);S._releaseFingerprint=fp;seedOff(S);try{if(typeof normalizeVerbStatusLists==='function')normalizeVerbStatusLists()}catch(e){}var after='';try{after=JSON.stringify(S)}catch(e){}if(before!==after)try{if(typeof saveState==='function')saveState()}catch(e){}return before!==after}
function bridgeHomeNeeded(){var S=st();if(!S||typeof currentPracticeVerbs!=='function')return false;var pc=currentPracticeVerbs().length,t=target();return !released().length||pc===0||(pc<20&&t&&pc>=t)||(!assess()&&pc>0&&pc<20)}
function bridgeHome(){var app=document.getElementById('app');if(!app)return false;try{if(typeof clearVerbHash==='function')clearVerbHash(true)}catch(e){}try{app.classList.remove('card')}catch(e){}var S=st();if(S){S.phase='home';S.currentTask=null}sync();var pc=typeof currentPracticeVerbs==='function'?currentPracticeVerbs().length:0,t=target();if(!released().length){app.innerHTML=(typeof statusBox==='function'?statusBox():'')+'<section class="card"><h2>Keine Verben freigegeben</h2><p class="small">Für deinen Kurs sind aktuell keine Verben A1 freigeschaltet.</p></section>';try{if(typeof saveState==='function')saveState()}catch(e){}return true}if(!pc){app.innerHTML=(typeof statusBox==='function'?statusBox():'')+'<section class="card"><h2>Keine aktiven Übungsverben</h2><p class="small">Alle aktuell freigegebenen Verben sind erledigt oder es gibt kein aktives Paket.</p></section>';try{if(typeof saveState==='function')saveState()}catch(e){}return true}if(pc<20&&t&&pc>=t){var h=(typeof statusBox==='function'?statusBox():'')+'<section class="card"><div class="grid task-grid">';if(typeof taskCard==='function'&&typeof examCard==='function')h+=taskCard('karteikarte','🃏','flashcards',1)+taskCard('memory','🧠','memory',2)+taskCard('bild_verb','🖼️','quiz',3)+taskCard('verb_bild','🔁','verbToImage',4)+taskCard('schreiben','✍️','writeVerb',5)+taskCard('hoeren_schreiben','👂','hearWrite',6)+taskCard('hoeren_sprechen','🎤','hearSpeak',7)+taskCard('bild_sprechen','🗣️','imageSpeak',8)+taskCard('satz_puzzle','🧩','sentencePuzzle',9)+taskCard('konjugieren','🔤','conjugationTask',10)+examCard();app.innerHTML=h+'</div></section>';try{if(typeof saveState==='function')saveState()}catch(e){}return true}return false}
function patch(){if(typeof window.unusedVerbs==='function'&&!window.unusedVerbs.__rb){var u=window.unusedVerbs;window.unusedVerbs=function(){return assess()?filt(u()):[]};window.unusedVerbs.__rb=true}if(typeof window.currentPracticeVerbs==='function'&&!window.currentPracticeVerbs.__rb){var cp=window.currentPracticeVerbs;window.currentPracticeVerbs=function(){sync();return filt(cp())};window.currentPracticeVerbs.__rb=true}if(typeof window.currentPackageAllVerbs==='function'&&!window.currentPackageAllVerbs.__rb){var ca=window.currentPackageAllVerbs;window.currentPackageAllVerbs=function(){sync();return filt(ca())};window.currentPackageAllVerbs.__rb=true}if(typeof window.verbsByStatus==='function'&&!window.verbsByStatus.__rb){window.verbsByStatus=function(){sync();var a=released(),A=new Set(a),S=st(),learned=new Set([].concat(S.learned||[],S.known||[]).filter(function(v){return A.has(v)})),active=uniq([].concat(S.active||[],S.unsure||[],S.unknown||[])).filter(function(v){return A.has(v)&&!learned.has(v)}),AS=new Set(active);return {active:active,learned:Array.from(learned),new:a.filter(function(v){return !learned.has(v)&&!AS.has(v)})}};window.verbsByStatus.__rb=true}if(typeof window.handleAssessmentClick==='function'&&!window.handleAssessmentClick.__rb){var h=window.handleAssessmentClick;window.handleAssessmentClick=function(){var run=function(){sync();if(!assess()){seedOff(st());if(typeof renderHome==='function')renderHome();return}return h.apply(this,arguments)}.bind(this);if(!loaded&&window.spVerbReleaseReady)return window.spVerbReleaseReady.then(run);return run()};window.handleAssessmentClick.__rb=true}if(typeof window.renderHome==='function'&&!window.renderHome.__rb){var r=window.renderHome;window.renderHome=function(){var args=arguments,ctx=this;if(!loaded&&window.spVerbReleaseReady){var app=document.getElementById('app');if(app)app.innerHTML='<section class="card"><h2>Verben werden geladen …</h2><p class="small">Die aktuelle Kursfreigabe wird geprüft.</p></section>';return window.spVerbReleaseReady.then(function(){sync();if(bridgeHomeNeeded())return bridgeHome();return r.apply(ctx,args)})}sync();if(bridgeHomeNeeded())return bridgeHome();return r.apply(ctx,args)};window.renderHome.__rb=true}}
function after(){patch();sync();try{if(typeof renderHome==='function'&&st()&&state.phase==='home')renderHome()}catch(e){}}
rel=local();window.spReleasedVerbList=released;window.spStrictReleasedVerbList=released;window.spVerbAssessmentEnabled=assess;window.spVerbPracticeTargetCount=target;window.spSyncVerbRelease=sync;window.spVerbReleaseDebug=function(){return {loaded:loaded,teacher:teacher(),courseId:rel&&(rel.id||rel.__docId),released:released(),target:target(),assessmentEnabled:assess(),data:data(),state:st()?{active:state.active,currentPackageVerbs:state.currentPackageVerbs,phase:state.phase,releaseFingerprint:state._releaseFingerprint}:null}};window.spVerbReleaseReady=load().then(function(){after();return data()}).catch(function(){loaded=true;after();return data()});patch();document.addEventListener('DOMContentLoaded',after);setTimeout(after,250);setTimeout(after,1000);setTimeout(after,3000);
})();