(function(){
let releaseData=null;
function json(k){try{return JSON.parse(localStorage.getItem(k)||'null')||{}}catch(e){return {}}}
function prof(){return window.profile||json('SP_USER_PROFILE')||json('SP_STUDENT_PROFILE')||{}}
function isTeacher(){var r=String(localStorage.getItem('SP_LOGIN_ROLE')||localStorage.getItem('SP_ACTIVE_ROLE')||'').toLowerCase();var p=prof();return r==='teacher'||r==='lehrer'||p.teacherPreview===true||p.isTeacher===true||localStorage.getItem('SP_TEACHER_PREVIEW')==='1'}
function hasData(d){return !!(d&&(d.enabledWords||d.releases||d.enabledModules||d.settings||d.defaultLocked!==undefined||d.releaseMode||d.verbenA1AssessmentEnabled!==undefined))}
function localData(){var p=prof();if(hasData(p.assignments))return p.assignments;var s=json('SP_COURSE_RELEASES');return hasData(s)?s:{}}
function codes(){var p=prof();var a=[p.kurs,p.kursnummer,p.courseCode,p.courseDocId,p.courseId,p.courseName,p.name,p.code,localStorage.getItem('SP_COURSE_CODE')].map(function(x){return String(x||'').trim()}).filter(Boolean);var out=[];a.forEach(function(x){out.push(x,x.toUpperCase(),x.toLowerCase(),x.replace(/\s+/g,''),x.toLowerCase().replace(/\s+/g,''))});return Array.from(new Set(out))}
async function getDoc(id){try{var s=await db.collection('courses').doc(String(id)).get();return s.exists?Object.assign({id:s.id},s.data()||{}):null}catch(e){return null}}
async function getQuery(field,val){try{var s=await db.collection('courses').where(field,'==',String(val)).limit(1).get();return s&&!s.empty?Object.assign({id:s.docs[0].id},s.docs[0].data()||{}):null}catch(e){return null}}
async function loadRemote(){if(isTeacher()){releaseData={releaseMode:'all',defaultLocked:false};return releaseData}if(!window.db)return null;var cs=codes();for(var i=0;i<cs.length;i++){var d=await getDoc(cs[i]);if(hasData(d)){releaseData=d;saveRelease(d);return d}}var fields=['courseCode','kurs','kursnummer','courseDocId','id','name','courseName','code'];for(var f=0;f<fields.length;f++){for(var j=0;j<cs.length;j++){var q=await getQuery(fields[f],cs[j]);if(hasData(q)){releaseData=q;saveRelease(q);return q}}}return null}
function saveRelease(d){try{localStorage.setItem('SP_COURSE_RELEASES',JSON.stringify(d));var p=prof();p.assignments=d;localStorage.setItem('SP_USER_PROFILE',JSON.stringify(p));localStorage.setItem('SP_STUDENT_PROFILE',JSON.stringify(p))}catch(e){}}
function data(){return isTeacher()?{releaseMode:'all',defaultLocked:false}:releaseData||localData()}
function get(o,path){var c=o;for(var i=0;i<path.length;i++){if(!c||typeof c!=='object'||!(path[i] in c))return undefined;c=c[path[i]]}return c}
function all(){return (window.ALL_VERBS||[]).map(function(x){return x.v}).filter(Boolean)}
function enabled(d,v){var ps=[['enabledWords',v],['enabledWords','verben-A1/'+v],['enabledWords','Verben A1/'+v],['releases','verben-A1','words',v],['releases','Verben A1','words',v]];for(var i=0;i<ps.length;i++){var x=get(d,ps[i]);if(x!==undefined)return x===true}return undefined}
function hasVerbControls(d){var ew=d.enabledWords||{};var names=all();if(Object.keys(ew).some(function(k){return k.indexOf('verben-A1/')>=0||k.indexOf('Verben A1/')>=0||names.indexOf(k)>=0}))return true;return !!(get(d,['releases','verben-A1','words'])||get(d,['releases','Verben A1','words']))}
function moduleOpen(d){var vals=[get(d,['enabledModules','Verben A1']),get(d,['enabledModules','verben-A1']),get(d,['releases','Verben A1','enabled']),get(d,['releases','verben-A1','enabled'])];if(vals.some(function(x){return x===false}))return false;if(vals.some(function(x){return x===true}))return true;return true}
function released(){var d=data();var names=all();if(isTeacher())return names;if(!hasData(d)||!moduleOpen(d))return [];if(d.releaseMode==='all'||d.releaseMode==='open'||d.defaultLocked===false&&!hasVerbControls(d))return names.filter(function(v){return enabled(d,v)!==false});return names.filter(function(v){return enabled(d,v)===true})}
function allowedSet(){return new Set(released())}
function filter(list){var s=allowedSet();return (list||[]).filter(function(v){return s.has(v)})}
function assessmentOn(){var d=data();var vals=[get(d,['settings','verben-A1','assessmentEnabled']),get(d,['settings','Verben A1','assessmentEnabled']),d.verbenA1AssessmentEnabled,get(d,['releases','verben-A1','assessmentEnabled']),get(d,['releases','Verben A1','assessmentEnabled'])];for(var i=0;i<vals.length;i++){if(vals[i]!==undefined)return vals[i]!==false}return true}
function cleanState(){if(!window.state||isTeacher())return;var s=allowedSet();['known','unsure','unknown','active','learned','practicePool','assessmentBatch','assessed','currentPackageVerbs'].forEach(function(k){if(Array.isArray(state[k]))state[k]=state[k].filter(function(v){return s.has(v)})});if(state.currentVerb&&!s.has(state.currentVerb))state.currentVerb='';if(state.currentTask&&state.currentTask.v&&!s.has(state.currentTask.v))state.currentTask=null;state.taskQueues={};state.taskDoneSets={};state.memoryCards=[];state.memoryDone=[];state.openCards=[];state.first=null;try{if(typeof saveState==='function')saveState()}catch(e){}}
function seedFirst20(){if(assessmentOn()||!window.state)return false;var list=released().slice(0,20);if(!list.length)return false;state.currentPackageVerbs=list.slice();state.assessmentBatch=list.slice();state.assessed=list.slice();state.known=filter(state.known||[]);state.unsure=list.filter(function(v){return !(state.learned||[]).includes(v)});state.unknown=[];state.active=state.unsure.slice();state.practicePool=[];state.currentVerb='';state.currentTask=null;state.phase='home';try{if(typeof saveState==='function')saveState()}catch(e){}return true}
function patch(){if(typeof window.unusedVerbs==='function'&&!window.unusedVerbs.__release2){var u=window.unusedVerbs;window.unusedVerbs=function(){if(!assessmentOn())return [];return filter(u())};window.unusedVerbs.__release2=true}if(typeof window.currentPracticeVerbs==='function'&&!window.currentPracticeVerbs.__release2){var cp=window.currentPracticeVerbs;window.currentPracticeVerbs=function(){seedFirst20();return filter(cp())};window.currentPracticeVerbs.__release2=true}if(typeof window.currentPackageAllVerbs==='function'&&!window.currentPackageAllVerbs.__release2){var ca=window.currentPackageAllVerbs;window.currentPackageAllVerbs=function(){seedFirst20();return filter(ca())};window.currentPackageAllVerbs.__release2=true}if(typeof window.handleAssessmentClick==='function'&&!window.handleAssessmentClick.__release2){var h=window.handleAssessmentClick;window.handleAssessmentClick=function(){cleanState();if(!assessmentOn()){seedFirst20();if(typeof renderHome==='function')renderHome();return}return h()};window.handleAssessmentClick.__release2=true}cleanState();seedFirst20()}
function rerender(){patch();try{if(typeof renderHome==='function')renderHome()}catch(e){}}
releaseData=localData();patch();document.addEventListener('DOMContentLoaded',patch);loadRemote().then(rerender).catch(function(){rerender()});setTimeout(patch,300);setTimeout(rerender,1200);setTimeout(rerender,3500);
window.spReleasedVerbList=released;window.spStrictReleasedVerbList=released;window.spVerbAssessmentEnabled=assessmentOn;window.spVerbReleaseDebug=function(){return {teacher:isTeacher(),codes:codes(),released:released(),assessmentEnabled:assessmentOn(),data:data(),state:window.state?{active:state.active,currentPackageVerbs:state.currentPackageVerbs,phase:state.phase}:null}};
})();