function memory(){
  state.phase="memory";state.currentGame="memory";
  const source=(state.practicePool&&state.practicePool.length?state.practicePool:state.active).filter(v=>!((state.taskDoneSets[taskDoneSetKey("memory")]||[]).some(k=>k.startsWith(v+":"))));
  const verbs=shuffle(source.length?source:(state.practicePool&&state.practicePool.length?state.practicePool:state.active)).slice(0,6);
  if(!verbs.length){renderHome();return}
  state.memoryCards=shuffle(verbs.flatMap(v=>[{type:"word",v},{type:"img",v}]));state.memoryDone=[];state.first=null;state.lock=false;saveState();renderMemory()
}
function renderMemory(){const done=state.memoryDone||[];$("app").innerHTML=`<h2>Memory</h2>${taskProgressHtml("memory","Memory")}<div class="memory">${state.memoryCards.map((c,i)=>`<button class="mem ${(done.includes(i)?"done":"")}" onclick="openMemory(${i})" id="mem${i}">${done.includes(i)?(c.type==="img"?imageBox(c.v,true):safeText(c.v)):"?"}</button>`).join("")}</div><div id="fb"></div>`;renderAndHydrate()}
function openMemory(i){if(state.lock)return;state.memoryDone=state.memoryDone||[];if(state.memoryDone.includes(i))return;const c=state.memoryCards[i];const el=$("mem"+i);el.classList.add("open");el.innerHTML=c.type==="img"?imageBox(c.v,true):`<span>${safeText(c.v)}</span>`;renderAndHydrate();if(state.first===null){state.first=i;saveState();return}const a=state.memoryCards[state.first];if(a.v===c.v&&a.type!==c.type){state.memoryDone.push(state.first,i);addEncounter(c.v,"memory",true);state.currentTask={skill:"memory",v:c.v,slot:findMemorySlot(c.v)};finishQueuedVerb("memory",c.v,true);state.first=null;saveState();if((state.memoryDone||[]).length===state.memoryCards.length){$("fb").innerHTML="<div class='ok'>Memory-Runde geschafft.</div>";setTimeout(()=>{if(taskDone("memory"))renderHome();else memory()},700)}}else{const first=state.first;state.lock=true;setTimeout(()=>{[$("mem"+first),$("mem"+i)].forEach(x=>{if(x){x.classList.remove("open");x.innerHTML="?"}});state.first=null;state.lock=false;saveState()},800)}}
function findMemorySlot(v){const done=state.taskDoneSets[taskDoneSetKey("memory")]||[];const source=(state.practicePool&&state.practicePool.length)?state.practicePool:state.active;const idx=source.findIndex((x,i)=>x===v&&!done.includes(x+":"+i));return idx<0?0:idx}
