const CFG={sub:'A1 Lektion 6 · Thema 3',key:'SP_L6_T3_V1'};
const CDN='https://sprachpilot.b-cdn.net/';
const WORDS=[
{id:'speisekarte',group:'Restaurant',type:'noun',article:'die',word:'Speisekarte',full:'die Speisekarte',image:'speisekarte.webp',sentence:'Ich lese die Speisekarte.',tr:{en:'menu',ru:'меню',uk:'меню',tr:'menü',ar:'قائمة الطعام',ja:'メニュー',ro:'meniu',pl:'menu',ku:'lîsteya xwarinê'}},
{id:'hamburger',group:'Restaurant',type:'noun',article:'der',word:'Hamburger',full:'der Hamburger',image:'hamburger.webp',sentence:'Ich esse den Hamburger.',tr:{en:'hamburger',ru:'гамбургер',uk:'гамбургер',tr:'hamburger',ar:'هامبرغر',ja:'ハンバーガー',ro:'hamburger',pl:'hamburger',ku:'hamburger'}},
{id:'speise',group:'Restaurant',type:'noun',article:'die',word:'Speise',full:'die Speise',image:'speise.webp',sentence:'Die Speise ist lecker.',tr:{en:'dish',ru:'блюдо',uk:'страва',tr:'yemek',ar:'طبق',ja:'料理',ro:'fel de mâncare',pl:'potrawa',ku:'xwarin'}},
{id:'pommes',group:'Restaurant',type:'noun',article:'die',word:'Pommes',full:'die Pommes',image:'pommes.webp',sentence:'Ich esse die Pommes.',alt:['die Pommes frites'],tr:{en:'fries',ru:'картофель фри',uk:'картопля фрі',tr:'patates kızartması',ar:'بطاطس مقلية',ja:'フライドポテト',ro:'cartofi prăjiți',pl:'frytki',ku:'kartolên sor kirî'}},
{id:'portion',group:'Restaurant',type:'noun',article:'die',word:'Portion',full:'die Portion',image:'portion.webp',sentence:'Ich nehme eine Portion Pommes.',tr:{en:'portion',ru:'порция',uk:'порція',tr:'porsiyon',ar:'حصة',ja:'一人前',ro:'porție',pl:'porcja',ku:'parçe'}},
{id:'ketchup',group:'Restaurant',type:'noun',article:'der/das',word:'Ketchup',full:'der/das Ketchup',image:'ketchup.webp',sentence:'Ich möchte Ketchup.',tr:{en:'ketchup',ru:'кетчуп',uk:'кетчуп',tr:'ketçap',ar:'كاتشب',ja:'ケチャップ',ro:'ketchup',pl:'ketchup',ku:'ketchup'}},
{id:'salat',group:'Restaurant',type:'noun',article:'der',word:'Salat',full:'der Salat',image:'salat.webp',sentence:'Ich esse den Salat.',tr:{en:'salad',ru:'салат',uk:'салат',tr:'salata',ar:'سلطة',ja:'サラダ',ro:'salată',pl:'sałatka',ku:'salata'}},
{id:'schinken',group:'Restaurant',type:'noun',article:'der',word:'Schinken',full:'der Schinken',image:'schinken.webp',sentence:'Ich esse den Schinken.',tr:{en:'ham',ru:'ветчина',uk:'шинка',tr:'jambon',ar:'لحم خنزير',ja:'ハム',ro:'șuncă',pl:'szynka',ku:'goştê parzekirî'}},
{id:'getraenk',group:'Restaurant',type:'noun',article:'das',word:'Getränk',full:'das Getränk',image:'getraenk.webp',sentence:'Ich trinke das Getränk.',tr:{en:'drink',ru:'напиток',uk:'напій',tr:'içecek',ar:'مشروب',ja:'飲み物',ro:'băutură',pl:'napój',ku:'vexwarin'}},
{id:'cola',group:'Restaurant',type:'noun',article:'die',word:'Cola',full:'die Cola',image:'cola.webp',sentence:'Ich trinke die Cola.',tr:{en:'cola',ru:'кола',uk:'кола',tr:'kola',ar:'كولا',ja:'コーラ',ro:'cola',pl:'cola',ku:'kola'}},
{id:'brot',group:'Basis',type:'noun',article:'das',word:'Brot',full:'das Brot',image:'brot.webp',sentence:'Ich esse das Brot.',tr:{en:'bread',ru:'хлеб',uk:'хліб',tr:'ekmek',ar:'خبز',ja:'パン',ro:'pâine',pl:'chleb',ku:'nan'}},
{id:'apfel',group:'Basis',type:'noun',article:'der',word:'Apfel',full:'der Apfel',image:'apfel.webp',sentence:'Ich esse den Apfel.',tr:{en:'apple',ru:'яблоко',uk:'яблуко',tr:'elma',ar:'تفاحة',ja:'りんご',ro:'măr',pl:'jabłko',ku:'sêv'}},
{id:'saft',group:'Basis',type:'noun',article:'der',word:'Saft',full:'der Saft',image:'saft.webp',sentence:'Ich trinke den Saft.',tr:{en:'juice',ru:'сок',uk:'сік',tr:'meyve suyu',ar:'عصير',ja:'ジュース',ro:'suc',pl:'sok',ku:'avê fêkî'}},
{id:'kaese',group:'Basis',type:'noun',article:'der',word:'Käse',full:'der Käse',image:'kaese.webp',sentence:'Ich esse den Käse.',tr:{en:'cheese',ru:'сыр',uk:'сир',tr:'peynir',ar:'جبن',ja:'チーズ',ro:'brânză',pl:'ser',ku:'penîr'}},
{id:'picknick',group:'Planen',type:'noun',article:'das',word:'Picknick',full:'das Picknick',image:'picknick.webp',sentence:'Wir planen ein Picknick.',tr:{en:'picnic',ru:'пикник',uk:'пікнік',tr:'piknik',ar:'نزهة',ja:'ピクニック',ro:'picnic',pl:'piknik',ku:'pîknîk'}},
{id:'party',group:'Planen',type:'noun',article:'die',word:'Party',full:'die Party',image:'party.webp',sentence:'Wir planen eine Party.',tr:{en:'party',ru:'вечеринка',uk:'вечірка',tr:'parti',ar:'حفلة',ja:'パーティー',ro:'petrecere',pl:'impreza',ku:'partî'}},
{id:'mitbringen',group:'Planen',type:'verb',article:'',word:'mitbringen',full:'mitbringen',image:'picknick.webp',sentence:'Ich bringe einen Salat mit.',tr:{en:'to bring along',ru:'приносить с собой',uk:'приносити з собою',tr:'getirmek',ar:'يحضر معه',ja:'持ってくる',ro:'a aduce',pl:'przynosić',ku:'bi xwe re anîn'}},
{id:'kaufen',group:'Planen',type:'verb',article:'',word:'kaufen',full:'kaufen',image:'einkaufen.webp',sentence:'Ich kaufe eine Cola.',tr:{en:'to buy',ru:'покупать',uk:'купувати',tr:'satın almak',ar:'يشتري',ja:'買う',ro:'a cumpăra',pl:'kupować',ku:'kirîn'}}
];
const COMPOUNDS=[
{left:'Apfel',right:'Saft',article:'der',word:'Apfelsaft',full:'der Apfelsaft',image:'apfelsaft.webp',rule:'der Saft → der Apfelsaft'},
{left:'Tomate',right:'Salat',article:'der',word:'Tomatensalat',full:'der Tomatensalat',image:'tomatensalat.webp',rule:'der Salat → der Tomatensalat'},
{left:'Schinken',right:'Salat',article:'der',word:'Schinkensalat',full:'der Schinkensalat',image:'schinkensalat.webp',rule:'der Salat → der Schinkensalat'},
{left:'Käse',right:'Brot',article:'das',word:'Käsebrot',full:'das Käsebrot',image:'kaesebrot.webp',rule:'das Brot → das Käsebrot'},
{left:'Schinken',right:'Brot',article:'das',word:'Schinkenbrot',full:'das Schinkenbrot',image:'schinkenbrot.webp',rule:'das Brot → das Schinkenbrot'}
];
const AKK_BEST=[
{q:'Ich esse ___ Hamburger.',a:'den',opts:['der','den','die'],sol:'Ich esse den Hamburger.'},{q:'Ich esse ___ Salat.',a:'den',opts:['der','den','das'],sol:'Ich esse den Salat.'},{q:'Ich trinke ___ Cola.',a:'die',opts:['den','die','das'],sol:'Ich trinke die Cola.'},{q:'Ich lese ___ Speisekarte.',a:'die',opts:['der','den','die'],sol:'Ich lese die Speisekarte.'},{q:'Ich trinke ___ Getränk.',a:'das',opts:['der','den','das'],sol:'Ich trinke das Getränk.'},{q:'Ich esse ___ Brot.',a:'das',opts:['der','den','das'],sol:'Ich esse das Brot.'}
];
const AKK_UNBEST=[
{q:'Ich nehme ___ Hamburger.',a:'einen',opts:['ein','einen','eine'],sol:'Ich nehme einen Hamburger.'},{q:'Ich nehme ___ Salat.',a:'einen',opts:['ein','einen','eine'],sol:'Ich nehme einen Salat.'},{q:'Ich nehme ___ Cola.',a:'eine',opts:['ein','einen','eine'],sol:'Ich nehme eine Cola.'},{q:'Ich nehme ___ Getränk.',a:'ein',opts:['ein','einen','eine'],sol:'Ich nehme ein Getränk.'},{q:'Ich nehme ___ Portion Pommes.',a:'eine',opts:['ein','einen','eine'],sol:'Ich nehme eine Portion Pommes.'}
];
const POSSESSIVE=[
{q:'Ich esse ___ Hamburger.',a:'meinen',opts:['mein','meinen','meine'],sol:'Ich esse meinen Hamburger.'},{q:'Ich trinke ___ Cola.',a:'meine',opts:['mein','meinen','meine'],sol:'Ich trinke meine Cola.'},{q:'Du isst ___ Salat.',a:'deinen',opts:['dein','deinen','deine'],sol:'Du isst deinen Salat.'},{q:'Du trinkst ___ Getränk.',a:'dein',opts:['dein','deinen','deine'],sol:'Du trinkst dein Getränk.'},{q:'Ich lese ___ Speisekarte.',a:'meine',opts:['mein','meinen','meine'],sol:'Ich lese meine Speisekarte.'}
];
const SVO=[
{s:'Der Mann isst den Hamburger.',sub:'Der Mann',verb:'isst',obj:'den Hamburger'},{s:'Die Frau trinkt die Cola.',sub:'Die Frau',verb:'trinkt',obj:'die Cola'},{s:'Das Kind nimmt eine Portion Pommes.',sub:'Das Kind',verb:'nimmt',obj:'eine Portion Pommes'},{s:'Der Kellner bringt das Getränk.',sub:'Der Kellner',verb:'bringt',obj:'das Getränk'},{s:'Anna liest die Speisekarte.',sub:'Anna',verb:'liest',obj:'die Speisekarte'}
];
const ERRORS=[
{wrong:'Ich esse der Hamburger.',right:'Ich esse den Hamburger.',a:'den',tip:'der → den im Akkusativ'},{wrong:'Ich nehme ein Salat.',right:'Ich nehme einen Salat.',a:'einen',tip:'ein → einen bei der-Wörtern'},{wrong:'Ich esse mein Hamburger.',right:'Ich esse meinen Hamburger.',a:'meinen',tip:'mein → meinen bei der-Wörtern'},{wrong:'Du trinkst deinen Cola.',right:'Du trinkst deine Cola.',a:'deine',tip:'die Cola bleibt die/deine'},{wrong:'Ich trinke den Getränk.',right:'Ich trinke das Getränk.',a:'das',tip:'das bleibt das'}
];
const DIALOGS=[
{title:'Picknick planen',text:'A: Wir machen am Samstag ein Picknick.\nB: Super. Was brauchen wir?\nA: Ich bringe einen Salat und Getränke mit.\nB: Ich kaufe Cola und eine Portion Pommes.\nA: Bringst du auch Ketchup mit?\nB: Ja, ich bringe Ketchup mit.',qs:[['Sie machen am Samstag ein Picknick.',true],['A bringt einen Salat mit.',true],['B kauft Wasser.',false],['B bringt Ketchup mit.',true]]},
{title:'Party planen',text:'A: Wir machen am Freitag eine Party.\nB: Was kaufen wir?\nA: Wir kaufen Hamburger, Pommes und Cola.\nB: Brauchen wir auch Salat?\nA: Ja, wir brauchen einen Salat.',qs:[['Die Party ist am Freitag.',true],['Sie kaufen Hamburger.',true],['Sie brauchen keine Getränke.',false],['Sie kaufen einen Salat.',true]]}
];
const MESSAGES=[
{title:'Nachricht: Picknick',text:'Hallo Sara,\nwir machen morgen ein Picknick im Park. Ich bringe einen Salat und Brot mit. Kannst du bitte Getränke kaufen? Wir brauchen Cola und Wasser. Bring bitte auch Ketchup mit.\nLiebe Grüße\nMila',qs:[['Das Picknick ist heute.',false],['Mila bringt einen Salat mit.',true],['Sara soll Getränke kaufen.',true],['Sie brauchen Ketchup.',true]]},
{title:'Nachricht: Party',text:'Hallo Tom,\ndie Party ist am Samstag um 18 Uhr. Bitte bring eine Portion Pommes und Ketchup mit. Ich kaufe Hamburger und Cola. Anna bringt einen Salat mit.\nBis Samstag!\nLeo',qs:[['Die Party ist am Samstag.',true],['Tom bringt Hamburger mit.',false],['Leo kauft Cola.',true],['Anna bringt einen Salat mit.',true]]}
];
const SENTENCES=[
{parts:['Ich','bringe','einen Salat','mit.'],sol:'Ich bringe einen Salat mit.'},{parts:['Wir','kaufen','die Cola.'],sol:'Wir kaufen die Cola.'},{parts:['Tom','bringt','Ketchup','mit.'],sol:'Tom bringt Ketchup mit.'},{parts:['Anna','nimmt','einen Hamburger.'],sol:'Anna nimmt einen Hamburger.'},{parts:['Wir','brauchen','Getränke.'],sol:'Wir brauchen Getränke.'}
];
const TASKS=[['karteikarten.html',WORDS.length,'Karteikarten'],['artikel.html',WORDS.filter(w=>w.type==='noun').length,'Artikel'],['bild-wort.html',WORDS.length,'Bild → Wort'],['komposita-bauen.html',COMPOUNDS.length,'Komposita bauen'],['komposita-artikel.html',COMPOUNDS.length,'Artikel von Komposita'],['akkusativ-bestimmt.html',AKK_BEST.length,'den · die · das'],['akkusativ-unbestimmt.html',AKK_UNBEST.length,'einen · eine · ein'],['meinen-deinen.html',POSSESSIVE.length,'meinen · deinen'],['svo.html',SVO.length,'Subjekt · Verb · Objekt'],['nom-akk.html',SVO.length,'Nominativ oder Akkusativ'],['dialoge-planen.html',8,'Dialoge planen'],['nachrichten-rf.html',8,'Nachrichten R/F'],['fehler-finden.html',ERRORS.length,'Fehler finden'],['satz-bauen.html',SENTENCES.length,'Satz bauen'],['pruefung.html',10,'Prüfung']];
const ICONS={'karteikarten.html':'🃏','artikel.html':'🔤','bild-wort.html':'🖼️','komposita-bauen.html':'🧱','komposita-artikel.html':'🏷️','akkusativ-bestimmt.html':'🎯','akkusativ-unbestimmt.html':'1️⃣','meinen-deinen.html':'👤','svo.html':'📌','nom-akk.html':'⚖️','dialoge-planen.html':'💬','nachrichten-rf.html':'📩','fehler-finden.html':'🛠️','satz-bauen.html':'🧩','pruefung.html':'★'};
const LANGS={en:'Englisch',ru:'Russisch',tr:'Türkisch',uk:'Ukrainisch',ar:'Arabisch',ja:'Japanisch',ro:'Rumänisch',pl:'Polnisch',ku:'Kurdisch'};
function profile(){try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||localStorage.getItem('SP_STUDENT_PROFILE')||'null')}catch(e){return null}}
function langKey(){const m=String(profile()?.muttersprache||profile()?.motherLanguage||'').toLowerCase();if(['uk','ua'].includes(m)||m.includes('ukrain'))return'uk';if(m.includes('russ'))return'ru';if(m.includes('türk')||m.includes('turk'))return'tr';if(m.includes('arab'))return'ar';if(m.includes('japan'))return'ja';if(m.includes('rumän')||m.includes('ruman'))return'ro';if(m.includes('pol'))return'pl';if(m.includes('kurd'))return'ku';return'en'}
function tr(w){const k=langKey(),t=w.tr||{};return t[k]||t.en||'—'}
function full(w){return w.full||((w.article?`${w.article} `:'')+w.word)}function img(w){return CDN+(w.image||w.id+'.webp')}
function visual(w){return `<div class="task-img-box"><img src="${img(w)}" alt="${full(w)}" onerror="this.parentElement.textContent='${full(w)}'"></div>`}function miniVisual(w){return `<img src="${img(w)}" alt="${full(w)}" onerror="this.replaceWith(document.createTextNode('${full(w)}'))">`}
function simple(x){return String(x||'').toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[.,!?;:]/g,'').replace(/\s+/g,' ')}function exact(v,s){const a=simple(v);return (Array.isArray(s)?s:[s]).some(x=>simple(x)===a)}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function say(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='de-DE';u.rate=.86;speechSynthesis.speak(u)}
function taskKey(file){return CFG.key+'_'+file}function loadTask(file,total){try{const st=JSON.parse(localStorage.getItem(taskKey(file))||'null');if(st&&st.total===total&&Array.isArray(st.done)&&Array.isArray(st.queue))return st}catch(e){}return{total,done:[],queue:[...Array(total).keys()].sort(()=>Math.random()-.5),current:null,tries:0,hadWrong:false}}
function saveTask(file,st){localStorage.setItem(taskKey(file),JSON.stringify(st));syncTask(file,st)}function spNextIndex(file,total){let st=loadTask(file,total);if(st.current===null||st.current===undefined){if(!st.queue.length&&st.done.length<total)st.queue=[...Array(total).keys()].filter(i=>!st.done.includes(i)).sort(()=>Math.random()-.5);st.current=st.queue.shift();st.tries=0;st.hadWrong=false;saveTask(file,st)}return st.current}
function spMarkRight(file,total){let st=loadTask(file,total),c=st.current;if(c!==null&&c!==undefined){if(st.hadWrong||st.tries>0){if(!st.done.includes(c)&&!st.queue.includes(c))st.queue.push(c)}else if(!st.done.includes(c))st.done.push(c)}st.current=null;st.tries=0;st.hadWrong=false;saveTask(file,st)}function spMarkWrong(file,total){let st=loadTask(file,total);st.tries=(st.tries||0)+1;st.hadWrong=true;saveTask(file,st);return st.tries}
function pctFor(file,total){return total?Math.round((loadTask(file,total).done.length||0)/total*100)||0:0}function progress(file,total){const d=loadTask(file,total).done.length,p=pctFor(file,total);return `<div class="small">${d} richtig · ${total-d} übrig · ${p}%</div><div class="progress"><div class="bar" style="width:${p}%"></div></div>`}
function help3(t,a,b,sol){if(t===1)return `<div class="no">${a}</div>`;if(t===2)return `<div class="hint">${b}</div>`;return `<div class="no">Lösung: ${sol}</div>`}function instruction(txt){return `<div class="task-instruction">${txt}</div>`}function complete(area,file,next='index.html'){area.innerHTML=`<div class="finish-box"><div class="finish-icon">✓</div><div class="question">Geschafft!</div><div class="hint">Diese Aufgabe ist abgeschlossen.</div><div class="actions"><a class="btn" href="${next}">Weiter →</a><a class="btn secondary" href="index.html">Zum Menü</a></div></div>`}
function markTaskDone(file,total){saveTask(file,{total,done:[...Array(total).keys()],queue:[],current:null,tries:0,hadWrong:false})}function syncTask(file,st){try{const done=st.done?.length||0,total=st.total||0,percent=total?Math.round(done/total*100):0;const payload={module:'wortschatz',moduleTitle:'Wortschatz',level:'A1',lesson:6,theme:3,topicId:'wortschatz-a1-lektion-6-thema-3',title:'A1 Lektion 6 · Thema 3',file,taskTitle:(TASKS.find(t=>t[0]===file)||[])[2]||file,percent,done,total,completed:percent>=100};if(window.SPProgress&&SPProgress.recordTaskProgress)SPProgress.recordTaskProgress(payload)}catch(e){}}
function header(title,showReset=false){const h=document.querySelector('.topbar');if(!h)return;const p=profile(),name=`${p?.vorname||p?.firstName||''} ${p?.nachname||p?.lastName||''}`.trim()||'Schüler/in',dashboard=localStorage.getItem('SP_LOGIN_ROLE')==='teacher'?'/teacher/index.html':'/student-dashboard/index.html';h.innerHTML=`<div class="topbar-main"><a class="brand" href="/index.html"><div class="logo"><img src="/assets/logo/sprachpilot-logo.png" alt="SprachPilot"></div><div><h1>SprachPilot</h1><div class="subtitle">${title} · ${CFG.sub}</div></div></a><div class="account-tools"><span class="account-pill">${name}</span><a class="account-link" href="${dashboard}">Dashboard</a><a class="account-link" href="/profile/index.html">Profil</a></div></div><nav class="nav"><a class="btn secondary" href="index.html">← Zurück</a><a class="btn secondary" href="uebersicht.html">Übersicht</a>${showReset?'<button class="btn danger-btn" onclick="resetThemeProgress()">Fortschritte löschen</button>':''}</nav>`}
function resetThemeProgress(){if(!confirm('Fortschritte in Thema 3 löschen?'))return;Object.keys(localStorage).filter(k=>k.startsWith(CFG.key)).forEach(k=>localStorage.removeItem(k));location.reload()}
function renderOverview(target){const groups=[...new Set(WORDS.map(w=>w.group))];target.innerHTML=groups.map(g=>`<section class="type-block"><div class="type-title">${g}</div>${WORDS.filter(w=>w.group===g).map(w=>`<div class="word-row"><div class="word-placeholder">${miniVisual(w)}</div><div><b>${full(w)}</b><br><span class="small">${w.sentence}${w.alt?' / '+w.alt.join(' / '):''}</span><div class="small">Übersetzung (${LANGS[langKey()]||'EN'}): ${tr(w)}</div><span class="tag">${w.type}</span></div></div>`).join('')}</section>`).join('')+`<section class="type-block"><div class="type-title">Grammatik</div><div class="grammar-rule"><b>Akkusativ:</b> der → den, ein → einen, mein/dein → meinen/deinen.</div><div class="grammar-rule"><b>Komposita:</b> Der Artikel kommt vom letzten Wort: der Saft → der Apfelsaft, das Brot → das Käsebrot.</div><div class="grammar-rule"><b>SVO:</b> Wer? = Subjekt/Nominativ. Was? = Objekt/Akkusativ.</div></section>`}
function renderMenu(){const avg=Math.round(TASKS.reduce((s,t)=>s+pctFor(t[0],t[1]),0)/TASKS.length)||0;totalCircle.textContent=avg+'%';totalBar.style.width=avg+'%';totalText.textContent=TASKS.filter(t=>pctFor(t[0],t[1])>=100).length+' / '+TASKS.length+' Aufgaben abgeschlossen';taskGrid.innerHTML=`<div class="grid">${TASKS.map((t,i)=>{const p=pctFor(t[0],t[1]);return `<a class="module" href="${t[0]}"><div class="num">${i+1}. ${t[2]}</div><div class="big-icon">${ICONS[t[0]]||'▶'}</div><p class="small">Akkusativ, Komposita, Restaurant und Planen üben.</p><div class="progress"><div class="bar" style="width:${p}%"></div></div><div class="small">${p}%</div><div class="start">${p>=100?'Fertig':'Starten'}</div></a>`}).join('')}</div>`}
