const L6T4_CFG={key:'SP_L6_T4_V1',topicId:'wortschatz-a1-lektion-6-thema-4',title:'A1 Lektion 6 · Thema 4'};
const L6T4_TASKS=[['plural-sprechen.html',()=>window.L6T4PluralItems?.length||0,'Plural sprechen']];
function l6t4Profile(){try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||localStorage.getItem('SP_STUDENT_PROFILE')||'null')}catch(e){return null}}
function l6t4IsPreview(){return localStorage.getItem('SP_LOGIN_ROLE')==='teacher'&&(localStorage.getItem('SP_TEACHER_PREVIEW')==='1'||sessionStorage.getItem('SP_TEACHER_PREVIEW')==='1')}
function l6t4Storage(){return l6t4IsPreview()?sessionStorage:localStorage}
function l6t4TaskKey(file){return (l6t4IsPreview()?'SP_L6_T4_PREVIEW_':L6T4_CFG.key+'_')+file}
function l6t4Simple(value){return String(value||'').toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[.,!?;:]/g,'').replace(/\s+/g,' ')}
function l6t4Exact(value,solutions){const normalized=l6t4Simple(value);return (Array.isArray(solutions)?solutions:[solutions]).some(solution=>l6t4Simple(solution)===normalized)}
function l6t4Shuffle(list){const copy=list.slice();for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function l6t4Load(file,total){try{const value=JSON.parse(l6t4Storage().getItem(l6t4TaskKey(file))||'null');if(value&&value.total===total&&Array.isArray(value.done)&&Array.isArray(value.queue))return value}catch(e){}return{total,done:[],queue:l6t4Shuffle([...Array(total).keys()]),current:null,tries:0,hadWrong:false}}
function l6t4Save(file,state){l6t4Storage().setItem(l6t4TaskKey(file),JSON.stringify(state));l6t4Sync(file,state)}
function l6t4Sync(file,state){if(l6t4IsPreview())return;try{const done=state.done.length,total=state.total,percent=total?Math.round(done/total*100):0,title=(L6T4_TASKS.find(task=>task[0]===file)||[])[2]||file;window.SPProgress?.recordTaskProgress?.({module:'wortschatz',moduleTitle:'Wortschatz',level:'A1',lesson:6,theme:4,topicId:L6T4_CFG.topicId,title:L6T4_CFG.title,file,taskTitle:title,percent,done,total,completed:percent>=100})}catch(e){}}
function l6t4NextIndex(file,total){const state=l6t4Load(file,total);if(state.current===null||state.current===undefined){if(!state.queue.length&&state.done.length<total)state.queue=l6t4Shuffle([...Array(total).keys()].filter(index=>!state.done.includes(index)));state.current=state.queue.shift();state.tries=0;state.hadWrong=false;l6t4Save(file,state)}return state.current}
function l6t4Wrong(file,total){const state=l6t4Load(file,total);state.tries=(state.tries||0)+1;state.hadWrong=true;l6t4Save(file,state);return state.tries}
function l6t4Right(file,total){const state=l6t4Load(file,total),current=state.current;if(current!==null&&current!==undefined){if(state.hadWrong||state.tries>0){if(!state.done.includes(current)&&!state.queue.includes(current))state.queue.push(current)}else if(!state.done.includes(current))state.done.push(current)}state.current=null;state.tries=0;state.hadWrong=false;l6t4Save(file,state)}
function l6t4Percent(file,total){const state=l6t4Load(file,total);return total?Math.round(state.done.length/total*100):0}
function l6t4Progress(file,total){const state=l6t4Load(file,total),percent=l6t4Percent(file,total);return `<div class="small">${state.done.length} richtig · ${total-state.done.length} übrig · ${percent}%</div><div class="progress"><div class="bar" style="width:${percent}%"></div></div>`}
function l6t4Header(title,showReset=false){const header=document.querySelector('.topbar');if(!header)return;const profile=l6t4Profile(),name=`${profile?.vorname||profile?.firstName||''} ${profile?.nachname||profile?.lastName||''}`.trim()||'Schüler/in',dashboard=localStorage.getItem('SP_LOGIN_ROLE')==='teacher'?'/teacher/index.html':'/student-dashboard/index.html';header.innerHTML=`<div class="topbar-main"><a class="brand" href="/index.html"><div class="logo"><img src="/assets/logo/sprachpilot-logo.png" alt="SprachPilot"></div><div><h1>SprachPilot</h1><div class="subtitle">${title} · ${L6T4_CFG.title}</div></div></a><div class="account-tools"><span class="account-pill">${name}</span><a class="account-link" href="${dashboard}">Dashboard</a><a class="account-link" href="/profile/index.html">Profil</a></div></div><nav class="nav"><a class="btn secondary" href="index.html">← Zurück</a>${showReset?'<button class="btn secondary" type="button" onclick="l6t4Reset()">Fortschritte löschen</button>':''}</nav>`}
function l6t4Reset(){if(!confirm('Fortschritte in Lektion 6 · Thema 4 löschen? Bereits verdiente Punkte bleiben erhalten.'))return;const storage=l6t4Storage(),keys=[];for(let i=0;i<storage.length;i++){const key=storage.key(i);if(String(key).includes('SP_L6_T4'))keys.push(key)}keys.forEach(key=>storage.removeItem(key));location.href='index.html?reset='+Date.now()}
function l6t4RenderMenu(){const grid=document.getElementById('taskGrid'),circle=document.getElementById('totalCircle'),text=document.getElementById('totalText'),bar=document.getElementById('totalBar');const tasks=L6T4_TASKS.map(task=>[task[0],task[1](),task[2]]),average=Math.round(tasks.reduce((sum,task)=>sum+l6t4Percent(task[0],task[1]),0)/Math.max(1,tasks.length));if(circle)circle.textContent=average+'%';if(bar)bar.style.width=average+'%';if(text)text.textContent=tasks.filter(task=>l6t4Percent(task[0],task[1])>=100).length+' / '+tasks.length+' Aufgaben abgeschlossen';if(grid)grid.innerHTML='<div class="grid">'+tasks.map((task,index)=>{const percent=l6t4Percent(task[0],task[1]);return `<a class="module" href="${task[0]}?v=l6t4-plural1"><div class="num">${index+1}. ${task[2]}</div><div class="big-icon">🎤</div><p class="small">Pluralformen aus Lektion 6 sprechen oder ersatzweise schreiben.</p><div class="progress"><div class="bar" style="width:${percent}%"></div></div><div class="small">${percent}%</div><div class="start">${percent>=100?'Fertig':'Starten'}</div></a>`}).join('')+'</div>'}
function l6t4Say(text){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='de-DE';utterance.rate=.86;speechSynthesis.speak(utterance)}
function l6t4Complete(area,next='index.html'){area.innerHTML=`<div class="finish-box"><div class="finish-icon">✓</div><h2>Geschafft!</h2><p>Du hast alle Pluralformen fehlerfrei wiederholt.</p><div class="actions"><a class="btn" href="${next}">Weiter →</a><a class="btn secondary" href="index.html">Zum Menü</a></div></div>`}
