(function(){
'use strict';
window.L6T4PluralItems=[
 {id:'wetter',source:'Thema 1',singular:'das Wetter',noPlural:true},
 {id:'sonne',source:'Thema 1',singular:'die Sonne',plural:'die Sonnen'},
 {id:'regen',source:'Thema 1',singular:'der Regen',noPlural:true},
 {id:'wind',source:'Thema 1',singular:'der Wind',plural:'die Winde'},
 {id:'wolke',source:'Thema 1',singular:'die Wolke',plural:'die Wolken'},
 {id:'schnee',source:'Thema 1',singular:'der Schnee',noPlural:true},
 {id:'gewitter',source:'Thema 1',singular:'das Gewitter',plural:'die Gewitter'},
 {id:'blitz',source:'Thema 1',singular:'der Blitz',plural:'die Blitze'},
 {id:'eis',source:'Thema 1',singular:'das Eis',noPlural:true},
 {id:'donner',source:'Thema 1',singular:'der Donner',noPlural:true},
 {id:'hagel',source:'Thema 1',singular:'der Hagel',noPlural:true},
 {id:'nebel',source:'Thema 1',singular:'der Nebel',noPlural:true},
 {id:'sturm',source:'Thema 1',singular:'der Sturm',plural:'die Stürme'},
 {id:'fruehling',source:'Thema 2',singular:'der Frühling',plural:'die Frühlinge'},
 {id:'sommer',source:'Thema 2',singular:'der Sommer',plural:'die Sommer'},
 {id:'herbst',source:'Thema 2',singular:'der Herbst',plural:'die Herbste'},
 {id:'winter',source:'Thema 2',singular:'der Winter',plural:'die Winter'},
 {id:'speisekarte',source:'Thema 3',singular:'die Speisekarte',plural:'die Speisekarten'},
 {id:'hamburger',source:'Thema 3',singular:'der Hamburger',plural:'die Hamburger'},
 {id:'speise',source:'Thema 3',singular:'die Speise',plural:'die Speisen'},
 {id:'portion',source:'Thema 3',singular:'die Portion',plural:'die Portionen'},
 {id:'ketchup',source:'Thema 3',singular:'der/das Ketchup',noPlural:true},
 {id:'salat',source:'Thema 3',singular:'der Salat',plural:'die Salate'},
 {id:'schinken',source:'Thema 3',singular:'der Schinken',noPlural:true},
 {id:'getraenk',source:'Thema 3',singular:'das Getränk',plural:'die Getränke'},
 {id:'cola',source:'Thema 3',singular:'die Cola',plural:'die Colas'},
 {id:'brot',source:'Thema 3',singular:'das Brot',plural:'die Brote'},
 {id:'apfel',source:'Thema 3',singular:'der Apfel',plural:'die Äpfel'},
 {id:'saft',source:'Thema 3',singular:'der Saft',plural:'die Säfte'},
 {id:'kaese',source:'Thema 3',singular:'der Käse',noPlural:true},
 {id:'picknick',source:'Thema 3',singular:'das Picknick',plural:'die Picknicks'},
 {id:'party',source:'Thema 3',singular:'die Party',plural:'die Partys'},
 {id:'apfelsaft',source:'Thema 3',singular:'der Apfelsaft',plural:'die Apfelsäfte'},
 {id:'tomatensalat',source:'Thema 3',singular:'der Tomatensalat',plural:'die Tomatensalate'},
 {id:'schinkensalat',source:'Thema 3',singular:'der Schinkensalat',plural:'die Schinkensalate'},
 {id:'kaesebrot',source:'Thema 3',singular:'das Käsebrot',plural:'die Käsebrote'},
 {id:'schinkenbrot',source:'Thema 3',singular:'das Schinkenbrot',plural:'die Schinkenbrote'},
 {id:'hunger',source:'Thema 4',singular:'der Hunger',noPlural:true},
 {id:'durst',source:'Thema 4',singular:'der Durst',noPlural:true},
 {id:'hobby',source:'Thema 4',singular:'das Hobby',plural:'die Hobbys'},
 {id:'beruf',source:'Thema 4',singular:'der Beruf',plural:'die Berufe'},
 {id:'alter',source:'Thema 4',singular:'das Alter',noPlural:true},
 {id:'freizeit',source:'Thema 4',singular:'die Freizeit',plural:'die Freizeiten'},
 {id:'wuerfel',source:'Thema 4',singular:'der Würfel',plural:'die Würfel'},
 {id:'freund',source:'Thema 4',singular:'der Freund',plural:'die Freunde'},
 {id:'gitarre',source:'Thema 4',singular:'die Gitarre',plural:'die Gitarren'},
 {id:'fahrrad',source:'Thema 4',singular:'das Fahrrad',plural:'die Fahrräder'},
 {id:'buch',source:'Thema 4',singular:'das Buch',plural:'die Bücher'},
 {id:'film',source:'Thema 4',singular:'der Film',plural:'die Filme'},
 {id:'farbe',source:'Thema 4',singular:'die Farbe',plural:'die Farben'},
 {id:'musik',source:'Thema 4',singular:'die Musik',noPlural:true},
 {id:'krimi',source:'Thema 4',singular:'der Krimi',plural:'die Krimis'},
 {id:'lieblingsbuch',source:'Thema 4',singular:'das Lieblingsbuch',plural:'die Lieblingsbücher'},
 {id:'lieblingsfilm',source:'Thema 4',singular:'der Lieblingsfilm',plural:'die Lieblingsfilme'},
 {id:'lieblingsfarbe',source:'Thema 4',singular:'die Lieblingsfarbe',plural:'die Lieblingsfarben'},
 {id:'lieblingshobby',source:'Thema 4',singular:'das Lieblingshobby',plural:'die Lieblingshobbys'}
].map(item=>({...item,answer:item.noPlural?'kein Plural üblich':item.plural}));
})();
