(function(){
'use strict';

const V=(id,word,meaning,image,extra={})=>({id,word,meaning,image,...extra});
const C=(prompt,answer,options,hint,image='',audio='')=>({kind:'choice',prompt,answer,options,hint,image,audio});
const I=(prompt,answer,hint,image='',answers=[])=>({kind:'input',prompt,answer,answers,hint,image});
const O=(prompt,answer,tokens,hint,image='')=>({kind:'order',prompt,answer,tokens,hint,image});
const F=(prompt,minWords=4,example='')=>({kind:'free',prompt,minWords,example});

const vocabulary=[
 V('hunger','der Hunger','Man möchte etwas essen.','hunger.webp',{plural:'kein Plural üblich',example:'Ich habe Hunger.'}),
 V('durst','der Durst','Man möchte etwas trinken.','durst.webp',{plural:'kein Plural üblich',example:'Ich habe Durst.'}),
 V('tanzen','tanzen','Musik hören und den Körper bewegen.','tanzen.webp',{example:'Wir tanzen gern.'}),
 V('wandern','wandern','lange zu Fuß in der Natur gehen.','wandern.webp',{example:'Am Sonntag wandern wir.'}),
 V('schwimmen','schwimmen','sich im Wasser bewegen.','schwimmen.webp',{example:'Ich schwimme gern.'}),
 V('gitarre-spielen','Gitarre spielen','Musik mit einer Gitarre machen.','gitarre_spielen.webp',{example:'Lea spielt Gitarre.'}),
 V('freunde-treffen','Freunde treffen','mit Freunden zusammen sein.','freunde_treffen.webp',{example:'Ich treffe oft Freunde.'}),
 V('fahrrad-fahren','Fahrrad fahren','mit dem Fahrrad fahren.','fahrrad_fahren.webp',{example:'Tim fährt gern Fahrrad.'}),
 V('stricken','stricken','mit Wolle Kleidung machen.','stricken.webp',{example:'Meine Oma strickt gern.'}),
 V('grillen','grillen','Essen draußen auf einem Grill machen.','grillen.webp',{example:'Wir grillen am Samstag.'}),
 V('hobby','das Hobby','etwas, das man gern in der Freizeit macht.','hobby.webp',{plural:'die Hobbys',example:'Mein Hobby ist Schwimmen.'}),
 V('wichtig','wichtig','etwas ist nicht egal.','wichtig.webp',{example:'Freizeit ist wichtig.'}),
 V('internet-surfen','im Internet surfen','Internetseiten ansehen.','im_internet_surfen.webp',{example:'Ich surfe oft im Internet.'}),
 V('beruf','der Beruf','Arbeit, die eine Person macht.','beruf.webp',{plural:'die Berufe',example:'Was ist dein Beruf?'}),
 V('alter','das Alter','wie viele Jahre eine Person hat.','alter.webp',{plural:'kein Plural üblich',example:'Wie ist dein Alter?'}),
 V('freizeit','die Freizeit','Zeit ohne Arbeit oder Schule.','freizeit.webp',{plural:'kein Plural üblich',example:'In meiner Freizeit lese ich.'}),
 V('spass','Das macht Spaß.','Das ist schön und man macht es gern.','spass.webp',{example:'Tanzen macht Spaß.'}),
 V('dabeihaben','dabeihaben','etwas bei sich haben.','dabeihaben.webp',{example:'Hast du den Würfel dabei?'}),
 V('nur','nur','nicht mehr als das.','nur.webp',{example:'Ich habe nur zehn Minuten.'}),
 V('genau','genau','richtig; ganz klar.','genau.webp',{example:'Genau, das stimmt.'}),
 V('schon','schon','etwas ist früher als erwartet fertig oder passiert.','schon.webp',{example:'Ich bin schon fertig.'}),
 V('gucken','gucken','ansehen.','gucken.webp',{example:'Wir gucken einen Film.'}),
 V('noch','noch','etwas dauert weiter oder kommt zusätzlich.','noch.webp',{example:'Ich lerne noch Deutsch.'}),
 V('toll','toll','sehr gut.','toll.webp',{example:'Der Film ist toll.'}),
 V('glauben','glauben','denken, dass etwas stimmt.','glauben.webp',{example:'Ich glaube, der Film ist gut.'}),
 V('ich-glaube','Ich glaube …','Ich denke …','ich_glaube.webp',{example:'Ich glaube, Anna kommt.'}),
 V('stimmt','Stimmt.','Das ist richtig.','stimmt.webp',{example:'Ja, das stimmt.'}),
 V('oh-wie-dumm','Oh, wie dumm!','Eine unangenehme Sache ist passiert.','oh_wie_dumm.webp',{example:'Der Bus ist weg. Oh, wie dumm!'}),
 V('na-klar','Na klar.','Ja, natürlich.','na_klar.webp',{example:'Kommst du mit? – Na klar!'}),
 V('ganz-sicher','ganz sicher','ohne Zweifel.','ganz_sicher.webp',{example:'Ich komme ganz sicher.'}),
 V('auf-jeden-fall','auf jeden Fall','ganz sicher.','auf_jeden_fall.webp',{example:'Ich komme auf jeden Fall.'}),
 V('naechste-woche','nächste Woche','die Woche nach dieser Woche.','naechste_woche.webp',{example:'Nächste Woche habe ich Urlaub.'}),
 V('naechstes-wochenende','nächstes Wochenende','Samstag und Sonntag nach diesem Wochenende.','naechstes_wochenende.webp',{example:'Nächstes Wochenende wandern wir.'}),
 V('naechsten-samstag','nächsten Samstag','der Samstag nach diesem Samstag.','naechsten_samstag.webp',{example:'Nächsten Samstag grillen wir.'}),
 V('wuerfel','der Würfel','kleiner Gegenstand mit Zahlen von eins bis sechs.','wuerfel.webp',{plural:'die Würfel',example:'Der Würfel liegt auf dem Tisch.'}),
 V('wuerfeln','würfeln','einen Würfel werfen.','wuerfeln.webp',{example:'Du würfelst zuerst.'}),
 V('oft','oft','viele Male.','oft.webp',{example:'Ich lese oft.'}),
 V('immer','immer','jedes Mal.','immer.webp',{example:'Ich frühstücke immer.'}),
 V('nie','nie','kein einziges Mal.','nie.webp',{example:'Ich spiele nie Tennis.'}),
 V('selten','selten','nicht oft.','selten.webp',{example:'Wir gehen selten ins Kino.'}),
 V('manchmal','manchmal','einige Male, aber nicht oft.','manchmal.webp',{example:'Manchmal grille ich.'}),
 V('leider','leider','etwas ist schade.','leider.webp',{example:'Leider habe ich keine Zeit.'}),
 V('es-gibt','es gibt','etwas ist da.','es_gibt.webp',{example:'Hier gibt es ein Schwimmbad.'}),
 V('vielleicht','vielleicht','es ist möglich, aber nicht sicher.','vielleicht.webp',{example:'Vielleicht komme ich mit.'}),
 V('gleich','gleich','sehr bald.','gleich.webp',{example:'Ich komme gleich.'}),
 V('moment-mal','Moment mal.','Bitte kurz warten.','moment_mal.webp',{example:'Moment mal, wo ist mein Buch?'}),
 V('guck-mal','Guck mal.','Sieh das an.','guck_mal.webp',{example:'Guck mal, der Film beginnt.'}),
 V('sag-mal','Sag mal.','Ich möchte etwas fragen.','sag_mal.webp',{example:'Sag mal, was ist dein Hobby?'}),
 V('kein-problem','Kein Problem.','Alles ist in Ordnung.','kein_problem.webp',{example:'Du kommst später? Kein Problem.'}),
 V('weiss-nicht','Ich weiß es nicht.','Ich kenne die Antwort nicht.','ich_weiss_es_nicht.webp',{example:'Wann kommt Tim? Ich weiß es nicht.'}),
 V('besonders','besonders','mehr als andere; speziell.','besonders.webp',{example:'Ich mag besonders Krimis.'})
];

const activityOptions=['tanzen','wandern','schwimmen','Gitarre spielen','Freunde treffen','Fahrrad fahren','stricken','grillen','im Internet surfen'];
const imageFile={
 'tanzen':'tanzen.webp','wandern':'wandern.webp','schwimmen':'schwimmen.webp',
 'Gitarre spielen':'gitarre_spielen.webp','Freunde treffen':'freunde_treffen.webp',
 'Fahrrad fahren':'fahrrad_fahren.webp','stricken':'stricken.webp','grillen':'grillen.webp',
 'im Internet surfen':'im_internet_surfen.webp'
};

const tasks=[
 {id:'cards',title:'Karteikarten',icon:'🗂️',description:'Wörter, Bedeutungen, Bilder und Beispielsätze lernen.',kind:'cards',items:vocabulary},
 {id:'image-word',title:'Bild → Wort',icon:'🖼️',description:'Sieh das Bild und wähle das passende Wort.',items:[
   C('Was macht die Person?','tanzen',activityOptions,'Die Person bewegt sich zur Musik.','tanzen.webp'),
   C('Was machen die Personen?','wandern',activityOptions,'Sie gehen lange in der Natur.','wandern.webp'),
   C('Was macht die Person?','schwimmen',activityOptions,'Die Person ist im Wasser.','schwimmen.webp'),
   C('Was macht die Person?','Gitarre spielen',activityOptions,'Sie macht Musik mit einer Gitarre.','gitarre_spielen.webp'),
   C('Was macht die Person?','Freunde treffen',activityOptions,'Mehrere Freunde sind zusammen.','freunde_treffen.webp'),
   C('Was macht die Person?','Fahrrad fahren',activityOptions,'Sie fährt auf zwei Rädern.','fahrrad_fahren.webp'),
   C('Was macht die Person?','stricken',activityOptions,'Sie arbeitet mit Wolle.','stricken.webp'),
   C('Was machen die Personen?','grillen',activityOptions,'Sie machen Essen draußen.','grillen.webp'),
   C('Was macht die Person?','im Internet surfen',activityOptions,'Sie sieht Internetseiten an.','im_internet_surfen.webp')
 ]},
 {id:'word-image',title:'Wort → Bild',icon:'🔎',description:'Lies das Wort und wähle das richtige Bild.',kind:'image-choice',items:activityOptions.map((word,i)=>({kind:'image-choice',prompt:word,answer:word,hint:`Suche das Bild zu „${word}“.`,options:[word,...activityOptions.filter(x=>x!==word).slice(i%5,i%5+3)].slice(0,4).map(x=>({label:x,image:imageFile[x]}))}))},
 {id:'listen-image',title:'Hören → Bild',icon:'🔊',description:'Höre eine Aktivität und wähle das Bild.',kind:'image-choice',items:activityOptions.map((word,i)=>({kind:'image-choice',prompt:'Höre und wähle das Bild.',answer:word,audio:word,hint:`Das Wort beginnt mit „${word[0]}“.`,options:[word,...activityOptions.filter(x=>x!==word).slice((i+2)%5,(i+2)%5+3)].slice(0,4).map(x=>({label:x,image:imageFile[x]}))}))},
 {id:'article',title:'Artikel wiederholen',icon:'der',description:'Wähle der, die oder das.',items:[
   C('___ Hunger','der',['der','die','das'],'Hunger ist maskulin.'),C('___ Durst','der',['der','die','das'],'Durst ist maskulin.'),C('___ Hobby','das',['der','die','das'],'Hobby ist neutral.'),C('___ Beruf','der',['der','die','das'],'Beruf ist maskulin.'),C('___ Alter','das',['der','die','das'],'Alter ist neutral.'),C('___ Freizeit','die',['der','die','das'],'Freizeit ist feminin.'),C('___ Würfel','der',['der','die','das'],'Würfel ist maskulin.'),C('___ Gitarre','die',['der','die','das'],'Gitarre ist feminin.'),C('___ Fahrrad','das',['der','die','das'],'Fahrrad ist neutral.'),C('___ Lieblingsbuch','das',['der','die','das'],'Buch ist neutral.'),C('___ Lieblingsfilm','der',['der','die','das'],'Film ist maskulin.'),C('___ Lieblingsfarbe','die',['der','die','das'],'Farbe ist feminin.')
 ]},
 {id:'plural',title:'Plural sprechen',icon:'🎤',description:'Singular hören und den Plural mit Artikel sprechen oder schreiben.',external:'plural-sprechen.html'},
 {id:'sound-activity',title:'Geräusch → Aktivität',icon:'🎧',description:'Höre eine Aktivität und finde das passende Verb.',items:[
   C('Welche Aktivität hörst du?','Gitarre spielen',activityOptions,'Du hörst Musik mit einer Gitarre.','', 'Gitarre spielen'),C('Welche Aktivität hörst du?','grillen',activityOptions,'Es geht um Essen draußen.','', 'grillen'),C('Welche Aktivität hörst du?','Fahrrad fahren',activityOptions,'Es geht um ein Fahrrad.','', 'Fahrrad fahren'),C('Welche Aktivität hörst du?','Freunde treffen',activityOptions,'Mehrere Freunde sind zusammen.','', 'Freunde treffen'),C('Welche Aktivität hörst du?','wandern',activityOptions,'Personen gehen in der Natur.','', 'wandern'),C('Welche Aktivität hörst du?','schwimmen',activityOptions,'Die Person ist im Wasser.','', 'schwimmen')
 ]},
 {id:'noun-verb',title:'Nomen und Verb verbinden',icon:'↔️',description:'Was passt zusammen?',items:[
   C('die Gitarre','Gitarre spielen',['Gitarre spielen','Fahrrad fahren','grillen','stricken'],'Mit diesem Instrument macht man Musik.'),C('das Fahrrad','Fahrrad fahren',['Fahrrad fahren','schwimmen','tanzen','wandern'],'Man fährt damit.'),C('der Würfel','würfeln',['würfeln','gucken','glauben','stricken'],'Man wirft ihn im Spiel.'),C('die Freunde','Freunde treffen',['Freunde treffen','im Internet surfen','Fahrrad fahren','grillen'],'Man ist mit Freunden zusammen.'),C('das Internet','im Internet surfen',['im Internet surfen','Gitarre spielen','wandern','schwimmen'],'Man sieht Webseiten an.'),C('der Grill','grillen',['grillen','stricken','tanzen','gucken'],'Man macht damit Essen draußen.'),C('die Wolle','stricken',['stricken','würfeln','schwimmen','tanzen'],'Damit macht man Kleidung.'),C('das Schwimmbad','schwimmen',['schwimmen','wandern','grillen','gucken'],'Dort ist viel Wasser.')
 ]},
 {id:'phrases',title:'Redemittel und Bedeutung',icon:'💬',description:'Ordne Gesprächsbausteine einer Situation zu.',items:[
   C('Du möchtest kurz warten.','Moment mal.',['Moment mal.','Na klar.','Kein Problem.','Stimmt.'],'Du bittest um kurze Zeit.'),C('Du möchtest etwas zeigen.','Guck mal.',['Guck mal.','Sag mal.','Leider.','Vielleicht.'],'Du sagst: Sieh das an.'),C('Du möchtest eine Frage beginnen.','Sag mal.',['Sag mal.','Guck mal.','Oh, wie dumm!','Stimmt.'],'Danach kommt eine Frage.'),C('Du bist sicher einverstanden.','Na klar.',['Na klar.','Vielleicht.','Leider.','Ich weiß es nicht.'],'Das bedeutet: Ja, natürlich.'),C('Eine Person macht einen kleinen Fehler. Du bist nicht böse.','Kein Problem.',['Kein Problem.','Oh, wie dumm!','Stimmt.','Guck mal.'],'Alles ist in Ordnung.'),C('Du kennst die Antwort nicht.','Ich weiß es nicht.',['Ich weiß es nicht.','Stimmt.','Na klar.','Ganz sicher.'],'Du hast keine Antwort.'),C('Die Aussage ist richtig.','Stimmt.',['Stimmt.','Vielleicht.','Leider.','Moment mal.'],'Das bedeutet: Das ist richtig.'),C('Der Bus ist schon weg.','Oh, wie dumm!',['Oh, wie dumm!','Na klar.','Kein Problem.','Stimmt.'],'Etwas Unangenehmes ist passiert.')
 ]},
 {id:'nehmen',title:'nehmen in Dialogen',icon:'☕',description:'Wähle die richtige Form von nehmen.',items:[
   C('Ich ___ einen Tee.','nehme',['nehme','nimmst','nimmt','nehmen'],'Bei ich heißt es „nehme“.'),C('Was ___ du?','nimmst',['nehme','nimmst','nimmt','nehmt'],'Bei du heißt es „nimmst“.'),C('Mara ___ nur Wasser.','nimmt',['nehme','nimmst','nimmt','nehmen'],'Mara = sie.'),C('Wir ___ zwei Portionen.','nehmen',['nehme','nimmt','nehmen','nehmt'],'Bei wir heißt es „nehmen“.'),C('Was ___ ihr?','nehmt',['nehme','nimmst','nimmt','nehmt'],'Bei ihr heißt es „nehmt“.'),C('Die Gäste ___ Kaffee.','nehmen',['nimmt','nehmt','nehmen','nimmst'],'Die Gäste = sie (Plural).'),C('A: Möchtest du Kuchen? B: Nein, ich ___ nur einen Kaffee.','nehme',['nehme','nimmst','nimmt','nehmt'],'Die Antwort beginnt mit „ich“.'),C('A: Was nimmt Tim? B: Er ___ eine Cola.','nimmt',['nehme','nimmst','nimmt','nehmen'],'Tim = er.')
 ]},
 {id:'yes-no-doch',title:'ja, nein oder doch?',icon:'↩️',description:'Wähle die passende kurze Antwort.',items:[
   C('Spielst du gern Tennis? – ___, sehr gern.','Ja',['Ja','Nein','Doch'],'Die Frage ist positiv. Die Antwort stimmt zu.'),C('Spielst du nicht gern Tennis? – ___, ich spiele sehr gern.','Doch',['Ja','Nein','Doch'],'Eine negative Frage wird positiv beantwortet.'),C('Gehst du heute nicht schwimmen? – ___, ich gehe schwimmen.','Doch',['Ja','Nein','Doch'],'Die Person korrigiert die negative Frage.'),C('Hast du Hunger? – ___, ich habe keinen Hunger.','Nein',['Ja','Nein','Doch'],'Die Frage ist positiv. Die Antwort verneint.'),C('Hast du keinen Durst? – ___, ich möchte Wasser.','Doch',['Ja','Nein','Doch'],'Die Person hat Durst.'),C('Trefft ihr heute Freunde? – ___, wir bleiben zu Hause.','Nein',['Ja','Nein','Doch'],'Die Antwort ist negativ.'),C('Surfst du oft im Internet? – ___, jeden Abend.','Ja',['Ja','Nein','Doch'],'Die Antwort bestätigt die Frage.'),C('Grillt ihr am Samstag nicht? – ___, auf jeden Fall.','Doch',['Ja','Nein','Doch'],'Die negative Frage wird positiv beantwortet.')
 ]},
 {id:'doch-answer',title:'Mit doch antworten',icon:'DOCH',description:'Negative Aussagen mit doch korrigieren.',items:[
   I('Du spielst nicht gern Tennis. – ___','Doch, ich spiele gern Tennis.','Beginne mit „Doch“ und korrigiere die Aussage.', '', ['Doch, ich spiele gerne Tennis.']),I('Du kannst nicht schwimmen. – ___','Doch, ich kann schwimmen.','Beginne mit „Doch“.'),I('Du hast keinen Hunger. – ___','Doch, ich habe Hunger.','Die Antwort sagt das Gegenteil.'),I('Ihr trefft heute keine Freunde. – ___','Doch, wir treffen heute Freunde.','Beginne mit „Doch, wir …“.'),I('Mara fährt nicht gern Fahrrad. – ___','Doch, Mara fährt gern Fahrrad.','Korrigiere die negative Aussage.'),I('Du grillst am Samstag nicht. – ___','Doch, ich grille am Samstag.','Beginne mit „Doch, ich …“.')
 ]},
 {id:'dialog-rf',title:'Dialoge: richtig oder falsch',icon:'✓✗',description:'Lies kurze Dialoge und prüfe die Aussage.',items:[
   C('A: Was ist dein Hobby? B: Ich schwimme gern. Aussage: Schwimmen ist das Hobby.','Richtig',['Richtig','Falsch'],'B sagt: Ich schwimme gern.'),C('A: Grillst du oft? B: Nein, nur selten. Aussage: B grillt immer.','Falsch',['Richtig','Falsch'],'„selten“ ist nicht „immer“.'),C('A: Hast du den Würfel dabei? B: Na klar. Aussage: B hat den Würfel dabei.','Richtig',['Richtig','Falsch'],'„Na klar“ bedeutet ja.'),C('A: Kommst du nächsten Samstag? B: Vielleicht. Aussage: B kommt ganz sicher.','Falsch',['Richtig','Falsch'],'„Vielleicht“ ist nicht sicher.'),C('A: Spielst du nicht gern Gitarre? B: Doch, sehr gern. Aussage: B spielt gern Gitarre.','Richtig',['Richtig','Falsch'],'„Doch“ korrigiert die negative Frage.'),C('A: Was ist dein Lieblingsfilm? B: Ein Krimi. Aussage: B mag besonders Krimis.','Richtig',['Richtig','Falsch'],'Der Lieblingsfilm ist ein Krimi.'),C('A: Wann kommst du? B: Gleich. Aussage: B kommt nächste Woche.','Falsch',['Richtig','Falsch'],'„gleich“ bedeutet sehr bald.'),C('A: Hast du Hunger? B: Nein. Aussage: B möchte etwas essen.','Falsch',['Richtig','Falsch'],'B hat keinen Hunger.')
 ]},
 {id:'dialog-abc',title:'Dialoge: A, B oder C',icon:'ABC',description:'Wähle die passende Antwort.',items:[
   C('A: Was machst du in deiner Freizeit? B: ___','Ich treffe oft Freunde.',['Ich treffe oft Freunde.','Ich bin 32 Jahre alt.','Mein Beruf ist Koch.'],'Gefragt wird nach Freizeit.'),C('A: Was ist dein Hobby? B: ___','Mein Hobby ist Schwimmen.',['Mein Hobby ist Schwimmen.','Ich habe Durst.','Nächste Woche.'],'Gefragt wird nach dem Hobby.'),C('A: Spielst du nicht gern Tennis? B: ___','Doch, sehr gern.',['Doch, sehr gern.','Nein, ich bin Koch.','Vielleicht 30 Jahre.'],'Negative Frage, positive Antwort.'),C('A: Wann grillt ihr? B: ___','Nächsten Samstag.',['Nächsten Samstag.','Im Garten toll.','Mit einem Würfel.'],'Gefragt wird nach einem Zeitpunkt.'),C('A: Hast du den Würfel dabei? B: ___','Na klar.',['Na klar.','Ich glaube Sport.','Das Alter.'],'Gefragt wird, ob etwas dabei ist.'),C('A: Welchen Film findest du toll? B: ___','Ich finde den neuen Krimi toll.',['Ich finde den neuen Krimi toll.','Ich finde meine Schlüssel.','Ich bin im Internet.'],'„toll finden“ bedeutet beurteilen.'),C('A: Was ist dein Beruf? B: ___','Ich bin Verkäufer.',['Ich bin Verkäufer.','Ich bin 35 Jahre alt.','Ich wandere gern.'],'Gefragt wird nach dem Beruf.'),C('A: Wie alt bist du? B: ___','Ich bin 35 Jahre alt.',['Ich bin 35 Jahre alt.','Mein Hobby ist Grillen.','Ich komme gleich.'],'Gefragt wird nach dem Alter.')
 ]},
 {id:'gaps',title:'Dialoglücken',icon:'▤',description:'Setze den passenden Gesprächsbaustein ein.',items:[
   C('A: ___, was ist dein Hobby? B: Schwimmen.','Sag mal',['Sag mal','Guck mal','Stimmt','Leider'],'Danach kommt eine Frage.'),C('A: Ich spiele gern Tennis. B: ___, ich auch.','Stimmt',['Stimmt','Moment mal','Leider','Ich weiß es nicht'],'B stimmt zu.'),C('A: Kommst du nächsten Samstag? B: ___, ich habe noch keinen Plan.','Vielleicht',['Vielleicht','Ganz sicher','Immer','Stimmt'],'B ist nicht sicher.'),C('A: Ich habe den Würfel vergessen. B: ___, wir haben noch einen.','Kein Problem',['Kein Problem','Oh, wie dumm!','Leider','Nie'],'Es gibt eine einfache Lösung.'),C('A: ___, da ist dein Buch. B: Danke!','Guck mal',['Guck mal','Sag mal','Moment mal','Vielleicht'],'A zeigt etwas.'),C('A: Wann beginnt der Film? B: ___.','Ich weiß es nicht.',['Ich weiß es nicht.','Na klar.','Stimmt.','Auf jeden Fall.'],'B kennt die Antwort nicht.'),C('A: Der Bus ist weg. B: ___','Oh, wie dumm!',['Oh, wie dumm!','Na klar.','Kein Problem.','Guck mal.'],'Etwas Unangenehmes ist passiert.'),C('A: Kommst du mit? B: ___!','Na klar',['Na klar','Leider','Vielleicht','Moment mal'],'B sagt deutlich ja.')
 ]},
 {id:'complete-dialog',title:'Dialoge selbst ergänzen',icon:'✍️',description:'Schreibe eine passende vollständige Antwort.',items:[F('A: Was ist dein Hobby? B: …',4,'Mein Hobby ist Schwimmen.'),F('A: Was machst du in deiner Freizeit? B: …',5,'In meiner Freizeit treffe ich Freunde.'),F('A: Spielst du nicht gern Tennis? B: …',4,'Doch, ich spiele gern Tennis.'),F('A: Wann grillt ihr? B: …',3,'Wir grillen nächsten Samstag.'),F('A: Was ist dein Lieblingsfilm? B: …',4,'Mein Lieblingsfilm ist ein Krimi.'),F('A: Hast du den Würfel dabei? B: …',3,'Ja, ich habe ihn dabei.')]},
 {id:'speak-dialog',title:'Dialog sprechen oder schreiben',icon:'🎙️',description:'Antworte in einem kurzen Dialog.',kind:'speak',items:[
   {kind:'speak',prompt:'Frage: Was machst du gern in deiner Freizeit?',answer:'Ich treffe gern Freunde.',answers:['Ich treffe gern Freunde.','In meiner Freizeit treffe ich gern Freunde.'],hint:'Beginne mit „Ich …“ oder „In meiner Freizeit …“.'},
   {kind:'speak',prompt:'Frage: Spielst du nicht gern Tennis?',answer:'Doch, ich spiele gern Tennis.',hint:'Beginne mit „Doch“.'},
   {kind:'speak',prompt:'Frage: Wann grillst du?',answer:'Ich grille nächsten Samstag.',answers:['Ich grille nächsten Samstag.','Nächsten Samstag grille ich.'],hint:'Nenne „nächsten Samstag“.'},
   {kind:'speak',prompt:'Frage: Was ist dein Lieblingshobby?',answer:'Mein Lieblingshobby ist Schwimmen.',hint:'Beginne mit „Mein Lieblingshobby …“.'},
   {kind:'speak',prompt:'Frage: Hast du den Würfel dabei?',answer:'Ja, ich habe den Würfel dabei.',answers:['Ja, ich habe den Würfel dabei.','Ja, ich habe ihn dabei.'],hint:'Antworte mit ja und „dabeihaben“.'},
   {kind:'speak',prompt:'Frage: Wie oft surfst du im Internet?',answer:'Ich surfe oft im Internet.',answers:['Ich surfe oft im Internet.','Ich surfe manchmal im Internet.','Ich surfe selten im Internet.','Ich surfe nie im Internet.'],hint:'Verwende oft, manchmal, selten oder nie.'}
 ]},
 {id:'listen-abc',title:'Hören: A, B oder C',icon:'🎧',description:'Höre kurze Aussagen und wähle die richtige Information.',items:[
   C('Was macht Nina oft?','Sie trifft Freunde.',['Sie trifft Freunde.','Sie strickt.','Sie spielt Tennis.'],'Im Hörtext steht „oft“.','', 'Nina hat wenig Freizeit. Aber am Freitag trifft sie oft ihre Freunde.'),C('Was macht Tim nie?','Er fährt nie Fahrrad.',['Er fährt nie Fahrrad.','Er wandert nie.','Er grillt nie.'],'Achte auf „nie“.','', 'Tim schwimmt gern und wandert manchmal. Fahrrad fährt er nie.'),C('Was ist Marias Lieblingshobby?','Gitarre spielen.',['Gitarre spielen.','Schwimmen.','Grillen.'],'Sie spricht über Musik.','', 'Maria hört besonders gern Musik. Ihr Lieblingshobby ist Gitarre spielen.'),C('Wann grillt Familie Ali?','Nächsten Samstag.',['Nächsten Samstag.','Nächste Woche am Montag.','Heute.'],'Achte auf den Tag.','', 'Familie Ali möchte grillen. Sie grillt nicht heute, sondern nächsten Samstag.'),C('Hat Omar den Würfel dabei?','Ja.',['Ja.','Nein.','Das weiß man nicht.'],'Er sagt „Na klar“.','', 'Lea fragt: Omar, hast du den Würfel dabei? Omar sagt: Na klar, er ist in meiner Tasche.'),C('Wie findet Lea den Film?','Toll.',['Toll.','Langweilig.','Schlecht.'],'Achte auf ihre Meinung.','', 'Lea hat den neuen Film gesehen. Sie findet ihn toll, besonders die Musik.')
 ]},
 {id:'finden',title:'finden: zwei Bedeutungen',icon:'🔍',description:'Erkennen: suchen/entdecken oder Meinung sagen.',items:[
   C('Ich finde meinen Schlüssel nicht.','suchen oder entdecken',['suchen oder entdecken','eine Meinung sagen'],'Es geht um einen Schlüssel.'),C('Ich finde den Film toll.','eine Meinung sagen',['suchen oder entdecken','eine Meinung sagen'],'„toll“ ist eine Bewertung.'),C('Mara findet ihr Buch unter dem Tisch.','suchen oder entdecken',['suchen oder entdecken','eine Meinung sagen'],'Das Buch war vorher nicht da.'),C('Wie findest du das Lied?','eine Meinung sagen',['suchen oder entdecken','eine Meinung sagen'],'Gefragt wird nach einer Bewertung.'),C('Tim findet sein Fahrrad vor der Schule.','suchen oder entdecken',['suchen oder entdecken','eine Meinung sagen'],'Er entdeckt das Fahrrad.'),C('Wir finden Grillen toll.','eine Meinung sagen',['suchen oder entdecken','eine Meinung sagen'],'„toll“ zeigt eine Meinung.'),C('Wo finde ich die Informationen?','suchen oder entdecken',['suchen oder entdecken','eine Meinung sagen'],'Gefragt wird nach einem Ort.'),C('Ich finde den Beruf interessant.','eine Meinung sagen',['suchen oder entdecken','eine Meinung sagen'],'„interessant“ ist eine Bewertung.')
 ]},
 {id:'questions',title:'Hobbys und Lieblingssachen',icon:'❓',description:'Ordne Fragen und passende Antworten.',items:[
   C('Was ist dein Hobby?','Mein Hobby ist Schwimmen.',['Mein Hobby ist Schwimmen.','Ich bin 28 Jahre alt.','Ich bin Koch.'],'Gefragt wird nach einem Hobby.'),C('Was sind deine Hobbys?','Meine Hobbys sind Wandern und Lesen.',['Meine Hobbys sind Wandern und Lesen.','Mein Hobby ist Wandern.','Ich habe Hunger.'],'Die Frage steht im Plural.'),C('Was machst du in deiner Freizeit?','Ich treffe Freunde und lese.',['Ich treffe Freunde und lese.','Ich bin Verkäufer.','Nächsten Samstag.'],'Gefragt wird nach Freizeitaktivitäten.'),C('Was ist dein Lieblingsbuch?','Mein Lieblingsbuch ist „Momo“.',['Mein Lieblingsbuch ist „Momo“.','Meine Lieblingsfarbe ist Blau.','Ich lese manchmal.'],'Gefragt wird nach einem Buch.'),C('Was ist dein Lieblingsfilm?','Mein Lieblingsfilm ist ein Krimi.',['Mein Lieblingsfilm ist ein Krimi.','Ich gucke oft Filme.','Mein Hobby ist Tennis.'],'Gefragt wird nach einem Film.'),C('Was ist deine Lieblingsfarbe?','Meine Lieblingsfarbe ist Blau.',['Meine Lieblingsfarbe ist Blau.','Mein Lieblingsfilm ist neu.','Ich male selten.'],'Gefragt wird nach einer Farbe.'),C('Welche Musik hörst du gern?','Ich höre gern Popmusik.',['Ich höre gern Popmusik.','Ich spiele Gitarre.','Mein Beruf ist Musiker.'],'Gefragt wird nach Musik.'),C('Was ist dein Beruf?','Ich bin Verkäuferin.',['Ich bin Verkäuferin.','Ich bin 30 Jahre alt.','Ich wandere gern.'],'Gefragt wird nach Arbeit.')
 ]},
 {id:'singular-plural',title:'Hobby: Singular und Plural',icon:'1↔2',description:'Wähle die passende Frage oder Antwort.',items:[
   C('Eine Aktivität: Schwimmen.','Mein Hobby ist Schwimmen.',['Mein Hobby ist Schwimmen.','Meine Hobbys sind Schwimmen.'],'Eine Aktivität steht im Singular.'),C('Zwei Aktivitäten: Schwimmen und Lesen.','Meine Hobbys sind Schwimmen und Lesen.',['Mein Hobby ist Schwimmen und Lesen.','Meine Hobbys sind Schwimmen und Lesen.'],'Mehrere Hobbys brauchen Plural.'),C('Frage nach einer Lieblingssache: Buch.','Was ist dein Lieblingsbuch?',['Was ist dein Lieblingsbuch?','Was sind deine Lieblingsbuch?'],'Lieblingsbuch steht im Singular.'),C('Frage nach mehreren Hobbys.','Was sind deine Hobbys?',['Was ist dein Hobby?','Was sind deine Hobbys?'],'Mehrere Hobbys: sind/deine.'),C('Antwort zu „Was ist deine Lieblingsfarbe?“','Meine Lieblingsfarbe ist Blau.',['Meine Lieblingsfarbe ist Blau.','Meine Lieblingsfarben sind Blau.'],'Eine Lieblingsfarbe im Singular.'),C('Antwort zu „Was sind deine Hobbys?“','Meine Hobbys sind Tanzen und Wandern.',['Mein Hobby ist Tanzen und Wandern.','Meine Hobbys sind Tanzen und Wandern.'],'Frage und Antwort stehen im Plural.'),C('Frage nach einem Hobby.','Was ist dein Hobby?',['Was ist dein Hobby?','Was sind dein Hobby?'],'Singular: ist/dein.'),C('Antwort zu „Was ist dein Lieblingsfilm?“','Mein Lieblingsfilm ist ein Krimi.',['Mein Lieblingsfilm ist ein Krimi.','Meine Lieblingsfilme sind ein Krimi.'],'Ein Film steht im Singular.')
 ]},
 {id:'profile',title:'Mein Freizeitprofil',icon:'👤',description:'Schreibe über deine Freizeit, Hobbys und Lieblingssachen.',kind:'free',items:[F('Schreibe deinen Beruf und dein Alter.',6,'Ich bin Lehrerin und 32 Jahre alt.'),F('Schreibe zwei Hobbys.',6,'Meine Hobbys sind Lesen und Wandern.'),F('Schreibe, was du oft und was du selten machst.',9,'Ich treffe oft Freunde. Ich spiele selten Tennis.'),F('Schreibe dein Lieblingsbuch oder deinen Lieblingsfilm.',6,'Mein Lieblingsfilm ist ein Krimi.'),F('Schreibe deine Lieblingsfarbe und welche Musik du gern hörst.',9,'Meine Lieblingsfarbe ist Blau. Ich höre gern Popmusik.'),F('Schreibe einen Plan für nächstes Wochenende.',7,'Nächstes Wochenende will ich wandern und Freunde treffen.')]},
 {id:'exam',title:'Themenprüfung',icon:'★',description:'Wortschatz, Hören, Dialoge, nehmen, doch und Hobbys.',exam:true,items:[
   C('Bild: Person bewegt sich zur Musik.','tanzen',['tanzen','wandern','stricken','schwimmen'],'Die Person hört Musik.','tanzen.webp'),C('___ Hobby','das',['der','die','das'],'Hobby ist neutral.'),C('Plural: das Fahrrad','die Fahrräder',['die Fahrräder','die Fahrrade','der Fahrräder'],'Achte auf Artikel und Umlaut.'),C('Ich ___ einen Tee.','nehme',['nehme','nimmst','nimmt','nehmt'],'Bei ich heißt es „nehme“.'),C('Spielst du nicht gern Tennis? – ___, sehr gern.','Doch',['Ja','Nein','Doch'],'Negative Frage, positive Antwort.'),C('Du möchtest etwas zeigen.','Guck mal.',['Guck mal.','Sag mal.','Moment mal.','Leider.'],'Du sagst: Sieh das an.'),C('A: Was machst du in deiner Freizeit? B: ___','Ich treffe oft Freunde.',['Ich treffe oft Freunde.','Ich bin 30 Jahre alt.','Mein Beruf ist Koch.'],'Gefragt wird nach Freizeit.'),C('Ich finde den Film toll. „finden“ bedeutet hier …','eine Meinung sagen',['suchen oder entdecken','eine Meinung sagen'],'„toll“ ist eine Bewertung.'),C('Höre: Was macht Nina oft?','Sie trifft Freunde.',['Sie trifft Freunde.','Sie grillt.','Sie strickt.'],'Achte auf „oft“.','', 'Nina liest manchmal. Aber besonders oft trifft sie ihre Freunde.'),O('Ordne die Antwort.','Meine Hobbys sind Wandern und Lesen.',['Wandern','Meine','und','Hobbys','Lesen.','sind'],'Mehrere Hobbys: Meine Hobbys sind …'),I('Du hast keinen Hunger. – ___','Doch, ich habe Hunger.','Beginne mit „Doch“.'),F('Schreibe drei Sätze über deine Freizeit. Verwende oft, selten oder nie.',12,'Ich lese oft. Ich grille selten. Ich spiele nie Tennis.')
 ]}
];

window.L6T4_DATA={vocabulary,tasks,activityOptions,imageFile};
})();