(function(){
'use strict';
const params=new URLSearchParams(location.search);
const taskId=params.get('task')||'cards';
const task=window.L6T4_DATA?.tasks?.find(item=>item.id===taskId);
const meta=L6T4_TASKS.find(item=>item.id===taskId);
const area=document.getElementById('area');
const FILE=`task-${taskId}`;
const CDN='https://sprachpilot.b-cdn.net/';
let currentIndex=null,orderSelection=[],recognition=null;

function esc(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function imageUrl(file){return CDN+encodeURIComponent(file||'')}
function imageBlock(file,alt='',small=false,pure=false){
 if(!file)return'';
 const fallback=pure?'<div class="image-fallback pure" hidden><span aria-hidden="true">🖼️</span></div>':`<div class="image-fallback" hidden><strong>${esc(alt||'Bild')}</strong><span>Bild konnte nicht geladen werden.</span></div>`;
 return`<div class="visual ${small?'small-visual':''} ${pure?'pure-visual':''}"><img src="${imageUrl(file)}" alt="${esc(alt)}" onerror="this.hidden=true;this.nextElementSibling.hidden=false">${fallback}</div>`
}
function accepted(item){const list=[item.answer,...(item.answers||[])];if(taskId==='cards'){const withoutArticle=String(item.word||'').replace(/^(der|die|das)\s+/i,'');list.push(item.word,withoutArticle)}return list.filter(Boolean)}
function current(){const state=l6t4Load(FILE,task.items.length);currentIndex=state.current===null||state.current===undefined?l6t4NextIndex(FILE,task.items.length):state.current;return task.items[currentIndex]}
function genericHint(item){const solution=String(item.answer||item.word||'');if(item.kind==='order')return'Das Subjekt steht zuerst. Das Verb steht im Aussagesatz auf Position 2.';if(item.kind==='image-choice'||item.pureImage)return'Achte genau auf das Bild und höre noch einmal.';if(solution)return`Die Lösung beginnt mit „${solution.charAt(0)}“.`;return'Lies die Aufgabe noch einmal.'}
function hint(item){const tries=l6t4Load(FILE,task.items.length).tries||0;if(tries===1)return'<div class="no">Noch nicht richtig. Versuche es noch einmal.</div>';if(tries===2)return`<div class="hint"><strong>Hinweis:</strong> ${esc(item.hint||genericHint(item))}</div>`;if(tries>=3)return`<div class="no"><strong>Lösung:</strong> ${esc(item.answer||item.word)}<br>Gib die richtige Antwort jetzt selbst ein. Die Aufgabe kommt später noch einmal.</div>`;return''}
function technical(message){const box=document.getElementById('tech');if(box)box.innerHTML=`<div class="hint">${esc(message)}</div>`}
function feedbackHtml(item){return`<div id="feedback" class="feedback">${hint(item)}</div><div id="tech"></div>`}
function top(){return`${l6t4Progress(FILE,task.items.length)}<div class="task-instruction">${esc(task.description||'Bearbeite die Aufgabe.')}</div>`}
function showAudio(text){return`<button class="btn secondary" type="button" data-action="audio" data-audio="${esc(text)}">🔊 Anhören</button>`}
function dialogHtml(lines){if(!Array.isArray(lines)||!lines.length)return'';return`<div class="chat-window">${lines.map((line,index)=>`<div class="chat-row ${line.side==='right'?'right':'left'} speaker-${index%2}"><div class="chat-name">${esc(line.speaker)}</div><div class="chat-bubble">${esc(line.text)}</div></div>`).join('')}</div>`}
function requirementsHtml(item){const requirements=(item.requirements||[]).map(text=>`<li>${esc(text)}</li>`).join('');const starters=(item.sentenceStarters||[]).map(text=>`<span>${esc(text)}</span>`).join('');return`${requirements?`<div class="writing-requirements"><strong>Dein Text enthält:</strong><ul>${requirements}</ul></div>`:''}${starters?`<div class="sentence-starters"><strong>Satzanfänge und Hilfswörter:</strong><div>${starters}</div></div>`:''}${item.example?`<details class="example-details"><summary>Kurzes Beispiel ansehen</summary><pre>${esc(item.example)}</pre></details>`:''}`}
function render(){
 if(!task||!meta){area.innerHTML='<div class="finish-box"><h2>Aufgabe nicht gefunden</h2><a class="btn" href="index.html">Zur Übersicht</a></div>';return}
 if(task.exam&&!l6t4ExamUnlocked()){area.innerHTML='<div class="finish-box"><div class="finish-icon">🔒</div><h2>Prüfung noch gesperrt</h2><p>Schließe zuerst alle anderen Aufgaben zu 100% ab.</p><a class="btn" href="index.html">Zur Übersicht</a></div>';return}
 const state=l6t4Load(FILE,task.items.length);if(state.done.length>=task.items.length){finish();return}
 const item=current();if(!item){l6t4Storage().removeItem(l6t4TaskKey(FILE));currentIndex=l6t4NextIndex(FILE,task.items.length);return render()}
 orderSelection=[];l6t4Header(meta.title);document.title=`${meta.title} · L6T4`;
 if(task.kind==='cards')renderCard(item);else renderQuestion(item)
}
function renderCard(item){
 const plural=item.plural?`<div><span>Plural</span><strong>${esc(item.plural)}</strong></div>`:'';
 area.innerHTML=`${top()}<div class="flip-wrap"><div id="verbFlipCard" class="flip-card" role="button" tabindex="0" aria-label="Karte umdrehen"><div class="flip-face flip-front">${imageBlock(item.image,item.word)}</div><div class="flip-face flip-back"><div class="flip-word">${esc(item.word)}</div><div class="flip-note">Lösung</div><div class="card-details">${plural}<div><span>Beispiel</span><strong>${esc(item.example||'')}</strong></div></div><button type="button" class="btn secondary card-listen-btn" id="cardListenBtn">🔊 Anhören</button></div></div></div><div class="hint card-translation">Bedeutung: <b>${esc(item.meaning)}</b></div><div class="actions card-actions"><button id="cardMicBtn" type="button" class="btn">Sprechen</button><button id="cardWriteBtn" type="button" class="btn secondary">Schreiben</button></div><div id="cardMicStatus" class="small card-mic-status"></div><div id="cardAnswerBox" class="card-answer-box" hidden><div class="answer-row"><input id="cardAnswerInput" autocomplete="off" placeholder="Wort schreiben"><button id="cardCheckBtn" type="button" class="btn">Kontrollieren</button></div></div><div id="feedback" class="feedback">${hint(item)}</div><div id="tech"></div><div id="cardAfter" class="actions card-actions"></div>`;
 const card=document.querySelector('#verbFlipCard');card.addEventListener('click',reveal);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();reveal()}});document.querySelector('#cardListenBtn').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();l6t4Say(item.word)});document.querySelector('#cardMicBtn').addEventListener('click',startMic);document.querySelector('#cardWriteBtn').addEventListener('click',openCardWrite);document.querySelector('#cardCheckBtn').addEventListener('click',()=>check(document.querySelector('#cardAnswerInput').value));document.querySelector('#cardAnswerInput').addEventListener('keydown',e=>{if(e.key==='Enter')check(e.target.value)})
}
function renderQuestion(item){
 let body='';const audio=item.audio?`<div class="audio-panel">${showAudio(item.audio)}${item.audioName?`<span class="audio-name">${esc(item.audioName)}</span>`:'<span>Du kannst den Hörtext mehrmals hören.</span>'}</div>`:'';const visual=item.image?imageBlock(item.image,item.prompt,false,!!item.pureImage):'';const dialogue=dialogHtml(item.dialog);
 if(item.kind==='choice'||!item.kind){const options=l6t4Shuffle(item.options||[]);body=`<div class="option-grid">${options.map(option=>`<button class="option" type="button" data-answer="${esc(option)}">${esc(option)}</button>`).join('')}</div>`}
 else if(item.kind==='image-choice'){const options=l6t4Shuffle(item.options||[]);body=`<div class="image-choice-grid">${options.map(option=>`<button class="image-option" type="button" data-answer="${esc(option.label)}">${imageBlock(option.image,option.label,true,true)}<span class="sr-only">${esc(option.label)}</span></button>`).join('')}</div>`}
 else if(item.kind==='input')body=inputBox('Schreibe die vollständige Antwort.');
 else if(item.kind==='order'){const tokens=l6t4Shuffle(item.tokens||[]);body=`<div class="order-answer" id="orderAnswer"><span>Klicke die Wörter in der richtigen Reihenfolge an.</span></div><div class="token-grid">${tokens.map((token,index)=>`<button class="token" type="button" data-token="${esc(token)}" data-token-index="${index}">${esc(token)}</button>`).join('')}</div><div class="actions centered"><button class="btn" type="button" data-action="check-order">Prüfen</button><button class="btn secondary" type="button" data-action="undo-order">Zurück</button><button class="btn ghost" type="button" data-action="reset-order">Neu</button></div>`}
 else if(item.kind==='free')body=`<div class="free-box">${requirementsHtml(item)}<label for="freeAnswer">Deine Antwort</label><textarea id="freeAnswer" rows="9" placeholder="Schreibe vollständige Sätze."></textarea><p class="small">Erwartete Länge: ${item.minWords||4}${item.maxWords?` bis ${item.maxWords}`:''} Wörter.</p><button class="btn" type="button" data-action="save-free">Speichern und weiter</button></div>`;
 else if(item.kind==='speak')body=`<div class="speech-box"><p>Sprich eine vollständige Antwort oder schreibe sie.</p><div class="actions centered"><button class="btn" type="button" data-action="mic">🎤 Antwort sprechen</button><button class="btn secondary" type="button" data-action="write">✍️ Stattdessen schreiben</button></div>${inputBox('Schreibe deine vollständige Antwort.')}</div>`;
 else if(item.kind==='catalog')body=`<div class="sound-catalog"><p>Diese Liste ist für die späteren echten Geräuschdateien vorbereitet.</p><div class="sound-list">${(item.entries||[]).map(entry=>`<div class="sound-row"><span class="sound-number">${entry.index}</span><strong>${esc(entry.activity)}</strong><code>${esc(entry.file)}</code></div>`).join('')}</div><button class="btn" type="button" data-action="complete-catalog">Liste geprüft</button></div>`;
 const questionTitle=item.onlyImagePrompt?'':`<h2 class="question">${esc(item.prompt)}</h2>`;
 area.innerHTML=`${top()}<div class="question-card">${dialogue}${visual}${audio}<p class="eyebrow">Aufgabe ${l6t4Load(FILE,task.items.length).done.length+1}</p>${questionTitle}${body}${feedbackHtml(item)}</div>`;bindEnter()
}
function inputBox(label){return`<div id="writeArea" class="answer-area"><label for="answerInput">${esc(label)}</label><div class="answer-row"><input id="answerInput" autocomplete="off"><button class="btn" data-action="check-input" type="button">Prüfen</button></div></div>`}
function bindEnter(){document.getElementById('answerInput')?.addEventListener('keydown',event=>{if(event.key==='Enter')check(event.target.value)})}
function check(value){const item=current();if(!String(value||'').trim())return;const isCorrect=l6t4Exact(value,accepted(item));l6t4RegisterAttempt(FILE,task.items.length,currentIndex,isCorrect);if(isCorrect){right();return}l6t4Wrong(FILE,task.items.length);render()}
function right(){const state=l6t4Load(FILE,task.items.length),repeated=state.hadWrong||state.tries>0;l6t4Right(FILE,task.items.length);area.querySelectorAll('button,input,textarea').forEach(element=>element.disabled=true);const feedback=document.getElementById('feedback');if(feedback)feedback.innerHTML=`<div class="ok">Richtig.${repeated?' Die Aufgabe kommt am Ende noch einmal.':''}</div>`;setTimeout(render,650)}
function reveal(){const item=current();const card=document.querySelector('#verbFlipCard');if(card?.classList.contains('flipped'))return;card?.classList.add('flipped');l6t4RegisterAttempt(FILE,task.items.length,currentIndex,false);l6t4Wrong(FILE,task.items.length);const after=document.querySelector('#cardAfter');if(after){after.innerHTML='<button type="button" class="btn" id="cardHelpNext">Weiter</button>';document.querySelector('#cardHelpNext').onclick=()=>{l6t4Right(FILE,task.items.length);render()}}}
function openCardWrite(message=''){const box=document.querySelector('#cardAnswerBox'),status=document.querySelector('#cardMicStatus');if(box)box.hidden=false;if(status&&message)status.textContent=message;setTimeout(()=>document.querySelector('#cardAnswerInput')?.focus(),30)}
function saveFree(){const item=current(),field=document.getElementById('freeAnswer'),value=String(field?.value||'').trim(),words=value.split(/\s+/).filter(Boolean).length;if(words<(item.minWords||4)){document.getElementById('feedback').innerHTML=`<div class="hint">Schreibe mindestens ${item.minWords||4} Wörter.</div>`;field?.focus();return}if(item.maxWords&&words>item.maxWords){document.getElementById('feedback').innerHTML=`<div class="hint">Kürze deinen Text auf höchstens ${item.maxWords} Wörter.</div>`;field?.focus();return}l6t4RegisterAttempt(FILE,task.items.length,currentIndex,true);l6t4MarkFreeRight(FILE,task.items.length);area.querySelectorAll('button,input,textarea').forEach(element=>element.disabled=true);document.getElementById('feedback').innerHTML='<div class="ok">Gespeichert.</div>';setTimeout(render,600)}
function completeCatalog(){l6t4RegisterAttempt(FILE,task.items.length,currentIndex,true);l6t4MarkFreeRight(FILE,task.items.length);render()}
function selectToken(button){if(button.disabled)return;orderSelection.push(button.dataset.token);button.disabled=true;updateOrder()}
function updateOrder(){const target=document.getElementById('orderAnswer');if(target)target.innerHTML=orderSelection.length?orderSelection.map(token=>`<span>${esc(token)}</span>`).join(' '):'<span>Klicke die Wörter in der richtigen Reihenfolge an.</span>'}
function undoOrder(){if(!orderSelection.length)return;orderSelection.pop();const buttons=[...area.querySelectorAll('[data-token]')],used={};orderSelection.forEach(token=>used[token]=(used[token]||0)+1);buttons.forEach(button=>{const token=button.dataset.token;if(used[token]){button.disabled=true;used[token]--}else button.disabled=false});updateOrder()}
function resetOrder(){orderSelection=[];area.querySelectorAll('[data-token]').forEach(button=>button.disabled=false);updateOrder()}
function startMic(){const item=current(),Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;const inputId=taskId==='cards'?'cardAnswerInput':'answerInput';if(!Recognition){if(taskId==='cards')openCardWrite('Das Mikrofon wird nicht unterstützt. Bitte schreibe die Antwort.');else{technical('Das Mikrofon wird nicht unterstützt. Bitte schreibe die Antwort.');document.getElementById(inputId)?.focus()}return}stopMic();let received=false,failed=false;try{recognition=new Recognition()}catch(e){technical('Das Mikrofon konnte nicht gestartet werden. Bitte schreibe die Antwort.');return}recognition.lang='de-DE';recognition.interimResults=false;recognition.maxAlternatives=5;technical('Ich höre zu …');recognition.onresult=event=>{received=true;const alternatives=Array.from(event.results[0]||[]).map(result=>result.transcript);const exact=alternatives.find(value=>l6t4Exact(value,accepted(item)));if(taskId==='cards')openCardWrite();check(exact||alternatives[0]||'')};recognition.onerror=()=>{failed=true;if(taskId==='cards')openCardWrite('Das Mikrofon hat nicht funktioniert. Bitte schreibe die Antwort.');else technical('Das Mikrofon ist blockiert oder hat nicht funktioniert. Bitte schreibe die Antwort.')};recognition.onend=()=>{recognition=null;if(!received&&!failed){if(taskId==='cards')openCardWrite('Ich konnte nichts erkennen. Bitte schreibe die Antwort.');else technical('Ich konnte nichts erkennen. Bitte schreibe die Antwort.')}};try{recognition.start()}catch(e){technical('Das Mikrofon konnte nicht gestartet werden. Bitte schreibe die Antwort.')}}
function stopMic(){if(recognition)try{recognition.abort()}catch(e){}recognition=null}
function finish(){const next=l6t4NextTask(taskId),suffix=next.includes('?')?'&v=l6t4-revision1':'?v=l6t4-revision1';l6t4Complete(area,next==='index.html'?next:next+suffix,task.exam?'Du hast die Themenprüfung abgeschlossen.':'Du hast diese Aufgabe fehlerfrei abgeschlossen.')}
area.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.answer!==undefined)return check(button.dataset.answer);if(button.dataset.token!==undefined)return selectToken(button);const action=button.dataset.action;if(action==='check-input')return check(document.getElementById('answerInput')?.value||'');if(action==='audio')return l6t4Say(button.dataset.audio||'',()=>technical('Die Audioausgabe funktioniert hier nicht.'));if(action==='mic')return startMic();if(action==='write')return taskId==='cards'?openCardWrite():document.getElementById('answerInput')?.focus();if(action==='save-free')return saveFree();if(action==='complete-catalog')return completeCatalog();if(action==='check-order')return check(orderSelection.join(' '));if(action==='undo-order')return undoOrder();if(action==='reset-order')return resetOrder()});
window.addEventListener('beforeunload',stopMic);render();
})();