const CFG=window.SP_L5_THEME||{id:'Thema-3',title:'Wann? Termine und Tageszeiten',sub:'A1 Lektion 5 · Thema 3',key:'SP_L5_T3_V2'};
const WORDS=[
{id:'montag',article:'der',word:'Montag',plural:'die Montage',type:'Tag',tr:{en:'Monday'}},{id:'dienstag',article:'der',word:'Dienstag',plural:'die Dienstage',type:'Tag',tr:{en:'Tuesday'}},{id:'mittwoch',article:'der',word:'Mittwoch',plural:'die Mittwoche',type:'Tag',tr:{en:'Wednesday'}},{id:'donnerstag',article:'der',word:'Donnerstag',plural:'die Donnerstage',type:'Tag',tr:{en:'Thursday'}},{id:'freitag',article:'der',word:'Freitag',plural:'die Freitage',type:'Tag',tr:{en:'Friday'}},{id:'samstag',article:'der',word:'Samstag',plural:'die Samstage',type:'Tag',tr:{en:'Saturday'}},{id:'sonntag',article:'der',word:'Sonntag',plural:'die Sonntage',type:'Tag',tr:{en:'Sunday'}},
{id:'morgen',article:'der',word:'Morgen',plural:'die Morgen',type:'Tageszeit',tr:{en:'morning'}},{id:'vormittag',article:'der',word:'Vormittag',plural:'die Vormittage',type:'Tageszeit',tr:{en:'late morning'}},{id:'mittag',article:'der',word:'Mittag',plural:'die Mittage',type:'Tageszeit',tr:{en:'noon'}},{id:'nachmittag',article:'der',word:'Nachmittag',plural:'die Nachmittage',type:'Tageszeit',tr:{en:'afternoon'}},{id:'abend',article:'der',word:'Abend',plural:'die Abende',type:'Tageszeit',tr:{en:'evening'}},{id:'nacht',article:'die',word:'Nacht',plural:'die Nächte',type:'Tageszeit',tr:{en:'night'}},
{id:'acht-uhr',word:'acht Uhr',type:'Uhrzeit',tr:{en:'eight o’clock'}},{id:'halb-neun',word:'halb neun',type:'Uhrzeit',tr:{en:'half past eight'}},{id:'viertel-nach-zehn',word:'Viertel nach zehn',type:'Uhrzeit',tr:{en:'quarter past ten'}},{id:'zehn-vor-acht',word:'zehn vor acht',type:'Uhrzeit',tr:{en:'ten to eight'}},
{id:'wochenende',article:'das',word:'Wochenende',plural:'die Wochenenden',type:'Zeitraum',tr:{en:'weekend'}},{id:'woche',article:'die',word:'Woche',plural:'die Wochen',type:'Zeitraum',tr:{en:'week'}},{id:'monat',article:'der',word:'Monat',plural:'die Monate',type:'Zeitraum',tr:{en:'month'}},
{id:'aufstehen',word:'aufstehen',type:'Verb',tr:{en:'to get up'}},{id:'aufräumen',word:'aufräumen',type:'Verb',tr:{en:'to tidy up'}},{id:'fernsehen',word:'fernsehen',type:'Verb',tr:{en:'to watch TV'}},{id:'anrufen',word:'anrufen',type:'Verb',tr:{en:'to call'}},{id:'anfangen',word:'anfangen',type:'Verb',tr:{en:'to start'}},{id:'arbeiten',word:'arbeiten',type:'Verb',tr:{en:'to work'}},{id:'lernen',word:'lernen',type:'Verb',tr:{en:'to learn'}}
];
const SORT_ITEMS=[['um 8 Uhr','Uhrzeit'],['um halb neun','Uhrzeit'],['um Viertel nach zehn','Uhrzeit'],['um zehn vor acht','Uhrzeit'],['am Morgen','Tageszeit'],['am Vormittag','Tageszeit'],['am Nachmittag','Tageszeit'],['am Abend','Tageszeit'],['in der Nacht','Tageszeit'],['am Montag','Tag'],['am Dienstag','Tag'],['am Freitag','Tag'],['am Wochenende','Tag'],['von Montag bis Freitag','Zeitraum'],['von 8 bis 12 Uhr','Zeitraum'],['von halb neun bis zwölf Uhr','Zeitraum'],['eine Woche','Zeitraum'],['zwei Monate','Zeitraum']];
const PREP=[
['Ich stehe ___ sieben Uhr auf.','um'],['Der Kurs beginnt ___ Montag.','am'],['Ich lerne ___ Vormittag Deutsch.','am'],['Die Pause ist ___ zehn Uhr.','um'],['Ich arbeite ___ Freitag.','am'],['Ich sehe ___ Abend fern.','am'],['Ich räume ___ Nachmittag auf.','am'],['Ich schlafe ___ Nacht.','in der'],['Der Kurs geht ___ neun ___ zwölf Uhr.','von bis'],['Ich arbeite ___ Montag ___ Freitag.','von bis'],['Der Termin ist ___ halb drei.','um'],['Ich rufe dich ___ Abend an.','am'],['Wir lernen ___ Wochenende.','am'],['Der Unterricht ist ___ Dienstag.','am'],['Die Praxis ist ___ acht ___ sechzehn Uhr geöffnet.','von bis'],['Ich frühstücke ___ Morgen.','am'],['Das Training ist ___ Mittwoch ___ achtzehn Uhr.','am um'],['Ich komme ___ Viertel nach zehn.','um'],['Ich habe ___ Mittag Pause.','am'],['Das Baby schläft ___ Nacht.','in der']
];
const BUILD=[
{parts:'___ Nachmittag / ich / aufräumen / .',answers:['Am Nachmittag räume ich auf.','Ich räume am Nachmittag auf.']},
{parts:'___ sieben Uhr / ich / aufstehen / .',answers:['Um sieben Uhr stehe ich auf.','Ich stehe um sieben Uhr auf.']},
{parts:'___ Abend / ich / fernsehen / .',answers:['Am Abend sehe ich fern.','Ich sehe am Abend fern.']},
{parts:'___ Montag / der Kurs / anfangen / .',answers:['Am Montag fängt der Kurs an.','Der Kurs fängt am Montag an.']},
{parts:'___ zehn Uhr / ich / anrufen / .',answers:['Um zehn Uhr rufe ich an.','Ich rufe um zehn Uhr an.']},
{parts:'___ Vormittag / ich / Deutsch lernen / .',answers:['Am Vormittag lerne ich Deutsch.','Ich lerne am Vormittag Deutsch.']},
{parts:'___ Nacht / ich / schlafen / .',answers:['In der Nacht schlafe ich.','Ich schlafe in der Nacht.']},
{parts:'___ Montag bis Freitag / ich / arbeiten / .',answers:['Von Montag bis Freitag arbeite ich.','Ich arbeite von Montag bis Freitag.']},
{parts:'___ 8 bis 12 Uhr / der Kurs / dauern / .',answers:['Von 8 bis 12 Uhr dauert der Kurs.','Der Kurs dauert von 8 bis 12 Uhr.']},
{parts:'___ Samstag / ich / einkaufen / .',answers:['Am Samstag kaufe ich ein.','Ich kaufe am Samstag ein.']}
];
const HEAR=[['Ich rufe dich am Abend an.','am Abend',['am Abend','um Abend','in der Abend','von Abend bis Nacht']],['Der Kurs fängt um neun Uhr an.','um neun Uhr',['um neun Uhr','am neun Uhr','von neun Uhr','in der neun Uhr']],['Ich schlafe in der Nacht.','in der Nacht',['in der Nacht','am Nacht','um Nacht','von Nacht']],['Ich räume am Nachmittag auf.','am Nachmittag',['am Nachmittag','um Nachmittag','in der Nachmittag','von Nachmittag']],['Der Kurs ist von neun bis zwölf Uhr.','von neun bis zwölf Uhr',['von neun bis zwölf Uhr','am neun bis zwölf Uhr','um neun bis zwölf Uhr','bis neun von zwölf Uhr']],['Am Vormittag lerne ich Deutsch.','am Vormittag',['am Vormittag','um Vormittag','in der Vormittag','von Vormittag']]];
const PLAN=[['Montag','9-12 Uhr','Deutschkurs'],['Dienstag','15 Uhr','Termin'],['Mittwoch','18-19 Uhr','Training'],['Donnerstag','am Nachmittag','aufräumen'],['Freitag','am Abend','fernsehen'],['Samstag','in der Nacht','schlafen']];
const PLAN_Q=[['Wann ist der Deutschkurs?',['am Montag von 9 bis 12 Uhr','Der Deutschkurs ist am Montag von 9 bis 12 Uhr.']],['Wann ist der Termin?',['am Dienstag um 15 Uhr','Der Termin ist am Dienstag um 15 Uhr.']],['Von wann bis wann ist das Training?',['am Mittwoch von 18 bis 19 Uhr','Das Training ist am Mittwoch von 18 bis 19 Uhr.']],['Wann räumt die Person auf?',['am Donnerstag am Nachmittag','Die Person räumt am Donnerstag am Nachmittag auf.','Am Donnerstag am Nachmittag räumt die Person auf.']],['Wann sieht die Person fern?',['am Freitag am Abend','Die Person sieht am Freitag am Abend fern.','Am Freitag am Abend sieht die Person fern.']],['Wann schläft die Person?',['am Samstag in der Nacht','Die Person schläft am Samstag in der Nacht.','Am Samstag in der Nacht schläft die Person.']]];
const SPEAK=[['Wann stehen Sie auf?',['Ich stehe um sieben Uhr auf.','Um sieben Uhr stehe ich auf.']],['Wann räumen Sie auf?',['Ich räume am Nachmittag auf.','Am Nachmittag räume ich auf.']],['Wann sehen Sie fern?',['Ich sehe am Abend fern.','Am Abend sehe ich fern.']],['Wann arbeiten Sie?',['Ich arbeite von Montag bis Freitag.','Von Montag bis Freitag arbeite ich.']],['Wann lernen Sie Deutsch?',['Ich lerne am Vormittag Deutsch.','Am Vormittag lerne ich Deutsch.']],['Wann schlafen Sie?',['Ich schlafe in der Nacht.','In der Nacht schlafe ich.']]];
const DIALOGS=[
{lines:['A: Wann fängt der Kurs an?','B: Der Kurs fängt ___ neun Uhr an.'],answers:['um']},
{lines:['A: Was machst du am Nachmittag?','B: Ich räume ___ Nachmittag auf.'],answers:['am']},
{lines:['A: Wann rufst du mich an?','B: Ich rufe dich ___ Abend an.'],answers:['am']},
{lines:['A: Von wann bis wann arbeitest du?','B: Ich arbeite ___ acht ___ vier Uhr.'],answers:['von','bis']},
{lines:['A: Wann schläfst du?','B: Ich schlafe ___ Nacht.'],answers:['in der']},
{lines:['A: Wann hast du Deutsch?','B: Ich habe ___ Montag Deutsch.'],answers:['am']}
];
const INTERVIEW=[
['Wann stehen Sie auf?'],['Wann frühstücken Sie?'],['Wann haben Sie Deutschkurs?'],['Wann arbeiten Sie?'],['Wann räumen Sie auf?'],['Wann sehen Sie fern?'],['Wann schlafen Sie?']
];
function profile(){try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||'null')}catch(e){return null}}
function tr(w){return (w.tr&&w.tr.en)||'—'}
function full(w){return w.article?`${w.article} ${w.word}`:w.word}
function simple(x){return String(x||'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/\s+/g,' ').toLowerCase().replace(/[!?;:]/g,'').replace(/\.$/,'')}
function ok(v,a){const s=simple(v);return (Array.isArray(a)?a:[a]).some(x=>s===simple(x))}
function sentenceLooksRight(v){const raw=String(v||'').trim();if(!/^[A-ZÄÖÜ]/.test(raw))return false;if(!/\.$/.test(raw))return false;return true}
function hasTime(v){const s=simple(v);return /\bum\b|\bam\b|\bin der nacht\b|\bvon\b.*\bbis\b/.test(s)}
function verbSecond(v){const s=simple(v);return /^(ich|der|die|das|wir|sie)\s+(stehe|raeume|sehe|rufe|fange|faengt|lerne|arbeite|schlafe|kaufe|dauert|ist)\b/.test(s)||/^(am|um|von|in der nacht)\b.*\s+(stehe|raeume|sehe|rufe|faengt|lerne|arbeite|schlafe|kaufe|dauert|ist)\b/.test(s)}
function variants(s){return Array.isArray(s)?s:[s]}
function imgHtml(w){return `<div class="word-placeholder">${w.word}</div>`}
function bigImgHtml(w){return `<div class="placeholder-img">${w.word}</div>`}
function header(title,showReset=false){const h=document.querySelector('.topbar');if(!h)return;const p=profile();const name=[p?.vorname||p?.firstName||'',p?.nachname||p?.lastName||''].join(' ').trim()||'Schüler/in';const dash=localStorage.getItem('SP_LOGIN_ROLE')==='teacher'?'/teacher/index.html':'/student-dashboard/index.html';h.innerHTML=`<div class="topbar-main"><a class="brand" href="/index.html"><div class="logo"><img src="/assets/logo/sprachpilot-logo.png" alt="SprachPilot"></div><div><h1>SprachPilot</h1><div class="subtitle">${title} · ${CFG.sub}</div></div></a><div class="account-tools"><span class="account-pill">${name}</span><a class="account-link" href="${dash}">Dashboard</a><a class="account-link" href="/profile/index.html">Profil</a></div></div><nav class="nav"><a class="btn secondary" href="${location.pathname.endsWith('index.html')||/\/Thema-3\/?$/.test(location.pathname)?'../index.html':'index.html'}">← Zurück</a>${showReset?'<button class="btn danger" onclick="resetThemeProgress()">Fortschritte löschen</button>':''}</nav>`}
function taskKey(file){return CFG.key+'_'+file}
function loadTask(file,total){try{const st=JSON.parse(localStorage.getItem(taskKey(file))||'null');if(st&&st.total===total&&Array.isArray(st.done)&&Array.isArray(st.queue))return st}catch(e){}return{total,done:[],queue:[...Array(total).keys()].sort(()=>Math.random()-.5),current:null,tries:0,hadWrong:false}}
function saveTask(file,st){localStorage.setItem(taskKey(file),JSON.stringify(st))}
function spNextIndex(file,total){let st=loadTask(file,total);if(st.current===null||st.current===undefined){if(!st.queue.length&&st.done.length<total)st.queue=[...Array(total).keys()].filter(i=>!st.done.includes(i)).sort(()=>Math.random()-.5);st.current=st.queue.shift();st.tries=0;st.hadWrong=false;saveTask(file,st)}return st.current}
function spMarkRight(file,total){let st=loadTask(file,total),c=st.current;if(c!==null&&c!==undefined){if(st.hadWrong||st.tries>0){if(!st.done.includes(c)&&!st.queue.includes(c))st.queue.push(c)}else if(!st.done.includes(c))st.done.push(c)}st.current=null;st.tries=0;st.hadWrong=false;saveTask(file,st)}
function spMarkWrong(file,total){let st=loadTask(file,total);st.tries=(st.tries||0)+1;st.hadWrong=true;saveTask(file,st);return st.tries}
function pctFor(file,total){if(!total)return 0;return Math.round(loadTask(file,total).done.length/total*100)||0}
function spProgressHtml(file,total){const st=loadTask(file,total),p=pctFor(file,total);return `<div class="small">${st.done.length} richtig · ${total-st.done.length} übrig · ${p}%</div><div class="progress"><div class="bar" style="width:${p}%"></div></div>`}
function complete(area,file,next='index.html'){area.innerHTML=`<div class="finish-box"><div class="finish-icon">✓</div><div class="question">Geschafft!</div><div class="hint">Diese Aufgabe ist abgeschlossen.</div><div class="actions"><a class="btn" href="${next}">Weiter →</a><a class="btn secondary" href="index.html">Zum Menü</a></div></div>`}
function resetThemeProgress(){if(!confirm('Fortschritte in diesem Thema löschen?'))return;Object.keys(localStorage).filter(k=>k.startsWith(CFG.key)).forEach(k=>localStorage.removeItem(k));location.reload()}
function sayGerman(t){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='de-DE';u.rate=.92;speechSynthesis.speak(u)}
function startMic(btn,cb){const SR=window.SpeechRecognition||window.webkitSpeechRecognition,status=document.getElementById('micStatus');if(!SR){if(status)status.textContent='Mikrofon wird hier nicht unterstützt. Bitte schreibe.';return}const r=new SR();r.lang='de-DE';r.interimResults=false;r.maxAlternatives=3;btn.disabled=true;btn.textContent='Ich höre …';r.onresult=e=>{const v=e.results[0][0].transcript;btn.disabled=false;btn.textContent='🎤 Sprechen';if(status)status.textContent='Erkannt: '+v;cb(v)};r.onerror=()=>{btn.disabled=false;btn.textContent='🎤 Sprechen';if(status)status.textContent='Mikrofon hat nicht funktioniert.'};r.onend=()=>{btn.disabled=false};r.start()}
function cardPrompt(w){return w.article?'Sage oder schreibe das Wort mit Artikel.':'Sage oder schreibe das Wort.'}
function cardTip(w){return w.article?'Artikel und Wort':'Wort'}