const CFG=window.SP_L5_THEME||{id:'Thema-3',title:'Wann? Termine und Tageszeiten',sub:'A1 Lektion 5 · Thema 3',key:'SP_L5_T3_V1'};
const WORDS=[
{id:'montag',article:'der',word:'Montag',plural:'die Montage',type:'Tag',tr:{en:'Monday'}},{id:'dienstag',article:'der',word:'Dienstag',plural:'die Dienstage',type:'Tag',tr:{en:'Tuesday'}},{id:'mittwoch',article:'der',word:'Mittwoch',plural:'die Mittwoche',type:'Tag',tr:{en:'Wednesday'}},{id:'donnerstag',article:'der',word:'Donnerstag',plural:'die Donnerstage',type:'Tag',tr:{en:'Thursday'}},{id:'freitag',article:'der',word:'Freitag',plural:'die Freitage',type:'Tag',tr:{en:'Friday'}},{id:'samstag',article:'der',word:'Samstag',plural:'die Samstage',type:'Tag',tr:{en:'Saturday'}},{id:'sonntag',article:'der',word:'Sonntag',plural:'die Sonntage',type:'Tag',tr:{en:'Sunday'}},{id:'morgen',article:'der',word:'Morgen',plural:'die Morgen',type:'Tageszeit',tr:{en:'morning'}},{id:'vormittag',article:'der',word:'Vormittag',plural:'die Vormittage',type:'Tageszeit',tr:{en:'late morning'}},{id:'mittag',article:'der',word:'Mittag',plural:'die Mittage',type:'Tageszeit',tr:{en:'noon'}},{id:'nachmittag',article:'der',word:'Nachmittag',plural:'die Nachmittage',type:'Tageszeit',tr:{en:'afternoon'}},{id:'abend',article:'der',word:'Abend',plural:'die Abende',type:'Tageszeit',tr:{en:'evening'}},{id:'nacht',article:'die',word:'Nacht',plural:'die Nächte',type:'Tageszeit',tr:{en:'night'}},{id:'um',word:'um',type:'Präposition',tr:{en:'at'}},{id:'am',word:'am',type:'Präposition',tr:{en:'on / in the'}},{id:'von',word:'von',type:'Präposition',tr:{en:'from'}},{id:'bis',word:'bis',type:'Präposition',tr:{en:'until / to'}},{id:'fernsehen',word:'fernsehen',type:'Verb',tr:{en:'to watch TV'}},{id:'aufraeumen',word:'aufräumen',type:'Verb',tr:{en:'to tidy up'}},{id:'anfangen',word:'anfangen',type:'Verb',tr:{en:'to start'}},{id:'anrufen',word:'anrufen',type:'Verb',tr:{en:'to call'}},{id:'kurs',article:'der',word:'Kurs',plural:'die Kurse',type:'Nomen',tr:{en:'course'}},{id:'termin',article:'der',word:'Termin',plural:'die Termine',type:'Nomen',tr:{en:'appointment'}},{id:'pause',article:'die',word:'Pause',plural:'die Pausen',type:'Nomen',tr:{en:'break'}},{id:'arbeit',article:'die',word:'Arbeit',plural:'die Arbeiten',type:'Nomen',tr:{en:'work'}},{id:'training',article:'das',word:'Training',plural:'die Trainings',type:'Nomen',tr:{en:'training'}},{id:'wann',word:'wann',type:'Fragewort',tr:{en:'when'}}
];
const SORT_ITEMS=[['um 8 Uhr','um'],['um halb neun','um'],['um Viertel nach zehn','um'],['am Montag','am'],['am Wochenende','am'],['am Morgen','am'],['am Vormittag','am'],['am Mittag','am'],['am Nachmittag','am'],['am Abend','am'],['in der Nacht','nacht'],['von 9 bis 12 Uhr','vonbis'],['von Montag bis Freitag','vonbis'],['von halb neun bis zwölf Uhr','vonbis']];
const UM_AM=[['Ich komme ___ acht Uhr.','um'],['Der Kurs ist ___ Montag.','am'],['Ich lerne ___ Vormittag.','am'],['Die Pause ist ___ zehn Uhr.','um'],['Ich arbeite ___ Freitag.','am'],['Ich sehe ___ Abend fern.','am'],['Ich rufe dich ___ Nachmittag an.','am'],['Ich schlafe ___ Nacht.','in der']];
const MIX=[['Der Kurs geht ___ neun ___ zwölf Uhr.','von bis'],['Ich habe ___ Montag Deutsch.','am'],['Der Termin ist ___ halb drei.','um'],['Ich arbeite ___ Montag ___ Freitag.','von bis'],['Die Pause ist ___ 10 Uhr.','um'],['Ich sehe ___ Abend fern.','am'],['Ich schlafe ___ Nacht.','in der'],['Der Kurs fängt ___ neun Uhr an.','um'],['Ich räume ___ Nachmittag auf.','am'],['Ich rufe dich ___ Abend an.','am']];
const BUILD=[['ich / sehe / am Abend / fern','Ich sehe am Abend fern.'],['ich / räume / am Nachmittag / auf','Ich räume am Nachmittag auf.'],['der Kurs / fängt / um neun Uhr / an','Der Kurs fängt um neun Uhr an.'],['ich / rufe / dich / am Abend / an','Ich rufe dich am Abend an.'],['ich / schlafe / in der Nacht','Ich schlafe in der Nacht.'],['der Termin / ist / am Montag / um zehn Uhr','Der Termin ist am Montag um zehn Uhr.'],['die Arbeit / ist / von acht bis vier Uhr','Die Arbeit ist von acht bis vier Uhr.'],['am Vormittag / lerne / ich / Deutsch','Am Vormittag lerne ich Deutsch.']];
const HEAR=[['Ich rufe dich am Abend an.','am Abend',['am Abend','um Abend','in der Abend','von Abend bis Nacht']],['Der Kurs fängt um neun Uhr an.','um neun Uhr',['um neun Uhr','am neun Uhr','von neun Uhr','in der neun Uhr']],['Ich schlafe in der Nacht.','in der Nacht',['in der Nacht','am Nacht','um Nacht','von Nacht']],['Ich räume am Nachmittag auf.','am Nachmittag',['am Nachmittag','um Nachmittag','in der Nachmittag','von Nachmittag']],['Der Kurs ist von neun bis zwölf Uhr.','von neun bis zwölf Uhr',['von neun bis zwölf Uhr','am neun bis zwölf Uhr','um neun bis zwölf Uhr','bis neun von zwölf Uhr']],['Am Vormittag lerne ich Deutsch.','am Vormittag',['am Vormittag','um Vormittag','in der Vormittag','von Vormittag']]];
const PLAN=[['Montag','9-12 Uhr','Deutschkurs'],['Dienstag','15 Uhr','Termin'],['Mittwoch','18-19 Uhr','Training'],['Donnerstag','am Nachmittag','aufräumen'],['Freitag','am Abend','fernsehen'],['Samstag','in der Nacht','schlafen']];
const PLAN_Q=[['Wann ist der Deutschkurs?','am Montag von 9 bis 12 Uhr'],['Wann ist der Termin?','am Dienstag um 15 Uhr'],['Von wann bis wann ist das Training?','am Mittwoch von 18 bis 19 Uhr'],['Wann räumt die Person auf?','am Donnerstag am Nachmittag'],['Wann sieht die Person fern?','am Freitag am Abend'],['Wann schläft die Person?','am Samstag in der Nacht']];
const SPEAK=[['am Abend / fernsehen','Ich sehe am Abend fern.'],['um neun Uhr / Kurs / anfangen','Der Kurs fängt um neun Uhr an.'],['am Nachmittag / anrufen','Ich rufe am Nachmittag an.'],['in der Nacht / schlafen','Ich schlafe in der Nacht.'],['von Montag bis Freitag / arbeiten','Ich arbeite von Montag bis Freitag.'],['am Vormittag / Deutsch lernen','Ich lerne am Vormittag Deutsch.']];
const DIALOGS=[['Wann fängt der Kurs an?','Der Kurs fängt um neun Uhr an.'],['Wann rufst du mich an?','Ich rufe dich am Abend an.'],['Was machst du am Nachmittag?','Ich räume auf.'],['Wann siehst du fern?','Am Abend.'],['Von wann bis wann arbeitest du?','Von acht bis vier Uhr.']];
function profile(){try{return JSON.parse(localStorage.getItem('SP_USER_PROFILE')||'null')}catch(e){return null}}
function tr(w){return (w.tr&&w.tr.en)||'—'}
function full(w){return w.article?`${w.article} ${w.word}`:w.word}
function simple(x){return String(x||'').toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[.,!?;:]/g,'').replace(/\s+/g,' ')}
function ok(v,a){const s=simple(v);return a.some(x=>s===simple(x))}
function variants(s){return [s,s.replace(/9/g,'neun').replace(/10/g,'zehn').replace(/12/g,'zwölf').replace(/15/g,'fünfzehn').replace(/18/g,'achtzehn').replace(/19/g,'neunzehn')]}
function imgHtml(w){return `<div class="word-placeholder">${w.word}</div>`}
function bigImgHtml(w){return `<div class="placeholder-img">${w.word}</div>`}
function header(title,showReset=false){const h=document.querySelector('.topbar');if(!h)return;const p=profile();const name=[p?.vorname||p?.firstName||'',p?.nachname||p?.lastName||''].join(' ').trim()||'Schüler/in';const dash=localStorage.getItem('SP_LOGIN_ROLE')==='teacher'?'/teacher/index.html':'/student-dashboard/index.html';h.innerHTML=`<div class="topbar-main"><a class="brand" href="/index.html"><div class="logo"><img src="/assets/logo/sprachpilot-logo.png" alt="SprachPilot"></div><div><h1>SprachPilot</h1><div class="subtitle">${title} · ${CFG.sub}</div></div></a><div class="account-tools"><span class="account-pill">${name}</span><a class="account-link" href="${dash}">Dashboard</a><a class="account-link" href="/profile/index.html">Profil</a></div></div><nav class="nav"><a class="btn secondary" href="${location.pathname.endsWith('index.html')||/\/Thema-3\/?$/.test(location.pathname)?'../index.html':'index.html'}">← Zurück</a><a class="btn secondary" href="uebersicht.html">Übersicht</a><a class="btn secondary" href="statistik.html">Statistik</a>${showReset?'<button class="btn danger" onclick="resetThemeProgress()">Fortschritte löschen</button>':''}</nav>`}
function taskKey(file){return CFG.key+'_'+file}
function loadTask(file,total){try{const st=JSON.parse(localStorage.getItem(taskKey(file))||'null');if(st&&st.total===total&&Array.isArray(st.done)&&Array.isArray(st.queue))return st}catch(e){}return{total,done:[],queue:[...Array(total).keys()].sort(()=>Math.random()-.5),current:null,tries:0,hadWrong:false}}
function saveTask(file,st){localStorage.setItem(taskKey(file),JSON.stringify(st))}
function spNextIndex(file,total){let st=loadTask(file,total);if(st.current===null||st.current===undefined){if(!st.queue.length&&st.done.length<total)st.queue=[...Array(total).keys()].filter(i=>!st.done.includes(i)).sort(()=>Math.random()-.5);st.current=st.queue.shift();st.tries=0;st.hadWrong=false;saveTask(file,st)}return st.current}
function spMarkRight(file,total){let st=loadTask(file,total),c=st.current;if(c!==null&&c!==undefined){if(st.hadWrong||st.tries>0){if(!st.done.includes(c)&&!st.queue.includes(c))st.queue.push(c)}else if(!st.done.includes(c))st.done.push(c)}st.current=null;st.tries=0;st.hadWrong=false;saveTask(file,st)}
function spMarkWrong(file,total){let st=loadTask(file,total);st.tries=(st.tries||0)+1;st.hadWrong=true;saveTask(file,st);return st.tries}
function pctFor(file,total){if(!total)return 0;return Math.round(loadTask(file,total).done.length/total*100)||0}
function spProgressHtml(file,total){const st=loadTask(file,total),p=pctFor(file,total);return `<div class="small">${st.done.length} richtig · ${total-st.done.length} übrig · ${p}%</div><div class="progress"><div class="bar" style="width:${p}%"></div></div>`}
function complete(area,file,next='index.html'){area.innerHTML=`<div class="finish-box"><div class="finish-icon">✓</div><div class="question">Geschafft!</div><div class="hint">Diese Aufgabe ist abgeschlossen.</div><div class="actions"><a class="btn" href="${next}">Weiter →</a><a class="btn secondary" href="index.html">Zum Menü</a></div></div>`}
function resetThemeProgress(){if(!confirm('Fortschritte in diesem Thema löschen?'))return;Object.keys(localStorage).filter(k=>k.startsWith(CFG.key)).forEach(k=>localStorage.removeItem(k));location.reload()}
function renderOverview(el){const groups={};WORDS.forEach(w=>(groups[w.type]=groups[w.type]||[]).push(w));el.innerHTML=Object.keys(groups).map(g=>`<div class="type-block"><div class="type-title">${g}</div>${groups[g].map(w=>`<div class="word-row">${imgHtml(w)}<div><b>${full(w)}</b><div class="native-trans"><b>Muttersprache:</b> ${tr(w)}</div><div class="small">${w.type}</div></div></div>`).join('')}</div>`).join('')}
function renderStats(el){const st=loadTask('karteikarten.html',WORDS.length);el.innerHTML=WORDS.map((w,i)=>`<div class="word-row">${imgHtml(w)}<div><b>${full(w)}</b><div class="small">${st.done.includes(i)?'gelernt':'noch offen'}</div></div></div>`).join('')}
function sayGerman(t){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='de-DE';u.rate=.92;speechSynthesis.speak(u)}
function startMic(btn,cb){const SR=window.SpeechRecognition||window.webkitSpeechRecognition,status=document.getElementById('micStatus');if(!SR){if(status)status.textContent='Mikrofon wird hier nicht unterstützt. Bitte schreibe.';return}const r=new SR();r.lang='de-DE';r.interimResults=false;r.maxAlternatives=3;btn.disabled=true;btn.textContent='Ich höre …';r.onresult=e=>{const v=e.results[0][0].transcript;btn.disabled=false;btn.textContent='🎤 Sprechen';if(status)status.textContent='Erkannt: '+v;cb(v)};r.onerror=()=>{btn.disabled=false;btn.textContent='🎤 Sprechen';if(status)status.textContent='Mikrofon hat nicht funktioniert.'};r.onend=()=>{btn.disabled=false};r.start()}
function nextBtn(next){return `<div class="actions"><a class="btn" href="${next}">Weiter →</a><a class="btn secondary" href="index.html">Zum Menü</a></div>`}
function cardPrompt(w){return w.article?'Sage das Wort mit Artikel.':'Sage das Wort.'}
function cardTip(w){return w.article?'Artikel und Wort':'Wort'}